### ISSUE TITLE
[bug] menu accelerator not working on windows

### ISSUE THREAD

**Issue by preampinbut** [tauri-apps/tauri#6365] opened 2023-02-26 21:25 UTC
### Describe the bug

Menu accelerator not working as expected as in electron did
click working but cant trigger by using keyboard
*windows 11

### Reproduction

1. yarn create tauri-app
1.1. react-ts
2. yarn install
3. yarn build
4. add this to builder
``` rust
.menu(Menu::new().add_submenu(Submenu::new(
            "File",
            Menu::new().add_item(
                CustomMenuItem::new("quit".to_string(), "Quit").accelerator("CmdOrCtrl+Q"),
            ),
        )))
        .on_menu_event(move |event| match event.menu_item_id() {
            "quit" => {
                event.window().close().unwrap();
            }
            _ => {}
        })
```
5. yarn tauri dev

### Platform and versions

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 110.0.1587.56
  › MSVC: 
  › Node.js: 16.17.0
  › npm: 8.15.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by FabianLars** [comment] 2023-02-26 21:31
Duplicate of https://github.com/tauri-apps/tauri/issues/4085 - relevant wry issue: https://github.com/tauri-apps/wry/issues/451 (tldr: waiting for microsoft :/ ).
Thanks for the report!

**Closed as not planned by FabianLars** 2023-02-26 21:31 UTC
Labels: type: bug, status: needs triage
