### ISSUE TITLE
[bug] could not compile `tauri-macros` 

### ISSUE THREAD

**Issue by faithysq666** [tauri-apps/tauri#4798] opened 2022-07-30 02:39 UTC
### Describe the bug

could not compile `tauri-macros`  due to export ordinal too large: 66355，collect2.exe: error: ld returned 1 exit status

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 103.0.1264.77
  › MSVC:
  › Node.js: 16.16.0
  › npm: 8.15.1
  › pnpm: 7.5.2
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset        
  › distDir: ../dist   
  › devPath: ../dist   

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri

### Additional context

![Snipaste_2022-07-30_10-32-39](https://user-images.githubusercontent.com/66512309/181867014-c9fc7681-4ad3-485e-bfe5-18d8ef825731.png)
![Snipaste_2022-07-30_10-32-50](https://user-images.githubusercontent.com/66512309/181867017-983ac183-7f3b-457e-94aa-e18d8b8e6c14.png)

**Comment by FabianLars** [comment] 2022-07-30 09:50
Duplicate of #4794.

**Closed as completed by FabianLars** 2022-07-30 09:50 UTC
Labels: type: bug, status: needs triage
