### ISSUE TITLE
[docs] Yew + listen

### ISSUE THREAD

**Issue by memodyssey** [tauri-apps/tauri#5487] opened 2022-10-26 09:51 UTC
Hello, I would like to implement the emit function with Yew but I don't how can I implement it especially the **listen** function with the warm-bindgen.
https://tauri.app/v1/guides/features/events/

```typescript
import { emit, listen } from '@tauri-apps/api/event'

// listen to the `click` event and get a function to remove the event listener
// there's also a `once` function that subscribes to an event and automatically unsubscribes the listener on the first event
const unlisten = await listen('click', (event) => {
  // event.event is the event name (useful if you want to use a single callback fn for multiple event types)
  // event.payload is the payload object
}

// emits the `click` event with the object payload
emit('click', {
  theMessage: 'Tauri is awesome!',
}) 
```

Is there any way to do this with a frontend built with rust ?

**Comment by FabianLars** [comment] 2022-11-17 14:50
Duplicate of https://github.com/tauri-apps/tauri-docs/issues/952

We probably won't adress this directly in the docs like this. But instead focus on stuff like this https://github.com/JonasKruckenberg/tauri-sys

**Closed as not planned by FabianLars** 2022-11-17 14:50 UTC
Labels: type: documentation
