### ISSUE TITLE
getDisplayMedia() has permission issue

### ISSUE THREAD

**Issue by devtool20000** [tauri-apps/tauri#2600] opened 2021-09-14 00:25 UTC
### **Describe the bug**
Hi I try to call getDisplayMedia() but got permission issue, see details below, thanks!

### **To Reproduce**
1. Check out the sample code from [here](https://github.com/cris20000/test-tauri-webrtc)
2. cd to src-tauri/my-app run ```yarn && yarn start```, this start the react dev server
3. in root folder run ```yarn tauri dev```
4. After the application starts, click the "test" button, this will trigger the getDisplayMedia() api. Click the "Inspect Element", you will see the error in console "Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

### **Expected behavior**
It should call the getDisplayMedia() successfully without error. 

### **Screenshots**
![image](https://user-images.githubusercontent.com/85258537/133173608-1e2b0183-04de-44f3-952e-7cc957779c58.png)

### **Platform and Versions (required):**
```
Operating System - Mac OS, version 11.5.2 X64

Node.js environment
  Node.js - 14.17.2
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.13
  yarn - 1.22.4

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/src-tauri
/.idea

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - my-app/build
  devPath - http://localhost:3000


```

### **Additional context**
I already add the Info.plist under src-tauri with the following configuration
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>Request camera access for WebRTC</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Request microphone access for WebRTC</string>
</dict>
</plist>
```
The getUserMedia() works properly, but getDisplayMedia() didn't. I try to run the same react app inside safari and the getDisplayMedia() works properly in it.

**Comment by alectrocute** [comment] 2022-01-21 14:01
Side effect of #2317?

**Comment by cliqer** [comment] 2022-06-27 20:47
I am experiencing the same error.
```console
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
```
and on the server I get:
```console
+++     0x60000040ee60  0       1       914797062695125
```
My plist is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.automation.apple-events</key>
    <true/>
    <key>com.apple.security.device.usb</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>
```
and the request is:
```js
  return await navigator.mediaDevices.getDisplayMedia({
    audio: false,
    video: {
      //@ts-ignore
      mandatory: {
        displaySurface: 'monitor', // tried 'desktop', 'screen', 'display'
        chromeMediaSourceId: 1,
        minWidth: 1280,
        maxWidth: 1680,
        minHeight: 720,
        maxHeight: 1050
      }
    }
  }).then(stream => console.log(stream))
    .catch(e => console.log(e))
```
Also `window.isSecureContext` returns `true` on all platforms.
Any solutions?

**Comment by cliqer** [comment] 2022-08-05 05:15
`navigator.mediaDevices.getDisplayMedia` throw `NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

Can someone please help with this problem for Webkit on MacOS?

**Comment by daniel-abramov** [comment] 2022-08-15 18:28
@cliqer, I'm not an expert, so not sure if what I'm going to say would make any sense, but AFAIK there is no such thing as `chromeMediaSourceId` in the WebRTC spec. I assume you might be using the `chromeMediaSourceId` as this is something you would use with Electron when calling their `getUserMedia` function to capture a specific window.

It seems like this is very specific to the Chromium engine and Electron even [implemented an extension/helper](https://github.com/electron/electron/blob/3c63f075bd35333b80f78c462cdba1440b3fec55/shell/browser/web_contents_permission_helper.cc) to handle the `chromeMediaSourceId` inside `getUserMedia()`.

I'm not sure these could work with `getDisplayMedia` and Tauri without implementing some sort of a Tauri plugin that would have a functionality similar to the `desktopCapturer` in Electron.

**Comment by cliqer** [comment] 2022-08-15 19:05
@application-developer-DA you are totally right.

WKWebView does not support `getDisplayMedia` and currently, there is no way to share a screen on MacOS.

There are a few solutions that could be a workaround but need implementation:
- A custom `getUserMedia` like Electron and Cordova did.
- The new ScreenCaptureKit framework: https://developer.apple.com/documentation/screencapturekit/capturing_screen_content_in_macos

This is a mandatory feature of our application as we need webrtc screen sharing and the only problem we have as to port it to Tauri/rust from electron is the luck of capturing the video stream of the screen.

Any good soul out there with the knowledge to port electron's implementation of `getUserMedia` or `getDisplayMedia` to WKWebView or can recommend any other solutions for Tauri/rust?

Any recommendations would be very much appreciated.

**Comment by daniel-abramov** [comment] 2022-08-15 19:29
> This is a mandatory feature of our application as we need webrtc screen sharing and the only problem we have as to port it to Tauri/rust from electron is the luck of capturing the video stream of the screen.

Yeah, right. We're in the same boat.

> Any good soul out there with the knowledge to port electron's implementation of getUserMedia or getDisplayMedia to WKWebView or can recommend any other solutions for Tauri/rust?
> Any recommendations would be very much appreciated.

I think the only "viable" (not really unfortunately) option would be using [`webrtc-rs`](https://github.com/webrtc-rs/webrtc), but the client stack for the WebRTC [has not yet been implemented](https://github.com/webrtc-rs/webrtc/issues/94) and is part of a roadmap. There is an open issue to create an example [to use it with Tauri](https://github.com/webrtc-rs/webrtc/issues/111).

I think basically you're left with 2 options here:

1. Rely upon Electron (probably not a desirable option if you're choosing Tauri for the same reason we do).
2. Implement some sort of a [Tauri Plugin](https://tauri.app/v1/guides/features/plugin/) that would bring the desired support of the WebRTC Screen Capturing. This might take a decent amount of time before it matches the feature-set of Electron's `desktopCapturer` though (Disclaimer: I don't have much experience with Tauri plugins, so perhaps this whole idea is also far away from being optimal).

**Comment by towe75** [comment] 2023-04-01 16:06
I'm not a tauri user but i came across the same problem and found this post. 

After quite some digging i was able to get a acceptable solution for my WKWebView based project..

a) ensure to request screen capture permissions for the app itself via CGPreflightScreenCaptureAccess() / CGRequestScreenCaptureAccess()

b) it's necessary to implement a private delegate. I found this here: https://github.com/SafeExamBrowser/seb-mac/issues/150

Try this minimal example that i derived from my own project:

```
@protocol WKUIDelegatePrivateTauri <NSObject>

typedef NS_OPTIONS(NSUInteger, _WKCaptureDevices) {
    _WKCaptureDeviceMicrophone = 1 << 0,
    _WKCaptureDeviceCamera = 1 << 1,
    _WKCaptureDeviceDisplay = 1 << 2,
};

- (void)_webView:(WKWebView *)webView requestUserMediaAuthorizationForDevices:(_WKCaptureDevices)devices url:(NSURL *)url mainFrameURL:(NSURL *)mainFrameURL decisionHandler:(void (^)(BOOL authorized))decisionHandler;
@end

@interface TauriDelegate : NSObject <WKUIDelegatePrivateTauri>

@end

@implementation TauriDelegate

- (void)_webView:(WKWebView *)webView
      requestUserMediaAuthorizationForDevices:(_WKCaptureDevices)devices url:(NSURL *)url
      mainFrameURL:(NSURL *)mainFrameURL
      decisionHandler:(void (^)(BOOL authorized))decisionHandler
{
    decisionHandler(true);
}

@end
```

With this i was able to get a media stream. Although the chooser is still missing. It shares the screen with the browser view on it. 

Maybe the situation improves with a later webkit version. Seems they work on it: https://github.com/WebKit/WebKit/pull/9789

Hope this helps you! 
Who knows, maybe i will use tauri for a future project ;-)

**Comment by veaba** [comment] 2023-05-11 16:50
+1 
Can't  record audio.
![image](https://github.com/tauri-apps/tauri/assets/8652596/2d52064b-3f4b-4e9b-aa6e-27e7ffdd60f8)

**Comment by ZhoufangErqiangu** [comment] 2023-08-25 09:45
i got same error on ubuntu 22.04. i am sure my code works well in browsers.

**Comment by FabianLars** [comment] 2023-08-29 09:25
This issue is about macOS. On Linux, even though it's the same error message, the cause is different == webrtc just isn't a thing in webkitgtk yet (to be exact, it is being worked on but hidden behind a build flag only distro maintainers can flip)

**Comment by stolinski** [comment] 2023-09-05 23:23
Has anyone managed to get this working? Just calling getDisplayMedia leads to the same errors @cliqer was having in 2022.

**Comment by cliqer** [comment] 2023-09-06 00:15
@stolinski, this has been fixed in [Webkit v16.1](https://developer.apple.com/documentation/safari-release-notes/safari-16_1-release-notes) on Ventura.
This means that getDisplayMedia only works if your Tauri app runs on Ventura with the latest Safari.

**Comment by stolinski** [comment] 2023-09-06 00:33
<img width="814" alt="Screenshot 2023-09-05 at 6 32 38 PM" src="https://github.com/tauri-apps/tauri/assets/669383/be66a7c7-b1a5-401c-9dd6-7898ebea7757">

Wild I'm on Sonoma and hitting permissions issues. I need to find how to reset permissions in this app if they have been denied somehow.

**Comment by cliqer** [comment] 2023-09-06 00:47
@stolinski try the following if you haven't. Hope it helps:
```
// src-tauri/info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>Request camera access for WebRTC</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>Request microphone access for WebRTC</string>
</dict>
</plist>
```
```
//src-tauri/Release.entitlements
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.automation.apple-events</key>
    <true/>
    <key>com.apple.security.device.usb</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>
```
in your tauri.conf.json:
```json
{
 {
 "tauri": {
  "macOSPrivateApi": true,
  "bundle": {
      "active": true,
      "macOS": {
        "entitlements": "Release.entitlements",
        "exceptionDomain": "",
        "frameworks": [],
      },
      "resources": [],
      "targets": ["app"],
      }
    },
    "security": {
      "csp": null
    }
  }
}

**Comment by stolinski** [comment] 2023-09-06 01:09
Thanks for the help @cliqer but sadly no dice. Still hitting the same permissions error.

**Comment by stolinski** [comment] 2023-09-06 15:25
So I can confirm that getDisplayMedia has been added to WKWebView it does not work within Tauri still because there is no permission dialog and therefore the request for getDisplayMedia will always return a permission denied error. So this seems to be an issue with Tauri as is right now as you are unable to grant permissions to use getDisplayMedia.

**Comment by cliqer** [comment] 2023-09-06 15:31
@stolinski it works for me and dialogue is being displayed in the latest Tauri v1 and Ventura 13.5.1 (22G90):
<img width="297" alt="image" src="https://github.com/tauri-apps/tauri/assets/3495993/eea7262e-551c-41df-969e-08b2e7955002">
I am requesting it simply like this:
```js
return await navigator.mediaDevices.getDisplayMedia({
            audio: false,
            video: true
})
```

**Comment by stolinski** [comment] 2023-09-06 15:44
Is this in development? How frustrating. I'm on Sonoma, latest Tauri v1 and just getting the permissions failed instantly with the same getDisplayMedia code to request. 

Do you know of a way to reset permissions completely on a Tauri app? I've tried building for production and got the same permission failure immediately.

**Comment by stolinski** [comment] 2023-09-06 16:56
Just fired up a totally fresh Tauri app, requested 
```
navigator.mediaDevices.getDisplayMedia({
            audio: false,
            video: true
})
```
And got hit with the same permission denied error without a dialogue. Now wondering if this is a Sonoma related issue. (on 14.0 Beta (23A5337a))

**Comment by stolinski** [comment] 2023-09-16 20:48
Small update on this. 

I can confirm that the permissions prompt is being issued on MacOS v13 but not on v14, which is still unreleased although in rc. I'll update again once the OS is official.
```
[✔] Environment
    - OS: Mac OS 14.0.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.1 (eb26296b5 2023-08-03)
    ✔ Cargo: 1.71.1 (7f1d04c00 2023-07-29)
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.5.0
    - pnpm: 8.5.0
    - yarn: 1.22.19
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.14
    - tauri-build [RUST]: 2.0.0-alpha.8
    - wry [RUST]: 0.33.0
    - tao [RUST]: 0.22.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.14

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

**Comment by seanaye** [comment] 2023-10-03 19:22
I'm on tauri v2 and MacOS 13.5.1. Sometime the `getDisplayMedia` call is really long, like multiple seconds, when my app is not doing anything, completely idle. Sometime it the permission dialog appears instantly and sometimes it takes up to 30seconds. Should I open this as a separate issue?

**Comment by cliqer** [comment] 2023-10-03 20:43
Upgraded to Sonoma v14 and previous implementation doesn't work anymore.
I assume this has to do with [Safari 17 changes in WebRTC](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#WebRTC).

**Comment by GorIvanov** [comment] 2023-10-13 15:26
Same in the linux (Arch)!

getUserMedia error: 
NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

webkit2gtk version is 2.42.1-1
It should work fine with webRTC, but.....

Is there any thought when this will be fixed?

**Comment by FabianLars** [comment] 2023-10-13 16:08
No idea when this will be fixed, the webkitgtk didn't gave any ETAs or hints but they are actively working on it.

Oh and to be clear, Linux does not have webrtc support yet so there isn't any "bug" preventing it, it's just not there yet.

**Comment by tarushnagpal** [comment] 2023-10-19 12:09
> Upgraded to Sonoma v14 and previous implementation doesn't work anymore.
I assume this has to do with [Safari 17 changes in WebRTC](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#WebRTC).

@cliqer I am not sure that is the case, I just launched a simple WebView from xcode with a target of Sonoma 14.0 and did a simple `navigator.mediaDevices.getDisplayMedia()` and it worked, this might be something tauri specific not sure though

**Comment by callumcox** [comment] 2023-10-22 22:11
I've been hitting the same problem and think I've narrowed it down to the flags supplied to the webview in Wry...

Using `webkit2gtk-4.0` (running on Ubuntu), if I start a WebView pointing at the same application as I'm firing up in Tauri Media Stream and Web RTC are defaulted to off.  If I start a WebView with `--enable-media-stream=true` and `--enable-webrtc=true` the view correctly prompts for permissions when `navigator.mediaDevices.getUserMedia({ audio: true, video: true })` is called and can then call `navigator.mediaDevices.enumerateDevices()`.

Looking at the [args supplied to the webview](https://github.com/tauri-apps/wry/blob/f2299c2e02bc93acd3ba12e7d1dd21859e50c49f/src/webview/mod.rs#L338C44-L338C44) these flags aren't being supplied and so I'm assuming it's defaulting to webkit2gtk's defaults of off (though this is based on a cursory inspection of the code and some extrapolation based on what I've observed).

I also couldn't find a way to supply additional args to enable these on the target platform that exists for Windows.

**Comment by stolinski** [comment] 2023-11-10 18:47
@callumcox 
Were you able to supply those flags in an app with Tauri apis?

**Comment by tarushnagpal** [comment] 2023-11-16 08:25
> Upgraded to Sonoma v14 and previous implementation doesn't work anymore. I assume this has to do with [Safari 17 changes in WebRTC](https://developer.apple.com/documentation/safari-release-notes/safari-17-release-notes#WebRTC).

@cliqer Were you able to get this to work in MacOS?

**Comment by cliqer** [comment] 2023-11-23 11:46
> @cliqer Were you able to get this to work in MacOS?

@tarushnagpal Unfortunately no

**Comment by tarushnagpal** [comment] 2023-11-23 12:34
> > @cliqer Were you able to get this to work in MacOS?
> 
> @tarushnagpal Unfortunately no

Damn, Launching a webview in a fresh xcode app and calling a `getDisplayMedia` works just fine, has to be something with how we instantiate the web view from tauri, will get time to take a look over the weekend hopefully 🤞.

**Comment by seanaye** [comment] 2023-11-27 16:03
@tarushnagpal any updates?

**Comment by tarushnagpal** [comment] 2023-11-30 13:56
Was able to identify and fix the issue here https://github.com/tauri-apps/wry/pull/1107, thanks to @pewsheen recognising where the bug resided!

**Comment by seanaye** [comment] 2024-01-17 13:32
awesome, thanks! Can this issue be closed now?

**Comment by FabianLars** [comment] 2024-01-17 14:59
If someone using the latest tauri version and macos 14 can confirm that this pr helped, yes :)

**Comment by szymeo** [comment] 2024-01-18 18:38
@FabianLars could you elaborate please? I just created a new project with latest tauri and still experience the issue

**Comment by cliqer** [comment] 2024-01-18 18:41
I checked on the latest v2.alpha with Sonoma, and it works.
Unfortunately, it doesn't work on v1; I had to migrate my project :/

**Comment by tarushnagpal** [comment] 2024-01-18 18:44
@cliqer I think the latest tauri v1 doesn't have the latest wry package, it was only released in [wry v0.35.1](https://github.com/tauri-apps/wry/releases/tag/wry-v0.35.1), What I have done in my release pipeline is use my own "local" version of tauri with a changed Cargo.toml for wry runtime pointing to 0.35.1

**Comment by FabianLars** [comment] 2024-01-18 18:56
Cool, thanks for confirming. Backporting it to wry 0.24 (the version tauri v1 uses) should be fairly straightforward.

**Closed as completed by FabianLars** 2024-01-18 18:56 UTC
Labels: type: bug, priority: 2 medium, platform: macOS

**Comment by matthiasg** [comment] 2024-01-31 10:37
@FabianLars not possible in 1.5.4 yet correct ?

**Comment by FabianLars** [comment] 2024-01-31 11:32
correct

**Comment by matthiasg** [comment] 2024-01-31 11:46
Any work scheduled to backport ?

**Comment by FabianLars** [comment] 2024-01-31 12:14
no, we're focused on getting v2 to beta right now. if someone opens a pr we can take a look though.

**Comment by nzoschke** [comment] 2024-01-31 22:28
Thanks, in general this is working for me with V2 and the Info.plist.

But with `await navigator.mediaDevices.enumerateDevices()` I see devices missing in the Tauri app that are available in standard OSX Safari app.

```
await navigator.mediaDevices.getUserMedia({
  audio: true,
  video: false,
});
var devices = await navigator.mediaDevices.enumerateDevices()
console.log(JSON.stringify(devices));
```

Tauri:

```json
[
  {"deviceId":"5FF5BAB0009113ACC1477BDA0A1EA60FF64D5CC7","kind":"audioinput","label":"MacBook Pro Microphone","groupId":"19306579CF9380E2372D7691ACE283DC31F4AE7B"},
  {"deviceId":"97062E9CE4E98A8320BB77F306345F12C07B5A53","kind":"audioinput","label":"Noah’s iPhone Microphone","groupId":"658F702E23F4D59C4D4CFE26C601542AFBFC64BA"},
  {"deviceId":"C8645C00DC77A82269219035D29208FC86D836DD","kind":"videoinput","label":"FaceTime HD Camera","groupId":""},
  {"deviceId":"2E8657E4F1B108EF7CFD060F2BF66A340E221F7D","kind":"videoinput","label":"OBS Virtual Camera","groupId":""},
  {"deviceId":"084BE7A852816C49220C06FA8DF0ED0265EEB29F","kind":"videoinput","label":"Noah’s iPhone Camera","groupId":""},
  {"deviceId":"2D227FB9C6D1138E1769DFE648589478ADCDEF4B","kind":"videoinput","label":"Noah’s iPhone Desk View Camera","groupId":""}
]
```

Safari Desktop:

```json
[
  {"deviceId":"52ABD94C026B20C3FF3AF37F701E156A1BE7557A","kind":"audioinput","label":"MacBook Pro Microphone","groupId":"082C98394E90C47939E93C4A521FF1E982B9C215"},
  {"deviceId":"3CD54FEBE4DEFCBE248BFD371AD7D1CEED8D417E","kind":"audioinput","label":"BlackHole 16ch","groupId":"F71A04BCA6C2953330B04D6A356896A85DC10F8B"},
  {"deviceId":"279BC0FB9937E89F18F1A04DFA531855FFE2F8DF","kind":"audioinput","label":"XONE 96 USB 1","groupId":"9A76BF4CBE512A38ABC52BA057DDFA3A8B6AA31A"},
  {"deviceId":"F5AEE340A817CCE0D3687ECAE87B0572CD2004B5","kind":"audioinput","label":"Noah’s iPhone Microphone","groupId":"AA5084E4581D1676318EB719F7C8A57951D19576"},
  {"deviceId":"99C9D3E03D55E4E77505F6F1262951F7EC63D8AF","kind":"videoinput","label":"FaceTime HD Camera","groupId":""},
  {"deviceId":"8A5CF3B9CA0470C0F011F520A3E95B25A8A3A5DE","kind":"videoinput","label":"OBS Virtual Camera","groupId":""},
  {"deviceId":"0D5F60A9F4499ABE928B9F7FE9AEE1639B8A5AB1","kind":"videoinput","label":"Noah’s iPhone Camera","groupId":""},
  {"deviceId":"8D37863FA87C4452BBC4477D8839B217FD106677","kind":"videoinput","label":"Noah’s iPhone Desk View Camera","groupId":""}
]
```

The two devices missing are `BlackHole 16ch` which is a virtual audio device from https://github.com/ExistentialAudio/BlackHole and `XONE 96 USB 1` which is an external USB soundcard.

I'll keep digging into if its possible to get access to these devices in Tauri / wry, or Swift / WKWebview, but asking here in case anyone else knows.

**Comment by aryavsaigal** [comment] 2024-02-27 22:18
> Thanks, in general this is working for me with V2 and the Info.plist.
> 
> But with `await navigator.mediaDevices.enumerateDevices()` I see devices missing in the Tauri app that are available in standard OSX Safari app.
> 
> ```
> var devices = await navigator.mediaDevices.enumerateDevices()
> console.log(JSON.stringify(devices));
> ```
> 
> Tauri:
> 
> ```json
> [
>   {"deviceId":"5FF5BAB0009113ACC1477BDA0A1EA60FF64D5CC7","kind":"audioinput","label":"MacBook Pro Microphone","groupId":"19306579CF9380E2372D7691ACE283DC31F4AE7B"},
>   {"deviceId":"97062E9CE4E98A8320BB77F306345F12C07B5A53","kind":"audioinput","label":"Noah’s iPhone Microphone","groupId":"658F702E23F4D59C4D4CFE26C601542AFBFC64BA"},
>   {"deviceId":"C8645C00DC77A82269219035D29208FC86D836DD","kind":"videoinput","label":"FaceTime HD Camera","groupId":""},
>   {"deviceId":"2E8657E4F1B108EF7CFD060F2BF66A340E221F7D","kind":"videoinput","label":"OBS Virtual Camera","groupId":""},
>   {"deviceId":"084BE7A852816C49220C06FA8DF0ED0265EEB29F","kind":"videoinput","label":"Noah’s iPhone Camera","groupId":""},
>   {"deviceId":"2D227FB9C6D1138E1769DFE648589478ADCDEF4B","kind":"videoinput","label":"Noah’s iPhone Desk View Camera","groupId":""}
> ]
> ```
> 
> Safari Desktop:
> 
> ```json
> [
>   {"deviceId":"52ABD94C026B20C3FF3AF37F701E156A1BE7557A","kind":"audioinput","label":"MacBook Pro Microphone","groupId":"082C98394E90C47939E93C4A521FF1E982B9C215"},
>   {"deviceId":"3CD54FEBE4DEFCBE248BFD371AD7D1CEED8D417E","kind":"audioinput","label":"BlackHole 16ch","groupId":"F71A04BCA6C2953330B04D6A356896A85DC10F8B"},
>   {"deviceId":"279BC0FB9937E89F18F1A04DFA531855FFE2F8DF","kind":"audioinput","label":"XONE 96 USB 1","groupId":"9A76BF4CBE512A38ABC52BA057DDFA3A8B6AA31A"},
>   {"deviceId":"F5AEE340A817CCE0D3687ECAE87B0572CD2004B5","kind":"audioinput","label":"Noah’s iPhone Microphone","groupId":"AA5084E4581D1676318EB719F7C8A57951D19576"},
>   {"deviceId":"99C9D3E03D55E4E77505F6F1262951F7EC63D8AF","kind":"videoinput","label":"FaceTime HD Camera","groupId":""},
>   {"deviceId":"8A5CF3B9CA0470C0F011F520A3E95B25A8A3A5DE","kind":"videoinput","label":"OBS Virtual Camera","groupId":""},
>   {"deviceId":"0D5F60A9F4499ABE928B9F7FE9AEE1639B8A5AB1","kind":"videoinput","label":"Noah’s iPhone Camera","groupId":""},
>   {"deviceId":"8D37863FA87C4452BBC4477D8839B217FD106677","kind":"videoinput","label":"Noah’s iPhone Desk View Camera","groupId":""}
> ]
> ```
> 
> The two devices missing are `BlackHole 16ch` which is a virtual audio device from https://github.com/ExistentialAudio/BlackHole and `XONE 96 USB 1` which is an external USB soundcard.
> 
> I'll keep digging into if its possible to get access to these devices in Tauri / wry, or Swift / WKWebview, but asking here in case anyone else knows.

Did you get this working somehow?

**Comment by nzoschke** [comment] 2024-02-29 04:06
I just edited above, calling `await navigator.mediaDevices.getUserMedia({audio: true,video: false})` is important on safari / webkit. But still some devices are missing under Tauri.

**Comment by stolinski** [comment] 2024-03-18 04:38
I am unable to get this working still in dev mode via `pnpm tauri dev`.

After updating everything, I am now able to successfully get the prompt on fully built apps. 

Is this a limitation that I'll have to work around or should getDisplayMedia permissions prompt correctly in dev.

In dev I see the same NotAllowedError.

```
[✔] Environment
    - OS: Mac OS 14.4.0 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.10.0
    - pnpm: 8.14.1
    - npm: 10.2.3
    - bun: 1.0.25

[-] Packages
    - tauri [RUST]: 2.0.0-beta.11
    - tauri-build [RUST]: 2.0.0-beta.9
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.5
    - @tauri-apps/cli [NPM]: 2.0.0-beta.9

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

Happens even in a brand new project. I'd be interested in seeing what's different in a working example on your end from what's going on with me.

**Comment by tarushnagpal** [comment] 2024-03-18 09:06
Hey, won't [this PR](https://github.com/tauri-apps/wry/pull/1186) break all mac versions between 14.0 to 14.2? we should probably still have that check in but just for versions between these so that the notification does not get suppressed

**Comment by pewsheen** [comment] 2024-03-18 10:42
> I am unable to get this working still in dev mode via `pnpm tauri dev`.
> 
> After updating everything, I am now able to successfully get the prompt on fully built apps.
> 
> Is this a limitation that I'll have to work around or should getDisplayMedia permissions prompt correctly in dev.
> 
> In dev I see the same NotAllowedError.
> 
> ```
> [✔] Environment
>     - OS: Mac OS 14.4.0 X64
>     ✔ Xcode Command Line Tools: installed
>     ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
>     ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
>     ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
>     ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
>     - node: 20.10.0
>     - pnpm: 8.14.1
>     - npm: 10.2.3
>     - bun: 1.0.25
> 
> [-] Packages
>     - tauri [RUST]: 2.0.0-beta.11
>     - tauri-build [RUST]: 2.0.0-beta.9
>     - wry [RUST]: 0.37.0
>     - tao [RUST]: 0.26.1
>     - @tauri-apps/api [NPM]: 2.0.0-beta.5
>     - @tauri-apps/cli [NPM]: 2.0.0-beta.9
> 
> [-] App
>     - build-type: bundle
>     - CSP: unset
>     - frontendDist: ../dist
>     - devUrl: http://localhost:1420/
>     - framework: Svelte
>     - bundler: Vite
> ```
> 
> Happens even in a brand new project. I'd be interested in seeing what's different in a working example on your end from what's going on with me.

It's kind of tricky when running `tauri dev`. It's actually asking the permission for where you call the `dev` command, like Terminal or vscode

**Comment by pewsheen** [comment] 2024-03-18 10:47
> Hey, won't [this PR](https://github.com/tauri-apps/wry/pull/1186) break all mac versions between 14.0 to 14.2? we should probably still have that check in but just for versions between these so that the notification does not get suppressed

Yes, it will break those versions. We can do a version check for it, but we don't know the actual affected version yet. What we know is 14.0 is affected, and doesn't know which exact version that Apple changed the behavior back. It would take time to test it.

**Comment by stolinski** [comment] 2024-03-18 15:56
> It's kind of tricky when running `tauri dev`. It's actually asking the permission for where you call the `dev` command, like Terminal or vscode

That tracks. Is there anyway to get those perms accepted on initialization or is using getDisplayMedia in `tauri dev` just out of the question.

**Comment by tarushnagpal** [comment] 2024-03-19 09:00
> Yes, it will break those versions. We can do a version check for it, but we don't know the actual affected version yet. What we know is 14.0 is affected, and doesn't know which exact version that Apple changed the behavior back. It would take time to test it.

It would be better to test it rather than knowingly release a Tauri version that would break on some MacOS versions imo 😅

**Comment by pewsheen** [comment] 2024-03-20 08:12
> > It's kind of tricky when running `tauri dev`. It's actually asking the permission for where you call the `dev` command, like Terminal or vscode
> 
> That tracks. Is there anyway to get those perms accepted on initialization or is using getDisplayMedia in `tauri dev` just out of the question.

I don't know how it really works under the ground, but from my experience, I can use `tauri dev` for `getDisplayMedia` after I grant permission to my vscode or iTerm

**Comment by stolinski** [comment] 2024-04-05 19:53
> > > It's kind of tricky when running `tauri dev`. It's actually asking the permission for where you call the `dev` command, like Terminal or vscode
> > 
> > 
> > That tracks. Is there anyway to get those perms accepted on initialization or is using getDisplayMedia in `tauri dev` just out of the question.
> 
> I don't know how it really works under the ground, but from my experience, I can use `tauri dev` for `getDisplayMedia` after I grant permission to my vscode or iTerm

Did you just add it via the MacOS Perms in system prefs? I've given term and vscode screen recording perms but still no go in dev mode.

**Comment by pewsheen** [comment] 2024-04-08 01:40
> > > > It's kind of tricky when running `tauri dev`. It's actually asking the permission for where you call the `dev` command, like Terminal or vscode
> > > 
> > > 
> > > That tracks. Is there anyway to get those perms accepted on initialization or is using getDisplayMedia in `tauri dev` just out of the question.
> > 
> > 
> > I don't know how it really works under the ground, but from my experience, I can use `tauri dev` for `getDisplayMedia` after I grant permission to my vscode or iTerm
> 
> Did you just add it via the MacOS Perms in system prefs? I've given term and vscode screen recording perms but still no go in dev mode.

It turns out they are two different issues https://github.com/tauri-apps/wry/issues/1195

It may work with `tauri-beta.12` and below and with macOS 14+ since we revert https://github.com/tauri-apps/wry/pull/1111 at `wry-0.38`. But with the latest tauri release you'll need to patch Wry as a workaround, like what https://github.com/tauri-apps/wry/pull/1111 does but without version check.

**Comment by ktecho** [comment] 2024-07-23 21:04
Should this work for all the desktop OS? I read all the issues here are with Mac...

I'm trying on Linux with Tauri v2, but I cannot get the permission dialog to appear...

**Comment by FabianLars** [comment] 2024-07-24 08:01
@ktecho Linux (webkitgtk) does not support webrtc at all yet. So we're not just talking about permissions issues there.

**Comment by ktecho** [comment] 2024-07-24 08:32
> @ktecho Linux (webkitgtk) does not support webrtc at all yet. So we're not just talking about permissions issues there.

So there is no way to scan a QR code with Tauri on Linux?

**Comment by FabianLars** [comment] 2024-07-24 08:33
Not in the frontend at least. There should be some camera Rust crates that should support Linux.

**Comment by kamalkech** [comment] 2024-10-16 22:35
> [cliqer](/cliqer)

what about windows and linux ??
