### ISSUE TITLE
[bug] Can't call base64 PowerShell command in tauri

### ISSUE THREAD

**Issue by Bukmopbl4** [tauri-apps/tauri#5769] opened 2022-12-05 23:26 UTC
### Describe the bug

<img width="896" alt="image" src="https://user-images.githubusercontent.com/19820469/205934600-56fd8edd-8390-41d7-903e-3af606e84418.png">

I can't call PowerShell command in base64 mode in tauri.

### Reproduction

await new window.__TAURI__.shell.Command('powershell.exe',['-exec', 'bypass', '-enc', 'ZQBjAGgAbwAgADEAMgAzADQA']).execute();

### Expected behavior

expected response {code: 0, signal: null, stdout: '1234\r', stderr: ''}

### Platform and versions

Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 107.0.1418.62
  › MSVC: 
      - Visual Studio Build Tools 2022
  › Node.js: 16.18.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-i686-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0 (outdated, latest: 1.2.1)

**Comment by amrbashir** [comment] 2022-12-06 01:35
try `await new window.__TAURI__.shell.Command('powershell',['-exec', 'bypass', '-enc', 'ZQBjAGgAbwAgADEAMgAzADQA']).execute();`

You can't use `-c` with `-enc`

**Comment by Bukmopbl4** [comment] 2022-12-06 14:07
> try `await new window.__TAURI__.shell.Command('powershell',['-exec', 'bypass', '-enc', 'ZQBjAGgAbwAgADEAMgAzADQA']).execute();`
> 
> You can't use `-c` with `-enc`

Yes, you are right, right without "-с". I made a mistake in the example, but the essence does not change. The command is not working.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/19820469/205933676-8274c321-dd89-45a3-ba12-27b7ca571e89.png">

**Comment by amrbashir** [comment] 2022-12-06 18:53
duplicate of #5309

**Closed as not planned by amrbashir** 2022-12-06 18:53 UTC
Labels: type: bug, status: needs triage

**Comment by Bukmopbl4** [comment] 2022-12-06 21:55
![](https://user-images.githubusercontent.com/19820469/206026731-e8d469bd-df7a-47b1-ae26-048f29ca67f5.png)
works now
