### ISSUE TITLE
[feat] Allow the Window Menu to be modified within the frontend

### ISSUE THREAD

**Issue by TechStudent10** [tauri-apps/tauri#6796] opened 2023-04-25 16:58 UTC
### Describe the problem

I feel as if a lot of applications modify their menus dynamically. But you can only add the menu once, at the beginning of the application, in the backend. That means applications cannot change their menus, not in the backend nor the frontend.

### Describe the solution you'd like

I would like a `tauri-api` function that allows you to change the menus. If not, at least in Tauri commands.

**Comment by amrbashir** [comment] 2023-04-25 17:39
duplicate of https://github.com/tauri-apps/tauri/issues/6617

**Closed as not planned by amrbashir** 2023-04-25 17:39 UTC
Labels: type: feature request
