### ISSUE TITLE
[bug] V2 Tauri custom titlebar unable to resize when decorations is false

### ISSUE THREAD

**Issue by Sir-Thom** [tauri-apps/tauri#8519] opened 2024-01-01 16:49 UTC
### Describe the bug

I was trying v2 of tauri and I noticed that if you set decorations to false in the tauri.conf.json  the ability to resize the application is impossible even if you set resizable to true.

### Reproduction

1.  `npm create tauri-app@latest -- --alpha`
2.  add the demo titlebar to the project :
3.  make those configuration in the tauri.conf.json : 
```
{
  "build": {
    "beforeDevCommand": "yarn dev",
    "beforeBuildCommand": "yarn build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist",
    "withGlobalTauri": true
  },
  
  "package": {
    "productName": "tauri-app",
    "version": "0.0.0"
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
    },
    "security": {
      "csp": null
    },
    
    "windows": [
      {
        "decorations": false,
        "fullscreen": false,
        "resizable": true,
        "title": "tauri-app",
        "width": 800,
        "height": 600
      }
    ]
  },
  "plugins": {
    "shell": {
      "open": true
    },
    "allowlist":{
      "all": true,
      "window": {
        "center": false,
        "close": true,
        "create": false,
        "hide": false,
        "maximize": true,
        "minimize": true,
        "print": false,
        "requestUserAttention": false,
        "setAlwaysOnTop": false,
        "setCursorGrab": true,
        "setCursorIcon": true,
        "setCursorPosition": false,
        "setCursorVisible": false,
        "setDecorations": false,
        "setFocus": true,
        "setFullscreen": true,
        "setIcon": true,
        "setMaxSize": false,
        "setMinSize": false,
        "setPosition": false,
        "setResizable": true,
        "setSize": true,
        "setSkipTaskbar": false,
        "setTitle": true,
        "show": true,
        "startDragging": true,
        "unmaximize": true,
        "unminimize": true

      }
    }
  }
}
```

### Expected behavior

the application is able to be resize when decorations is set to false

### Full `tauri info` output

```text
[✔] Environment
    - OS: openSUSE 20231226 X64
    ✔ webkit2gtk-4.1: 2.42.4
    ✔ rsvg2: 2.57.0
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 21.4.0
    - pnpm: 8.11.0
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.20
    - tauri-build [RUST]: 2.0.0-alpha.13
    - wry [RUST]: 0.35.1
    - tao [RUST]: 0.24.0
    - tauri-cli [RUST]: 2.0.0-alpha.20
    - @tauri-apps/api [NPM]: 2.0.0-alpha.13
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.20

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

### Additional context

I have tested this on Linux and Windows  and the same bug happen and I am pretty sure it also the same thing on macOS

**Comment by percy507** [comment] 2024-01-02 01:58
I can confirm same bug on Windows10/11 with same tauri version (2.0.0-alpha.20). (If `set_decorations(false)`, then the window can't resize by mouse.)

There is a minimal demo. https://github.com/percy507/test-tauri-v2/tree/cannot-resize

**Comment by drl990114** [comment] 2024-01-11 07:19
same question

**Comment by FabianLars** [comment] 2024-01-11 09:17
The pr that fixes it is linked right above your comment 😅
![grafik](https://github.com/tauri-apps/tauri/assets/30730186/655f3c3c-b7f3-4bfa-8707-1e008f7b201a)
It will be part of the next alpha release.

**Comment by drl990114** [comment] 2024-01-11 11:04
ok thanks i will wait for this

**Comment by mattjoe480** [comment] 2024-01-18 12:09
Is there any way to downgrade tauri package to a working version. when i change version in cargo it gets ignored

**Closed as completed** 2024-01-18 17:34 UTC
Labels: type: bug, priority: 1 high, status: needs triage

**Comment by drl990114** [comment] 2024-01-31 08:25
@FabianLars Excuse me again, when will the next version be released? Alpha.21 does not seem to include a fix for this issue

**Comment by FabianLars** [comment] 2024-01-31 08:26
beta.0 will be released this week. No new alpha before that.

**Comment by drl990114** [comment] 2024-01-31 08:46
> beta.0 will be released this week. No new alpha before that.

Okay, thank you !

**Comment by pzyyll** [comment] 2024-05-27 11:57
This bug seems to still exist in the latest version(beta.20)?

**Comment by ReduxFlakes** [comment] 2024-06-13 22:24
I can confirm that in Tauri.beta.22 the issue persists. 
Looks like I can only resize from the left side of the Window. Also when I have the mouse half way from the TitleBar, the mouse changes to the resize cursor but I still can't resize and also not drag the window.

**Comment by amrbashir** [comment] 2024-06-13 23:55
Should be fixed in the next release with https://github.com/tauri-apps/tauri/pull/9862

**Comment by cck190891** [comment] 2024-07-07 10:22
Hi, I'm using the beta.23 version. In the initial project,`"decorations": false` resizing the window works fine, but when I add `unstable `to the Tauri features, it stops working. Is there a way to solve this?

**Comment by patrik-u** [comment] 2024-10-09 16:14
Using Tauri 2.0.2, unstable, with multiwebview and setting decorations to false makes it so I can't resize the window. The resize cursor sometimes triggers on the top part of my window but not anywhere else. 

```rust
tauri = { version = "2.0.2", features = ["unstable"] }

....

   let window = tauri::window::WindowBuilder::new(app, "main")
                .inner_size(width, height)
                .decorations(false)
                .resizable(true)
                .title("Vibe")
                .build()?;

            let browser_view = window.add_child(
                tauri::webview::WebviewBuilder::new(
                    "browser",
                    WebviewUrl::External("https://github.com/tauri-apps/tauri".parse().unwrap()),
                ),
                LogicalPosition::new(0., top_bar_height),
                LogicalSize::new(width, height - top_bar_height),
            )?;

            let top_bar_view: tauri::Webview = window.add_child(
                tauri::webview::WebviewBuilder::new("top-bar", WebviewUrl::App("top-bar".into())),
                LogicalPosition::new(0., 0.),
                LogicalSize::new(width, top_bar_height),
            )?;

            // Listen for resize events and adjust the child webviews accordingly
            window.on_window_event(move |event| {
                if let WindowEvent::Resized(new_size) = event {
                    let new_width = new_size.width;
                    let new_height = new_size.height;

                    // Resize the top bar (keeping its height constant)
                    top_bar_view
                        .set_size(LogicalSize::new(new_width, top_bar_height as u32))
                        .expect("Failed to resize top bar");

                    // Resize the browser view to fill the remaining space
                    browser_view
                        .set_size(LogicalSize::new(
                            new_width,
                            new_height - top_bar_height as u32,
                        ))
                        .expect("Failed to resize browser view");

                    // Move the browser view to start below the top bar
                    browser_view
                        .set_position(LogicalPosition::new(0., top_bar_height))
                        .expect("Failed to reposition browser view");
                }
            });
```

**Comment by tedsteen** [comment] 2024-11-14 14:18
It seems to still be an issue. When doing `window_builder.decorations(false)` the window cannot be resized by f.ex doing `getCurrentWindow().setSize(...)` in javascript.
I'm on latest Tauri (2.1.1)

It works fine on MacOS, the issue is on windows (I have only tried Windows 11)

**Comment by tedsteen** [comment] 2024-11-15 17:54
Interesting detail.. If you set `window_builder.shadow(false)` resizing works again.. 🤔🤔

**Comment by lanten** [comment] 2024-11-25 09:50
> It seems to still be an issue. When doing `window_builder.decorations(false)` the window cannot be resized by f.ex doing `getCurrentWindow().setSize(...)` in javascript. I'm on latest Tauri (2.1.1)
> 
> It works fine on MacOS, the issue is on windows (I have only tried Windows 11)

same question
