### ISSUE TITLE
[bug]  cannot download file 

### ISSUE THREAD

**Issue by kknono** [tauri-apps/tauri#6305] opened 2023-02-18 01:56 UTC
### Describe the bug

hi,
it cannot download file, but it works well in native browser.
codes like:

import { saveAs } from "file-saver";
 saveAs(anyBlob, "test.xlsx");

### Platform and versions

Environment
  › OS: Mac OS 13.0.1 X64
  › Node.js: 16.17.0
  › npm: 9.5.0
  › pnpm: 7.13.4
  › yarn: 1.22.11
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

**Comment by FabianLars** [comment] 2023-02-18 09:36
should be a duplicate of #4633. thanks for the report.

**Closed as not planned by FabianLars** 2023-02-18 09:36 UTC
Labels: type: bug, status: needs triage
