### ISSUE TITLE
Windows Defender Trojan detected 

### ISSUE THREAD

**Issue by jdheeter** [tauri-apps/tauri#2640] opened 2021-09-23 02:11 UTC
![image](https://user-images.githubusercontent.com/2530957/134445284-de31184d-ee74-4867-b2d3-7e7f4bebc83c.png)
Detected: Trojan:Script/Sabsik.TE.A!ml

## tauri info
``` Operating System - Windows, version 10.0.19042 X64
Webview2 - 93.0.961.52

Node.js environment
  Node.js - 14.17.6
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.24.0
  yarn - 1.22.11

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/.git
/.github
/.quasar
/.vscode
/dist
/node_modules
/public
/src
/src-pwa
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist/pwa
  devPath - http://localhost:8080
  framework - Vue.js (Quasar)
  bundler - Webpack 

```
## cargo.toml
```
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "app"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.2" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
fs2 = "0.4.3"
# winreg = "0.10.1"

[dependencies.tauri]
version = "1.0.0-beta.8"
features = ["api-all", "system-tray"]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

```

**Comment by amrbashir** [comment] 2021-10-30 06:31
duplicate of #2486

**Closed as completed** 2021-10-30 06:31 UTC
Labels: status: invalid
