### ISSUE TITLE
[bug] iOS init with node package manager fails to detect required dependency exist

### ISSUE THREAD

**Issue by pewsheen** [tauri-apps/tauri#8941] opened 2024-02-22 02:47 UTC
### Describe the bug

Failed to run `pnpm tauri ios init`

**Error Message**
```sh
> recipies@0.0.0 tauri /Users/jason/Documents/tauri-docs/recipies
> tauri "ios" "init"

/Users/jason/Documents/tauri-apps/tauri/tooling/cli/node
use remote
        # don't mind this, I am tracking down this issue
        Info "/Users/jason/Documents/tauri-docs/recipies/node_modules/.bin/../../../../tauri-apps/tauri/tooling/cli/node/tauri.js" relative to "/Users/jason/Documents/tauri-docs/recipies/src-tauri/gen/apple" is "../../../node_modules/.bin/../../../../tauri-apps/tauri/tooling/cli/node/tauri.js" 
        Info detected rustc version 1.75.0 (82e1608df 2023-12-21)
        Info package `xcodegen` present: false
Installing `xcodegen`...
       Error failed to install Apple dependencies: Failed to install `xcodegen`: command ["brew", "reinstall", "xcodegen"] exited with code 1: command ["brew", "reinstall", "xcodegen"] exited with code 1
```

- Run with `cargo tauri ios init` is good; `pnpm`, `npm`, `yarn` failed, suspecting only node cli binary has the issue
- All happens when executing `duct::cmd(...).run()`
  - Some commands are fine, like `cd`, `rustc --version (why)`
  - Most of the command return with exited code 1: `echo`, `command`, `xcodegen`, `brew`
  - However, using `duct::cmd` with `capture_stdout().run()` will success

### Reproduction

1. Create Tauri app with CTA `pnpm create tauri-app --beta`
2. `pnpm install` then `pnpm tauri ios init`

### Expected behavior

Run `pnpm tauri ios init` successfully

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.11.1
    - pnpm: 8.14.1
    - yarn: 1.22.19
    - npm: 10.2.4
    - bun: 1.0.26

[-] Packages
    - tauri [RUST]: 2.0.0-beta.3
    - tauri-build [RUST]: 2.0.0-beta.2
    - wry [RUST]: 0.36.0
    - tao [RUST]: 0.25.0
    - tauri-cli [RUST]: 2.0.0-beta.2
    - @tauri-apps/api [NPM]: 2.0.0-beta.1
    - @tauri-apps/cli [NPM]: 2.0.0-beta.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

### Additional context

Discord support: https://discord.com/channels/616186924390023171/1209297064505376898

**Comment by pewsheen** [comment] 2024-02-22 06:44
Seems broken after commit https://github.com/tauri-apps/tauri/commit/c426c0dca2ad5d8bc8e2ed458658234f5c2e132c

**Comment by lucasfernog** [comment] 2024-02-22 12:19
I'm investigating this. Duplicate of #6203

**Closed as completed by lucasfernog** 2024-02-22 12:19 UTC
Labels: type: bug, status: needs triage
