### ISSUE TITLE
build failed when productName contain chinese word[bug] 

### ISSUE THREAD

**Issue by xzf158** [tauri-apps/tauri#7166] opened 2023-06-08 14:28 UTC
### Describe the bug

when run `yarn tauri build --target i686-pc-windows-msvc`, get  error like blow, It's work find on Tauri  1.2.0, but get error on Tauri 1.3.0
  
Running makensis.exe to produce D:\Projects\tauri-super-tool\src-tauri\target\i686-pc-windows-msvc\debug\bundle\nsis\你好_0.2.0_x86-setup.exe
File: "D:\Projects\tauri-super-tool\src-tauri\target\i686-pc-windows-msvc\debug\浣犲ソ.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "D:\Projects\tauri-super-tool\src-tauri\target\i686-pc-windows-msvc\debug\nsis\x86\installer.nsi" on line 421 -- aborting creation process
       Error failed to bundle project: `系统找不到指定的文件。 (os error 2)`

### Platform and versions

```text
OS: Windows 10.0.22621 X64
    ✔ WebView2: 112.0.1722.68
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.16.0
    - yarn: 1.22.19
    - npm: 9.6.7
```

### Additional context

  "package": {
    "productName": "你好",
    "version": "0.2.0"
  },

**Comment by amrbashir** [comment] 2023-06-08 14:30
duplicate of https://github.com/tauri-apps/tauri/issues/7036, will be fixed in the next release.

**Closed as not planned by amrbashir** 2023-06-08 14:30 UTC
Labels: type: bug, status: needs triage
