### ISSUE TITLE
[feat] The app couldn't run on android 7 (Nogutat) emulator or physical device by tauri build

### ISSUE THREAD

**Issue by ximing-xu** [tauri-apps/tauri#9516] opened 2024-04-20 05:11 UTC
### Describe the problem

use tauri version is 2.0.0-beta, and I run this command to build an android apk, the app can install on android 7 physical device, but it could not open, it will quick crash. is there any way to build android apk by tauri that can run on android 7 device? is there any spacial way to config tauri to build android 7 apk?

### Describe the solution you'd like

1. `npm run tauri android dev` The android 7 emulator could not open the app, it will show the app has stopped
2. `npm run tauri android build` ,I install this apk on an android 7 device,  When I try to open the app, it closes quickly

**Comment by bigrocs** [comment] 2024-08-16 03:41
有解决吗 我的7也崩溃 11以下可以打开但是白屏

**Comment by loikki** [comment] 2024-08-20 06:39
Duplicate of #8788

**Comment by ximing-xu** [comment] 2024-08-27 07:29
is the bug was fixed? It still happen in tauri-2.0.0-rc5

**Comment by loikki** [comment] 2024-08-27 20:58
I am not a maintainer of tauri. Just saying it was already reported. I have never had any answer for the issue and I doubt that anyone will work on that until we get a first release

**Comment by ximing-xu** [comment] 2024-08-28 05:52
got it!

**Comment by FabianLars** [comment] 2024-10-15 06:52
Closing as duplicate of #8788

**Closed as not planned by FabianLars** 2024-10-15 06:52 UTC
Labels: type: feature request, platform: Android
