### ISSUE TITLE
[bug] Dynamic window created with js randomly freezes itself and other windows on focus or drag

### ISSUE THREAD

**Issue by mmpneo** [tauri-apps/tauri#5087] opened 2022-08-29 12:16 UTC
### Describe the bug

Video captured on repro repository
https://user-images.githubusercontent.com/3977499/187198539-4ffc8ad0-6348-4c9a-8942-f949cbc1f387.mp4

### Reproduction

https://github.com/mmpneo/tauri-dynamic-window-freeze

### Platform and versions

Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 104.0.1293.70
  › MSVC:
      - Visual Studio Community�2019
      - Visual Studio Community 2022
  › Node.js: 16.13.0
  › npm: 7.6.1
  › pnpm: 6.11.0
  › yarn: 3.1.1
  › rustup: 1.25.1
  › rustc: 1.65.0-nightly
  › cargo: 1.65.0-nightly
  › Rust toolchain: nightly-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: git+https://github.com/tauri-apps/tauri?branch=dev#ef8ca7b36366c146ac8246aa02ea6f30bc05ca2b (1.0.5),
  › tauri-build [RUST]: git+https://github.com/tauri-apps/tauri?branch=dev#ef8ca7b36366c146ac8246aa02ea6f30bc05ca2b (1.0.4),
  › tao [RUST]: 0.13.3,
  › wry [RUST]: 0.20.2,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ .yarn
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by Moon1102** [comment] 2022-08-30 02:39
@mmpneo  I add this `.titlebar div{ pointer-events: none; }` in inputfield.html, line 39 and feel smoother.

[test video](https://user-images.githubusercontent.com/15380331/187335788-e4816288-c0dd-4de7-82f9-a9c75a4a1469.mov)

Hope it meets your expectations.

**Comment by mmpneo** [comment] 2022-08-30 02:50
@Moon1102 it's definitely smoother , good catch, thank you.
freezes still occurs on win10 tho.

**Comment by amrbashir** [comment] 2022-08-30 14:22
duplicate of https://github.com/tauri-apps/tauri/issues/4870 , will be fixed in the next release

**Comment by FabianLars** [comment] 2022-08-30 14:27
We tested it with tauri's git version

**Comment by amrbashir** [comment] 2022-08-30 14:30
my bad, didn't notice that in the Cargo.toml

**Comment by FabianLars** [comment] 2024-12-04 16:37
Closing as this issue is over 2 years old. Will reopen if someone confirms that it's still an issue with latest tauri. fwiw there were no other similar reports that i can remember

**Closed as not planned by FabianLars** 2024-12-04 16:37 UTC
Labels: type: bug
