### ISSUE TITLE
UNABLE to SAVE File EVEN DOE using correct method? [2021]

### ISSUE THREAD

**Issue by copyandexecute** [tauri-apps/tauri#1132] opened 2021-01-04 09:21 UTC
Dear Tauri Team,
I am trying to download a jar file and then save it with your provided funcation "writeBinaryFile". Unfortunately it does not work.

 ```
 await axios({
          url: '/downloads/client/latest.jar',
          method: "GET",
          responseType: "blob", // important
          onDownloadProgress: (progressEvent) => {
            setProgress(Math.round((progressEvent.loaded * 100) / progressEvent.total));
          }
        }).then(async value => {
          const mcDir = await promisified({cmd: "minecraftDir"});
          console.log(mcDir)
          console.log(value)
          console.log(value.data)
          await writeBinaryFile({contents: value.data, path: mcDir + "/norisk/test.jar"}, {});
        })
```

It creates an EMPTY + CORRUPTED File.
Whats the correct use?

Your sincerely,
Max

**Comment by zakpatterson** [comment] 2021-01-06 08:23
Duplicate of #1133 I think.

**Comment by nothingismagick** [comment] 2021-01-06 08:31
agreed.

**Closed as completed by nothingismagick** 2021-01-06 08:31 UTC
Labels: type: bug
