### ISSUE TITLE
[bug] When I turn off resizeable, I set the width and height to enforce 200px

### ISSUE THREAD

**Issue by heart-to-the-sea** [tauri-apps/tauri#6245] opened 2023-02-12 04:29 UTC
### Describe the bug

Did not get the 10px*10px form

### Reproduction

1.tauri.conf.json config

    "windows": [
      {
        "fullscreen": false,
        "resizable": false,
        "title": "tauri_test",
        "y": 10,
        "x": 1180,
        "width": 10,
        "height": 10,
        "minHeight": 10,
        "minWidth": 10,
        "hiddenTitle": true,
        "alwaysOnTop": true,
        "transparent": true,
        "skipTaskbar": true,
        "decorations": false
      } 

2 run npm run tauri dev

### Expected behavior

Hope to get a form with a width and height of 10px*10px

### Platform and versions

-------------OS----------------------- 
  OS: EndeavourOS Linux x86_64 
  Kernel: 6.1.9-arch1-2 
  Uptime: 1 day, 1 hour, 47 mins 
  Packages: 1291 (pacman) 
  Shell: zsh 5.9 
  Resolution: 2560x1440 
  DE: GNOME 43.2 
  WM: Mutter 
  WM Theme: Adwaita 
  Theme: Arc-Dark [GTK2/3] 
  Icons: Qogir-dark [GTK2/3] 
  Terminal: gnome-terminal 
  CPU: AMD Ryzen 9 5950X (32) @ 4.000G 
  GPU: AMD ATI Radeon RX 6600/6600 XT/ 
  Memory: 13681MiB / 64207MiB 

Environment
  › Node.js: 19.6.0
  › npm: 9.3.1
  › pnpm: 7.26.2
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.68.0-nightly
  › cargo: 1.68.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

### Stack trace

```shell
void
```

### Additional context

void

**Comment by FabianLars** [comment] 2023-02-12 09:29
Duplicate of #6125, see [#561](https://github.com/tauri-apps/tao/issues/561). Thanks for the report!

**Closed as not planned by FabianLars** 2023-02-12 09:29 UTC
Labels: type: bug, status: needs triage

**Comment by heart-to-the-sea** [comment] 2023-02-12 17:08
> Duplicate of #6125, see [#561](https://github.com/tauri-apps/tao/issues/561). Thanks for the report!

oke
