### ISSUE TITLE
[feat] A cli command to change project version

### ISSUE THREAD

**Issue by s3xysteak** [tauri-apps/tauri#9106] opened 2024-03-07 02:55 UTC
### Describe the problem

We have `npm version` to change the version in package.json.
```sh
npm version 0.0.2
```
When we wanna change a version of tauri-app, we have to :

- Change the version in package.json
- Change the version in Cargo.toml
- Change the version in tauri.conf.json

We also need to keep them consistent, which is inconvenient after repeating multiple times.

### Describe the solution you'd like

A Cli command like:
```sh
pnpm tauri version 0.0.2
```
It will change the versions in package.json / Cargo.toml / tauri.conf.json.

**Comment by amrbashir** [comment] 2024-03-07 03:21
duplicate of #4643

**Closed as not planned by amrbashir** 2024-03-07 03:21 UTC
Labels: type: feature request
