### ISSUE TITLE
[feat][v2] add ability to handle app activation on macOS

### ISSUE THREAD

**Issue by pronebird** [tauri-apps/tauri#9619] opened 2024-04-30 15:56 UTC
### Describe the problem

On macOS it's normal for app to remain active even if all windows are closed. It's often the case that the app running without any windows attempts to open some sort of window as user clicks on the app icon in dock. For example for a text editor, the new untitled document can be created and the window presented to user.

### Describe the solution you'd like

I'd like to have a hook that enables me to perform some action when the app becomes active.

In native development with Swift, the following method in the `NSApplicationDelegate.applicationDidBecomeActive` seems to be appropriate.

**Comment by amrbashir** [comment] 2024-04-30 16:01
I belive duplicate of #3084

**Closed as not planned by amrbashir** 2024-04-30 16:01 UTC
Labels: type: feature request
