### ISSUE TITLE
[bug] Unable to open 2 different Tauri apps

### ISSUE THREAD

**Issue by stumpam** [tauri-apps/tauri#4181] opened 2022-05-20 20:23 UTC
### Describe the bug

When one tauri app is opened, and we want to open the second one the second one will crash on unexpected null pointer. If we don't start the second one from the command line it will hang with blank screen unable to close by close button.

### Reproduction

1. Open Tauri app (by `yarn tauri dev` or double clicking on .exe file)
2. Try to open another one (by `yarn tauri dev` in another folder or double clicking another .exe file)

### Expected behavior

Both application should be opened independently on each other.

### Platform and versions

```shell
› OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.47
  › MSVC:
      - Visual Studio Build Tools 2019
  › Node.js: 17.9.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc
```

### Stack trace

```shell
[0520/222121.169:ERROR:validation_errors.cc(106)] Invalid message: VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null field [0520/222121.169:ERROR:interface_endpoint_client.cc(665)] Message 81787869 rejected by interface embedded_browser.mojom.EmbeddedBrowser
```

**Comment by lucasfernog** [comment] 2022-05-21 19:08
Probably related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/1207#issuecomment-1124978808 maybe you're using QT too?

**Comment by stumpam** [comment] 2022-05-21 19:48
I found the "bug", it is my fault, I use the same `identifier` in `tauri.conf.json` in both apps. But maybe it should still not end with window without any response, but unique identifier works as intended. But maybe it can be issue if you want two apps (mabye with different versions), it can not be opened.

**Comment by lucasfernog** [comment] 2022-05-22 17:39
I tried with two different apps with the same identifier (both in dev and installed applications) and still couldn't reproduce it. I'll close this since the identifier must be unique anyway, and currently the installer does not allow two versions of the app installed at the same time.

**Closed as completed by lucasfernog** 2022-05-22 17:39 UTC
Labels: type: bug
