### ISSUE TITLE
[bug] Problem with permissions in linux application, permissions of microphone

### ISSUE THREAD

**Issue by Pedro-phd** [tauri-apps/tauri#8851] opened 2024-02-13 16:47 UTC
### Describe the bug

I am creating an application in tauri using nuxt for my frontend, my application is being developed and tested on a linux ubuntu.

My application requires the use of microphone permission, so that it is possible to record the audio, however when I open my frontend on my Edge browser it asks for permission and the application works correctly, however when I try to run the application in the tauri webview it doesn't ask for permission, not even when I use `allowList all` as true it recognizes the permission, and without that my application doesn't work

### Full `tauri info` output

```text
[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-02-14 11:29
webkitgtk (the webview on linux) doesn't support webrtc yet. That's why it's not asking for permission.

I'll close this as a duplicate of https://github.com/tauri-apps/tauri/issues/5370 but the main tracking issue is here https://github.com/tauri-apps/wry/issues/85 - we're waiting for upstream though, not much we can do.

**Closed as not planned by FabianLars** 2024-02-14 11:29 UTC
Labels: type: bug, status: needs triage
