### ISSUE TITLE
100% CPU Usage and > 3min Startup Time For no-server Mode on Linux Pop!_OS 20.04

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri#902] opened 2020-07-28 22:37 UTC
**Describe the bug**
When starting an app in `no-server` mode, the app takes an extremely long time to start ( > 3 mins ) while taking 100% of one CPU core on Pop!_OS 20.04 ( which is essentially equivalent Ubuntu 20.04 ). This is on a machine with 12 2.6GHz CPUs.

**To Reproduce**
1. Clone the demo app: https://github.com/zicklag/temp_tauri-problem-example
2. Run `yarn`
3. Run `yarn tauri build`
4. Run `./src-tauri/target/release/temp-tauri-problem-example`
5. The app will hang for an extended period of time before starting up

**Expected behavior**
The app should start up almost instantly.

**Platform and Versions:**

OS: Pop!_OS 20.04 — Linux(5.4.0-7634-generic) — linux/x64
Node: 12.18.2
NPM: 6.14.5
Yarn: 1.22.4
Rustc: 1.22.4

**Additional context**
I ran a debugger and traced the execution and found that everything runs fine until Tauri actually starts the webview. This makes me fairly sure that this isn't actually a bug in Tauri itself, but a bug in webkit or webkitgtk or some other related technology. I opened the issue here because it directly effects Tauri apps on my platform and I wasn't sure exactly where else to report the problem.

At one point ( with a different application than the demo application ) I created an export of the data URL that Tauri will send to the Webview and saved it in a file ( which you can download [here](https://github.com/zicklag/bin-dump/blob/master/tauri.txt) ). Then **very strangely** I happened to try to open that file with `gedit` and amazingly enough *gedit did the same thing*. Gedit would take 100% of my CPU core and hang for a long time ( I didn't wait for it to come back up ). That was something I did not expect. I'm assuming its the same as whatever is causing the issue for webview.

I can verify that the `gedit` problem is not just the size of the file because when I create a file of the same size by running `head -c 1500000 /dev/urandom | base64 > data.txt` and then open that file with `gedit data.txt` it loads instantly.

**Comment by nklayman** [comment] 2020-07-30 01:17
I get the same issue on ubuntu 20.04, so it's not something weird with your system.

**Comment by nklayman** [comment] 2020-07-30 01:27
Also it works if you comment out both the `css/vendor.xxxxx` and `js/vendor.xxxxx` file imports from `index.html`.

**Comment by ghost** [comment] 2020-08-28 13:18
Hey I haved very simmilar issue. But when I the chang
```json
"tauri": {
    "embeddedServer": {
      "active": true --> Stay on True
    },
```
And
```json
"allowlist": {
      "all": false --> Change from true to false
    },
```
then App work wihout 100% cpu core usages.
But you have right it is some bug with webkit probably.
If you try this, tell do work for you this ? 

I Work with vue and yarn
```bash
vue create app-test
vue add tauri
yarn tauri:serve
```
or
```bash
yarn tauri:build
```

**Comment by zicklag** [comment] 2020-08-28 15:09
Interesting, I haven't had any trouble yet with the embedded server set to `true`. I only had trouble when the embedded server was `false`.

I'm not 100% sure I've tried that exact combo yet, but I'll try it later.

**Comment by u12206050** [comment] 2020-10-10 06:01
I have the same issue on macOS Catalina. Starting up and for quite a while it runs at ±99% and then after a long while I see it sometimes goes down to ±70% (still very high)

If I disable `embeddedServer` then it is at ±200% cpu usage.
If I set `allowlist.all` to `false` then the app doesn't really work exactly but still runs high cpu. need documentation on how to specify specific what is allowed.

Any ideas?
Here is my built app if you want to test on osx: https://github.com/u12206050/runcloud-desktop-app/releases/download/0.1.1/runcloudapp_0.1.1_x64.dmg

**Comment by happybeing** [comment] 2020-10-10 11:09
I have this on Ubuntu 20.04. I just started trying out Tauri by converting Svelte web apps to desktop apps, so far no issues with `tauri dev`, it just works (with both Hermit and Cloudish patterns)!

So I built two patterns Hermit and Cloudish to test this issue. Using `tauri build`...

Pattern (embeddedServer.active/allowlist.all)
- Hermit (false/false) the app never starts and after my CPU gets hammered.
- Cloudish (true/false) works like a dream. Really impressive!

**Comment by u12206050** [comment] 2020-10-28 21:27
Noticed also that on my Mac book pro it uses a constant 100 amount of battery, correlating to the 100% cpu usage.
If Tauri is ever going to really make an impact this has to be solved. Doesn't help that it uses less memory if it just drains all other resources.

**Comment by nothingismagick** [comment] 2020-11-01 17:50
@lucasfernog & @tensor-programming - we have to figure out what is going on here. its really important

**Comment by nklayman** [comment] 2020-11-06 06:24
I did some investigation but couldn't figure out the root cause, I may be able to take another look at it sometime.

**Comment by u12206050** [comment] 2020-11-06 07:00
Were you able to reproduce the the same issue?

**Comment by spacemeowx2** [comment] 2021-01-11 19:24
I found that it's because in no-server mode, the packer will pack index.html and its scripts into index.tauri.html, and then convert this file into data url. The 100% CPU is decoding and coping your code to memory.

It took me about 10 secs to load my app. And the size of `index.tauri.html` is about 500KB.

So the size of `index.tauri.html` makes the app hanging.


I solved startup freezing by using `import` in my JS entry.

just rename `index.tsx` to `app.tsx` and make a new `index.tsx` with:
```js
import('./app')
```

https://github.com/spacemeowx2/slp-tauri/commit/575361507a96ecf0f57701b013090717ee0d12a6

@nothingismagick

**Comment by nklayman** [comment] 2021-01-30 23:32
The PR linked above will prevent inlining of assets greater than 5kb in size, which fixes this issue. However, uninlined assets have some other problems that need to be dealt with. We're also looking into a replacement for the whole inline/no-server mode that makes use of custom protocols to make a new no-server mode that is as easy and reliable as the embedded-server mode.

**Comment by nklayman** [comment] 2021-02-01 01:42
Now that the PR is merged, this issue is fixed. However, the example repo posted here still doesn't load quite properly due to `url()`s in the external CSS. I'm going to close this issue, but keep in mind that it still doesn't load fully.

**Closed as completed by nklayman** 2021-02-01 01:42 UTC
Labels: type: bug

**Comment by nklayman** [comment] 2021-02-06 23:38
Good news! I got the custom protocol working on linux, and was able to run this app on the new no-server mode without any issues. It will be a little while till we release the version of tauri that uses custom protocols, but when we do it will solve pretty much every issue with the current no-server mode.

**Comment by nileshtrivedi** [comment] 2021-11-27 12:09
@nklayman Any update on Tauri release supporting custom protocols?

**Comment by FabianLars** [comment] 2021-11-27 12:21
@nileshtrivedi every beta(-rc) release uses custom protocols (dropping the above mentioned server/noserver modes), so that's 8 months of usage 👍
