### ISSUE TITLE
[bug] MacOS notification not working with safari in example API app

### ISSUE THREAD

**Issue by ShivamJoker** [tauri-apps/tauri#3241] opened 2022-01-18 08:38 UTC
### Describe the bug

Notification API not working in MacOS with Safari as default browser

### Reproduction

Clone the example of api from tauri repo and run it.
Then go to notification tab and click on send notification.

![image](https://user-images.githubusercontent.com/23727670/149900795-965a108b-4a40-41b0-a9f4-54d5a2197fb7.png)

### Platform and versions

```shell
Operating System - Mac OS, version 12.1.0 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.3.1
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustc - 1.58.0
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.0
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)

App directory structure
/dist
/node_modules
/public
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: asset: customprotocol: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
```

**Comment by jmcartlamy** [comment] 2022-03-02 14:07
MacOS notification still not working on Release Candidate.

When we call `requestPermission()`, promise is always resolved with `denied` value. MacOS system preferences notifications do not show anything about the application.

### Platform and versions

```
Operating System - Mac OS, version 11.5.2 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.1.2
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustup - 1.24.3
  rustc - 1.59.0
  cargo - 1.59.0
  toolchain - stable-x86_64-apple-darwin

App directory structure
/node_modules
/public
/src-tauri
/src
/build

App
  tauri - 1.0.0-rc.3
  tauri-build - 1.0.0-beta.4
  tao - 0.6.2
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
```

**Comment by lucasfernog** [comment] 2022-03-12 03:25
We need more information on this issue. I don't see a relation between Safari as default browser and the notification not working (I just tested it and it's working ok) @ShivamJoker 

@jmcartlamy can you write an example app? did you enable the notification allowlist? also if you already clicked `deny` on the permission request dialog before, you'd need to `$ rm $HOME/Library/Application\ Support/com.your.bundleid/.tauri-settings`.

**Comment by elibroftw** [comment] 2022-03-13 23:04
Can I request that examples be added directly to the docs? https://tauri.studio/docs/api/js/modules/notification has 0 examples. 

There should be an example with the Notification Web API and also an example using `window.__TAURI__.notification.sendNotification`

**Comment by elibroftw** [comment] 2022-03-13 23:18
Yeah, there's no examples, and since I've never used the Notification API, I'm getting problems:

The docs say I can use `Notification`, but simply calling

`Notification.requestPermission()` in the frontend panics Tauri:
```
thread 'main' panicked at 'This API cannot be called on the main thread. Try using `std::thread::spawn` or `tauri::async_runtime::spawn`.', C:\Users\maste\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-runtime-wry-0.2.1\src\lib.rs:1129:8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
webview2: panic in callback function. Aborting because it's UB to unwind across FFI boundaries.
error: process didn't exit successfully: `target\debug\app.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

**Comment by elibroftw** [comment] 2022-03-13 23:24
The `new Notification("Notification title", {
      body: "This is the notification body",
    });` example doesn't even work on Windows. There's no error messages either.

**Comment by FabianLars** [comment] 2022-03-13 23:29
@elibroftw that panic is caused by an outdated tauri-runtime-wry dependency. Yours is 0.2.1, but the latest is 0.3.x. Try running `cargo update` in your src-tauri dir (probably a good idea to make sure that your dependencies in Cargo.toml are up-to-date too)

**Comment by elibroftw** [comment] 2022-03-13 23:50
Is there a way for the notification permission to be true by default?

**Comment by JonasKruckenberg** [comment] 2022-03-14 08:18
> Is there a way for the notification permission to be true by default?

Not on macOS at least, because the OS will prompt the user first. I don't know enough about windows or the different linux DEs to know if they have similar checks in place.

**Comment by lucasfernog** [comment] 2022-03-14 13:22
We do the check ourselves so there is a way around it, but you'd need to create a file yourself and save the correct information (quite some work, you shouldn't do it).

**Comment by elibroftw** [comment] 2022-03-14 14:22
On Windows and Linux, I've never had to accept permissions to see notifications from an app. Therefore there shouldn't be an artificial alert box for something that is not needed on Linux and Windows.

**Comment by jmcartlamy** [comment] 2022-03-21 17:29
@lucasfernog After testing the example API app, I see it's working correctly. I re-tested on my project and it turns out that it works now too. The way macOS handles notifications is very particular and I must have missed the permission request dialog.

**Closed as completed** 2022-03-21 17:57 UTC
Labels: type: bug, status: needs more info, platform: macOS

**Comment by henit-chobisa** [comment] 2023-08-01 17:20
hey @ShivamJoker & @lucasfernog, I am getting the same problem like above, I am trying to make rocket.chat desktop in tauri as a Google summer of Code project, and I am stuck with the notifications part, I have injected a script in the webview and also defined a command for the same, I take the notification data and I trigger the notification provided by the tauri api, Can you please have a look on my code, I would be really really really grateful to you. Thanks

Injection Script
```
// Listen for the 'notification' event
const sendNotification = (notificationObj) => {
  const notificationData = { title: notificationObj.title, body: notificationObj.text}
  window.__TAURI__.invoke('send_notification', { notificationData }).then((message) => console.log(message)).catch((e) => console.log("Error Occured", e));
}


self.addEventListener('notification', (event) => {
  event.preventDefault();
  window.__TAURI__.notification.isPermissionGranted().then((isPermissionGranted) => {
    console.log("Notification Permission", isPermissionGranted)
    if (isPermissionGranted === false) {
      window.__TAURI__.notification.requestPermission().then((permission) => {
        if (permission !== 'granted') {
          return;
        }
        sendNotification(event.detail.notification)
      });
    } else {
      sendNotification(event.detail.notification)
    }
  })
});
```

Tauri Command
```
#[tauri::command]
fn send_notification(notification_data: serde_json::Value) {
    let title = notification_data["title"].as_str().unwrap();
    let body = notification_data["body"].as_str().unwrap();
    // let tag = notification_data["tag"].as_str().unwrap();
    // let data = notification_data["data"].as_str().unwrap();
    println!("Notificatin Recieved with title {} and body {}", title.to_string(), body.to_string());

    let notification: Notification = Notification::new("com.rocket.chat").title(title.to_string()).body(body.to_string());

    let result = notification.show().map_err(|e| e.to_string());

match result {
    Ok(()) => println!("Ok, Notification Shown"),
    Err(e) => println!("Error: {}", e),
}
}   
```
