### ISSUE TITLE
Blurry and translucent background on a transparent window

### ISSUE THREAD

**Issue by richardaum** [tauri-apps/tauri#2827] opened 2021-10-31 15:26 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to use a blurry background on a transparent window element (sidebar).

**Describe the solution you'd like**
Use `backdrop-filter` along with a transparent window to achieve a blurry background.

**Describe alternatives you've considered**
I've also tried to use `-webkit-filter: blur(20px)`, but same thing happens.

**Additional context**

The following screenshots were taken with a transparent window - `transparent: true` on tauri.conf.json. The window is in front of my OS wallpaper. 

| Description | Image |
| -- | -- |
| On the left side I have a div with `backdrop-filter: blur(20px)` and also a `background: rgba(238, 238, 244, 0.5)`. On the right side I have another but with `background: transparent`. | ![image](https://user-images.githubusercontent.com/2018161/139590151-cd439b2b-268f-4d0c-b3e1-338469075db6.png) |
| When I add the same image I use on my OS wallpaper on `<body>`, the desired blur effect appears.  | ![image](https://user-images.githubusercontent.com/2018161/139590310-d4b7fd56-448f-4e7a-be07-47639252b6f7.png) |

Conclusion: The blur effects appears only when the image is part of the application, and doesn't consider what is behind the transparent window. Should it?

**Info**

- Linux (Zorin OS)
- "@tauri-apps/api": "^1.0.0-beta.8"
- "@tauri-apps/cli": "^1.0.0-beta.10"

<details>
  <summary>tauri.conf.json</summary>

```json
{
  "package": {
    "productName": "findr",
    "version": "0.1.0"
  },
  "build": {
    "distDir": "../build",
    "devPath": "http://localhost:3000",
    "beforeDevCommand": "yarn start",
    "beforeBuildCommand": "yarn build"
  },
  "tauri": {
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "macOS": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false,
        "exceptionDomain": "",
        "signingIdentity": null,
        "entitlements": null
      },
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "updater": {
      "active": false
    },
    "allowlist": {
      "all": true
    },
    "windows": [
      {
        "title": "Findr",
        "width": 800,
        "height": 600,
        "resizable": true,
        "fullscreen": false,
        "decorations": false,
        "transparent": true
      }
    ],
    "security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'"
    }
  }
}
```
</details>

**Comment by amrbashir** [comment] 2021-10-31 16:57
This is the expected behavior on Linux and Windows, `backdrop-filter` only affects DOM elements, anything behind the window will not be blurred.  

The solution is to blur the window itself. It is not currently implemented and needs to be added in upstream first, subscribe to this tauri-apps/tao#137

**Comment by amrbashir** [comment] 2021-12-06 13:53
for anyone interested in this issue, I made a https://github.com/tauri-apps/tauri-plugin-vibrancy to experiment with the feature. it supports tao and tauri and I'd appreciate feedback on different Windows versions, macOS support will be added later. 

Edit: macOS is now supported.

**Comment by lucasfernog** [comment] 2021-12-31 18:42
Closing this since you can try out the plugin from Amr now. The feature might land in tauri v2.

**Closed as completed by lucasfernog** 2021-12-31 18:42 UTC
Labels: type: feature request, status: upstream

**Comment by arialpew** [comment] 2024-05-23 10:51
@lucasfernog Do we have any news about this for v2 ?

**Comment by btjawa** [comment] 2024-12-16 15:13
v2 has launched, any news for this?

**Comment by FabianLars** [comment] 2024-12-19 15:34
it's part of v2 (added in early alpha i think) via the window `windowEffects` config. https://v2.tauri.app/reference/config/#windoweffectsconfig (don't have an example on hand rn)

**Comment by btjawa** [comment] 2024-12-19 15:45
@FabianLars Thanks for that!
