### ISSUE TITLE
Tauri Notification displays as Powershell.

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#5606] opened 2022-11-10 23:02 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/93608862/201223937-2e423071-edb8-4087-84c6-67b24e08cd63.png)

### Reproduction

```js
let permissionGranted = await isPermissionGranted();
if (!permissionGranted) {
  const permission = await requestPermission();
  permissionGranted = permission === "granted";
}
if (permissionGranted) {
  sendNotification("Tauri is awesome!");
  sendNotification({ title: "TAURI", body: "Tauri is awesome!" });
}
```
(copied from docs)

### Expected behavior

It should display the app name and icon of the app above the notification, not powershell.

### Platform and versions

```
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 107.0.1418.35
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: 7.14.2
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src: 'self'; media-src 'self' asset:
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ .git
  ├─ .github
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by FabianLars** [comment] 2022-11-11 07:04
Duplicate of #3700. You unfortunately need to install the app msi to have it display the correct name&icon.

**Closed as not planned** 2022-11-11 07:04 UTC
Labels: type: bug, status: needs triage

**Comment by rahulgandhi2411** [comment] 2023-06-29 07:17
not working even if the msi is installed
