### ISSUE TITLE
[bug]Unhandled Promise Rejection: invalid args `value` for command `set_size`: invalid value: map, expected map with a single key

### ISSUE THREAD

**Issue by songjiachao** [tauri-apps/tauri#9403] opened 2024-04-08 08:51 UTC
### Describe the bug

import { getCurrent } from '@tauri-apps/api/webviewWindow';
import { LogicalSize } from '@tauri-apps/api/window';

const resetWindowSize = async () => {
  await getCurrent().setSize(new LogicalSize(960, 400));
};

![image](https://github.com/tauri-apps/tauri/assets/70792885/209e75ab-625b-4870-b5c5-36e723c33e25)

### Full `tauri info` output

```text
➜  desktop git:(feat-launcher) ✗ cargo tauri info


[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.11.1
    - pnpm: 8.15.6
    - yarn: 1.22.19
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - tauri-cli [RUST]: 2.0.0-beta.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.0

[-] App
    - build-type: bundle
    - CSP: style-src 'unsafe-inline' 'self' https://fonts.googleapis.com; connect-src ipc: http://ipc.localhost ws: https:; font-src https://fonts.gstatic.com self asset: http://asset.localhost tauri:; img-src 'self' asset: blob: data: https: http:; default-src 'self' customprotocol: asset:
    - frontendDist: ../dist
    - devUrl: http://127.0.0.1:1420/
    - framework: React (Next.js)
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-04-08 08:56
Duplicate of #9370, thanks for the report :)

**Closed as not planned by FabianLars** 2024-04-08 08:56 UTC
Labels: type: bug, status: needs triage
