### ISSUE TITLE
[bug] JSON error: unexpected character 'u' while parsing major version number

### ISSUE THREAD

**Issue by greedyhao** [tauri-apps/tauri#4801] opened 2022-07-30 14:05 UTC
### Describe the bug

Very similar to https://github.com/tauri-apps/tauri/issues/4610
I'm trying to use a static JSON located in my gitee repo as an updater, but when I attempt an update I get `JSON error: unexpected character 'u' while parsing major version number`
`TAURI_PRIVATE_KEY` and `TAURI_KEY_PASSWORD` is set

update-status return

![image](https://user-images.githubusercontent.com/25771942/181917754-bc5b621f-d75e-4d58-8774-2418672c3187.png)

update.json
```
{
  "version": "v0.1.1",
  "notes": "Test version",
  "pub_date": "2022-07-30T19:25:57Z",
  "platforms": {
    "windows-x86_64": {
      "signature": "dW50cnVzdGVkIGNvbW1lbnQ6IHNpZ25hdHVyZSBmcm9tIHRhdXJpIHNlY3JldCBrZXkKUlVTZm5sWVJxR2tKK1RwQWYyWmlRcVRDbXJOMmFxOUI0aXdPU1UwK05qMFBXb1NYU2RXRXNkTEs0MTFONExybUIvWWQyUlZQcThuT2JWTytSQm9VNVFZOTdSam40aG9pZmd3PQp0cnVzdGVkIGNvbW1lbnQ6IHRpbWVzdGFtcDoxNjU5MTg1MTgxCWZpbGU6ZWVfdG9vbHNfMC4xLjFfeDY0X2VuLVVTLm1zaS56aXAKdmpaV2V2bDJ2aUJUaGhOSmhaMXEzSmNIWXJNQngxZlo4SjduRzBLTXpyN2hEWkVNSjBBbWJsZ1lZZS9SN1M0UHBtaUNHQnJvTytJR0RxVzVnUDhMQ0E9PQo=",
      "url": "https://gitee.com/haozhu1997/tauri-app-updates/blob/master/ee_tools/windows/x64/ee_tools_0.1.1_x64_en-US.msi.zip"
    }
  }
}
```

tauri.conf.json
```
    "updater": {
      "active": true,
      "endpoints": [
          "https://gitee.com/haozhu1997/tauri-app-updates/blob/master/ee_tools/update.json"
      ],
      "dialog": false,
      "pubkey": "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IEY5MDk2OUE4MTE1NjlFOUYKUldTZm5sWVJxR2tKK1J3S2d6d0tVR1dYc1pWamRDT1JSaUNhVlRnK1F0eWFJR0FYd1JHOWdRQ1IK"
    },
```

project place
`https://github.com/greedyhao/ee_tools/tree/master`

updater place
`https://gitee.com/haozhu1997/tauri-app-updates`

### Reproduction

1. Generate public and private keys with tauri signer generate
2. Populate tauri.conf.json pubkey with contents of .key.pub and updater endpoint with raw gitee link of updater JSON
3. Build and sign release
4. Upload .msi.zip to github as a release
5. Populate updater JSON with new version number, signature from contents of .msi.zip.sig, and url from from github release
6. Push JSON to gitee
7. Open older version of application and attempt update

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 103.0.1264.71
  › MSVC:
      - Visual Studio Community 2022
  › Node.js: 18.6.0
  › npm: 8.13.2
  › pnpm: 7.6.0
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by FabianLars** [comment] 2022-07-30 14:21
The endpoint url is not correct. It needs to point to the `raw` file instead of the git gui containing it. In github the url would look like this https://raw.githubusercontent.com/tauri-apps/tauri/dev/.gitignore no idea about gitee

**Comment by greedyhao** [comment] 2022-07-31 15:41
> The endpoint url is not correct. It needs to point to the `raw` file instead of the git gui containing it. In github the url would look like this https://raw.githubusercontent.com/tauri-apps/tauri/dev/.gitignore no idea about gitee

Thank you. That solves my problem

But now there's another problem

After the upgrade, the program cannot run properly

![image](https://user-images.githubusercontent.com/25771942/182034118-bf0f4767-c48f-425a-9c1b-6c2eda2a8c73.png)
![image](https://user-images.githubusercontent.com/25771942/182034134-4e29770a-be90-4e08-abd8-8ab0e2092ef7.png)

**Comment by lucasfernog** [comment] 2022-07-31 20:29
@greedyhao can you file a separate issue with details to reproduce it? I'll close this one since it's been resolved.

**Closed as completed by lucasfernog** 2022-07-31 20:29 UTC
Labels: type: bug, status: needs triage
