### ISSUE TITLE
[bug] shell open crash on Windows

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#9624] opened 2024-04-30 18:05 UTC
### Describe the bug

I use shell plugin in v2 project.
I use it to open folder in explorer.exe
Second time opening of same folder it focus the explorer.exe window and tauri app is crashing.

### Reproduction

Use simple repro repo
https://github.com/thewh1teagle/tauri-crash-01

Or just use shell plugin , 
1.open some folder eg: `shell.open("C:\\Users")`
2. First time it will open the explorer successfully, open again. it will focus the explorer window and then tauri app will crash.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 124.0.2478.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.12.0
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 2.0.0-beta.16
    - tauri-build [RUST]: 2.0.0-beta.13
    - wry [RUST]: 0.39.3
    - tao [RUST]: 0.27.1
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

### Additional context

Originally happens in v2 typescript [project](https://github.com/thewh1teagle/vibe).

**Comment by amrbashir** [comment] 2024-05-16 01:36
closing as duplicate of #1137, thanks for the repro though ❤️

**Closed as not planned by amrbashir** 2024-05-16 01:36 UTC
Labels: type: bug, status: needs triage

**Comment by thewh1teagle** [comment] 2024-05-16 01:44
> closing as duplicate of #1137, thanks for the repro though ❤️

Did you meaned to mention another issue?
Because the issue you mentioned is closed,
and It still happens (today) with most recent tauri (core / cli / plugins)
[vibe/desktop/src-tauri](https://github.com/thewh1teagle/vibe/tree/main/desktop/src-tauri)
[vibe/releases/latest](https://github.com/thewh1teagle/vibe/releases/tag/v1.0.5)

**Comment by amrbashir** [comment] 2024-05-16 01:54
sorry I meant https://github.com/tauri-apps/plugins-workspace/issues/1137, I am still investigating the issue
