### ISSUE TITLE
[feat] I hope to add the function of dynamically changing the theme of the window

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#6422] opened 2023-03-11 06:47 UTC
### Describe the problem

I'd like to be able to add a method like: `setTheme` to the window to change the theme color, not just on startup!

### Describe the solution you'd like

Dynamic theme color modification

**Comment by FabianLars** [comment] 2023-03-11 09:30
Duplicate of https://github.com/tauri-apps/tauri/issues/5279. Thanks for the request.

**Closed as not planned** 2023-03-11 09:30 UTC
Labels: type: feature request
