### ISSUE TITLE
[feat] transparent app above fullscreen apps

### ISSUE THREAD

**Issue by mediarl** [tauri-apps/tauri#11791] opened 2024-11-25 10:30 UTC
### Describe the problem

I created a transparent app that goes on top of other apps. It works well when the Tauri app is over other apps that are maximized, but not when the other apps are in fullscreen. I thought it was not possible until I saw "Screen Studio" app that is a transparent app on top of maximized or fullscreen apps.

### Describe the solution you'd like

Having a flag like alwaysOnTop to specify that it should include also on top of other fullscreen apps

### Alternatives considered

I read it might be possible using Cocoa AppKit. I tried this code (in the setup function) but although it compiles, it still did not allow me to display the app on top of fullscreen apps.

```
use cocoa::appkit::NSWindow;
use cocoa::appkit::NSWindowCollectionBehavior;

let window = app.get_webview_window("main").unwrap();
let ns_window = window.ns_window().unwrap() as id;

unsafe {
   let behavior = NSWindowCollectionBehavior::NSWindowCollectionBehaviorTransient
       | NSWindowCollectionBehavior::NSWindowCollectionBehaviorIgnoresCycle
       | NSWindowCollectionBehavior::NSWindowCollectionBehaviorFullScreenAuxiliary;

   ns_window.setCollectionBehavior_(behavior);
}
```

### Additional context

[_[OSX overlay on native FullscreenMode](https://stackoverflow.com/questions/19933171/osx-overlay-on-native-fullscreenmode)_](https://stackoverflow.com/questions/19933171/osx-overlay-on-native-fullscreenmode)

**Comment by FabianLars** [comment] 2024-11-25 10:38
Thanks for the request, and especially for including your research!! I'll have to close this as a duplicate of https://github.com/tauri-apps/tauri/issues/3326 or https://github.com/tauri-apps/tauri/issues/9556 or https://github.com/tauri-apps/tauri/issues/11488

**Closed as not planned by FabianLars** 2024-11-25 10:38 UTC
Labels: type: feature request, platform: macOS
