### ISSUE TITLE
Tauri production build does not make http calls

### ISSUE THREAD

**Issue by UmashankarRahangdale** [tauri-apps/tauri#5849] opened 2022-12-16 09:53 UTC
My tauri production build is unable to make normal http calls. getting following error when making a rest call over http.
Mixed Content: The page at 'https://tauri.localhost/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xyz.com/login'. 
This request has been blocked; the content must be served over HTTPS.

I dont want my node server to be on https and other applications consume it and i dont want them to change anything.

**Comment by FabianLars** [comment] 2022-12-16 09:59
Duplicate of #3007. Thanks for the report.

**Closed as not planned by FabianLars** 2022-12-16 09:59 UTC

**Comment by prayag17** [comment] 2023-05-12 08:25
Did you ever find aa fix for this issue?

**Comment by Valentim-Gab** [comment] 2024-09-21 22:40
A client application using https cannot consume an api in http.

**Comment by Ghadi00** [comment] 2024-12-29 19:39
Hello, I am having the same issue here on production did anyone find any solution?

**Comment by prayag17** [comment] 2024-12-30 05:47
Use the http plugin for Tauri to make request

**Comment by JoseRupallan** [comment] 2025-11-12 16:56
@prayag17 what do i do if i need to use src for an image tag

**Comment by prayag17** [comment] 2025-11-12 19:05
@JoseRupallan you just need to import the image in your js/ts file like

`import imageName as 'path/to/image';`

And then use the imageName variable as the value for your source, this is not really dependent on the http plugin
