### ISSUE TITLE
[bug] download wix failed 

### ISSUE THREAD

**Issue by GeorgeHcc** [tauri-apps/tauri#8647] opened 2024-01-20 15:52 UTC
### Describe the bug

when i run `cargo tauri build` and downloading wix,throw a network error.it seems that connetion failed,but when i use curl,it  works.

# ternimal report
```
cargo tauri build
     Running beforeBuildCommand `pnpm build`

> tauri-app@0.0.0 build D:\CodeRepository\__React__STACK\Electron\tauri-app
> vue-tsc --noEmit && vite build

    Finished release [optimized] target(s) in 0.48s
        Info Verifying wix package
 Downloading https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip 
       Error failed to bundle project: `https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip: Connection Failed: Connect error: 由于连接方在一段时间后没有正确答复 
或连接的主机没有反应，连接尝试失败。 (os error 10060)`
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.144
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13)
    ✔ cargo: 1.74.0 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)   
    - node: 18.16.0
    - pnpm: 8.6.11
    - yarn: 1.22.21
    - npm: 9.7.2

[-] Packages
    - tauri-build [RUST]: 1.5.1
    - tao [RUST]: 0.16.6
    - tauri-cli [RUST]: 1.5.7
    - @tauri-apps/api [NPM]: 1.4.0 (outdated, latest: 1.5.3)
    - @tauri-apps/cli [NPM]: 1.5.7 (outdated, latest: 1.5.9)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-01-20 17:13
Looks like a duplicate of https://github.com/tauri-apps/tauri/issues/7338. There are english and chinese comments so i hope there's something helpful for you too. Basically it should be issues with proxies.

**Closed as not planned by FabianLars** 2024-01-20 17:13 UTC
Labels: type: bug, status: needs triage
