### ISSUE TITLE
[bug] 32bit window 10 can't build

### ISSUE THREAD

**Issue by nyrf** [tauri-apps/tauri#3223] opened 2022-01-15 14:58 UTC
### Describe the bug

i use 32bit win10 and use tao next branch, but it still  failed

```bash
1028 |   let mut userdata = winuser::GetWindowLongPtrW(window, winuser::GWL_USERDATA);
     |                      --------------------------------------------------------- expected due to this value
...
1051 |         userdata = createstruct.lpCreateParams as LONG_PTR;
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `isize`
```

### Platform and versions

```shell
Operating System - Windows, version 10.0.18363 X32
Node.js environment
  Node.js - 16.13.2
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  pnpm - 6.25.1
  yarn - 1.22.15

Rust environment
  rustc - 1.60.0-nightly
  cargo - 1.60.0-nightly

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0-nightly
  cargo - 1.60.0-nightly
  toolchain - nightly-i686-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
```

### Stack trace

```shell
tao-0.5.2\src\platform_impl\windows\window.rs:1051:20
     |
1028 |   let mut userdata = winuser::GetWindowLongPtrW(window, winuser::GWL_USERDATA);
     |                      --------------------------------------------------------- expected due to this value
...
1051 |         userdata = createstruct.lpCreateParams as LONG_PTR;
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `isize`

   Compiling bincode v1.3.3
For more information about this error, try `rustc --explain E0308`.
error: could not compile `tao` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by lucasfernog** [comment] 2022-01-15 15:15
Duplicate of #3067

**Comment by nyrf** [comment] 2022-01-15 15:24
@lucasfernog I have followed that issue and use `yarn tauri build -t i686-pc-windows-msvc` from https://github.com/tauri-apps/tauri/issues/3067#issuecomment-995345262, got same error.

**Comment by lucasfernog** [comment] 2022-01-15 15:47
@nyrf did you also follow https://github.com/tauri-apps/tauri/issues/3067#issuecomment-993627628 ?

**Comment by nyrf** [comment] 2022-01-15 16:57
> @nyrf did you also follow [#3067 (comment)](https://github.com/tauri-apps/tauri/issues/3067#issuecomment-993627628) ?

I've tried and got a new error

```bash
   Compiling cssparser v0.27.2
error: could not find native static library `WebView2LoaderStatic`, perhaps an -L flag is missing?

error: could not compile `webview2-com-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: failed to build app

Caused by:
    Result of `cargo build` operation was unsuccessful: exit code: 101
```

**Comment by lucasfernog** [comment] 2022-01-15 17:32
I think it's related to this: https://github.com/tauri-apps/tauri/pull/3173/files

**Comment by ilopsource** [comment] 2022-01-15 18:04
> I think it's related to this: https://github.com/tauri-apps/tauri/pull/3173/files
![image](https://user-images.githubusercontent.com/29702441/149632740-7ace8535-d857-4c41-b462-e3f995389214.png)
![image](https://user-images.githubusercontent.com/29702441/149632747-99a55670-348f-46fd-8c26-1f267812833f.png)

I followed the documentation to set, but still have the same error and I can download  Microsoft.Web.WebView2

**Comment by lucasfernog** [comment] 2022-01-15 19:02
Issue found: after creating the config file, a `cargo clean` was needed.

**Closed as completed by lucasfernog** 2022-01-15 19:02 UTC
Labels: type: bug

**Comment by nyrf** [comment] 2022-01-15 19:39
Thanks, it works now.
