### ISSUE TITLE
[bug] Can't run dev: Found argument '/usr/bin/node18' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by xtexx** [tauri-apps/tauri#5503] opened 2022-10-28 13:21 UTC
### Discussed in https://github.com/tauri-apps/tauri/discussions/5502

<div type='discussions-op-text'>

<sup>Originally posted by **xtexChooser** October 28, 2022</sup>
Hello,

I just created a new project with `pnpm create tauri-app` and I got an error while I was running `pnpm tauri dev`: `error: Found argument '/usr/bin/node18' which wasn't expected, or isn't valid in this context`.

```
➜  ChitangHI pnpm create tauri-app
../../.pnpm-store/v3/tmp/dlx-9572        |   +3 +
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /mnt/src/.pnpm-store/v3
  Virtual store is at:             ../../.pnpm-store/v3/tmp/dlx-9572/node_modules/.pnpm
../../.pnpm-store/v3/tmp/dlx-9572        | Progress: resolved 10, reused 3, downloaded 0, added 3, done

✔ Project name · test
✔ Choose your package manager · pnpm
✔ Choose your UI template · react-ts

Please follow https://tauri.app/v1/guides/getting-started/prerequisites to install the needed prerequisites, if you haven't already.

Done, Now run:
  cd test
  pnpm install
  pnpm tauri dev

➜  ChitangHI cd test
➜  test pnpm install
 WARN  GET https://registry.yarnpkg.com/supports-preserve-symlinks-flag error (ERR_SOCKET_TIMEOUT). Will retry in 10 seconds. 2 retries left.
Packages: +91
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are cloned from the content-addressable store to the virtual store.
  Content-addressable store is at: /mnt/src/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 120, reused 91, downloaded 0, added 91, done

dependencies:
+ @tauri-apps/api 1.1.0
+ react 18.2.0
+ react-dom 18.2.0

devDependencies:
+ @tauri-apps/cli 1.1.1
+ @types/node 18.11.7
+ @types/react 18.0.24
+ @types/react-dom 18.0.8
+ @vitejs/plugin-react 2.2.0
+ typescript 4.8.4
+ vite 3.2.1

Done in 2m 0.4s
➜  test pnpm tauri dev

> test@0.0.0 tauri /mnt/src/Project/ChitangHI/test
> tauri "dev"

error: Found argument '/usr/bin/node18' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-tauri [OPTIONS] <SUBCOMMAND>

For more information try --help
 ELIFECYCLE  Command failed with exit code 2.
➜  test 

```

How can I solve it?

```
➜  test pnpm --version
7.13.6
➜  test cargo --version
cargo 1.66.0-nightly (9210810d1 2022-10-25)
➜  test rustc --version 
rustc 1.66.0-nightly (0da281b60 2022-10-27)

```</div>

**Comment by lucasfernog** [comment] 2022-10-28 13:26
Duplicate of #5343, fixed by #5345 (will be available in v1.2).

**Closed as not planned by lucasfernog** 2022-10-28 13:26 UTC
Labels: status: invalid
