### ISSUE TITLE
Custom titlebar cannot be dragged with fingers

### ISSUE THREAD

**Issue by renjiali** [tauri-apps/tauri#9245] opened 2024-03-22 03:47 UTC
### Describe the bug

My code is as follows

tauri.conf.json
`
  "windows": [
      {
        "decorations": false,
        "title": "渔田自助机",
        "width": 800,
        "height": 600,
        "transparent": true
      }
    ],
    
    "window": {
        "all": false,
        "close": true,
        "hide": true,
        "show": true,
        "maximize": true,
        "minimize": true,
        "unmaximize": true,
        "unminimize": true,
        "startDragging": true
      }
    
    
`
My Components
`
<template>
  <div data-tauri-drag-region class="titlebar">
    <t-button size="large" theme="default" variant="text" @click="() => appWindow.minimize()" class="titlebar-button" id="titlebar-minimize">
      <t-icon name="remove"></t-icon>
    </t-button>
    <t-button size="large" theme="default" variant="text" @click="() => appWindow.toggleMaximize()" class="titlebar-button" id="titlebar-maximize">
      <t-icon name="fullscreen-1"></t-icon>
    </t-button>
    <t-button size="large" theme="default" variant="text" @click="() => appWindow.close()" class="titlebar-button" id="titlebar-close">
      <t-icon name="close"></t-icon>
    </t-button>
  </div>
</template>

<script setup lang="ts">
import { appWindow } from "@tauri-apps/api/window";
</script>
<style lang="less" scoped>
.titlebar {
  height: 50px;
  background: transparent;
  user-select: none;
  display: flex;
  justify-content: flex-end;
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  .titlebar-button {
    display: inline-flex;
    justify-content: center;
    align-items: center;
    width: 30px;
    height: 30px;
    font-size: 25px;
    color: #888;
    &:hover {
      color: #555;
    }
  }
  #titlebar-close {
    font-size: 30px;
  }
}
</style>

`

Using a mouse is normal, but there is no response when using fingers. Clicking and double clicking on the toolbar are both normal. Simply dragging with fingers without any response; I changed it to "decorations": true. Fingers are normal and can be dragged. Why is this?
使用鼠标是正常的，但是使用手指没有反应，点击和双击tablebar都是正常的。仅仅是手指拖动无反应；我修改为 "decorations": true,手指是正常的，可以手指拖动，这是为什么？

### Reproduction

Using a mouse is normal, but there is no response when using fingers. Clicking and double clicking on the toolbar are both normal. Simply dragging with fingers without any response; I changed it to "decorations": true. Fingers are normal and can be dragged. Why is this?
使用鼠标是正常的，但是使用手指没有反应，点击和双击tablebar都是正常的。仅仅是手指拖动无反应；我修改为 "decorations": true,手指是正常的，可以手指拖动，这是为什么？

### Expected behavior

Using a mouse is normal, but there is no response when using fingers. Clicking and double clicking on the toolbar are both normal. Simply dragging with fingers without any response; I changed it to "decorations": true. Fingers are normal and can be dragged. Why is this?
使用鼠标是正常的，但是使用手指没有反应，点击和双击tablebar都是正常的。仅仅是手指拖动无反应；我修改为 "decorations": true,手指是正常的，可以手指拖动，这是为什么？

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 122.0.2365.92
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 8.15.4
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.6.1
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.11

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-03-22 14:10
duplicate of https://github.com/tauri-apps/tauri/issues/4746

**Closed as not planned by FabianLars** 2024-03-22 14:10 UTC
Labels: type: bug, status: needs triage
