### ISSUE TITLE
[feat] Wrappers for other languages

### ISSUE THREAD

**Issue by Drew-Chase** [tauri-apps/tauri#9834] opened 2024-05-20 18:12 UTC
### Describe the problem

I love the project, but I'm not a huge fan of the Rust compiler due to its performance issues.

### Describe the solution you'd like

A wrapper/port of the project for other languages like C++ or C#

**Comment by amrbashir** [comment] 2024-05-20 18:17
duplicate of https://github.com/tauri-apps/tauri/issues/4670

**Closed as not planned by amrbashir** 2024-05-20 18:17 UTC
Labels: type: feature request
