### ISSUE TITLE
[bug] Tauri Incompatibility with Rust Edition 2024

### ISSUE THREAD

**Issue by iamsauravsharma** [tauri-apps/tauri#11829] opened 2024-11-29 13:35 UTC
### Describe the bug

Tauri encounter issues when build  using Rust Edition 2024. This may be due to its dependency on the `cargo_toml` crate, which is currently specified as version ^0.17. This version does not support Rust Edition 2024,  Upgrading to cargo_toml version ^0.20 might resolve the problem.

### Reproduction

- Create a new Tauri project
- Update the Cargo.toml to set edition = "2024". (Use latest nightly)
- Run tauri

### Expected behavior

The project should compile and run successfully with Rust Edition 2024.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.1.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.85.0-nightly (a2545fd6f 2024-11-28)
    ✔ cargo: 1.85.0-nightly (4c39aaff6 2024-11-25)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin
    - node: 22.11.0
    - pnpm: 9.13.2
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-dialog 🦀: 2.0.3
    - @tauri-apps/plugin-dialog : 2.0.1
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ./dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Stack trace

```text
TOML parse error at line 6, column 11
    |
  6 | edition = "2024"
    |           ^^^^^^
  data did not match any variant of untagged enum Inheritable
  : TOML parse error at line 6, column 11
    |
  6 | edition = "2024"
    |           ^^^^^^
  data did not match any variant of untagged enum Inheritable
```

**Comment by FabianLars** [comment] 2024-11-29 18:32
duplicate of https://github.com/tauri-apps/tauri/issues/10412

**Closed as not planned by FabianLars** 2024-11-29 18:32 UTC
Labels: type: bug, status: needs triage
