### ISSUE TITLE
[bug] Unable to play video and audio tags in compiled app on manjaro(arch)

### ISSUE THREAD

**Issue by Fractal-Tess** [tauri-apps/tauri#4506] opened 2022-06-28 14:13 UTC
### Describe the bug

Hello there

In dev mode, the application behaves as normal and everything works, but once the application has been built and run, the two tags fail to work. The resulting error from trying to play from the tags is the following :
```bash
Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
```
I have already asked about this issue on Tauri's discord channel. FabianLars was kind enough to offer his help, but even he couldn't figure out why it behaved this way. Here is the [link](https://discord.com/channels/616186924390023171/990661255519940608) to the discord thread.

(Sidenote: I tried compiling this and running it on my ubuntu laptop (which) took forever to get dependencies and build. 
However, the same thing is observed at that machine as well.)

### Reproduction

You can try to duplicate this by using my basic[ Svelte-Kit Tauri Template](https://github.com/Fractal-Tess/Svelte-Kit-Tauri-Template) that I've been messing around with for the past few days.
But please note that you should use the `testing-audio` branch instead of `main`.

```bash
git clone --branch testing-audio https://github.com/Fractal-Tess/Svelte-Kit-Tauri-Template
cd Svelte-Kit-Tauri-Template/
npm i
npm run tauri build
```

### Expected behavior

It is expected that the audio/video tags should work as normal and playback the desired files which are pointed to by the 'src' attribute of the HTML tags.

### Platform and versions

```shell
❯ cargo tauri info

Environment
  › OS: Manjaro 21.3.0 X64
  › Node.js: 18.3.0
  › npm: 8.12.2
  › pnpm: 7.1.0
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ static
  ├─ node_modules
  ├─ src
  ├─ .git
  ├─ build
  ├─ .svelte-kit
  └─ src-tauri
```

**Comment by lucasfernog** [comment] 2022-06-29 03:32
Duplicate of #3725

**Closed as completed by lucasfernog** 2022-06-29 03:32 UTC
Labels: type: bug
