### ISSUE TITLE
[feat] Generate a d.ts file for @tauri-apps/api/core:invoke

### ISSUE THREAD

**Issue by alex-way** [tauri-apps/tauri#9589] opened 2024-04-27 09:44 UTC
### Describe the problem

There isn't any type safety for the invoke function, so it's extremely easy to pass invalid arguments.

### Describe the solution you'd like

I think it would be great if rust could generate a `d.ts` file with the different registered handlers.

This should be possible by creating a d.ts file in the root of the "frontend" src like so:

```typescript
declare module "@tauri-apps/api/core" {
	export function invoke<T>(
		cmd: "greet",
		args: {name: string},
		options?: unknown,
	): Promise<T>;

    export function invoke<T>(
		cmd: "meet",
		args: {greeting: string},
		options?: unknown,
	): Promise<T>;

// Optionally exclude this to provide stricter type safety
    export function invoke<T>(
		cmd: string,
		args?: unknown,
		options?: unknown,
	): Promise<T>;
}
```

There may be a better way to provide type safety but this was just my initial thoughts.

**Comment by FabianLars** [comment] 2024-04-27 12:57
Duplicate of https://github.com/tauri-apps/tauri/issues/1514, thanks for the feature request.

**Closed as not planned by FabianLars** 2024-04-27 12:57 UTC
Labels: type: feature request
