### ISSUE TITLE
[bug] run-iteration high CPU usage on Windows

### ISSUE THREAD

**Issue by lgou2w** [tauri-apps/tauri#10373] opened 2024-07-24 10:31 UTC
### Describe the bug

Actual usage varies by CPU. The worse the performance, the higher the usage.

### Windows 10 22H2 (19045.4651)

These two screenshots are running on VirtualBox with 4 CPU cores. If the CPU core is set to 1, then run_iteration will be 100% occupied.

`run_iteration.exe`:
![run-iteration](https://github.com/user-attachments/assets/37f86b8c-6806-423f-abae-489bd1fbf11f)

`helloworld.exe`:
![helloworld](https://github.com/user-attachments/assets/edc3ae85-f38c-4887-bc71-23ad001b72e9)

### Windows 11 23H2 (22631.3880)

This is Windows 11 running on a real physical machine.

https://github.com/user-attachments/assets/ceed1404-18ce-4439-b70f-ff1e343734f5

### BTW

I and tried the previous version of Tauri v1. Changed the run method to run_iteration as follows. The same problem occurs:

```rust
let mut app = ...
loop {
  let iteration = app.run_iteration();
  if iteration.window_count == 0 {
    break;
  }
}
```

### Reproduction

```shell
git clone -b dev https://github.com/tauri-apps/tauri.git
cd tauri
cargo run --example run-iteration --release
cargo run --example helloworld --release
```

Compare their usage in Task Manager.

### Expected behavior

`run_iteration.exe` should be the same as `helloworld.exe`.

### Full `tauri info` output

```text
Windows 10 SDK (10.0.19041.0)

[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.15.1
    - pnpm: 9.5.0
    - npm: 9.6.5

[-] Packages
    - tauri [RUST]: 2.0.0-beta.24
    - tauri-build [RUST]: 2.0.0-beta.19
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - @tauri-apps/api [NPM]: 2.0.0-beta.15
    - @tauri-apps/cli [NPM]: 2.0.0-beta.22

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-07-24 10:48
Thanks for the report! I think this is a duplicate of https://github.com/tauri-apps/tauri/issues/8631 :)

**Closed as not planned by FabianLars** 2024-07-24 10:48 UTC
Labels: type: bug, status: needs triage

**Comment by lgou2w** [comment] 2024-07-24 10:57
> Thanks for the report! I think this is a duplicate of #8631 :)

Thanks for the reply. I apologize for not searching to see that the issue already existed. :)
