### ISSUE TITLE
[bug] failed to create webview to open custom protocol url

### ISSUE THREAD

**Issue by xdewx** [tauri-apps/tauri#6990] opened 2023-05-18 08:54 UTC
### Describe the bug

```ts 
let ww = new WebviewWindow(item.id, {
    url:'https://custom.localhost/pages/index.html',
    title: 'test',
  });
```

the url can't be intercepted by tauri.

### Platform and versions

```text
windows 11
1.3.0
```

**Comment by amrbashir** [comment] 2023-05-18 13:07
duplicate of #5478

**Closed as not planned by amrbashir** 2023-05-18 13:07 UTC
Labels: type: bug, status: needs triage
