### ISSUE TITLE
[bug] Tauri 2.0.0-rc shows blank window after upgrading to webkit2gtk-4.1 2.44.3-2

### ISSUE THREAD

**Issue by tkuestner** [tauri-apps/tauri#10626] opened 2024-08-14 17:50 UTC
### Describe the bug

I created a new tauri app with `cargo create-tauri-app --rc`. Running it with `cargo tauri dev` shows am empty window. Web Dev tool also cannot be opened.

I suspect the reason is the update of webkit2gtk that EndeavourOS rolled out today:
> [2024-08-14T17:28:56+0200] [ALPM] upgraded webkit2gtk (2.44.2-1 -> 2.44.3-2)
> [2024-08-14T17:28:56+0200] [ALPM] upgraded webkit2gtk-4.1 (2.44.2-1 -> 2.44.3-2)

### Reproduction

1. `cargo create-tauri-app --rc`
2. Choose Rust + Leptos
3. `cd tauri-app && cargo tauri dev`

### Expected behavior

1. Show the Tauri template app (here with Leptos)
2. Show the Web Dev tools (from context menu or keyboard shortcut)

### Full `tauri info` output

```text
[✔] Environment
    - OS: EndeavourOS Rolling Release X64
    ✔ webkit2gtk-4.1: 2.44.2
    ✔ rsvg2: 2.58.2
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (2024-05-07)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.6.0
    - pnpm: 9.7.1
    - yarn: 1.22.22
    - npm: 10.8.2

[-] Packages
    - tauri [RUST]: 2.0.0-rc.2
    - tauri-build [RUST]: 2.0.0-rc.2
    - wry [RUST]: 0.41.0
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-rc.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-rc.3

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

### Additional context

I rolled back the package webkit2gtk-4.1 (not webkit2gtk) and the Tauri app displayed as expected without problems.

WebKitGTK announcement: https://webkitgtk.org/2024/08/13/webkitgtk2.44.3-released.html

**Comment by FabianLars** [comment] 2024-08-14 17:55
Welp, not much we can do then probably. 

Try running it with `WEBKIT_DISABLE_COMPOSITING_MODE=1` and/or `WEBKIT_DISABLE_DMABUF_RENDERER=1` maybe 🤔

**Comment by tkuestner** [comment] 2024-08-14 18:11
Thank you for the quick reply.

Unfortunately neither `WEBKIT_DISABLE_COMPOSITING_MODE=1` nor `WEBKIT_DISABLE_DMABUF_RENDERER=1` (or both together) changed the issue.

**Comment by naman-crabnebula** [comment] 2024-09-04 19:21
Hi!

Can you check it now? The issue is fixed in upstream, and it is working fine on my end in Arch Linux with `webkit2gtk-4.1 2.44.3-3`

**Comment by guillemcordoba** [comment] 2024-09-20 10:28
I'm also facing this in ubuntu 20.04, and I think it's actually quite bad... The only versions for libwebkit2gtk-4.1-dev that are available in ubuntu are 2.44.3-0 (which is broken at least for NVIDIA based GPUs) and an older 2.36 (which is too old to be compatible with tauri v2). 

I've tried with the environment variables, and they don't work. I've tried installing an older version of libwebkit2gtk-4.1-dev manually from their deb packages, without success. I've also tried upgrading to ubuntu 24.04, without success. I _think_ that what needs to happen is that the ubuntu team have to release the new and fixed version of the package to their official PPA. I have no idea whether this is something that can be visibly tracked somewhere, haven't found much in their launchpad. I think we are in this situation [since September the 9th](https://launchpad.net/ubuntu/jammy/amd64/libwebkit2gtk-4.1-dev).

So as far as I can see and after having researched this for a few days, I'm left with no way to have a release workflow for tauri apps using github actions, using the tauri action or any other kind of workflow, since github only supports ubuntu based workflows. I would be surprised if a lot of people are not affected by this. I understand that there's not that much that tauri devs can do, but I still think it's necessary to raise awareness that this is a big blocker for tauri v2 having a smooth DX. 

I'd be really happy to be wrong and get some directions on how to work around this... Maybe we can mount pressure for the ubuntu team to get this fixed?

**Comment by duncanawoods** [comment] 2024-09-21 15:58
> Maybe we can mount pressure for the ubuntu team to get this fixed?

It's been raised as a bug by Krzysztof Andrelczyk:

https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/2081166

By registering as an affected user, it increases the "bug heat" metric that hopefully gets it more urgent attention.

**Comment by GurjinderSingh** [comment] 2024-09-25 16:55
I think update on 2024-09-10 caused same issue on Ubuntu  24.04.

```
Upgrade: libjavascriptcoregtk-4.1-0:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), libwebkit2gtk-4.1-dev:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), gir1.2-javascriptcoregtk-4.1:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), gir1.2-javascriptcoregtk-6.0:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), gir1.2-webkit2-4.1:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), libjavascriptcoregtk-6.0-1:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), libjavascriptcoregtk-4.1-dev:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), webkit2gtk-driver:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), libwebkit2gtk-4.1-0:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), gir1.2-webkit-6.0:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1), libwebkitgtk-6.0-4:amd64 (2.44.2-0ubuntu0.24.04.2, 2.44.3-0ubuntu0.24.04.1)
```


> Thank you for the quick reply.
> 
> Unfortunately neither `WEBKIT_DISABLE_COMPOSITING_MODE=1` nor `WEBKIT_DISABLE_DMABUF_RENDERER=1` (or both together) changed the issue.

same for me

**Comment by tetuaoro** [comment] 2024-10-15 15:20
I'm also facing this issue.

EDIT : downgrading the packages work for me [#354](https://github.com/hrzlgnm/mdns-browser/issues/354)

**Comment by SakiiCode** [comment] 2024-10-23 10:02
Fixed on Linux Mint after upgrading to libwebkit2gtk 2.46.1

**Comment by tetuaoro** [comment] 2024-10-24 12:41
> Fixed on Linux Mint after upgrading to libwebkit2gtk 2.46.1

Thx, Ubuntu 24.4 works too `libwebkit2gtk 2.46.1` and `trunk 0.21.1`.

**Comment by GurjinderSingh** [comment] 2024-10-24 19:26
If you marked an old version as 'hold,' it can now be removed using commands.

### list package on hold 
```
sudo apt-mark showhold
```

```
gir1.2-javascriptcoregtk-4.1
gir1.2-webkit2-4.1
libjavascriptcoregtk-4.1-0
libjavascriptcoregtk-4.1-dev
libwebkit2gtk-4.1-0
libwebkit2gtk-4.1-dev
```
### remove from hold 
```
sudo apt-mark unhold gir1.2-javascriptcoregtk-4.1 gir1.2-webkit2-4.1 libjavascriptcoregtk-4.1-0 libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-0 libwebkit2gtk-4.1-dev
```
update to latest version 2.46.1

@FabianLars  
please close issues 

https://github.com/tauri-apps/tauri/issues/11166

**Closed as completed** 2024-10-24 20:20 UTC
Labels: type: bug, status: upstream, platform: Linux
