### ISSUE TITLE
[bug] Tauri 'Winodw Customization' chapter example code will lead to tauri crash

### ISSUE THREAD

**Issue by awkj** [tauri-apps/tauri#3426] opened 2022-02-12 15:02 UTC
### Describe the bug

I run example https://tauri.studio/docs/guides/window-customization

When I click the button, Tauri Crash, it's fault stdout 

```
2022-02-12 22:59:48.372 app[45984:642099] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff804d24f0b __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff804a85b9d objc_exception_throw + 48
        2   CoreFoundation                      0x00007ff804de0434 _CFThrowFormattedException + 202
        3   CoreFoundation                      0x00007ff804deaca1 -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
        4   CoreFoundation                      0x00007ff804c33f12 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 251
        5   CoreFoundation                      0x00007ff804c33dfd +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
        6   VisionKitCore                       0x00007ffb14489a31 -[VKAnalyticsAnalyzerEvent coreAnalyticsDictionary] + 1292
        7   VisionKitCore                       0x00007ffb1444cfec -[VKAnalyticsProcessor processAndSendEvent:] + 96
        8   VisionKitCore                       0x00007ffb14443426 __69-[VKImageAnalyzer _processRequest:progressHandler:completionHandler:]_block_invoke_2 + 1254
        9   libdispatch.dylib                   0x00007ff804a2aad8 _dispatch_call_block_and_release + 12
        10  libdispatch.dylib                   0x00007ff804a2bcc9 _dispatch_client_callout + 8
        11  libdispatch.dylib                   0x00007ff804a31cee _dispatch_lane_serial_drain + 696
        12  libdispatch.dylib                   0x00007ff804a327c8 _dispatch_lane_invoke + 366
        13  libdispatch.dylib                   0x00007ff804a3c7e1 _dispatch_workloop_worker_thread + 758
        14  libsystem_pthread.dylib             0x00007ff804bdf074 _pthread_wqthread + 326
        15  libsystem_pthread.dylib             0x00007ff804bddffb start_wqthread + 15
)
libc++abi: terminating with uncaught exception of type NSException
```

### Platform and versions

```shell
Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.2
  @tauri-apps/api - 1.0.0-rc.0

Global packages
  npm - 8.3.1
  pnpm - 6.30.1
  yarn - 1.22.17

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin 

App directory structure
/dist
/node_modules
/src-tauri
/src

App
  tauri.rs - 1.0.0-rc.0
  build-type - bundle
  CSP - default-src 'self'
  distDir - ../dist
  devPath - http://localhost:3000/
  framework - React
```

**Comment by lucasfernog** [comment] 2022-02-12 15:43
Duplicate of #2934

**Closed as completed** 2022-02-12 15:43 UTC
Labels: type: bug

**Comment by awkj** [comment] 2022-02-12 15:47
sad, I had a slight suspicion that it might be a Safari/webkit problem, but I didn't really believe that such a common problem could actually happen with Safari/webkit

It's IE 2.0
