### ISSUE TITLE
Add config to disable the view sliding movement.

### ISSUE THREAD

**Issue by MountainAndMorning** [tauri-apps/tauri#4802] opened 2022-07-31 08:07 UTC
### Describe the problem

The app view will move when I slide the trackpad

https://user-images.githubusercontent.com/30199027/182016204-72337ba9-a264-4bb0-afea-70789faf1a71.mp4

.

### Describe the solution you'd like

Add a config to disable this effect.

**Comment by amrbashir** [comment] 2022-07-31 11:43
Please post your `tauri info`

**Comment by MountainAndMorning** [comment] 2022-07-31 12:11
Here is my package info:
```javascript
  "scripts": {
    "serve": "vite preview",
    "build": "vite build",
    "dev": "vite",
    "preview": "vite preview",
    "tauri": "tauri"
  },
  "dependencies": {
    "@mdi/font": "5.9.55",
    "@tauri-apps/api": "^1.0.2",
    "roboto-fontface": "*",
    "vue": "^3.2.37",
    "vuetify": "^3.0.0-beta.0",
    "vuex": "^4.0.0",
    "webfontloader": "^1.0.0"
  },
  "devDependencies": {
    "@mdi/js": "^7.0.96",
    "@tauri-apps/cli": "^1.0.5",
    "@types/webfontloader": "^1.0.0",
    "@vitejs/plugin-vue": "^3.0.0",
    "@vue/cli-plugin-vuex": "~5.0.0",
    "typescript": "^4.6.4",
    "vite": "^3.0.0",
    "vite-plugin-vuetify": "^1.0.0-alpha.0",
    "vue-cli-plugin-vuetify": "~2.5.1",
    "vue-tsc": "^0.38.4"
  },
  "type": "module"
```
It seems that this behaviour is common in the tauri apps. For example, the view of the mdsilo app, available at https://github.com/danloh/mdSilo-app, also move when I slide my trackpad.

https://user-images.githubusercontent.com/30199027/182025671-278d75d1-effc-4d41-801f-926aa3c2b2dc.mp4

.

**Comment by amrbashir** [comment] 2022-07-31 12:15
That's not `tauri info`, run `yarn tauri info` to get the full info we need.

**Comment by MountainAndMorning** [comment] 2022-07-31 12:22
Here is the result of `yarn tauri info`:
yarn run v1.22.19
$ tauri info

Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  ├─ .idea
  └─ src
✨  Done in 31.37s.

**Comment by amrbashir** [comment] 2022-07-31 12:26
I think this is duplicate of https://github.com/tauri-apps/tauri/issues/4309

**Closed as not planned by amrbashir** 2022-07-31 12:26 UTC
Labels: type: feature request

**Comment by MountainAndMorning** [comment] 2022-07-31 12:39
Thanks for your help. Can you tell me where I can add this css code to disable the bounce effect.
body {
	position: fixed;
	width: 100%;
	height: 100%;
	overflow: hidden;
}

**Comment by amrbashir** [comment] 2022-07-31 12:45
in your `css` file or in a style tag in your html like this https://www.w3schools.com/tags/tag_style.asp

**Comment by MountainAndMorning** [comment] 2022-07-31 12:54
I add code in the index.html file. But the problem still exists.
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vuetify 3 Vite Preview</title>
    <style>
        body {
            position: fixed;
            width: 100%;
            height: 100%;
            overflow: hidden;
        }
    </style>
</head>

<body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
</body>
</html>
```
