### ISSUE TITLE
Adding plugin to project fails to install NPM dependency

### ISSUE THREAD

**Issue by MrLightful** [tauri-apps/tauri#10906] opened 2024-08-28 08:30 UTC
# Problem
`pnpm tauri add process --verbose`

```
> tauri "add" "process" "--verbose"
    Info [tauri_cli::helpers::cargo] Installing Cargo dependency "tauri-plugin-process"...
    Info [tauri_cli::helpers::npm] Installing NPM dependency "@tauri-apps/plugin-process@2.0.0-rc"...
    Error [tauri_cli_node] Failed to install NPM dependency
 ELIFECYCLE  Command failed with exit code 1.
```

# Reproduce
The issue is reproducable on a dummy project: 
```
pnpm create tauri-app --rc
cd tauri-app
npm install
npm run tauri dev
```

# Hypothesis
The script attempts to install `@tauri-apps/plugin-process@2.0.0-rc`. Version `2.0.0-rc` doesn't exist, but `2.0.0-rc.0` does ([npm versions](https://www.npmjs.com/package/@tauri-apps/plugin-process?activeTab=versions)).

**Comment by MrLightful** [comment] 2024-08-28 08:41
`pnpm tauri add process@2.0.0-rc.0` works. But the default command is still expected to successfully install the latest or smth.

**Comment by amrbashir** [comment] 2024-08-28 15:13
This should be fixed in the next release, see https://github.com/tauri-apps/tauri/pull/10795

**Comment by FabianLars** [comment] 2024-09-05 16:21
https://github.com/tauri-apps/tauri/pull/10795 doesn't work for npm at least.

**Comment by amrbashir** [comment] 2024-09-18 04:18
What's the problematic `npm` and `pnpm` versions did you test with? 

I ran `npm add "@tauri-apps/plugin-http@^2.0.0-rc"` with npm and pnpm and both worked fine

**Comment by MrLightful** [comment] 2024-09-18 08:22
I actually can confirm that the latest version of cli works fine. I forgot that cli is a cargo package and not npm. So updating cargo (`cargo update`) in `/src-tauri`, and then attempting to add plugins works now.

**Comment by FabianLars** [comment] 2024-09-18 10:22
@amrbashir 
> What's the problematic npm and pnpm versions did you test with?

Latest pnpm (9.10) and whatever comes with lts node for npm (10.8.2). Latest tauri cli rc (rc.16).

`pnpm tauri add sql`:
```
...
      Adding wry v0.43.1 (latest: v0.44.0)
    Info Installing NPM dependency "@tauri-apps/plugin-sql@^2.0.0-rc"...
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @tauri-apps/plugin-sql@2.0.0-rc

This error happened while installing a direct dependency of A:\fabianlars\temp\add

The latest release of @tauri-apps/plugin-sql is "2.0.0-rc.1".

If you need the full list of all 17 published versions run "$ pnpm view @tauri-apps/plugin-sql versions".
Progress: resolved 5, reused 5, downloaded 0, added 0
Failed to install NPM dependency
    Error Failed to install NPM dependency
 ELIFECYCLE  Command failed with exit code 1.
```
^ same for `sql@2.0.0-rc` and `sql@^2.0.0-rc` btw - same for the process plugin mentioned above.

`npm run tauri add sql`:
```
...
      Adding wry v0.43.1 (latest: v0.44.0)
    Info Installing NPM dependency "@tauri-apps/plugin-sql@^2.0.0-rc"...
npm error code ETARGET
npm error notarget No matching version found for @tauri-apps/plugin-sql@2.0.0-rc.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: A:\_packages\npm\_logs\2024-09-18T10_17_55_748Z-debug-0.log
Failed to install NPM dependency
    Error Failed to install NPM dependency
```

----

I also had similar reports on discord so if i am using the command wrong, i'm not the only one at least.

----

Edit: Just got a new report so i'll re-open this until properly investigated.

**Closed as completed** 2024-09-19 20:11 UTC
Labels: type: bug, status: backlog

**Comment by Haprog** [comment] 2024-10-04 08:45
I'm using tauri-cli 2.0.0 with pnpm 9.12.0 and this still doesn't work. I get this:

![tauri-v2-pnpm-dep-install-issue](https://github.com/user-attachments/assets/62aa753a-4423-4cf9-811a-6364e42ccafe)

Should this be a different issue?

Maybe the problem is related to using pnpm in the project? I can add dependencies without issues manually with pnpm, but tauri CLI doesn't seem to be able to.

**Comment by Haprog** [comment] 2024-10-04 08:50
Nvm, my problem was my usage of pnpm workspaces and also installing dependencies in workspace root (which is my tauri app). If I tried manually adding that with:
```
pnpm add @tauri-apps/plugin-dialog@~2
```
I got:

>  ERR_PNPM_ADDING_TO_ROOT  Running this command will add the dependency to the workspace root, which might not be what you want - if you really meant it, make it explicit by running this command again with the -w flag (or --workspace-root). If you don't want to see this warning anymore, you may set the ignore-workspace-root-check setting to true.

I was able to get this working just by adding `ignore-workspace-root-check = true` into my `.npmrc`

**Comment by Haprog** [comment] 2024-10-04 08:51
However it would be nice if Tauri CLI would show the pnpm error message so this would have been faster to figure out.

**Comment by amrbashir** [comment] 2024-10-21 17:05
try with `--verbose` flag, it should show the error
