### ISSUE TITLE
[feat] Support for playing audio/video on linux/mac without requirng an interaction

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#3743] opened 2022-03-21 03:46 UTC
### Describe the problem

On linux and mac, playing audio/video requires interaction on the window

### Describe the solution you'd like

To add support to play video/audio on the app without requiring interactions

### Alternatives considered

Right now we are controling the mouse to click the top corner of the window

**Comment by FabianLars** [comment] 2022-03-21 07:58
should be a duplicate of #3478, right?

**Closed as completed** 2022-03-21 14:18 UTC
Labels: type: feature request, status: invalid
