### ISSUE TITLE
[feat] Support Rust function execution in the browser

### ISSUE THREAD

**Issue by Chralt98** [tauri-apps/tauri#9161] opened 2024-03-12 09:51 UTC
### Describe the problem

Currently the standard create tauri app scaffold build doesn't support the simple greet function written in Rust using the web browser. The Rust only executes on the desktop application.

### Describe the solution you'd like

Instead of running Rust functions as commands only in the desktop environment, one should be able to execute the Rust back-end program code in a compiled WASM binary in the browser instead.

In this way the web application in the browser is able to opt-in into fast runtime execution, if needed.

### Additional context

I read the issue [here](https://github.com/tauri-apps/tauri/issues/2852#issuecomment-964099967). 

> what's currently missing are wasm-native bindings for the tauri ap

**Comment by FabianLars** [comment] 2024-03-12 10:41
Thanks for the request :) This looks like a duplicate of https://github.com/tauri-apps/tauri/issues/8248 to me though so i'm closing this.

**Closed as not planned by FabianLars** 2024-03-12 10:41 UTC
Labels: type: feature request
