### ISSUE TITLE
[bug] Some kind of regression between commit 9bb689 and v1.0.0-rc.1 in webview

### ISSUE THREAD

**Issue by mihirsamdarshi** [tauri-apps/tauri#3452] opened 2022-02-14 06:05 UTC
### Describe the bug

There has been some kind of regression between commit 9bb689 and v1.0.0-rc.1 in the webview. 

Previously my application was able to build and load the webview just fine, however, now I seem to be getting an error in the webview: `TypeError: Attempted to assign to readonly value`. This occurs specifically with my `dayjs` and `lodash` dependencies.

I am not sure how to go about debugging this, let me know what info you need.

### Platform and versions

```shell
$ /Users/msamdars/Code/omicspipelines-infrastructure/node_modules/.bin/tauri info

Operating System - Mac OS, version 12.2.1 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-rc.2
  @tauri-apps/api - 1.0.0-rc.0

Global packages
  npm - 8.1.2
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustc - 1.60.0-nightly
  cargo - 1.60.0-nightly

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0-nightly
  cargo - 1.60.0-nightly
  toolchain - nightly-x86_64-apple-darwin

App directory structure
/.husky
/bin
/node_modules
/.cargo
/public
/.github
/src-tauri
/build
/.git
/infrastructure
/coverage
/.run
/.idea
/src

App
  tauri.rs - 1.0.0-rc.1
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:9090/
  framework - React
  bundler - Rollup
✨  Done in 10.23s.
```

**Comment by FabianLars** [comment] 2022-02-14 06:49
I'm lazy so I'm just gonna copy my answer from #3438:

Duplicate of #3424, #3416, #3406.
We released a fix of it already, try running `cargo update` in your src-tauri dir (make sure your tauri-build dependency in Cargo.toml is updated too).
If that doesn't work you can manually set tauri.conf.json > security > freezePrototype to false. Note that you should freeze the prototype later if possible.

**Closed as completed** 2022-02-14 06:50 UTC
Labels: status: invalid
