### ISSUE TITLE
[bug] Custom window menu disables default shortcuts

### ISSUE THREAD

**Issue by juancarloselorriaga** [tauri-apps/tauri#7428] opened 2023-07-16 12:38 UTC
### Describe the bug

Custom window menu disables Cmd + C, Cmd + V, Cmd + A in NextJS app
![imagen](https://github.com/tauri-apps/tauri/assets/34046056/45948618-78d8-4a73-bac2-d11b6b50ec9b)

### Reproduction

I haven't tried this on Windows or Linux, this is only Mac (that I know of)

1. Create a Tauri app with NextJS
2. Add a menu, it could be a new empty menu or with items.
3. Add an input HTML element to the NextJS app
4. Focus the input and write some text. Try the usual commands to copy, paste or select all.
5. They won't work.

### Expected behavior

Expected behaviour of an input and a keyboard interaction,

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.71.0-nightly (8bdcc62cb 2023-04-20)
    ✔ Cargo: 1.71.0-nightly (d0a4cbcee 2023-04-16)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: nightly-aarch64-apple-darwin (default)
    - node: 16.14.2
    - yarn: 1.22.10
    - npm: 8.5.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../out
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Additional context

By just removing .menu(menu) from the Tauri builder it works as expected.

**Comment by FabianLars** [comment] 2023-07-16 13:08
Duplicate of https://github.com/tauri-apps/tauri/issues/2397 (and a few others). Basically on macOS these shortcuts like these require the respective menu items which is why tauri adds a default one on macos.

**Closed as not planned** 2023-07-16 13:08 UTC
Labels: type: bug, status: needs triage
