### ISSUE TITLE
[bug] After installing via deb, the tray icon does not appear

### ISSUE THREAD

**Issue by witt-bit** [tauri-apps/tauri#11480] opened 2024-10-24 10:35 UTC
### Describe the bug

The tray icon is displayed normally in the `dev` startup scenario, but not when the deb file is installed

![image](https://github.com/user-attachments/assets/a915481e-8849-4efd-8521-80f133d4a7ee)

### Full `tauri info` output

```text
$ pnpm tauri info                                                                                          INT ✘ 

> eco-paste@0.3.0-beta.1 tauri /home/witt/codes/open-source/EcoPaste
> tauri "info"


[✔] Environment
    - OS: Manjaro 24.1.1 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.4
    ✔ rsvg2: 2.58.4
    ✔ rustc: 1.81.0 (eeb90cda1 2024-09-04)
    ✔ cargo: 1.81.0 (2dbb1af80 2024-08-20)
    ✔ rustup: 1.27.1 (2024-05-07)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 23.0.0
    - pnpm: 9.12.2
    - yarn: 1.22.22
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: git+https://github.com/Legend-Master/tao?branch=fix-set-theme-mac-crash#147a36719471864f3d165ef0f5ceba2acdd22687 (0.30.3)
    - @tauri-apps/api : 2.0.2 (outdated, latest: 2.0.3)
    - @tauri-apps/cli : 2.0.3 (outdated, latest: 2.0.4)


[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.0 (outdated, latest: 2.0.1)
    - tauri-plugin-single-instance 🦀: 2.0.1
    - @tauri-apps/plugin-single-instance : not installed!
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : 2.0.0 (outdated, latest: 2.0.1)
    - tauri-plugin-log 🦀: 2.0.1
    - @tauri-apps/plugin-log : 2.0.0
    - tauri-plugin-process 🦀: 2.0.1
    - @tauri-apps/plugin-process : 2.0.0
    - tauri-plugin-os 🦀: 2.0.1
    - @tauri-apps/plugin-os : 2.0.0
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : 2.0.0
    - tauri-plugin-sql 🦀: 2.0.1
    - @tauri-apps/plugin-sql : 2.0.0
    - tauri-plugin-autostart 🦀: 2.0.1
    - @tauri-apps/plugin-autostart : 2.0.0
    - tauri-plugin-dialog 🦀: 2.0.3
    - @tauri-apps/plugin-dialog : 2.0.0 (outdated, latest: 2.0.1)
    - tauri-plugin-updater 🦀: 2.0.2
    - @tauri-apps/plugin-updater : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

### Additional context

```shell
    ~  screenfetch                                                                                                                                                   ✔ 

 ██████████████████  ████████     witt@witt-cool
 ██████████████████  ████████     OS: Manjaro 24.1.1 Xahea
 ██████████████████  ████████     Kernel: x86_64 Linux 6.10.13-3-MANJARO
 ██████████████████  ████████     Uptime: 3d 8h 22m
 ████████            ████████     Packages: 1355
 ████████  ████████  ████████     Shell: zsh 5.9
 ████████  ████████  ████████     Resolution: 3840x1080
 ████████  ████████  ████████     DE: KDE
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     GTK Theme: Adwaita-dark [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Tela-circle-manjaro-light
 ████████  ████████  ████████     Disk: 167G / 467G (38%)
 ████████  ████████  ████████     CPU: AMD Ryzen 5 4500U with Radeon Graphics @ 6x 2.375GHz
 ████████  ████████  ████████     GPU: AMD Radeon Graphics (radeonsi, renoir, LLVM 18.1.8, DRM 3.57, 6.10.13-3-MANJARO)
                                  RAM: 10375MiB / 15359MiB
```

**Comment by ahqsoftwares** [comment] 2024-10-26 08:04
I have not been able to reproduce the same in my desktop app (tauri v2)

**Comment by downace** [comment] 2024-10-31 06:25
I've encountered similar issue.
But in my case it was caused by me trying to use custom tray icon, which was not bundled as a resource. So I'm not sure if it's related.

Before:
```ts
// app.ts
import { Image } from "@tauri-apps/api/image";
import { path } from "@tauri-apps/api";
// icon in src-tauri/icons/my-icon.png
await tray.setIcon(await Image.fromPath(await path.resolve("icons", "my-icon.png")));

// this was unreachable because of failed promise above (file not found in built app),
// tray icon was not showing
await tray.setMenu(...);
```

After:
```json5
// tauri.conf.json
{
  // ...
  "bundle": {
    "resources": ["resources/**/*"]
  }
}
```
```ts
// app.ts
import { Image } from "@tauri-apps/api/image";
import { resolveResource } from "@tauri-apps/api/path";
// icon moved to src-tauri/resources/icons/my-icon.png
await tray.setIcon(await Image.fromPath(await resolveResource("resources/icons/my-icon.png")));

// ok
await tray.setMenu(...);
```

**Comment by ayangweb** [comment] 2024-10-31 07:46
Hey 👋, everyone! I've managed to add to `resources` before using the icon, which is guaranteed to work on Windows, macOS and Linux (Gnome), but not Linux (KDE)!

<img width="1541" alt="image" src="https://github.com/user-attachments/assets/3b24848c-607d-40ac-b100-3a48250b5583">

<img width="1541" alt="image" src="https://github.com/user-attachments/assets/9e618486-a838-4665-b2c1-2c572535753b">

Linux (Gnome)：
<img width="1758" alt="image" src="https://github.com/user-attachments/assets/995ec8f1-3d20-4a4d-be72-f79f4fa5bcb6">

**Comment by ahqsoftwares** [comment] 2024-10-31 08:00
We enter the nice world of DEs again haha. Does anyone have any idea why it won't work in KDE?

**Comment by ahqsoftwares** [comment] 2024-10-31 08:00
There's no reproduction either

**Comment by amrbashir** [comment] 2024-11-01 00:18
please share a reproduction, the icon is displayed correctly on my KDE

**Comment by ayangweb** [comment] 2024-11-01 00:40
@amrbashir Hey 👋, can you try (https://github.com/EcoPasteHub/EcoPaste/releases/tag/v0.2.0) sometime? If it works, it should be a problem with @witt-bit's computer, right?

**Comment by amrbashir** [comment] 2024-11-01 01:02
I am on arch, not debian, so I had to use `debtap` to create an arch package and install it. It works on KDE and the tray icon shows up.

**Comment by ahqsoftwares** [comment] 2024-11-01 01:30
> I am on arch, not debian, so I had to use `debtap` to create an arch package and install it. It works on KDE and the tray icon shows up.

I'm on Ubuntu, it perfectly works. I also had kde neon. Tray icon used to work

**Comment by ayangweb** [comment] 2024-11-01 01:32
@amrbashir I implemented the tray in a pure front-end way, can you see any problems with the code?

https://github.com/EcoPasteHub/EcoPaste/blob/master/src/components/Tray/index.tsx

**Comment by amrbashir** [comment] 2024-11-01 01:35
@ayangweb I can't see a problem,  if you have any issue please make a minimal repro

**Comment by ayangweb** [comment] 2024-11-01 01:37
Haha🤣, I don't see any problems either, but it really doesn't work properly in KDE, all other platforms are fine.

**Comment by amrbashir** [comment] 2024-11-04 13:02
closing this then, since no one can reproduce.

**Closed as not planned by amrbashir** 2024-11-04 13:02 UTC
Labels: type: bug, platform: Linux, status: needs triage
