### ISSUE TITLE
[bug] `data-tauri-drag-region` affects the `resizable` of the window.

### ISSUE THREAD

**Issue by ayangweb** [tauri-apps/tauri#10735] opened 2024-08-22 07:44 UTC
### Describe the bug

In windows, if `data-tauri-drag-region` is set for the window top-level element, `resizable` will not work.

https://github.com/user-attachments/assets/140d0f65-44ae-4774-b439-09724e828617

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 127.0.2651.105
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-pc-windows-msvc (default)
    - node: 20.14.0
    - pnpm: 9.6.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
```

**Comment by amrbashir** [comment] 2024-08-22 14:11
This is kinda expected behavior due to the limitation of how undecorated window resizing is implemented on Windows in v1. This is however fixed in v2 (stay tuned for stable release).

A workaround for v1, would be to keep 1~5 px on each side of your app, that doesn't have `data-tauri-drag-region` just to allow resizing to work. 

Here is an example of adding `tauri-drag-region` to an inner container `div` and using `padding` on the `body` element.
```html
<head>
  <style>
  	body {
  	  padding: 5px;
  	}
  </style>
</head>

<body>
  <div data-tauri-drag-region>
    .. your app here ..
  </div>
</body>
```

**Closed as completed by amrbashir** 2024-08-22 14:11 UTC
Labels: type: bug, status: needs triage

**Comment by ayangweb** [comment] 2024-08-30 06:14
@amrbashir Hey, which pr is implemented in v2? I'd like to check it out!

**Comment by amrbashir** [comment] 2024-08-30 22:17
@ayangweb https://github.com/tauri-apps/tauri/pull/9862
