### ISSUE TITLE
[bug] THREE.WebGLRenderer: A WebGL context could not be created. Reason: "Could not create a WebGL context."

### ISSUE THREAD

**Issue by Lxdovic** [tauri-apps/tauri#8498] opened 2023-12-29 21:31 UTC
### Describe the bug

When i try to implement R3F (threejs) scenes on my desktop:
![Screenshot from 2023-12-29 21-54-48](https://github.com/tauri-apps/tauri/assets/80395681/c2f80905-258d-4bcf-a6fc-f2b1473c4be2)

It works when i open the app on my web browser but not inside tauri.
Also it works on my laptop and i couldn't figure out why.

Desktop
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.10
Release:	23.10
Codename:	mantic
``` 

Laptop
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
``` 

### Reproduction

```shell
git clone git@github.com:Lxdovic/tauri-webgl.git
npm pm run tauri dev
``` 

### Expected behavior

![image](https://github.com/tauri-apps/tauri/assets/80395681/4fb9680a-419f-4850-9468-720a3c70ffff)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 23.10 X64
    ✔ webkit2gtk-4.0: 2.42.3
    ✔ rsvg2: 2.54.7
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.10.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2023-12-29 22:42
Let's count this as a duplicate of https://github.com/tauri-apps/tauri/issues/6559. (Thanks for the report nonetheless)

**Closed as not planned by FabianLars** 2023-12-29 22:42 UTC
Labels: type: bug, status: needs triage
