### ISSUE TITLE
[bug] An insecure WebSocket connection may not be initiated from a page loaded over HTTPS

### ISSUE THREAD

**Issue by trookie2000** [tauri-apps/tauri#7651] opened 2023-08-18 07:25 UTC
### Describe the bug

Mixed Content: The page at 'https://tauri.localhost/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.2.171:8080/conn/d7c52c9d3dfe44638a75aacbf7a0b08e'. This request has been blocked; this endpoint must be available over WSS.

### Reproduction

No response

### Expected behavior

No response

### Platform and versions

```text
Environment
› OS: Windows 10.0.19044 X64
› Webview2: 104.0.1293.63
› MSVC:
- Visual Studio ���ɹ��� 2022
› Node.js: 16.15.1
› npm: 8.15.1
› pnpm: Not installed!
› yarn: 1.22.19
› rustup: 1.25.1
› rustc: 1.62.1
› cargo: 1.62.1
› Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
› @tauri-apps/cli [NPM]: 1.0.5
› @tauri-apps/api [NPM]: 1.0.2
› tauri [RUST]: 1.0.5,
› tauri-build [RUST]: 1.0.4,
› tao [RUST]: 0.12.2,
› wry [RUST]: 0.19.0,

App
› build-type: bundle
› CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
› distDir: ../dist
› devPath: http://localhost:5173
› framework: Vue.js

App directory structure
├─ .vscode
├─ dist
├─ node_modules
├─ public
├─ src
└─ src-tauri
```

### Stack trace

```text
Mixed Content: The page at 'https://tauri.localhost/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://192.168.2.171:8080/conn/d7c52c9d3dfe44638a75aacbf7a0b08e'. This request has been blocked; this endpoint must be available over WSS.

DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

**Comment by FabianLars** [comment] 2023-08-18 21:12
Hi 👋 This is a duplicate of <https://github.com/tauri-apps/tauri/issues/3007>. That issue also mentions a few workarounds if you can't make your websocket server use ssl. The most important workarounds are the websocket plugin, which can connect to non-secure servers just fine, and the localhost plugin which makes your frontend run on `http://localhost` (also exposing your frontend to the whole user system).
I'm also working on a better solution here https://github.com/tauri-apps/tauri/pull/7645 - i hope i can get it into 1.5 but no promises.

**Closed as not planned by FabianLars** 2023-08-18 21:12 UTC
Labels: type: bug, status: needs triage

**Comment by Zhuinden** [comment] 2023-11-16 11:22
Interestingly, you might just need to enable insecure content in your browser to fix it.

**Comment by scifishorts** [comment] 2025-03-12 19:14
I encountered this and solved it by adding --https to the package.json file for the serve instance.

"scripts": {
    "serve": "vue-cli-service serve --https",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
