### ISSUE TITLE
Intermittent Blank Screen On Windows

### ISSUE THREAD

**Issue by Kelerchian** [tauri-apps/tauri#1092] opened 2020-11-17 14:51 UTC
**Describe the bug**
A tauri app bundled in an `.msi` file shows blank intermittently when started.

**To Reproduce**
1. Clone [https://github.com/Kelerchian/try-tauri](https://github.com/Kelerchian/try-tauri)
2. `cd /{PROJECT_PATH}/src-ui; npm install; npm run build;` 
3. `cd /{PROJECT_PATH}/src-tauri; npx tauri build;`
4. run `/{PROJECT_PATH}/src-tauri/target/release/bundle/msi/try-tauri_0.1.0_x64.msi`
5. start `/{INSTALLATION_PATH}/try-tauri.exe`

**Expected behavior**
App does not show blank screen when started.

**Screenshots**
![tauri-blank-screen](https://user-images.githubusercontent.com/11693412/99404991-cec97900-291e-11eb-9962-58fb3e7df0d0.gif)

**Platform and Versions (please complete the following information):**
OS: Windows_NT(10.0.19042) - win32/x64
Edge: 44.19041.423.0_neutral__8wekyb3d8bbwe
Tauri.js: 0.13.0
Tauri-bundler: 0.9.4
Tauri.rs: 0.10.0
Node: v12.14.0
NPM: 6.13.7
Yarn: None
Rustc: 1.47.0 (18bf6b4f0 2020-10-07)

**Additional context**
From `tauri info`
  tauri.rs - 0.10.0
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist/ui
  devPath - http://localhost:41234

**Comment by mikart143** [comment] 2020-11-25 19:35
I have the same issue. Check what happens od edge and on IE11. It turns out that my tauri use ie11 not edge. I have no clue how to change this.

**Comment by lucasfernog** [comment] 2020-12-05 01:10
It's probably a compatibility issue (IE11) with your JavaScript code. Can you try running your app on IE and see if it works?

**Comment by Kelerchian** [comment] 2020-12-05 05:51
How do you see if uses edge or ie11, and how do you configure it?

Also, note that it is intermittent.
It sometimes renders the application, it sometimes doesn't.
I'm sure this is not an issue with the JS code because the JS code should be static in this bundled build unless Tauri intermittently switch between ie11 (not compatible) and edge (compatible) between different executions.

**Comment by lucasfernog** [comment] 2020-12-05 12:28
I can try it if there's a repo I can clone to reproduce it.
Otherwise I'd recommend downloading the Microsoft Edge DevTools on Windows Store and trying to see what's going on (debug flag needed, `npm run tauri --debug`).

**Comment by Kelerchian** [comment] 2020-12-05 13:09
I put a link on the top comment. Here you go https://github.com/Kelerchian/try-tauri

Oh, when debugged with Edge DevTools, the DevTools crashes

**Comment by nothingismagick** [comment] 2021-02-12 15:23
I believe this issue will also be resolved by the next release.

**Closed as completed by nothingismagick** 2021-02-12 15:23 UTC
Labels: type: bug
