### ISSUE TITLE
[bug] `npm run tauri dev` and similar commands failing after upgrading to Fedora 38

### ISSUE THREAD

**Issue by GeckoEidechse** [tauri-apps/tauri#6759] opened 2023-04-20 12:13 UTC
### Describe the bug

After upgrading from Fedora 37 to Fedora 38 I now get the following error when running `npm run tauri dev`

```
$ npm run tauri dev

> tauri
> tauri dev

error: The subcommand '/usr/bin/node-18' wasn't recognized

Usage: cargo-tauri [OPTIONS] <COMMAND>

For more information try '--help'
```

### Reproduction

1. Use a system with Fedora 38
2. Install all dependency for Tauri
3. Find a Tauri project that uses `npm`. For reference I used my project (https://github.com/R2NorthstarTools/FlightCore/) at commit `a74785bb9e6300b0baeb4f92aa647e3b498f7d0b`
4. Install dependencies with `npm install`
5. Run `npm run tauri dev`
6. You should the error message above with `error: The subcommand '/usr/bin/node-18' wasn't recognized`

### Platform and versions

```text
`npm run tauri info` gives the same error

$ npm run tauri info

> tauri
> tauri info

error: The subcommand '/usr/bin/node-18' wasn't recognized

Usage: cargo-tauri [OPTIONS] <COMMAND>

For more information try '--help'
```
```


### Stack trace

_No response_

### Additional context

While researching this issue I also came across this thread: https://discussion.fedoraproject.org/t/after-upgrading-to-fedora-38-i-cant-build-any-tauri-apps-that-need-nodejs/46945/

**Comment by FabianLars** [comment] 2023-04-20 12:17
Duplicate of https://github.com/tauri-apps/tauri/issues/6427, fixed in https://github.com/tauri-apps/tauri/pull/6432 which will be part of v1.3 (hopefully released soon). Thanks for the report :)

**Closed as not planned by FabianLars** 2023-04-20 12:17 UTC
Labels: type: bug, status: needs triage

**Comment by GeckoEidechse** [comment] 2023-04-20 12:19
Surprised I didn't find the issue while looking through GitHub but oh well ¯\\\_(ツ)\_/¯

Thanks for the heads-up ^^
