### ISSUE TITLE
[bug] Empty`defaultPath` on `dialog.save` causes crash

### ISSUE THREAD

**Issue by salmenf** [tauri-apps/tauri#9762] opened 2024-05-12 19:11 UTC
### Describe the bug

On Mac OS, calling `dialog.save` with the empty string as the `defaultPath` causes a panic, crashing the application.

### Reproduction

Call `dialog.save` with the empty string `""` as the `defaultPath`, e.g.:
```js
import {save} from "@tauri-apps/api/dialog"
save({defaultPath: ""})
```

### Expected behavior

I'd expect the same behavior as on Windows: If the `defaultPath` is the empty string, consider it undefined and use the system default behavior. If the title is left `undefined` on Mac, this already happens.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.13.0
    - npm: 10.7.0
    - bun: 1.1.7

[-] Packages
    - tauri [RUST]: 1.6.3
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.5.3 (outdated, latest: 1.5.5)
    - @tauri-apps/cli [NPM]: 1.5.13

[-] App
```

### Stack trace

```text
thread 'main' panicked at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_id-0.1.1/src/id.rs:62:9:
Attempted to construct an Id from a null pointer
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:686:12
   1: objc_id::id::Id<T,O>::from_retained_ptr
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_id-0.1.1/src/id.rs:62:9
   2: rfd::backend::macos::utils::url::INSURL::file_url_with_path
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.10.0/src/backend/macos/utils/url.rs:12:18
   3: rfd::backend::macos::file_dialog::panel_ffi::Panel::set_path
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.10.0/src/backend/macos/file_dialog/panel_ffi.rs:109:27
   4: rfd::backend::macos::file_dialog::panel_ffi::Panel::build_save_file
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.10.0/src/backend/macos/file_dialog/panel_ffi.rs:197:13
   5: rfd::backend::macos::file_dialog::<impl rfd::backend::AsyncFileSaveDialogImpl for rfd::file_dialog::FileDialog>::save_file_async::{{closure}}
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.10.0/src/backend/macos/file_dialog.rs:199:21
   6: rfd::backend::macos::modal_future::ModalFuture<R,D>::new::{{closure}}
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rfd-0.10.0/src/backend/macos/modal_future.rs:81:33
   7: dispatch::queue::Queue::exec_sync::{{closure}}
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dispatch-0.2.0/src/queue.rs:142:36
   8: dispatch::context_and_sync_function::work_read_closure
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dispatch-0.2.0/src/lib.rs:110:9
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <() as objc::message::MessageArguments>::invoke
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:128:17
  24: objc::message::platform::send_unverified::{{closure}}
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:27:9
  25: objc_exception::try::{{closure}}
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/src/lib.rs:68:31
  26: objc_exception::try_no_ret::try_objc_execute_closure
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/src/lib.rs:34:9
  27: RustObjCExceptionTryCatch
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/extern/exception.m:10:9
  28: objc_exception::try_no_ret
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/src/lib.rs:44:19
  29: objc_exception::try
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc_exception-0.1.2/src/lib.rs:67:9
  30: objc::exception::try
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/exception.rs:8:5
  31: objc::message::platform::send_unverified
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/apple/mod.rs:26:5
  32: objc::message::send_message
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/objc-0.2.7/src/message/mod.rs:178:5
  33: tao::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/event_loop.rs:193:16
  34: tao::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/platform_impl/macos/event_loop.rs:160:21
  35: tao::event_loop::EventLoop<T>::run
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.2/src/event_loop.rs:179:5
  36: <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.6/src/lib.rs:2302:5
  37: tauri::app::App<R>::run
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.6.3/src/app.rs:868:5
  38: tauri::app::Builder<R>::run
             at /Users/fsalmen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.6.3/src/app.rs:1722:5
  39: webwriter::main
             at ./src/main.rs:9:3
  40: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
libc++abi: terminating due to uncaught foreign exception
```

**Comment by amrbashir** [comment] 2024-05-13 16:13
The stack trace shows the panic at a different logic related to the path not the title; @pewsheen can you check why this panic and how is it related to the title?

**Comment by salmenf** [comment] 2024-05-14 18:43
I just amended my report: I mixed up up `title` and `defaultPath`. It is in fact `defaultPath` causing the issue, which I just tested again with the code above. Sorry for the confusion!

**Comment by amrbashir** [comment] 2024-05-15 00:18
then duplicate of #7566 and I will open a PR soon

**Closed as not planned by amrbashir** 2024-05-15 00:18 UTC
Labels: type: bug, platform: macOS, status: needs triage
