### ISSUE TITLE
does any plan for HarmonyOs ? [feat] 

### ISSUE THREAD

**Issue by zzjjbbaa** [tauri-apps/tauri#8375] opened 2023-12-12 07:38 UTC
### Describe the problem

does any plan for HarmonyOs ?

### Describe the solution you'd like

support for harmonyos

**Comment by FabianLars** [comment] 2023-12-12 10:21
Duplicate of #7287 (We currently have no specific plans in either direction)

**Closed as not planned by FabianLars** 2023-12-12 10:21 UTC
Labels: type: feature request
