### ISSUE TITLE
Window top outline[bug] 

### ISSUE THREAD

**Issue by Fractal-Tess** [tauri-apps/tauri#4238] opened 2022-05-29 20:05 UTC
### Describe the bug

Hello,

**DISCLAIMER** - I'm not sure if this is a bug or an user error.
I was trying to make myself a custom template for app development based on the [skitty](https://github.com/Mattchine/skitty) starter template available on GitHub.
I added border radius to the `body` and `html` tag, removed window decorations, and enable transparency in the  `tauri.conf.json` file.

### Reproduction

You can replicate the environment and webview window setup by cloning and running my skitty template derivative from my repo  [here](https://github.com/Fractal-Tess/Tauri-Svelte-Template)

### Expected behavior

Rather than expected, the unexpected behavior is the unwanted outline of the window like such:
![image](https://user-images.githubusercontent.com/75957529/170889319-1c4064be-33d8-43d4-97c7-10dcc73a8f7a.png)
Please notice the top corners of the image
![image](https://user-images.githubusercontent.com/75957529/170889338-1b3ac972-bbff-4f48-99b0-6b41952bfa83.png)

### Platform and versions

```shell
❯ yarn tauri info
yarn run v1.22.19

Environment
  › OS: Manjaro 21.2.6 X64
  › Node.js: 18.2.0
  › npm: 8.5.5
  › pnpm: 7.1.0
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu
```

**Comment by amrbashir** [comment] 2022-05-29 20:41
duplicate of #3466 , make sure to use the latest tauri version.

**Closed as completed by amrbashir** 2022-05-29 20:41 UTC
Labels: type: bug

**Comment by Fractal-Tess** [comment] 2022-05-29 21:08
> duplicate of #3466 , make sure to use the latest tauri version.

Thank you, updating solved my issue!
