### ISSUE TITLE
[feat] open at login

### ISSUE THREAD

**Issue by SorenHolstHansen** [tauri-apps/tauri#3836] opened 2022-04-01 07:25 UTC
### Describe the problem

It would be great if you could make the app open at login. The user can do this on their own (at least on mac, don't know about windows and linux), but it would be better to have it as default.

### Describe the solution you'd like

Preferrably this would be a setting like in [electron](https://www.electronjs.org/docs/latest/api/app#appsetloginitemsettingssettings-macos-windows)

**Comment by amrbashir** [comment] 2022-04-01 07:34
duplicate of #2589

**Closed as completed by amrbashir** 2022-04-01 07:34 UTC
Labels: type: feature request, status: invalid
