### ISSUE TITLE
[bug] is_fullscreen is still true after exiting fullscreen mode 

### ISSUE THREAD

**Issue by xuchaoqian** [tauri-apps/tauri#5259] opened 2022-09-21 21:32 UTC
### Describe the bug

is_fullscreen is still true after exiting fullscreen mode.

### Reproduction

1. clone the [demo repo](https://github.com/xuchaoqian/tauri-examples.git)
2. cd fullscreen
3. npm install --verbose
4. npm run tauri dev
5. enter fullscreen mode, will output the console log: INFO app - is_fullscreen: Ok(true)
6. exit fullscreen mode, will still output the console log:  INFO app - is_fullscreen: Ok(true)

### Expected behavior

 is_fullscreen should be false after exiting fullscreen mode 

### Platform and versions

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 14.18.1
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ src

**Comment by amrbashir** [comment] 2022-09-21 22:00
duplicate of #4519

**Closed as not planned by amrbashir** 2022-09-21 22:00 UTC
Labels: type: bug, status: needs triage
