### ISSUE TITLE
The program cannot start after add Splashscreen

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#916] opened 2020-08-02 07:42 UTC
**Describe the bug**
The program cannot start after add Splashscreen：
```
thread 'main' panicked at 'Failed to build webview: 系统找不到指定的文件。 (os error 2)', C:\Users\tobiastao\.cargo\registry\src\mirrors.tuna.tsinghua.e
du.cn-df7c3c540f42cdbd\tauri-0.9.0\src\app.rs:21:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\tauri-api-demos.exe` (exit code: 101)
```

if i delete this line of code ， everything is fine：

`.splashscreen_html("<div>The app is loading...</div>")`

**To Reproduce**
1. clone the repo:  git@github.com:TobiasTao/tauri-api-demos.git
2. yarn
3. yarn fe:dev
4. yarn be:dev

**Platform and Versions (please complete the following information):**

```
[tauri]: running info

Operating System - Windows_NT(10.0.18363) - win32/x64
Microsoft Edge - 44.18362.449.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.18.3
  tauri.js - 0.11.0

Rust environment
  rustc - 1.45.0
  cargo - 1.45.0
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.14.6
  yarn - 1.22.4

App directory structure
/.git
/.idea
/.vscode
/dist
/e2e
/node_modules
/src
/src-tauri

App
  tauri.rs - 0.9.0
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist/tauri-api-demos
  devPath - http://localhost:4200
```

**Comment by nothingismagick** [comment] 2020-08-02 08:35
Ok, thanks for the awesome info about this bug. We may already have a fix, but will need to confirm. I'm out of the office for now, but maybe @lucasfernog can verify that the latest PR fixed it.

**Comment by nklayman** [comment] 2020-08-28 22:03
I'm also getting this issue:
```
Running `target/debug/tauri-test`
thread 'main' panicked at 'Failed to build webview: No such file or directory (os error 2)', /home/noah/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.9.2/src/app.rs:21:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

 app:spawn Command "cargo" failed with exit code: 101 +0ms
```

**Comment by chumaumenze** [comment] 2020-09-03 20:06
Is there a way to fix this yet? I can't figure out where that error is from yet.

**Comment by nklayman** [comment] 2021-02-01 01:28
Duplicate of https://github.com/tauri-apps/tauri/issues/991.

**Closed as completed by nklayman** 2021-02-01 01:28 UTC
Labels: type: bug
