### ISSUE TITLE
[bug] Entry point TaskDialogIndirect could not be located

### ISSUE THREAD

**Issue by Massimiliano-solutiontech** [tauri-apps/tauri#6926] opened 2023-05-10 09:33 UTC
### Describe the bug

When I compile the app for Windows with the manifest by using the new feature available in `Tauri 1.3` I can't no more launch the application, when I try to open it the following error shows: `The procedure entry point TaskDialogIndirect could not be located in the dynamic link library C:\Users\user\Documents\Projects\test-app\src-tauri\target\release\test-app.exe`. If I rollback to simply `tauri_build::build();` the app starts without any problem 

![Screenshot 2023-05-10 alle 11 24 31](https://github.com/tauri-apps/tauri/assets/75322363/19196e1d-14dd-4014-920c-a253cfcabb93)

### Reproduction

`build.rs`

```rust
let mut windows = tauri_build::WindowsAttributes::new();
windows = windows.app_manifest(include_str!("window-app-manifest.xml"));
tauri_build::try_build(tauri_build::Attributes::new().windows_attributes(windows))
    .expect("failed to run build script");
```

`window-app-manifest.xml`

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
            </requestedPrivileges>
        </security>
    </trustInfo>
</assembly>
```

### Expected behavior

App starts requesting admin permissions

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 113.0.1774.35
    ✔ MSVC: Visual Studio Build Tools 2019
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.15.0
    - npm: 9.5.0

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Rollup
```

**Comment by FabianLars** [comment] 2023-05-10 09:42
I could swear we changed the wording of it in the docs. The issue is that your custom manifest must include the default too (shown at the bottom of the function doc: https://docs.rs/tauri-build/latest/tauri_build/struct.WindowsAttributes.html#method.app_manifest) if anything is enabled that enables the dialog feature (either by allowing the dialog allowlist itself, or by enabling the updater).

So in this case it would look something like this (untested):
```xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
        <requestedPrivileges>
            <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
        </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

Edit: We indeed changed it but forgot to merge the PR in time x) https://github.com/tauri-apps/tauri/pull/6736 - Therefore closing this as a duplicate of #6732 - thanks for the report :)

**Closed as not planned** 2023-05-10 09:44 UTC
Labels: type: bug, status: needs triage

**Comment by Mitoax** [comment] 2025-03-27 01:54
> I could swear we changed the wording of it in the docs. The issue is that your custom manifest must include the default too (shown at the bottom of the function doc: https://docs.rs/tauri-build/latest/tauri_build/struct.WindowsAttributes.html#method.app_manifest) if anything is enabled that enables the dialog feature (either by allowing the dialog allowlist itself, or by enabling the updater).
> 
> So in this case it would look something like this (untested):
> 
> <assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
>   <dependency>
>     <dependentAssembly>
>       <assemblyIdentity
>         type="win32"
>         name="Microsoft.Windows.Common-Controls"
>         version="6.0.0.0"
>         processorArchitecture="*"
>         publicKeyToken="6595b64144ccf1df"
>         language="*"
>       />
>     </dependentAssembly>
>   </dependency>
>   <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
>     <security>
>         <requestedPrivileges>
>             <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
>         </requestedPrivileges>
>     </security>
>   </trustInfo>
> </assembly>
> Edit: We indeed changed it but forgot to merge the PR in time x) [#6736](https://github.com/tauri-apps/tauri/pull/6736) - Therefore closing this as a duplicate of [#6732](https://github.com/tauri-apps/tauri/issues/6732) - thanks for the report :)

no, you didn't.... god knows what  your `your custom manifest` looks like.

![Image](https://github.com/user-attachments/assets/8ac2833d-89f5-40ef-8a50-12ce0f9f0003)
