### ISSUE TITLE
Unable to display webview in macOS Monterey

### ISSUE THREAD

**Issue by ysfscream** [tauri-apps/tauri#3006] opened 2021-12-01 14:00 UTC
### **Describe the bug**

Unable to display web-view in macOS Monterey. Run CLI:

```shell
yarn tauri dev
```

Open the window normally, but can not display the web content.

### **To Reproduce**
1. set up env.
2. run dev cli: `yarn tauri dev`

### **Screenshots**

![image](https://user-images.githubusercontent.com/21299158/144247469-b6ba2102-8a41-4142-b260-363a033db5bf.png)

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 12.0.1 X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.11
  yarn - 1.22.17

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/node_modules
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

**Comment by FabianLars** [comment] 2022-01-20 22:54
Looks like a duplicate of #2934 🤔 If not please reopen with more info (errors/stacktrace & reproduction repo)

**Closed as completed by FabianLars** 2022-01-20 22:54 UTC
Labels: type: bug, platform: macOS
