### ISSUE TITLE
JS API `resolvePath` does not include BaseDirectory

### ISSUE THREAD

**Issue by halgorithm** [tauri-apps/tauri#1833] opened 2021-05-14 16:57 UTC
**Describe the bug**
`resolvePath('file.txt', BaseDirectory.APP)` returns simply 'file.txt' without the `appDir()`

**Expected behavior**
It should return a full path string like "{APP_DIR}/file.txt" with APP_DIR being the platform-specific app dir.

**Platform and Versions**

```
Operating System - Windows, version 10.0.19042 X64
Webview2 - 90.0.818.56

Node.js environment
  Node.js - 16.0.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 7.10.0
  yarn - 1.23.0-20210103.1434

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App
  tauri.rs - 1.0.0-beta.1
```

**Comment by amrbashir** [comment] 2021-05-21 07:45
It works fine for me and I can't reproduce it. 
```js
resolvePath("file.txt", BaseDirectory.App).then(path => console.log(path));
```
results in
```
C:\Users\amrba\AppData\Roaming\com.tauri.api\file.txt
```

**Comment by amrbashir** [comment] 2021-05-21 07:47
I will close the issue but feel free to re-open it with further details if you're still having problems with it

**Closed as completed by amrbashir** 2021-05-21 07:47 UTC
Labels: type: bug
