### ISSUE TITLE
[bug] how do I run tauri app as root?

### ISSUE THREAD

**Issue by ralyodio** [tauri-apps/tauri#9759] opened 2024-05-12 17:08 UTC
### Describe the bug

I'm on arch/linux and am building a network sniffing tool so I need to run the whole app as root. I am doing `sudo -E pnpm tauri dev` and it builds without any errors, but the desktop app never pops up.

I'm using tshark btw which is why I need root and its much better to just run the desktop app as root.

I'm on KDE if that makes any difference.

### Reproduction

sudo -E pnpm tauri dev

### Expected behavior

desktop app should pop up.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Arch Linux Rolling Release X64
    ✔ webkit2gtk-4.0: 2.44.1
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.11.1
    - pnpm: 9.1.0
    - yarn: 1.22.22
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.6.5
    - tauri-build [RUST]: 1.5.2
    - wry [RUST]: 0.24.9
    - tao [RUST]: 0.16.9
    - tauri-cli [RUST]: 1.5.12
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.13

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
none
```

**Comment by ralyodio** [comment] 2024-05-12 18:09
`sudo echo $WAYLAND_DISPLAY` gives me:
`wayland-0`

**Comment by amrbashir** [comment] 2024-05-13 16:09
duplicate of https://github.com/tauri-apps/tauri/issues/6807

**Closed as not planned by amrbashir** 2024-05-13 16:09 UTC
Labels: type: bug, status: needs triage
