### ISSUE TITLE
[bug] visibleOnAllWorkspaces window not staying on top of full-screen apps on macOS

### ISSUE THREAD

**Issue by epodivilov** [tauri-apps/tauri#11488] opened 2024-10-24 21:42 UTC
### Describe the bug

Hi. I have a problem.
When creating a window with the visibleOnAllWorkspaces parameter on macOS, the window does not appear on top of all workspaces and full-screen windows. I found [another issue](https://github.com/tauri-apps/tauri/issues/2258) that suggests using app.set_activation_policy(tauri::ActivationPolicy::Accessory); to solve the problem, and it does work: the window appears above all system windows.

However, the app icon disappears from the Dock, which is not always desirable.

### Expected behavior

It would be helpful to have the ability to create a second window (in addition to the main one) that would always appear above all other windows, including full-screen ones, while:
•	The main window behaves normally (without hiding the Dock icon).
•	The secondary window is visible on all workspaces and appears on top of all other windows, without changing the standard behavior of the main window.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.0.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.15.0
    - pnpm: 9.6.0
    - yarn: 1.22.22
    - npm: 10.8.1

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.3
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.3
    - @tauri-apps/cli : 2.0.5

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-global-shortcut 🦀: 2.0.1
    - @tauri-apps/plugin-global-shortcut : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-10-25 16:23
Does the alwaysOnTop config change anything about the behavior?

**Comment by ayangweb** [comment] 2024-10-26 05:01
The code I wrote might help you.

https://github.com/EcoPasteHub/EcoPaste/pull/728/files

https://github.com/user-attachments/assets/d2b9cda1-2646-4141-80b8-40f6a4c2be6e

**Comment by epodivilov** [comment] 2024-10-28 11:18
@ayangweb thanks for your example. 

But the problem is that I can't combine a normal window and a floating window. And to have an icon in the dock as well. Just one thing. 

@FabianLars this flag works only on main desktop, not for fullscreen apps in macos

**Comment by epodivilov** [comment] 2024-10-28 20:34
I think I've found the solutions. I researched the @ayangweb app and came up with this option:
```rust
appHandle.set_activation_policy(ActivationPolicy::Accessory);

let second_window = appHandle.get_webview_window("second").unwrap();

let delegate = panel_delegate!(MyPanelDelegate {
    window_did_become_key,
    window_did_resign_key
});

delegate.set_listener(Box::new(move |delegate_name: String| {
    match delegate_name.as_str() {
        "window_did_become_key" => {
            handle.emit(MACOS_PANEL_FOCUS, true).unwrap();
        }
        "window_did_resign_key" => {
            handle.emit(MACOS_PANEL_FOCUS, false).unwrap();
        }
        _ => (),
    }
}));

let panel = second_window.to_panel().unwrap();
panel.set_collection_behaviour(
    NSWindowCollectionBehavior::NSWindowCollectionBehaviorCanJoinAllSpaces
        | NSWindowCollectionBehavior::NSWindowCollectionBehaviorStationary
        | NSWindowCollectionBehavior::NSWindowCollectionBehaviorFullScreenAuxiliary,
);

panel.set_delegate(delegate);
panel.set_level(NSMainMenuWindowLevel + 1);
panel.show();

appHandle.set_activation_policy(ActivationPolicy::Regular);
```

With this approach there is a small problem with the icon in the dock - it blinks. But otherwise everything works as required: the icon in the dock is present, the main window behaves as usual window, the popup panel appears on top of all windows, even full-screen ones.

**Comment by ahkohd** [comment] 2024-10-29 22:07
> Does the alwaysOnTop config change anything about the behavior?

It's a macos thing, the standard `NSWindow` can't be displayed over other fullscreen windows, you have to subclass the `NSWindow` to `NSPanel` [(tauri-nspanel)](https://github.com/ahkohd/tauri-nspanel) and set the right flags.

**Comment by FabianLars** [comment] 2024-11-25 10:38
Closing this as a duplicate of https://github.com/tauri-apps/tauri/issues/3326 and https://github.com/tauri-apps/tauri/issues/9556

**Closed as not planned by FabianLars** 2024-11-25 10:38 UTC
Labels: type: bug, platform: macOS, status: needs triage
