### ISSUE TITLE
[bug] Can't play local audio file in Linux

### ISSUE THREAD

**Issue by thewh1teagle** [tauri-apps/tauri#8654] opened 2024-01-22 11:34 UTC
### Describe the bug

`new Audio(localAudioPath).play()` throws  `Unhandled Promise Rejection: NotSupportedError: The operation is not supported`

When playing external audio it works.
```javascript
new Audio("https://samplelib.com/lib/preview/wav/sample-3s.wav").play()
```

### Reproduction

Load audio path with `open()` and convert it to asset path using `convertFileSrc`, then try to play with `new Audio(path).play()`

### Expected behavior

It should play the sound

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.42.4
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.7.0
    - npm: 10.1.0
    - bun: 1.0.3

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
```

### Additional context

https://discord.com/channels/616186924390023171/1198765010558664704

**Comment by FabianLars** [comment] 2024-01-22 18:37
Duplicate of https://github.com/tauri-apps/tauri/issues/3725 (don't mind the title, it's for audio and video), thanks for the report nonetheless.

**Closed as not planned by FabianLars** 2024-01-22 18:37 UTC
Labels: type: bug, status: needs triage

**Comment by thewh1teagle** [comment] 2024-01-22 20:24
@FabianLars 
It's very long list with a lot of solutions.
Do you know some known workround?

**Comment by FabianLars** [comment] 2024-01-22 20:30
Not really, no. The only this is to spawn a http server on the rust side that serves the file :/

**Comment by thewh1teagle** [comment] 2024-01-22 20:37
@FabianLars What about multipurpose custom protocol as workaround for such cases?
The goal is to load the files efficiently same as file object does, and easily with path.
So I will load it as URL to custom asset which will be handled from rust side

And of course I prefer not to spawn http server

**Comment by thewh1teagle** [comment] 2024-01-22 20:52
I tried to load image in the same path of the audio file and it loaded it. so it happens only in audio files / videos
![image](https://github.com/tauri-apps/tauri/assets/61390950/4af323ad-86b2-4ecc-8157-18e5a8e040f8)

**Comment by FabianLars** [comment] 2024-01-22 20:55
> What about multipurpose custom protocol as workaround for such cases?

The custom protocol is the issue here. webkitgtk simply cannot load audio/video from custom protocols, seemingly no matter how the rust side of it is implemented. iirc it doesn't accept unknown schemes. In the issue i linked there should also be a reference to the webkit bugtracker with hopefully more info.

**Comment by thewh1teagle** [comment] 2024-01-22 21:51
I reproduces the problem in simple `C` code which uses `webkitgtk`.
The problem happens there too.
I hope `tauri` won't use `webkitgtk` in long term. it doesn't have normal repo, seems to be very old, and so many bugs inside of `webkitgtk` itself.
I hope tauri will use `servo` project someday.

**Comment by amosjyng** [comment] 2024-02-14 03:01
+1, my experience with Tauri has been pretty pleasant except for webkitgtk, which has honestly been a real PITA.
