### ISSUE TITLE
[bug] error using dialog plugin open gallery and click ok return on android

### ISSUE THREAD

**Issue by dfsfdfse** [tauri-apps/tauri#10382] opened 2024-07-25 01:36 UTC
### Describe the bug

![image](https://github.com/user-attachments/assets/49cfa3e6-389b-4776-8e8b-0948301acbc2)
![image](https://github.com/user-attachments/assets/b9a91c7a-ef24-410e-a993-1e76d4b55056)
07-25 01:27:15.922  2104  2104 E CursorWindow: Failed to read row 0, column 4294967295 from a window with 1 rows, 10 columns
07-25 01:27:15.924  2104  2104 E Tauri   : getModifiedAtFromUri failed.
07-25 01:27:15.924  2104  2104 E Tauri   : java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.CursorWindow.nativeGetLong(Native Method)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.CursorWindow.getLong(CursorWindow.java:539)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.dialog.FilePickerUtils$Companion.getModifiedAtFromUri(FilePickerUtils.kt:108)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.dialog.DialogPlugin.createPickFilesResult(DialogPlugin.kt:139)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.dialog.DialogPlugin.filePickerResult(DialogPlugin.kt:93)
07-25 01:27:15.924  2104  2104 E Tauri   :      at java.lang.reflect.Method.invoke(Native Method)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginHandle.startActivityForResult$lambda-0(PluginHandle.kt:44)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginHandle.$r8$lambda$2ght1lnlhjUrFgO3RPGUbms4OJk(Unknown Source:0)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginHandle$$ExternalSyntheticLambda1.onResult(Unknown Source:6)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginManager._init_$lambda-0(PluginManager.kt:46)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginManager.$r8$lambda$tu-NX4xpUnJCRiofW32AQyUIPYo(Unknown Source:0)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginManager$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.Activity.dispatchActivityResult(Activity.java:8943)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread.deliverResults(ActivityThread.java:5519)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread.handleSendResult(ActivityThread.java:5565)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.os.Handler.dispatchMessage(Handler.java:106)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.os.Looper.loopOnce(Looper.java:205)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.os.Looper.loop(Looper.java:294)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread.main(ActivityThread.java:8176)
07-25 01:27:15.924  2104  2104 E Tauri   :      at java.lang.reflect.Method.invoke(Native Method)
07-25 01:27:15.924  2104  2104 E Tauri   :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
07-25 01:27:15.924  2104  2104 E Tauri   :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.113
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.0-nightly (9c9b56879 2024-05-05)
    ✔ cargo: 1.80.0-nightly (05364cb2f 2024-05-03)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.5.0
    - pnpm: 9.1.1
    - yarn: 1.22.19
    - npm: 9.8.0
    - bun: 1.1.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.22
    - tauri-build [RUST]: 2.0.0-beta.17
    - wry [RUST]: 0.40.1
    - tao [RUST]: 0.28.1
    - tauri-cli [RUST]: 2.0.0-beta.11
    - @tauri-apps/api [NPM]: 2.0.0-beta.13
    - @tauri-apps/cli [NPM]: 2.0.0-beta.20

[-] App
    - build-type: bundle
    - CSP: style-src 'self' 'unsafe-inline'; default-src 'self' ipc: http://ipc.localhost; img-src 'self' asset: http://localhost:9300/statics/ http://asset.localhost/ blob: data:   
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
07-25 01:27:15.922  2104  2104 E CursorWindow: Failed to read row 0, column 4294967295 from a window with 1 rows, 10 columns
07-25 01:27:15.924  2104  2104 E Tauri   : getModifiedAtFromUri failed.
07-25 01:27:15.924  2104  2104 E Tauri   : java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.CursorWindow.nativeGetLong(Native Method)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.CursorWindow.getLong(CursorWindow.java:539)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.database.CursorWrapper.getLong(CursorWrapper.java:131)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.dialog.FilePickerUtils$Companion.getModifiedAtFromUri(FilePickerUtils.kt:108)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.dialog.DialogPlugin.createPickFilesResult(DialogPlugin.kt:139)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.dialog.DialogPlugin.filePickerResult(DialogPlugin.kt:93)
07-25 01:27:15.924  2104  2104 E Tauri   :      at java.lang.reflect.Method.invoke(Native Method)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginHandle.startActivityForResult$lambda-0(PluginHandle.kt:44)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginHandle.$r8$lambda$2ght1lnlhjUrFgO3RPGUbms4OJk(Unknown Source:0)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginHandle$$ExternalSyntheticLambda1.onResult(Unknown Source:6)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginManager._init_$lambda-0(PluginManager.kt:46)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginManager.$r8$lambda$tu-NX4xpUnJCRiofW32AQyUIPYo(Unknown Source:0)
07-25 01:27:15.924  2104  2104 E Tauri   :      at app.tauri.plugin.PluginManager$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:793)
07-25 01:27:15.924  2104  2104 E Tauri   :      at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.Activity.dispatchActivityResult(Activity.java:8943)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread.deliverResults(ActivityThread.java:5519)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread.handleSendResult(ActivityThread.java:5565)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.os.Handler.dispatchMessage(Handler.java:106)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.os.Looper.loopOnce(Looper.java:205)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.os.Looper.loop(Looper.java:294)
07-25 01:27:15.924  2104  2104 E Tauri   :      at android.app.ActivityThread.main(ActivityThread.java:8176)
07-25 01:27:15.924  2104  2104 E Tauri   :      at java.lang.reflect.Method.invoke(Native Method)
07-25 01:27:15.924  2104  2104 E Tauri   :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
07-25 01:27:15.924  2104  2104 E Tauri   :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by FabianLars** [comment] 2024-07-25 11:05
Duplicate of https://github.com/tauri-apps/plugins-workspace/issues/1584 (I _moved_ your issue, i did not delete it :) )

**Closed as not planned by FabianLars** 2024-07-25 11:05 UTC
Labels: type: bug, status: needs triage
