### ISSUE TITLE
tauri-apps/cli init uses outdated dependencies.

### ISSUE THREAD

**Issue by Panquecas** [tauri-apps/tauri#2411] opened 2021-08-12 20:46 UTC
### **Description**
When creating a new tauri app via `tauri-cli / init`, the cargo.toml that is created includes outdated dependencies.

Currently:
```
[build-dependencies]
tauri-build = { version = "1.0.0-beta-rc.1" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.0.0-beta-rc.4", features = ["api-all"]}
```

tauri-build v`1.0.0-beta-rc.1` has been deprecated/deleted according to crates.io
I changed it to the most recent v`1.0.0-beta.3` 

tauri v`1.0.0-beta-rc.4` has also been _yanked_ so I updated it to v`1.0.0-beta.5`

 

### **To Reproduce**
- Create a new project. 
- Use yarn/npm to install `@tauri-apps/cli`
- run `yarn tauri init --ci` (or npm/global depending on how you have it setup)
- run `yarn tauri dev` (or other if npm/etc)
- error pops up complaining about dependency.

### **Expected behavior**
It is expected that `tauri init` would populate the cargo.toml with correct depdencies. 
Perhaps update the docs to mention that this might need to be updated manually, since deps could change frequently.

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19043 X64

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta-rc.4
  @tauri-apps/api Not installed

Global packages
  npm - 7.15.1
  yarn - 3.0.1

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.idea
/.yarn
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - ../dist
devPath - http://localhost:4000

```

### **Additional context**
This was my first time looking into Tauri. Followed the docs multiple times. Could prevent others from testing with Tauri if the docs/cli are outdated.

**Comment by FabianLars** [comment] 2021-08-12 21:27
I think that's not really the cli's mistake, but rather npm installing an outdated version of the cli (rc.4), which in turn tries to install outdated tauri packages.
You're not the first one mentioning this issue, but i'm still not able to reproduce it :thinking:
How are you installing the cli?
`npm install --save-dev @tauri-apps/cli`? -> adds the cli with a "*" version specifier, which still resolves to beta.6 at my end
`yarn add -D @tauri-apps/cli`? -> adds the cli with the "beta.6" version specifier. (same with pnpm)
(Same behavior when installing as a normal dep instead of a dev dep)

Maybe the best thing by now would be to try to remove the rc versions from npm, if that's possible, because everytime someone mentions this kind of issue, it's always version rc.4 :sweat_smile:

**Comment by Panquecas** [comment] 2021-08-13 02:01
> I think that's not really the cli's mistake, but rather npm installing an outdated version of the cli (rc.4), which in turn tries to install outdated tauri packages.
> You're not the first one mentioning this issue, but i'm still not able to reproduce it :thinking:
> How are you installing the cli?
> `npm install --save-dev @tauri-apps/cli`? -> adds the cli with a "*" version specifier, which still resolves to beta.6 at my end
> `yarn add -D @tauri-apps/cli`? -> adds the cli with the "beta.6" version specifier. (same with pnpm)
> (Same behavior when installing as a normal dep instead of a dev dep)
> 
> Maybe the best thing by now would be to try to remove the rc versions from npm, if that's possible, because everytime someone mentions this kind of issue, it's always version rc.4 :sweat_smile: 

Hmmm very interesting. 

I installed it via yarn's `yarn add -D @tauri-apps/cli`

I have no experience with publishing packages besides setting up private feeds via Azure so I have no idea what could cause this! 😅

When I get a chance I can check which version of cli is in my yarn package lock

**Comment by lucasfernog** [comment] 2021-08-13 12:34
We can see that you're running `@tauri-apps/cli - 1.0.0-beta-rc.4` from the info output.

**Comment by lucasfernog** [comment] 2021-08-13 13:05
I'm closing this since we can't reproduce it :/ you can manually change your package.json to use beta.6 instead of the beta-rc version.

**Closed as completed by lucasfernog** 2021-08-13 13:05 UTC
Labels: type: bug

**Comment by Panquecas** [comment] 2021-08-13 16:54
Hmm interesting. 
When installing @tauri-apps/cli via yarn, it sets the version to `^1.0.0-beta.6`. In the yarn.lock I can see that it resolves that to `1.0.0-beta-rc.4`

Using [npm's semver calculator ](https://semver.npmjs.com/) it shows that it should resolve to `1.0.0-beta.6` as expected.

> You're not the first one mentioning this issue, but i'm still not able to reproduce it 🤔

Really interesting how this isn't an isolated instance:

**Comment by lucasfernog** [comment] 2021-08-13 16:59
Funny that it doesn't happen for everyone.

TBH we messed up with the name `beta-rc`, that should be something else because for semver `beta-rc` > beta`. Maybe we should delete the beta-rc npm releases like we had to do for the crates.

**Comment by Panquecas** [comment] 2021-08-13 17:10
> Funny that it doesn't happen for everyone.

Gotta love programming!
