### ISSUE TITLE
100% CPU consumption bug

### ISSUE THREAD

**Issue by dizda** [tauri-apps/tauri#2074] opened 2021-06-25 04:12 UTC
### **Describe the bug**
When I launch the "helloworld" example, the CPU consumption goes to 100%.
The commit https://github.com/tauri-apps/tauri/commit/3280c4aa91e50a8ccdd561a8b48a12a4a13ea8d5 introduce the bug.

### **To Reproduce**
```bash
git checkout 3280c4aa91e50a8ccdd561a8b48a12a4a13ea8d5
cd examples/helloworld
cargo tauri dev
```

### **Expected behavior**
CPU Should be around 0% when idling.
Previous commit (f7d21a4b864e067856018e7b1f4ba178aea46d71) doesn't have this bug.

```bash
git checkout f7d21a4b864e067856018e7b1f4ba178aea46d71
cd examples/helloworld
cargo tauri dev
```

### **Screenshots**
Not useful

### **Platform and Versions (required):**
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta.3
  @tauri-apps/api - Not installed

Global packages
  npm - 7.15.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - path:"../../../core/tauri" [1.0.0-beta.1] (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self'
  distDir - ["../index.html"]
  devPath - ["../index.html"]
```

**Comment by dizda** [comment] 2021-06-25 04:46
I've also noticed that the mapping of commands between rust and the JS doesn't work.

**Comment by nothingismagick** [comment] 2021-06-25 08:42
That is because you are using the old version of tauri core.
```
tauri.rs - path:"../../../core/tauri" [1.0.0-beta.1] (no lockfile)
```

Please either update the source or use the latest crate from crates.io

**Comment by nothingismagick** [comment] 2021-06-25 08:59
Because its a bit confusing, I went and tried it, running directly on m1 mac from dev (both via yarn tauri and cargo tauri), without any problems - but you should remember a couple things:

1. please try to use latest toolchains - i.e. what is your version of the rust tauri-cli (`cargo tauri --version`)
2. try this: `cargo install tauri-cli --version ^1.0.0-beta.2` / or force install from the proper folder `/tooling/cli.rs`
3. or run the JS version (check out the pathing in that example's package.json

**Comment by dizda** [comment] 2021-06-25 09:11
FYI, I'm also on m1 mac.

>  what is your version of the rust tauri-cli 

❯ cargo tauri --version
cargo-tauri 1.0.0-beta.2

> `tauri.rs - path:"../../../core/tauri" [1.0.0-beta.1] (no lockfile)`

I think this is misinterpreted, because I've cloned the tauri repo, and checked out the right tag (1.0.0-beta.2).
I had first that issue with my own project, and I wanted to make sure the error was not coming from my projected, so I've tested it out with the provided examples from tauri's, and I encountered the same issues.

**Comment by dizda** [comment] 2021-06-25 09:16
> tauri.rs - path:"../../../core/tauri" [1.0.0-beta.1] (no lockfile)

About that part, it's when I've checked the earliest commit to find out when it started to produce the bug.

Here is the right `cargo tauri dev` when I check out the latest tag "git checkout tauri-v1.0.0-beta.2" (still with the bug)

```
❯ RUST_LOG=debug cargo tauri info

Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 16.3.0
  @tauri-apps/cli - 1.0.0-beta.3
  @tauri-apps/api - Not installed

Global packages
  npm - 7.15.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/src-tauri

App
  tauri.rs - path:"../../../core/tauri" [1.0.0-beta.2] (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self'
  distDir - ["../index.html"]
  devPath - ["../index.html"]
```

**Comment by dizda** [comment] 2021-06-25 09:19
active toolchain
----------------

1.52.1-aarch64-apple-darwin (overridden by '/Users/j/www/tauri/rust-toolchain')
rustc 1.52.1 (9bc8c42bb 2021-05-09)

**Comment by nothingismagick** [comment] 2021-06-25 09:22
I am on the same rustc as a matter of fact - although we should both move to 1.53.0 :|

**Comment by dizda** [comment] 2021-06-25 09:25
I've also tried with `yarn tauri dev`, same result.

I wonder what else could be different from your environment and mine? 
Do you get normal CPU consumption?

**Comment by nothingismagick** [comment] 2021-06-25 09:32
Care to visit our discord and we can have a chat about it? Ping denjell

**Comment by RuudBurger** [comment] 2021-06-26 22:51
@nothingismagick 

This is closed but I also have this issue.
Using `npx create-tauri-app` and picking the vanilla.js version.
If I run it cpu is at 100%.

```
Operating System - Mac OS, version 11.3.1 X64

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.3
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.13
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.2
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist
```

**Comment by myWsq** [comment] 2021-06-29 08:29
Same problem when using `vue-cli-plugin-tauri`

```
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 16.2.0
  @tauri-apps/cli - 1.0.0-beta.3
  @tauri-apps/api - Not installed

Global packages
  npm - 7.13.0
  yarn - 1.22.10

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/node_modules
/script
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.4
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

**Comment by nothingismagick** [comment] 2021-06-29 08:44
Hmm. You know, something I remembered is that I actually transferred the contents of my Intel mac to the M1, and I am actually still using the Intel version of rustc: `x86_64-apple-darwin` - I never bothered to switch over since everything was working fine.

Maybe @wusyong can help us out here, since he also has an m1

**Comment by RuudBurger** [comment] 2021-06-29 09:20
I'm on an Intel machine though, So it doesn't seem to be related to the m1

**Comment by lemarier** [comment] 2021-06-29 09:22
I can confirm tauri `api` kick my cpu at 100%, and wry didn’t. (Intel)

**Comment by yamadapc** [comment] 2021-06-29 12:38
![Screen Shot 2021-06-29 at 22 04 43](https://user-images.githubusercontent.com/3923654/123794363-163ccc80-d926-11eb-860e-29781ea5f620.png)

https://github.com/tauri-apps/tauri/blob/fe32afcc933920d6282ae1d63b041b182278a031/core/tauri-runtime-wry/src/lib.rs#L1369-L1385

I'm not familiar with `CFRunLoopObserverCreate` ; there's a busy loop per event-loop tick. Quite a few different things running there. I tried changing tao to `kCFRunLoopDefaultMode` but it doesn't change.

**Comment by yamadapc** [comment] 2021-06-29 12:49
This happened after changing deps from `beta.1` to `beta.4`

Also:
- https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/macos/app_state.rs#L418-L425

**Closed as completed** 2021-06-30 13:38 UTC
Labels: type: bug

**Comment by dizda** [comment] 2021-07-01 04:01
It did fix the issue!

Thanks everyone, good job @wusyong & @lucasfernog

**Comment by leimantas** [comment] 2021-07-02 10:03
<img width="752" alt="image" src="https://user-images.githubusercontent.com/46538777/124258164-633ebf80-db2d-11eb-8f76-91ba562f5b0a.png">
Just created app with **nxp create-tauri-app** React-ts

All dependencies updated.

CPU is 100%
