### ISSUE TITLE
[feat] customized bundle_dmg.sh options

### ISSUE THREAD

**Issue by orangelckc** [tauri-apps/tauri#6159] opened 2023-01-28 00:21 UTC
### Describe the problem

Is there a solution for customizing the `bundle_dmg.sh` options in folder `src-tauri`, whether adding a new `bundle.json` file or in `tauri.conf.json` file?
My purpose aims to add a background to the `.dmg` file. Locally I can use `create-dmg` to rebundle it, but how can I make it also into effect by using Github actions.
Any suggestions are welcomed.

### Describe the solution you'd like

A config file for bundling `dmg` file or bundle options in `tauri.conf.json` file

**Comment by FabianLars** [comment] 2024-02-28 10:18
Duplicate of https://github.com/tauri-apps/tauri/issues/4669 (added in v2, will _maybe_ be backported to v1 [here](https://github.com/tauri-apps/tauri/pull/8334))

**Closed as completed by FabianLars** 2024-02-28 10:18 UTC
Labels: type: feature request, platform: macOS
