### ISSUE TITLE
[bug] Window maximized tauri config option not working

### ISSUE THREAD

**Issue by CalvinWilkinson** [tauri-apps/tauri#11554] opened 2024-10-31 08:36 UTC
### Describe the bug

When the `maximized` setting in the _**tauri.conf.json**_ file is set to `true,` the window is not maximized when the application first starts.

When the `maximized` value is set to `true`, it does seem to change from one large size to a smaller size very rapidly. So it seems to be maximized at first for a split second, but then gets changed to the default size of 1000 x 1000 that I have set in the _**tauri.conf.json**_ file.

If I set the `maximized` value to `false`, this quick size change glitch does not occur. 

> [!Note]
> I am not using the _**Window State**_ or _**Window Customization**_ plugins in my application.

<details><summary>tauri.conf.json</summary>
<p>

```json
{
    "$schema": "../node_modules/@tauri-apps/cli/config.schema.json",
    "productName": "smart-desk",
    "version": "1.0.0-preview.7",
    "identifier": "com.engaged-agility.dev",
    "build": {
        "beforeBuildCommand": "pnpm run build-ui",
        "beforeDevCommand": "pnpm run dev-front-end",
        "frontendDist": "../out",
        "devUrl": "http://localhost:3000"
    },
    "bundle": {
        "active": true,
        "category": "Business",
        "copyright": "2024",
        "targets": [
            "app",
            "appimage",
            "deb",
            "dmg",
            "nsis"
        ],
        "externalBin": [],
        "icon": [
            "icons/32x32.png",
            "icons/128x128.png",
            "icons/128x128@2x.png",
            "icons/icon.icns",
            "icons/icon.ico"
        ],
        "windows": {
            "certificateThumbprint": null,
            "digestAlgorithm": "sha256",
            "timestampUrl": ""
        },
        "longDescription": "(S)cheduling (M)anagment (A)dmin (R)eporting (T)ool",
        "macOS": {
            "entitlements": null,
            "exceptionDomain": "",
            "frameworks": [],
            "providerShortName": null,
            "signingIdentity": null
        },
        "resources": [],
        "shortDescription": "Admin Tool",
        "linux": {
            "deb": {
                "depends": []
            }
        },
        "createUpdaterArtifacts": true
    },
    "plugins": {
        "updater": {
            "pubkey": "redacted",
            "endpoints": [
                "https://localhost:8000/latest-release-meta-data"
            ]
        }
    },
    "app": {
        "withGlobalTauri": true,
        "windows": [
            {
                "title": "SMART Desk",
                "center": true,
                "fullscreen": false,
                "resizable": true,
                "maximized": false,
                "width": 1000,
                "height": 1000
            }
        ],
        "security": {
            "csp": null,
            "capabilities": [
                "main-capability"
            ]
        }
    }
}
```

</p>
</details> 

### Reproduction

1. Set at least 1 window object in the _**tauri.conf.json**_ file to have a `maximized` setting to a value of `true`.
    ```json
    "app": {
        "withGlobalTauri": true,
        "windows": [
            {
                "title": "SMART Desk",
                "center": true,
                "fullscreen": false,
                "resizable": true,
                "maximized": true, // SET THIS TO TRUE
                "width": 1000,
                "height": 1000
            }
        ]
    }
    ```
3. Set the size to a relative small value to make sure that it is obvious that the window is not maximized.
4. Do not use the _**Window State**_ or _**Window Customization**_ plugins with any custom code to interfere with the setting.
5. Run the application with `pnpm tauri dev` or equivalent.
6. Observe that the window is not maximized.

### Expected behavior

With the `maximized` setting set to a value of `true` in the _**tauri.conf.json**_ file, I expected the window to be maximized upon startup.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 130.0.2849.56
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.15.0
    - pnpm: 9.12.3
    - npm: 10.7.0

[-] Packages
    - tauri 🦀: 2.0.6
    - tauri-build 🦀: 2.0.2
    - wry 🦀: 0.46.2
    - tao 🦀: 0.30.3
    - @tauri-apps/api : 2.0.2 (outdated, latest: 2.0.3)
    - @tauri-apps/cli : 2.0.2 (outdated, latest: 2.0.4)

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1
    - tauri-plugin-fs 🦀: 2.0.3
    - @tauri-apps/plugin-fs : 2.0.1
    - tauri-plugin-store 🦀: 2.1.0
    - @tauri-apps/plugin-store : 2.1.0
    - tauri-plugin-updater 🦀: 2.0.2
    - @tauri-apps/plugin-updater : 2.0.0
    - tauri-plugin-process 🦀: 2.0.1
    - @tauri-apps/plugin-process : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../out
    - devUrl: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Vite
```

### Stack trace

```text
N/A
```

**Comment by amrbashir** [comment] 2024-11-11 13:56
I wasn't able to reproduce this issue, please try again with latest tauri release, if the issue still happens please ping me and provide a minimal repro.

**Comment by CalvinWilkinson** [comment] 2024-11-12 17:54
> I wasn't able to reproduce this issue, please try again with latest tauri release, if the issue still happens please ping me and provide a minimal repro.

Will do.  I plan on updating to the latest version of Tauri soon anyways.  Thanks!!

**Comment by CalvinWilkinson** [comment] 2024-11-14 12:07
@amrbashir I wanted to update you on the situation.

I updated all of my Tauri dependencies to the latest version as of this morning, and when I set the `maximized` value to true, the window is not maximized when the app first runs.

**Comment by amrbashir** [comment] 2024-11-14 15:13
please provide a minimal repro as I can't reproduce at all, also make sure you're not using `tauri-plugin-window-state` which will unmaximize the window if it wasn't maximized in the saved state.

**Comment by CalvinWilkinson** [comment] 2024-11-15 09:01
> please provide a minimal repro as I can't reproduce at all, also make sure you're not using `tauri-plugin-window-state` which will unmaximize the window if it wasn't maximized in the saved state.

@amrbashir 

I have taken the app and pushed it to [this public repo](https://github.com/CalvinWilkinson/tauri-window-issue). Since this is a client application, I have stripped everything away except for the login page.  

I have also already set the `maximized` value to `true`.
I am also not using the `tauri-plugin-window-state` plugin.

Let me know if you need anything else.

**Comment by CalvinWilkinson** [comment] 2024-11-18 11:44
@amrbashir 

I noticed that this issue has been closed.  I was wondering if you were able to reproduce the issue with the public repository that I have created which you requested?

**Comment by amrbashir** [comment] 2024-11-18 15:49
yeah, seems to be an issue when using `center` with `maximized`

**Comment by amrbashir** [comment] 2024-11-18 22:22
looking at your reproduction, you are not using the latest tauri@2.1.0, updating to that, fixes the issue.

This was fixed in https://github.com/tauri-apps/tao/pull/992

**Closed as not planned by amrbashir** 2024-11-18 22:22 UTC
Labels: type: bug, status: needs triage
