### ISSUE TITLE
How to port Tauri to other system platforms?

### ISSUE THREAD

**Issue by 1595901624** [tauri-apps/tauri#9016] opened 2024-02-28 05:33 UTC
### Describe the problem

How to port Tauri to other system platforms？I would like to port Tauri to HarmonyOS. Are there any official porting documents available?

### Describe the solution you'd like

porting documents

**Comment by amrbashir** [comment] 2024-02-28 15:45
Unfortunately not, but you could take a look at https://github.com/tauri-apps/wry/tree/dev/src/android

**Comment by FabianLars** [comment] 2024-09-24 15:28
I'll close this as a duplicate of #7287 - If there are even other platforms there should imo each get their own issue,

**Closed as not planned by FabianLars** 2024-09-24 15:28 UTC
Labels: type: feature request
