### ISSUE TITLE
error command tauri info ?

### ISSUE THREAD

**Issue by conanchen** [tauri-apps/tauri#2932] opened 2021-11-22 03:50 UTC
following bug report scripts and tried to run tauri info as below ,  got error: 

❯ yarn tauri info
yarn run v1.22.10
$ tauri info
 app:spawn Running "/Users/xxxx/node_modules/.pnpm/registry.nlark.com+@tauri-apps+cli@1.0.0-beta.10/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms

Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 16.4.1
  @tauri-apps/cli - 1.0.0-beta.10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:323:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  @tauri-apps/api - tauri-apps
 app:spawn Command "/Users/xxxx/node_modules/.pnpm/registry.nlark.com+@tauri-apps+cli@1.0.0-beta.10/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 101 +1ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

❯ ./node_modules/@tauri-apps/cli/bin/tauri-cli tauri info

Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 16.4.1
  @tauri-apps/cli - 1.0.0-beta.10
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:323:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  @tauri-apps/api - tauri-apps%

**Comment by ghost** [comment] 2021-11-22 03:54
Duplicate of #2931

**Comment by FabianLars** [comment] 2021-11-22 09:30
duplicate of #2509

**Closed as completed by FabianLars** 2021-11-22 09:30 UTC
Labels: type: bug, status: invalid
