### ISSUE TITLE
[feat] Support file handling

### ISSUE THREAD

**Issue by mantou132** [tauri-apps/tauri#4529] opened 2022-06-30 05:36 UTC
### Describe the problem

Open with Tauri App when clicking the associated file

### Describe the solution you'd like

https://github.com/WICG/file-handling/blob/main/explainer.md#launch

**Comment by FabianLars** [comment] 2022-06-30 06:44
Duplicate of #3736 (and #918)

**Closed as completed by FabianLars** 2022-06-30 06:44 UTC
Labels: type: feature request
