### ISSUE TITLE
[bug] Cannot Reload Tauri After Making Backend Edits

### ISSUE THREAD

**Issue by ericwang401** [tauri-apps/tauri#8080] opened 2023-10-22 15:03 UTC
### Describe the bug

This bug inconsistently shows up when I make a change to the Rust backend. The GUI fails to launch after the application re-compiles after a change to the rust backend, and I receive this error

``` 
Info File src-tauri\src\processor\mod.rs changed. Rebuilding application...
    Blocking waiting for file lock on build directory
   Compiling app v0.0.0 (C:\Users\wange\Documents\GitHub\srm-executables-gui\src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 14.61s
thread '<unnamed>' panicked at src\interface\rust\desktop.rs:52:69:
failed to rename app: failed to rename `C:\Users\wange\Documents\GitHub\srm-executables-gui\src-tauri\target\debug\app.exe` to `C:\Users\wange\Documents\GitHub\srm-executables-gui\src-tauri\target\debug\SRM Executables.exe`

Caused by:
    Access is denied. (os error 5)
stack backtrace:
   0:     0x7ffd66c73f3f - napi_register_module_v1
   1:     0x7ffd666bf7cb - bz_internal_error
   2:     0x7ffd66c516d2 - napi_register_module_v1
   3:     0x7ffd66c7872a - napi_register_module_v1
   4:     0x7ffd66c7831e - napi_register_module_v1
   5:     0x7ffd66c77ee9 - napi_register_module_v1
   6:     0x7ffd66c79007 - napi_register_module_v1
   7:     0x7ffd66c78d95 - napi_register_module_v1
   8:     0x7ffd66c78ce9 - napi_register_module_v1
   9:     0x7ffd66c78cd4 - napi_register_module_v1
  10:     0x7ffd671eb905 - napi_register_module_v1
  11:     0x7ffd671ebd74 - napi_register_module_v1
  12:     0x7ffd66f98a8f - napi_register_module_v1
  13:     0x7ffd66f97c33 - napi_register_module_v1
  14:     0x7ffd66fb9df4 - napi_register_module_v1
  15:     0x7ffd66c6fc1b - napi_register_module_v1
  16:     0x7ffdcda77034 - BaseThreadInitThunk
  17:     0x7ffdce862651 - RtlUserThreadStart
```

### Reproduction

1. Clone https://github.com/OMRF/srm-executables-gui
2. `npm install`
3. `npm run tauri dev`
4. Make a change to any of the Rust files in `src-tauri` by adding a `println!("hello world!");` or any equivalent.

### Expected behavior

I want the application to successfully re-launch after I make an edit to the Rust backend and the application re-compiles.

### Platform and versions

```text
Windows 10 Enterprise 21H1 (OS Build 19043.1348)


[✔] Environment
    - OS: Windows 10.0.19043 X64
    ✔ WebView2: 118.0.2088.46
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.18.2
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.5

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Stack trace

```text
0:     0x7ffd66c73f3f - napi_register_module_v1
   1:     0x7ffd666bf7cb - bz_internal_error
   2:     0x7ffd66c516d2 - napi_register_module_v1
   3:     0x7ffd66c7872a - napi_register_module_v1
   4:     0x7ffd66c7831e - napi_register_module_v1
   5:     0x7ffd66c77ee9 - napi_register_module_v1
   6:     0x7ffd66c79007 - napi_register_module_v1
   7:     0x7ffd66c78d95 - napi_register_module_v1
   8:     0x7ffd66c78ce9 - napi_register_module_v1
   9:     0x7ffd66c78cd4 - napi_register_module_v1
  10:     0x7ffd671eb905 - napi_register_module_v1
  11:     0x7ffd671ebd74 - napi_register_module_v1
  12:     0x7ffd66f98a8f - napi_register_module_v1
  13:     0x7ffd66f97c33 - napi_register_module_v1
  14:     0x7ffd66fb9df4 - napi_register_module_v1
  15:     0x7ffd66c6fc1b - napi_register_module_v1
  16:     0x7ffdcda77034 - BaseThreadInitThunk
  17:     0x7ffdce862651 - RtlUserThreadStart
```

### Additional context

I am currently developing on a company machine. Before, I used to develop on my own personal machine (Windows 11) and had no issues.

On the company machine, I have tried reinstalling Rust/Rustup, re-cloning my project, checked antivirus (Crowdstrike & Windows Security report no issues). I even reinstalled the VM without any of the pre-installed software, and it did seem to resolve the issue for just a day before regressing.

**Comment by ericwang401** [comment] 2023-10-22 21:51
Here is my personal Windows 11 (22H2 Build 22621.2428) machine platform info
```
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 118.0.2088.61
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.18.0
    - npm: 10.2.1

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.5

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

**Comment by dkingsleya** [comment] 2024-03-05 13:19
I experienced the bug as well when trying to build a web scraper with tauri + next js, what I did to solve it was I tried to ctrl + c and restart the app (npm run dev) and it works as intended.

**Comment by jrmoynihan** [comment] 2024-03-15 19:02
Seeing the exact same issue.  Not solved by closing the process and restarting the `tauri dev` command.

**Comment by naruto00fa** [comment] 2024-07-02 01:25
Could resolve by close the process and wait about 1 minute, then rerun `tauri dev`, but it is annoying, hope some one give a better solution

> Seeing the exact same issue. Not solved by closing the process and restarting the `tauri dev` command.

**Comment by ericwang401** [comment] 2024-07-02 02:18
This ended up being an issue with my company's antivirus CrowdStrike. Every time my Tauri app recompiles, CrowdStrike locks the new exe to scan it briefly. But most of the time, the scan takes too long thus locking the file for too long. Then, when Tauri tries to rename, it panics because the file is still locked.

I never suspected it was CrowdStrike at the beginning because it never threw any messages, but after disabling CrowdStrike, I was able to recompile successfully every time.

It took over 6 months, several calls to IT, and even met with a CrowdStrike rep to find the reason. So use this advice to double check that your antivirus isn't causing any problems!!! I cannot emphasize this enough

**Closed as completed** 2024-07-02 02:18 UTC
Labels: type: bug, status: needs triage
