### ISSUE TITLE
tauri build fails at appimage.sh [bug] 

### ISSUE THREAD

**Issue by indegrowl** [tauri-apps/tauri#10522] opened 2024-08-07 14:25 UTC
### Describe the bug

It gives this error while running the command `tauri build --verbose`

```
Setting rpath in ELF file journaler.AppDir/usr/lib/libzstd.so.1 to $ORIGIN

-- Running input plugin: gtk --
[gtk/stdout] Installing AppRun hook
[gtk/stderr] chmod: cannot access 'journaler.AppDir/usr/lib64': No such file or directory
[gtk/stdout] Installing GLib schemas
[gtk/stderr] cp: cannot stat '/nix/store/c2v6ycn0sjcpx9ww8x7j4ima6xnpssry-glib-2.80.2/share/glib-2.0/schemas': No such file or directory
ERROR: Failed to run plugin: gtk (exit code: 1)
       Error [tauri_cli_node] failed to bundle project: error running appimage.sh
```

### Full `tauri info` output

```text
[✘] Environment
    - OS: NixOS 24.5.0 X64
    ✔ webkit2gtk-4.0: 2.44.2
    ✘ rsvg2: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rustc: 1.78.0 (9b00956e5 2024-04-29)
    ✔ cargo: 1.78.0 (54d8815d0 2024-03-26)
    ✔ rustup: 1.26.0 (1980-01-01)
    ✔ Rust toolchain: 1.78-x86_64-unknown-linux-gnu (default)
    - node: 20.12.2
    - npm: 10.5.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-08-07 15:04
Should be a duplicate of https://github.com/tauri-apps/tauri/issues/8535 (same error message)

**Closed as not planned by FabianLars** 2024-08-07 15:04 UTC
Labels: type: bug, status: needs triage, platform: Nix/NixOS
