### ISSUE TITLE
[bug] cargo's terminal output overflows

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri#3995] opened 2022-04-29 10:32 UTC
### Describe the bug

Tested in cmd and powershell, both inside and outside of the MS Terminal app.
![image](https://user-images.githubusercontent.com/30730186/165928218-794c0e69-dfa1-4456-90e7-c3e809d38d6d.png)

### Reproduction

1. run `cargo clean` in your src-tauri dir.
2. run `tauri dev`

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 100.0.1185.50
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: 6.32.10
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ dist
  ├─ node_modules
  └─ src-tauri
```

**Comment by lucasfernog** [comment] 2022-04-29 13:43
It looks like it isn't clearing the line properly to show the `Building [==============] ...` line. I'm not sure if that's the actual problem though.

**Comment by FabianLars** [comment] 2022-04-29 13:53
https://github.com/rust-lang/cargo/issues/9155

**Comment by lucasfernog** [comment] 2022-04-29 13:55
We're also forcing the color option, seems like that should be fixed in recent cargo releases.

**Comment by lucasfernog** [comment] 2022-04-29 13:56
`When running cargo with output not going to a TTY, and with the progress bar and color force-enabled, the output will now correctly clear the progress line` (part of the Cargo 1.52 changelog)

**Comment by FabianLars** [comment] 2022-04-29 14:02
okay then i guess it's not that cargo issue then since i'm on 1.60 🤔

**Comment by lucasfernog** [comment] 2022-04-29 14:03
It was happening to me once too, but then it just disappeared :D

**Comment by lucasfernog** [comment] 2022-04-29 14:05
You can see it's not a Cargo issue by running this:

```
 $env:CARGO_TERM_PROGRESS_WIDTH=100
 $env:CARGO_TERM_PROGRESS_WHEN='always'
cargo build --color always
```

something must be off on our processing

**Comment by lucasfernog** [comment] 2022-04-29 14:24
Got the error again lol let's see if i can fix it this time.

**Comment by lucasfernog** [comment] 2022-04-29 14:54
Seems like the problem is the terminal size. I'll see if their implementation is different, and fix it. Changing it from the `120` returned from terminal_size to 60 fixed it.

**Closed as completed** 2022-04-29 16:28 UTC
Labels: type: bug
