### ISSUE TITLE
[bug] Webview content outside window (macOS)

### ISSUE THREAD

**Issue by probablykasper** [tauri-apps/tauri#4636] opened 2022-07-09 19:16 UTC
### Describe the bug

It's possible to make content from the webview appear outside of the window, and cause some glitchines

https://user-images.githubusercontent.com/11315492/178119617-9602b1e7-a1ee-4606-8d85-2e6182ee6992.mp4

### Reproduction

I'm experiencing this specifically with this app: https://github.com/probablykasper/time-machine-inspector

### Platform and versions

```shell
Environment
  › OS: Mac OS 10.15.7 X64
  › Node.js: 16.15.0
  › npm: 8.12.1
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src 'self'; style-src 'unsafe-inline' *
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ node_modules
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ build
  ├─ .git
  ├─ assets
  └─ src
```

**Comment by FabianLars** [comment] 2024-12-04 14:30
I wonder if it's the same as https://github.com/tauri-apps/tauri/issues/4243 - i'll close this as a duplicate of that because either it is, or it's something we probably can't fix.

**Closed as not planned by FabianLars** 2024-12-04 14:30 UTC
Labels: type: bug, platform: macOS, status: needs triage

**Comment by probablykasper** [comment] 2024-12-05 01:54
Yeah my guess is that this is some driver, OS or webview issue outside of Tauri. Don't even know if the bug exists anymore
