### ISSUE TITLE
Initialize the window maximization issue.

### ISSUE THREAD

**Issue by sopaco** [tauri-apps/tauri#11309] opened 2024-10-10 13:06 UTC
### Describe the bug

Initialize the window maximization issue.
Through tauri.conf.json to configure window maximization, when the application starts, there is a process where the window size expands. How can we make it so that the window is maximized directly upon startup without any transition effect?

### Reproduction

```json
{
    "windows": [
        {
            "label": "main",
            "title": "Application Name",
            "url": "/main",
            "center": true,
            "maximized": true,
            "minWidth": 1280,
            "minHeight": 720
        }
    ]
}
```

### Full `tauri info` output

```text
-
```

### Additional context

tauri 2.0.1

**Comment by FabianLars** [comment] 2024-10-10 16:49
Please include the output of the `tauri info` command as required by the issue template.

**Comment by FabianLars** [comment] 2024-10-10 16:53
Ah actually, i'll close this as a duplicate of https://github.com/tauri-apps/tauri/issues/11284 (please confirm whether you're also on Windows)

**Closed as not planned by FabianLars** 2024-10-10 16:53 UTC
Labels: type: bug, status: needs triage
