### ISSUE TITLE
[bug] Failed to load resource: Unspecified proxy lookup failure

### ISSUE THREAD

**Issue by BTCB** [tauri-apps/tauri#7104] opened 2023-06-01 07:37 UTC
### Describe the bug

On Linux Mint, Unable to load image
![image](https://github.com/tauri-apps/tauri/assets/13432688/9d2ac0a4-c595-464a-85b0-15ffb01d1f4b)

### Platform and versions

```text
[✔] Environment
    - OS: Linux Mint 21.1 X64
    ✔ webkit2gtk-4.0: 2.38.6
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.15.0
    - pnpm: 8.5.1
    - yarn: 1.22.19
    - npm: 9.6.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:5173/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment] 2023-06-05 14:15
I'll temporarily close this due to the lack of enough information.

Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and fill the appropriate information fields to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as not planned by amrbashir** 2023-06-05 14:15 UTC
Labels: type: bug, platform: Linux, status: needs triage

**Comment by prayag17** [comment] 2023-07-11 12:07
Any fix for this? I am facing this issue on arch linux

**Comment by tam1m** [comment] 2023-07-13 16:46
I can reproduce this reliably. See https://github.com/prayag17/JellyPlayer/issues/126.

**Comment by Pylogmon** [comment] 2023-07-14 02:59
I also encountered this problem, I think this may be a dependency (such as webkit2gtk) caused by the problem, because my code was tested on Arch Linux without any problems before, recently I found this problem, but when I check out my repository to a long time ago version, It still trigger this problem.

**Comment by Pylogmon** [comment] 2023-07-14 03:51
I also had this problem, I just fixed it, I am not sure if you are in the same situation as me.

Since `tauri/api/http` does not support setting proxies, I set the `all_proxy` environment variable to set the proxy. When the proxy is set to empty, I set an empty string to `all_proxy`. This is not a problem before, but on the latest Arch Linux, I started to have an `Unspecified proxy lookup failure`. My approach is to remove the `all_proxy` environment variable when not setting the proxy.

https://github.com/pot-app/pot-desktop/blob/master/src-tauri/src/config.rs#L170C5-L170C5

**Comment by salman0ansari** [comment] 2023-10-17 09:43
what cause this error ?

**Comment by Etavioxy** [comment] 2023-11-21 03:31
No need to stop proxy, just set like this.

```
export all_proxy=<your-proxy-ip>:7890
export no_proxy="localhost,127.0.0.1,192.168.0.1"
```

`no_proxy` is an environment variable used to specify a host or domain name that does not require the use of a proxy.

`no_proxy` 是一个环境变量，用于指定不需要使用代理的主机或域名。

**Comment by ArcticLampyrid** [comment] 2024-05-31 05:00
For most applications (e.g., Electron-based applications, classical console applications like cURL and wget), they work well without specifying `no_proxy`. So why must I set `no_proxy` for Tauri-based applications? There are already countless tutorials that do not require setting the `no_proxy` environment variable.

**Comment by ArcticLampyrid** [comment] 2024-05-31 05:02
> I'll temporarily close this due to the lack of enough information.
> 
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and fill the appropriate information fields to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

@amrbashir 

Set `http_proxy` and `https_proxy` env, but do not set `no_proxy`.
Then run an application, which will `fetch("http://127.0.0.1:1234")`
You will meet this problem.


*Note: this is a Linux-specific problem.*
