### ISSUE TITLE
Include the option to show native window controls without titlebar

### ISSUE THREAD

**Issue by gardc** [tauri-apps/tauri#2956] opened 2021-11-24 14:24 UTC
**Is your feature request related to a problem? Please describe.**
Shipping a modern desktop app, it's frustrating not having the option for native window controls on a window without the window titlebar. E.g. on macOS, a window that is filled with the app's content but still has the traffic light controls intact. 
This results in frameless Tauri applications having to include their own window controls, which doesn't follow the native window interaction design and can lead to poor UX. 
Electron has this options as explained in its docs [here](https://www.electronjs.org/docs/latest/tutorial/window-customization#apply-custom-title-bar-styles-macos-windows). 

**Describe the solution you'd like**
I'd like a solution resembling Electron's, where you can set title bar style to `hidden` which will still show the native window controls without a titlebar.

**Describe alternatives you've considered**
Including the native window controls on a frameless window, and then having the configuration option to remove the window controls.

Example:
![Screenshot 2021-11-24 at 15 24 53](https://user-images.githubusercontent.com/41453409/143256274-1d3d1b56-c24a-496f-9944-311166a6df25.png)

**Comment by FabianLars** [comment] 2021-11-24 14:31
Possible duplicate of #2663?

**Comment by gardc** [comment] 2021-11-24 14:33
Yup, it is @FabianLars! Missed that one 😅

**Closed as completed** 2021-11-24 14:35 UTC
Labels: type: feature request, status: invalid
