### ISSUE TITLE
[bug] websocket is connected multiple times

### ISSUE THREAD

**Issue by WWQ-CODE** [tauri-apps/tauri#8943] opened 2024-02-22 03:19 UTC
### Describe the bug

why do tauri applications request Websockets (Websockets used in js) multiple times, resulting in 3+ long connections being established

### Expected behavior

![20240222-111553](https://github.com/tauri-apps/tauri/assets/18333349/cf425107-bddf-4db2-a2dd-3913f63aa3f6)

### Full `tauri info` output

```text
-
```

### Additional context

  const url = Utilities.makeBaseUrl(host, secure ? 'wss' : 'ws', APIKey)

      const conn: WebSocket = new NetworkProviders.WebSocket(url)

      conn.onerror = (err => {
        reject(err)
      }).bind(this)

**Comment by canxin121** [comment] 2024-02-22 03:56
Is this related to strict mode? You could try using useEffect and clean up the side effects(close the websocket connection)

**Comment by amrbashir** [comment] 2024-02-22 14:27
This is probably something related to HMR or hot-reload where connections are not being dropped, could also be the same as #8922. We can't do anything if it is the first so will close this as a duplicate of it

**Closed as not planned by amrbashir** 2024-02-22 14:27 UTC
Labels: type: bug, status: needs triage
