### ISSUE TITLE
[bug] window.requestUserAttention stops flashing before the window getting focus.

### ISSUE THREAD

**Issue by insopitus** [tauri-apps/tauri#8658] opened 2024-01-23 06:43 UTC
### Describe the bug

I call the method like this `appWindow.requestUserAttention(UserAttentionType.Informational)`, the taskbar icon flashes 3 times and  turns normal, before the window is focused.
I also tried the rust version of this api, `app_handle.get_window("main").unwrap().request_user_attention(Some(UserAttentionType::Informational));`, same result.

### Reproduction

js:  
```js
// the `getCurrent()` method imported from @tauri-apps/plugin-window might be bugged.
const appWindow = window.__TAURI__.window.getCurrent()
appWindow.requestUserAttention(UserAttentionType.Informational)
```

or 

rust:
 ```rust
app_handle.get_window("main").unwrap().request_user_attention(Some(UserAttentionType::Informational));
```

### Expected behavior

According to the documentation:
> pub enum UserAttentionType {
  /// ## Platform-specific
  /// - **macOS:** Bounces the dock icon until the application is in focus.
  /// - **Windows:** Flashes both the window and the taskbar button until the application is in focus.
  Critical,
  /// ## Platform-specific
  /// - **macOS:** Bounces the dock icon once.
  /// - **Windows:** Flashes the taskbar button until the application is in focus.
  Informational,
}

the taskbar icon of the app should keep flashing until window is in focus, at least on Windows.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 120.0.2210.144
    ✔ MSVC: Visual Studio ���ɹ��� 2022
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.11.0
    - pnpm: 7.27.0
    - yarn: 1.22.19
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.20
    - tauri-build [RUST]: 2.0.0-alpha.13
    - wry [RUST]: 0.35.1
    - tao [RUST]: 0.24.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.12
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.18

[-] App
    - build-type: build
    - CSP: default-src 'self' ipc: http://ipc.localhost; img-src 'self' asset: http://asset.localhost       
    - distDir: dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-01-23 12:33
Thanks for the report! Does this happen in both `tauri dev` and `tauri build`?

**Comment by insopitus** [comment] 2024-01-23 12:45
> Thanks for the report! Does this happen in both `tauri dev` and `tauri build`?

Yes, both do.

**Comment by amrbashir** [comment] 2024-01-23 16:32
I couldn't reproduce this at all, the window icon keeps flashing just fine for me. I am on Windows 11 22631.

Since we are using [`FLASHW_TIMERNOFG`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-flashwinfo) [here](https://docs.rs/tao/0.16.7/x86_64-pc-windows-msvc/src/tao/platform_impl/windows/window.rs.html#824), which means to flash until the window is focused, either this is a bug in Windows itself or somehow your window gains focus.

Either way, I think it is safe to close this issue but feel free to provide a minimal repro and I will take a look again.

**Closed as not planned by amrbashir** 2024-01-23 16:32 UTC
Labels: type: bug, status: needs triage

**Comment by insopitus** [comment] 2024-01-24 03:42
> I couldn't reproduce this at all, the window icon keeps flashing just fine for me. I am on Windows 11 22631.
> 
> Since we are using [`FLASHW_TIMERNOFG`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-flashwinfo) [here](https://docs.rs/tao/0.16.7/x86_64-pc-windows-msvc/src/tao/platform_impl/windows/window.rs.html#824), which means to flash until the window is focused, either this is a bug in Windows itself or somehow your window gains focus.
> 
> Either way, I think it is safe to close this issue but feel free to provide a minimal repro and I will take a look again.

@amrbashir I checked it again. The flashing works fine if there is only one instance of the app running. If there are more than one, the said bug may apear.

I was testing my chat app by running 2 instances on the same machine and talking to each other. The app instance that receives message flashes. When I send messages from one to the other, the flash happens only 3 times. But if I send message to one of them from another instance on another machine, the flash works fine.

I think the bug happens only in the situation where one instance request attention while another instance is in the foreground.

**Comment by amrbashir** [comment] 2024-01-24 14:27
I think that's just normal behavior for windows, even there is two processes, it still recognizes them as one app and so focusing any of them will be counted towards removing the flash.

Anyways, this is something we can't control unfortunately and probably why many apps use a single-instance application.

**Comment by insopitus** [comment] 2024-01-24 14:29
> I think that's just normal behavior for windows, even there is two processes, it still recognizes them as one app and so focusing any of them will be counted towards removing the flash.
> 
> Anyways, this is something we can't control unfortunately and probably why many apps use a single-instance application.

That makes sense. Thanks for explaining.

**Comment by muwoo** [comment] 2024-05-27 08:03
> I think that's just normal behavior for windows, even there is two processes, it still recognizes them as one app and so focusing any of them will be counted towards removing the flash.
> 
> Anyways, this is something we can't control unfortunately and probably why many apps use a single-instance application.

@Insopitus @amrbashir Why is request user Attention valid in the Electron multi-instance window?

**Comment by muwoo** [comment] 2024-05-27 08:20
I found that although Tauri can open multiple windows on the Windows operating system, it actually shares the same webview process. 

![img_v3_02b9_167e020b-a9a3-42e2-81f8-7da7cfa046cg](https://github.com/tauri-apps/tauri/assets/21073039/58458cf7-5f53-47e9-97d1-e20c1847c272)

But for electron, they start a different chromium process.

This should be the main reason

So is it necessary for tauri to support configuring different windows to use different webview processes?

**Comment by amrbashir** [comment] 2024-05-27 16:10
> > I think that's just normal behavior for windows, even there is two processes, it still recognizes them as one app and so focusing any of them will be counted towards removing the flash.
> > Anyways, this is something we can't control unfortunately and probably why many apps use a single-instance application.
> 
> @Insopitus @amrbashir Why is request user Attention valid in the Electron multi-instance window?

Not sure what you mean by multi-instance window? do you mean just multi-window application?

**Comment by muwoo** [comment] 2024-05-27 16:34
> > > I think that's just normal behavior for windows, even there is two processes, it still recognizes them as one app and so focusing any of them will be counted towards removing the flash.
> > > Anyways, this is something we can't control unfortunately and probably why many apps use a single-instance application.
> > 
> > 
> > @Insopitus @amrbashir Why is request user Attention valid in the Electron multi-instance window?
> 
> Not sure what you mean by multi-instance window? do you mean just multi-window application?

em…I can open multiple electron windows by double-clicking the application icon on Windows, and these multiple electron windows correspond to multiple processes that do not affect each other.
 
I noticed that tauri can also open multiple windows in this way, but they share the same process. 

Later, I tried to dynamically modify the identifier in the context when starting the tauri application in rust, and found that tauri started multiple processes, and the behavior was consistent with electron.

 But I don't know what happened between them

**Comment by amrbashir** [comment] 2024-05-27 16:59
I guess that's related to our use of [`FLASHW_TIMERNOFG`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-flashwinfo), which is the difference between our implementation and that of electron.

Electron uses `FLASHW_ALL` which flashes the taskbar icon and the window titlebar and doesn't have the notion of `Informational` vs `Critical` and they just have one mode to flash the window. They also have a hardcode of `4` flashes.

Winit/Tao/Tauri implementation have a notion of urgency when requesting user attention:
- `Informational`: flashes 4 times and only flashes the taskbar icon.
- `Critical`: flashes `u32::MAX`(4,294,967,295) times until the window is active and flashes the taskbar icon, and titlebar.

For `Informational`, we can skip adding `FLASHW_TIMERNOFG` which makes it a little bit closer to electron implementation, i.e the flashing will be gone once you focus the window that is flashed and not just any window in the application.

However for `Critical`, without `FLASHW_TIMERNOFG` the window will keep flashing for a very long time even after you focus it and won't stop until it flashes for 4,294,967,295 times, so we can't remove `FLASHW_TIMERNOFG` for `Critical` urgency.

**Comment by muwoo** [comment] 2024-05-28 06:50
Thank you very much for your reply. Yes, you are right, it is indeed the case. I tried to modify the processing of Information by `Tao` library according to your idea.

https://docs.rs/tao/0.16.7/x86_64-pc-windows-msvc/src/tao/platform_impl/windows/window.rs.html#824

```rust
UserAttentionType::Informational => (FLASHW_TRAY, 4)
```

I found that the performance of message reminders is consistent with that of Electron.

**Comment by muwoo** [comment] 2024-05-28 10:56
Can we add a new type to the `requestUserAttention` method, such as `UserAttentionType::Independent`? (This means that in multi-window mode, any window can flash the tray icon independently until the corresponding window is focused.)

In this way, developers can decide whether they need the performance of message reminders in multiple windows to be consistent with `Electron`.

**Comment by amrbashir** [comment] 2024-05-29 15:38
That would need to be implemented on other platforms, I think it is just fine to just modify the `Informational` variant but will need to be done for v2, as it is breaking change for v1
