### ISSUE TITLE
[bug] Key issue (__TAURI_INVOKE_KEY__)

### ISSUE THREAD

**Issue by DmitryAstafyev** [tauri-apps/tauri#3362] opened 2022-02-08 20:20 UTC
### Describe the bug

Direct runing `debug` or `release` version gives error
```Unhandled Promise Rejection: ReferenceError: Can't find variable: __TAURI_INVOKE_KEY__```

### Reproduction

1. Create a simple solution
2. Build with `npm run tauri build -- --debug` or `./node_modules/.bin/tauri build --debug`
3. Run `./target/debug/app_name` or `./target/release/app_name`

### Expected behavior

No such error

### Platform and versions

```shell
Operating System - Arch Linux, version Rolling Release X64

Node.js environment
  Node.js - 14.15.4
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.10
  yarn - 1.22.17

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

App directory structure
/.git
/src-tauri
/dist
/node_modules

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist
  bundler - Webpack
```
```


### Stack trace

_No response_

### Additional context

It's easy to fix. Just add to the top of the main `js` file
```
window.__TAURI_INVOKE_KEY__ = __TAURI_INVOKE_KEY__;
```
But I guess it should be fixed on another level

I've checked all other issuer related to __TAURI_INVOKE_KEY__, and it seems I have some another kind of issue.

**Comment by FabianLars** [comment] 2022-02-08 20:37
Soooo, if i would want to reproduce this i'd be stuck at Step 1 ("Create a simple solution"), because as you said yourself, your issue seems to be different from the others, (Publishing a repository containing a minimal reproduction (including lockfiles) is the best thing you can do to help us help you.

If i remember correctly this issue actually occurs on version mismatches (= outdated `@tauri-apps/cli`). Which most of the times is a yarn v2/v3 issue because that can't resolve our beta versions correctly (and you end up with beta-rc.4 instead of beta.10), but your info says you're running yarn v1, so this shouldn't be an issue.
To confirm this you can check your lock file and see to which version it resolved the tauri packages.

Sorry for this huge amount of text lol.

I'm going to close this as the invoke key got completely removed on the `next` branch, so this won't be an issue on the next release anymore.

Edit: As another hint for you to troubleshoot, if you don't use ES modules your javascript files will be wrappen in an IIFE, so stuff that's exposed in them won't be in global scope anymore. This should cause different errors tho...

**Closed as completed by FabianLars** 2022-02-08 20:37 UTC
Labels: type: bug
