### ISSUE TITLE
[bug] Can not use system base directory variables in shell cmd

### ISSUE THREAD

**Issue by ianho7** [tauri-apps/tauri#5480] opened 2022-10-25 11:30 UTC
### Describe the bug

I want to use shell command api to run a executable file, here is my code:
`

    const resourceDirPath = await resourceDir()
    console.log(resourceDirPath = ${resourceDirPath})
    const command = new Command('download', ['https://www.bilibili.com/video/BV1rP4y1U75S'])
    command.on('close', (data) => {
      console.log(`command finished with code ${data.code} and signal ${data.signal}`)
    })

    command.on('error', (error) => console.error(`command error: "${error}"`))
    command.stdout.on('data', (line) => {
      console.log(`command stdout: "${line}"`)
      if (line) {
        setLog(`${log}\n${line}`)
      }
    })
    command.stderr.on('data', (line) => console.log(`command stderr: "${line}"`))

    const child = await command.spawn()
    console.log('pid:', child.pid)

And here is my tauri.conf.json
`"shell": {
        "all": true,
        "execute": true,
        "sidecar": true,
        "open": true,
        "scope": [{
          "name": "download",
          "cmd": "$RESOURCE/sdk/you-get-darwin",
          "args": [{ "validator": "\\S+" }]
        }]
      }`

This is result:
![image](https://user-images.githubusercontent.com/26101033/197759180-be49d138-62ed-4094-b0c8-ebff2e6c9b25.png)

I check the resource directory(resourceDirPath = /Users/ianho/Documents/project/private/tauri-react-template/src-tauri/target/debug/
Index.tsx:61) and  the executable file is exists.
![image](https://user-images.githubusercontent.com/26101033/197759507-b8ec972c-2778-4594-bbf5-3118875bc569.png)

Could you please tell my what's wrong with my code or the correct way to use tauri api, thank a lot!

### Platform and versions

Environment
  › OS: Mac OS 12.3.1 X64
  › Node.js: 16.13.0
  › npm: 8.1.0
  › pnpm: 7.13.5
  › yarn: 1.22.10
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ .git
  └─ src

**Comment by FabianLars** [comment] 2022-10-25 11:47
~~Not 100% sure but i think the `$xxx` vars won't be resolved for the `cmd` property, so in this case it tries to open `<cwd>/$RESOURCE/sdk/you-get-darwin`.~~ Nevermind, i'm wrong. Too early for me lol. Maybe it's related to this bug https://github.com/tauri-apps/tauri/issues/5196 - a fix for this will be part of tauri 1.2

Since this is effectively what you're doing manually here, did you take a look at the sidecar feature? https://tauri.app/v1/guides/building/sidecar

**Comment by ianho7** [comment] 2022-10-25 14:42
> ~Not 100% sure but i think the `$xxx` vars won't be resolved for the `cmd` property, so in this case it tries to open `<cwd>/$RESOURCE/sdk/you-get-darwin`.~ Nevermind, i'm wrong. Too early for me lol. Maybe it's related to this bug #5196 - a fix for this will be part of tauri 1.2
> 
> Since this is effectively what you're doing manually here, did you take a look at the sidecar feature? https://tauri.app/v1/guides/building/sidecar

Thanks for response! sidebar feature is very useful!

**Comment by JMMarchant** [comment] 2022-10-28 16:39
I'm similarly running into this issue though can't use the sidecar due to the interplay between multiple binary files which all need to be colocated with each other).

Although it doesn't print the file path in the error message, I'm fairly certain you're almost right @FabianLars and the issue is that it's messing up the path in `cmd` and instead putting it in a _literal_ `$RESOURCE` directory (tested this by printing out the `resourceDir()` path and then placing a simple "Hello World!" binary at `resourceDir()/"$RESOURCE"/<rest of cmd path from scope>` where it suddenly works).

i.e. for this example it would be at `src-tauri/target/debug/$RESOURCE/sdk/you-get-darwin`

**Comment by JMMarchant** [comment] 2022-10-28 16:58
Have just tried it with `$HOME` in place of `$RESOURCE` and can confirm it's an issue with the $-vars not being substituted (despite the docs saying they are); instead of picking something up from my home directory it wasn't until I put it in the debug folder under a "$HOME" directory that it worked.

**Comment by lucasfernog** [comment] 2022-10-29 18:09
We can surely improve the shell configuration to allow resolving the command path with the predefined variables, but be careful to not confuse the arbitrary shell command execution with a sidecar.
A sidecar is automatically read from the resources directory, so you can specify `{ name: "sdk/you-get-darwin", sidecar: true }` instead of `{ name: 'download', cmd: '$RESOURCE/sdk/you-get-darwin` }` as long as you append the target triple to the sidecar file name and you'll automatic sidecar path resolution and it'll be easier to make it cross platform.

**Comment by JMMarchant** [comment] 2022-10-31 08:51
> A sidecar is automatically read from the resources directory, so you can specify `{ name: "sdk/you-get-darwin", sidecar: true }` instead of `{ name: 'download', cmd: '$RESOURCE/sdk/you-get-darwin` }` as long as you append the target triple to the sidecar file name and you'll automatic sidecar path resolution and it'll be easier to make it cross platform.

Is it guaranteed that a sidecar always gets packaged into the resources directory? My "main" sidecar binary has some dynamically linked libraries that it needs to be colocated with so need to have those end up in the same place.

**Comment by lucasfernog** [comment] 2022-11-03 21:37
Not really @JMMarchant that's one of the limitations of a sidecar. We'll try to include this enhancement on v1.2.

**Closed as completed** 2022-11-04 15:38 UTC
Labels: type: bug, scope: core
