### ISSUE TITLE
[feat] Add the ability to generate .msix or .appx

### ISSUE THREAD

**Issue by Andrew-web-coder** [tauri-apps/tauri#8548] opened 2024-01-05 09:19 UTC
### Describe the problem

Since I don't want to buy a certificate for my hobby project, I can't sign my app. So the only option for me is to distribute my app through Windows Store (without annoying security warnings). The problem is that it only accepts one of these package types:

>.msix, .msixbundle, .msixupload, .appx, .appxbundle, .appxupload, .xap

It appears that Tauri does not currently offer to create any of these package types

### Describe the solution you'd like

I would like to be able to generate .appx package like this:

```
npm run tauri build --target appx
```

**Comment by FabianLars** [comment] 2024-01-05 11:17
Hi, thanks for the request. We already have a tracking issue for msix here: https://github.com/tauri-apps/tauri/issues/4818

Also, for your usecase specifically, you can upload msi and exe installers to the store for i think a year now. First guide i found on google: https://www.advancedinstaller.com/publish-msi-exe-app-microsoft-store.html. The official MS guides aren't as explicit/obvious, but they have tabbers to select msi/exe starting here https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/overview?pivots=store-installer-msi-exe

That said, i don't know how compliant tauri app installers are with the store requirements since i didn't actually publish an app when i tried it myself back when it was new. I think we'd be interested in fixing any issues in that regard though.

**Comment by amrbashir** [comment] 2024-01-09 00:19
Closing as duplicate of #4818 but feel free to open new issues if our current .exe/.msi installers are not compliant with windows store.

**Closed as not planned by amrbashir** 2024-01-09 00:19 UTC
Labels: type: feature request, platform: Windows

**Comment by Andrew-web-coder** [comment] 2024-02-13 12:48
> you can upload msi and exe installers to the store

Yes, you can ..... but:


> Your app does not have a digital signature which violates Microsoft Store Policy [10.2.9](https://learn.microsoft.com/en-us/windows/apps/publish/store-policies) Your app must be digitally signed as per this policy with a SHA256 or higher code sign certificate.
