### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by saxobroko** [tauri-apps/tauri#932] opened 2020-08-08 13:46 UTC
**Describe the bug**
Npm says that the .cargo-lock is partially locked by another process, although there are no processes with the file in use. I've also tried deleting the file.

**To Reproduce**
1. enter 'npm run build'
2. The error occurs at 197/199

**Expected behavior**
Tauri should be succesfully compiled and it should continue with the build.

**Error Code**
```
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Users\\Saxon Brooker\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'tauri',
npm verb cli   'build',
npm verb cli   '-Z',
npm verb cli   'macro-backtrace',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.7
npm info using node@v14.5.0
npm verb run-script [ 'pretauri', 'tauri', 'posttauri' ]
npm info lifecycle saxobroko@2.0.1~pretauri: saxobroko@2.0.1
npm info lifecycle saxobroko@2.0.1~tauri: saxobroko@2.0.1

> saxobroko@2.0.1 tauri C:\Users\Saxon Brooker\Documents\electron\saxobroko
> tauri "build" "macro-backtrace"

[tauri]: running build
 app:spawn Running "cargo tauri-bundler --features embedded-server --release" +0ms

   Compiling saxobroko v0.1.0 (C:\Users\Saxon Brooker\Documents\electron\saxobroko\src-tauri)
   Compiling tauri v0.9.1
error: couldn't read C:/Users/Saxon Brooker/Documents/electron/saxobroko/src-tauri/target/release/.cargo-lock: The process cannot access the file because another process has locked a portion of the file. (os error 33)
     --> C:\Users\Saxon Brooker\Documents\electron\saxobroko\src-tauri\target\release\build\tauri-1207208a8ac84fc3\out/data.rs:75774:142
      |
75774 | ...ession::None, include_bytes!("C:/Users/Saxon Brooker/Documents/electron/saxobroko/src-tauri/target/release/.cargo-lock") as &'static [...
      |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

 app:tauri Shutting down tauri process... +11m=====================> ] 197/199: tauri
```

**Platform and Versions (please complete the following information):**

OS:  Windows_NT(10.0.19041) - win32/x64
Node: 14.5.0
NPM: 6.14.7
Yarn: 1.22.4
Rustc: 1.47.0-nightly

**Additional context**
I'm trying to convert from electron

**Comment by nklayman** [comment] 2020-08-08 18:45
The error message says that another process has locked that file. Restarting your computer should fix the problem.

**Comment by saxobroko** [comment] 2020-08-09 11:56
Restarting did not solve the issue

**Comment by zicklag** [comment] 2020-08-09 21:02
Do you have RLS or Rust Analyzer running?

**Comment by jamestthompson3** [comment] 2020-08-10 06:59
Try removing the target directory then rebuilding.

**Comment by saxobroko** [comment] 2020-08-11 15:07
This error occurs with some different files.
```
error: couldn't read C:/Users/Saxon Brooker/Documents/electron/saxobroko/src-tauri/target/release/deps/sysinfo-4a87a90655087ce6.sysinfo.5kg5tej0-cgu.5.rcgu.o: The system cannot find the file specified. (os error 2)
     --> C:\Users\Saxon Brooker\Documents\electron\saxobroko\src-tauri\target\release\build\tauri-1207208a8ac84fc3\out/data.rs:42847:190
      |
42847 | ...e, include_bytes!("C:/Users/Saxon Brooker/Documents/electron/saxobroko/src-tauri/target/release/deps/sysinfo-4a87a90655087ce6.sysinfo.5kg5tej0-cgu.5.rcgu.o") as...
      |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

    Building [=====================================================> ] 197/199: tauri
```

**Comment by jbolda** [comment] 2020-08-15 13:55
Just to rule it out, would you mind testing on stable rust? (not nightly)

**Comment by nklayman** [comment] 2021-02-01 01:30
Since this issue is so old and we haven't seen any new reports nor have we been able to reproduce it ourselfs, I'm going to close it.

**Closed as completed by nklayman** 2021-02-01 01:30 UTC
Labels: type: bug

**Comment by AsessionGuy** [comment] 2022-07-23 21:40
I'm having a similar issue with:
Tauri: cargo-tauri 1.0.5
OS: Windows 11 Pro (10.0.22000) x64
Rustc: 1.62.1

Also tried with node and got the same:
Node: 16.16.0
NPM: 8.11.0

```
PS C:\Users\galla\Desktop\kansel\kansel-app> cargo tauri dev
Info Watching C:\Users\galla\Desktop\kansel\kansel-app\src-tauri for changes...
Compiling app v0.1.0 (C:\Users\galla\Desktop\kansel\kansel-app\src-tauri)
error: failed to read asset at C:\Users\galla\Desktop\kansel\kansel-app\src-tauri\.\target\debug\.cargo-lock
because The process cannot access the file because another process has locked a portion of the file. (os error 33)
 --> src\main.rs:8:10
  |
8 |     .run(tauri::generate_context!())
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `tauri::generate_context` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `app` due to previous error
```

I use VS Code but I don't have rust-analyzer and restarting/deleting .cargo-lock didn't solve it.
I was following [this](https://tauri.app/v1/guides/getting-started/setup/) guide from tauri.app

**Comment by AsessionGuy** [comment] 2022-07-27 06:50
nvm, it was the same issue as the one on [#4723](https://github.com/tauri-apps/tauri/issues/4723#issue-1311261248) so using absolute paths solved it.
