### ISSUE TITLE
[bug] Partial HTML Drag is not work

### ISSUE THREAD

**Issue by LuXts** [tauri-apps/tauri#3277] opened 2022-01-24 17:56 UTC
### Describe the bug

I'm writing a vue3 tauri project with typescript. The behavior of the executable packaged with tauri is not consistent with the browser preview. In the API for HTML drag, only the `dragstart` and `dragend` work for me. The other don't trigger at all. 

Work:

* ondragstart
* ondragend

Not Work:

* ondragenter
* ondragleave
* ondragover
* ondrop

Not tested:

* ondragexit

I have set "fileDropEnabled":false.

### Reproduction

run:
```shell
vue create test
cd test
vue add tauri
yarn tauri:serve
```
HTML Example:

```html
<ul>
        <li
            draggable="true"
            ondragstart="console.log('start')"
            ondragenter="console.log('enter')"
            ondragend="console.log('end')"
            ondragover="console.log('over')"
            ondragleave="console.log('leave')"
            ondrop="console.log('drop')"
        >
            item1
        </li>
        <li
            draggable="true"
            ondragstart="console.log('start')"
            ondragenter="console.log('enter')"
            ondragend="console.log('end')"
            ondragover="console.log('over')"
            ondragleave="console.log('leave')"
            ondrop="console.log('drop')"
        >
            item2
        </li>
</ul>
```

Drag item1 onto item2.

firefox output:
```
start
enter
over
enter
leave
over
leave
end
```

tauri output:
```
start
end
```

> There is no Drop in this example.

### Platform and versions

```shell
Operating System - Arch Linux, version Rolling Release X64

Node.js environment
  Node.js - 17.3.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.3.2
  yarn - 1.22.17

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/src
/public
/.git
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - Set automatically by Vue CLI plugin
  devPath - Set automatically by Vue CLI plugin
  framework - Vue.js (Vue CLI)
  bundler - Webpack
```

### Additional context

My English isn't very good, please forgive me.

**Comment by JamesYeoman** [comment] 2022-01-25 16:50
Huh. That's really interesting. The app that I'm working on uses react and `react-beautiful-dnd` as a drag-and-drop framework. `react-beautiful-dnd` uses the html drag api under the hood, and I haven't noticed any bugs when dragging. Even the ondragover event fires correctly (I have a border on my drop component when a drag item is dragged over it).

Maybe try compiling [my app](https://github.com/JamesYeoman/dsrbmm/tree/app_settings) locally to see if it's something to do with your webview provider? Go into the `/src-tauri` folder and run `cargo tauri dev` (the vite dev server takes about 10 seconds once the tauri window appears before it emits the html).

If you drag any of the list items, you should see a green outline around the list itself, and if you drag the item off of the list, the outline should go and the list should collapse to fill the space that the item took. If that all works fine for you, then either react-beautiful-dnd lied to me about using the html drag-and-drop api under the hood, or something more weird is going on in configuration somewhere for you.

Either way, please update us when you have some answers

**Comment by LuXts** [comment] 2022-01-25 20:13
@JamesYeoman 
I have run your project, but something strange is happening. The program reloads repeatedly and very fast. i can't even distinguish the content. But you have suggested a good idea. I tried using `vuedraggable`. it worked. I'm guessing that the libraries modify some property, but I don't know much about that. I spent a few hours working on it, but didn't make much progress.

**This is a example.**

```html
// Here is the code that does not work.

<draggable> //  This is the component of vuedraggable.
    // Here is the same code working.
</draggable>
```


Also I tried to open the previous code using `epiphany` and found it had the exact same problem. This may be a problem with `webkit`. It has a different implementation of dragging than the others.

**Comment by JamesYeoman** [comment] 2022-01-26 10:15
@LuXts repeatedly loading? Really odd... maybe it's your arch installation that's the cause here. Maybe try running an ubuntu VM and running both the projects in that VM?

**Comment by amrbashir** [comment] 2022-01-30 17:19
This because of a conflict with `fileDropEnabled`. 
you have two options:
1. disable `fileDropEnabled` on your window but you won't get native file drop events.
2. keep `fileDropEnabled` and use a dragging component that has a fallback js implementation like `react-beautiful-dnd`.

Currently we are not aware of a fix to this conflict, so I am gonna close this issue.

**Closed as completed by amrbashir** 2022-01-30 17:19 UTC
Labels: type: bug

**Comment by FabianLars** [comment] 2022-01-30 17:23
@amrbashir quote from the initial issue:
> I have set "fileDropEnabled":false.

The weird/bad thing is that _some_ drag events work but not all.

**Comment by amrbashir** [comment] 2022-01-30 17:28
sorry, didn't see they tried "fileDropEnabled":false but anyhow, I doubt we can do anything here so I will keep the issue closed but please try running your example in epiphany browser and see if the events work correctly; if it does, let me know and I will reopen the issue.

**Comment by wesin** [comment] 2022-05-19 02:22
@JamesYeoman the main window is ok, but when you open a new window, then the drag is disable.

**Comment by w-ensink** [comment] 2022-06-04 16:24
I have this problem as well, using `react-dnd`. I also fixed it by setting `"fileDropEnabled": false`. When this option is left default, the drop callback is not called, all the other events are called like the should. When I use Safari, Chrome or Firefox the drop callback is called correctly. 

It says in the [documentation](https://tauri.studio/v1/api/config/#tauriconfig) that `"fileDropEnabled": false` is required on Windows only, but it seems to be required on macOS too...

**Comment by yogarasu** [comment] 2022-07-16 17:01
I had this problem when using react-dnd on my Mac, so I looked it up and arrived at this page and fixed the problem by setting fileDropEnabled to false.
I think it's okay to add notes to the document until you have a drastic solution.

**Comment by ghost** [comment] 2022-07-16 17:15
I ran into the same issue when I used react-dnd on my Mac
I didn't have to drop the file, so I was able to fix the problem by setting fileDropEnabled to false. thank you very much

**Comment by fpgaminer** [comment] 2022-10-19 21:26
Same here, onDrop events weren't firing.  Seems like a real bug to me?  Maybe this issue should be re-opened.

Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.10.0
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  ├─ assets
  └─ src

**Comment by Haprog** [comment] 2024-09-18 07:29
[Docs](https://tauri.app/v1/api/config/#windowconfig.filedropenabled) for `fileDropEnabled` says:

> Disabling it is required to use drag and drop on the frontend on Windows.

But this is definitely required on macOS too. I'm on macOS Sonoma 14.7 and was wondering why drag & drop does not work properly, but glad that I found this issue. After I set `fileDropEnabled: false` for my window it started working.

I'm using [react-mosaic](https://github.com/nomcopter/react-mosaic) for layout which internally uses `react-dnd` and the drag & drop for that did not work on macOS until I set `fileDropEnabled: false`.

**Comment by EverythingHello** [comment] 2024-10-15 10:24
Resolution：
https://v1.tauri.app/v1/api/config/#windowconfig.filedropenabled
https://v2.tauri.app/zh-cn/start/migrate/from-tauri-1/#tauri-%E9%85%8D%E7%BD%AE
v1.0：
```js
"app": {
    "windows": [
      {
         ...
        "fileDropEnabled": false
      }
    ],
```
v2.0：
```js
"app": {
    "windows": [
      {
         ...
        "dragDropEnabled": false
      }
    ],

**Comment by nekename** [comment] 2024-12-09 19:13
I have discovered this issue preventing my app functioning at all on Windows systems. While the solutions above do work I would like to point out that functionality was never impaired on Linux or macOS leading this problem to be unnoticed. If it is unfixable, the property should be disabled by default and some form of notice should be shown in the documentation of the property.

**Comment by gajendraxdev** [comment] 2026-03-22 09:02
I am experiencing a conflict between native and HTML5 drag-and-drop on Windows (Tauri 2.0)

dragDropEnabled: true: The native OS-level listener hijacks the window's DND system. This prevents the webview from receiving standard HTML5 dragover events, resulting in a persistent Forbidden (🚫) cursor for internal drags because the webview cannot preventDefault() on dragover to signal a valid drop target.
dragDropEnabled: false: The HTML5 DND works perfectly (internal drags work), but the OS level e.dataTransfer for external files is blocked/empty, making external file uploads impossible without custom Rust-to-JS event bridging.
It seems there is no 'hybrid' mode that allows the webview to handle internal DND while still receiving file paths from external drops without one side blocking the other.

I am droping a file for reference if `"dragDropEnabled": true`
![Image](https://github.com/user-attachments/assets/e39535f1-8d51-4363-ae26-851d3b2c3588)

**Comment by beaumontelliot757-arch** [comment] 2026-03-22 10:52
I'm running through the same problem is there any updates on this
