### ISSUE TITLE
[feat] http supports request progress and cancellation

### ISSUE THREAD

**Issue by varHarrie** [tauri-apps/tauri#5432] opened 2022-10-18 15:35 UTC
### Describe the problem

Provides the way to capture request progress and cancel requests.

### Describe the solution you'd like

Similar to axios [progress capturing](https://github.com/axios/axios#-progress-capturing) and [cancellation](https://github.com/axios/axios#cancellation).

```js
import { http } from '@tauri-apps/api';

const controller = new AbortController();

const response = await http.fetch(downloadUrl, {
    method: 'GET',
    responseType: ResponseType.Binary,
    signal: controller.signal,
    onUploadProgress (e) {
        console.log(e.loaded);
        console.log(e.total);
    },
    onDownloadProgress (e) {
        console.log(e.loaded);
        console.log(e.total);
    }
});

controller.abort();
```

**Comment by amrbashir** [comment] 2022-10-18 21:04
I made an attempt for this in [`0af01e6` (#5136)](https://github.com/tauri-apps/tauri/pull/5136/commits/0af01e6daa8365b6b11759106f96ec09e0daf915) but it is not very promising. I think in most cases the webview fetch api should be used in most scenarios and only use ours when dealing with CORS

**Comment by walidkorchi** [comment] 2023-04-25 13:39
> I made an attempt for this in [`0af01e6` (#5136)](https://github.com/tauri-apps/tauri/pull/5136/commits/0af01e6daa8365b6b11759106f96ec09e0daf915) but it is not very promising. I think in most cases the webview fetch api should be used in most scenarios and only use ours when dealing with CORS

The problem is that when using the [AbortController API](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) which is not supported, yet, with tauri HTTP API, you basically have to switch to the webview fetch API and then you're gonna be dealing CORS issues.
I'm not exactly sure how to fetch external resources if I get blocked between those.

**Comment by amrbashir** [comment] 2023-06-15 18:41
closing, this will be part of tauri-plugin-http, see https://github.com/tauri-apps/plugins-workspace/pull/428

**Closed as completed by amrbashir** 2023-06-15 18:41 UTC
Labels: scope: api.js, type: feature request, priority: 3 low, status: backlog
