### ISSUE TITLE
[bug] Tauri cant load WebVTT file with asset protocol.

### ISSUE THREAD

**Issue by promer94** [tauri-apps/tauri#6446] opened 2023-03-14 04:46 UTC
### Describe the bug

Tarui can't load WebVTT subtitles through asset protocol. 

When i try to load video and it subtitles using asset protocol.  I found that the video could be successfully loaded but not the subtitles.

<img width="1406" alt="CleanShot 2023-03-14 at 12 28 32@2x" src="https://user-images.githubusercontent.com/15878786/224893512-00fb9d9d-ed98-4727-a123-de84821dc182.png">
<img width="925" alt="CleanShot 2023-03-14 at 12 29 07@2x" src="https://user-images.githubusercontent.com/15878786/224894728-25828e39-d631-4f95-8b19-b7ab957a9ba9.png">

```json
{
  "tauri": {
    "allowlist": {
      "path": {
        "all": true
      },
      "dialog": {
        "open": true
      },
      "fs": {
        "all": true,
        "scope": [
          "$DOWNLOAD/**/*"
        ]
      },
      "protocol": {
        "all": true,
        "asset": true,
        "assetScope": [
          "$DOWNLOAD/**/*"
        ]
      }
    },
    "security": {
      "csp": "default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost; connect-src 'self' asset: https://asset.localhost"
    },
  }
}
```

### Expected behavior

Tarui should be able to load WebVTT subtitles through asset protocol.

### Platform and versions

```text
Environment
  › OS: Mac OS 13.2.0 X64
  › Node.js: 18.12.0
  › npm: 8.19.2
  › pnpm: 7.16.1
  › yarn: 1.23.0-20220130.1630
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost; connect-src 'self' asset: https://asset.localhost
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
```

**Comment by FabianLars** [comment] 2023-06-13 12:58
This _should_ be fixed by https://github.com/tauri-apps/tauri/pull/6390. According to https://github.com/tauri-apps/tauri/issues/6375#issuecomment-1561297660.

**Closed as completed by FabianLars** 2023-06-13 12:58 UTC
Labels: type: bug, status: needs triage

**Comment by mauritzn** [comment] 2023-06-17 21:51
This issue is unrelated to the asset protocol, rather this is caused by the overly strict CORS applied to captions compared to video files _(this is not a Tauri issues, rather a general browser issue)_, to fix this add `crossorigin="anonymous"` to the video element.

**Example:**
```html
<video src="..." controls width="500" height="300" crossorigin="anonymous">
  ...
</video>
```

**For more information:** [https://bugs.chromium.org/p/chromium/issues/detail?id=226019](https://bugs.chromium.org/p/chromium/issues/detail?id=226019)
