### ISSUE TITLE
[bug] Move the window between multiple screens, the window size is reset

### ISSUE THREAD

**Issue by lecepin** [tauri-apps/tauri#5239] opened 2022-09-19 17:11 UTC
### Describe the bug

The window size is configured in the `tauri.conf.json` file, and then modified by `appWindow.setSize(...)`.
When dragging a window to another screen, the size of the window becomes the value in `tauri.conf.json`.

### Platform and versions

```
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 18.3.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.64.0-nightly
  › cargo: 1.64.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.1.0 (outdated, latest: 1.1.1)
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.0,
  › tauri-build [RUST]: 1.1.0,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ .vscode
  └─ src
```

**Comment by amrbashir** [comment] 2022-09-19 17:51
duplicate of #5229

**Closed as not planned** 2022-09-19 17:51 UTC
Labels: type: bug, status: needs triage
