### ISSUE TITLE
[bug] Kaspersky identifies application as trojan

### ISSUE THREAD

**Issue by mschweimer** [tauri-apps/tauri#10302] opened 2024-07-16 14:44 UTC
### Describe the bug

Hello Tauri Community,

We are currently experiencing an issue where Kaspersky is incorrectly identifying our application as a Trojan. This problem has only arisen in the past week. Before that, everything was working without any issues.

We are receiving the following message from Kaspersky:
```
Description: Found
Type: Trojan
Name: HEUR:Trojan.Multi.Misslink.a
User: <username>
Object: reg:\HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
Reason: Expert analysis
Database date: 10.07.2024 18:11:00
```

We are using Kaspersky version: 12.5.0.539

Are you currently experiencing similar issues reported by other users or with other antivirus programs?

### Full `tauri info` output

```text
[✘] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 126.0.2592.102
    ✘ Couldn't detect any Visual Studio or VS Build Tools instance with MSVC and SDK components. Download from https://aka.ms/vs/17/release/vs_BuildTools.exe
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.19.0
    - yarn: 4.1.1
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3 (outdated, latest: 1.6.0)
    - @tauri-apps/cli [NPM]: 1.5.11 (outdated, latest: 1.6.0)
```

**Comment by FabianLars** [comment] 2024-07-16 15:16
We're currently tracking all (hopefully) false positives here https://github.com/tauri-apps/tauri/issues/2486 and on discord https://discord.com/channels/616186924390023171/1142423001002954854

We don't have much of a clue what's happening either and so far only recommended to report the false positives to the anti virus software and/or recompiling the app (if it's still happening, maybe backtrace the recent changes that may started it). For Kaspersky you can do this here: https://support.kaspersky.com/common/error/other/1870

Closing this as a duplicate of 2486 to keep the discussion in one place, thanks for the report though!

**Closed as not planned by FabianLars** 2024-07-16 15:16 UTC
Labels: type: bug, status: needs triage
