### ISSUE TITLE
cmd/c, cmd/v, cmd/x do not work onMacOS

### ISSUE THREAD

**Issue by sunhao8** [tauri-apps/tauri#2819] opened 2021-10-28 02:55 UTC
### **Describe the bug**
I've added a menu，but Keyboard shortcuts on MacOS such as cmd/c, cmd/v, cmd/x do not work in the Tauri window.
Right-click context menus, cmd/a, cmd/z do behave correctly 

### **To Reproduce**
1. cargo tauri dev
2. use keyboard shortcuts ( cmd/c, cmd/v, cmd/x do not work)

### **Expected behavior**
The respective keyboard shortcut to do its default function.

### **Platform and Versions (required):**

```
Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 14.18.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.10

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/bin
/node_modules
/webpack
/public
/src-tauri
/build
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:9091
  framework - React
  bundler - Webpack
```

**Comment by amrbashir** [comment] 2021-10-28 06:10
duplicate of #2397

**Closed as completed** 2021-10-28 06:10 UTC
Labels: status: invalid
