### ISSUE TITLE
Unhandled Promise Rejection: TypeError: window.__TAURI_IPC__ is not a function. 

### ISSUE THREAD

**Issue by yuanhaotian** [tauri-apps/tauri#8961] opened 2024-02-23 14:25 UTC
### Describe the bug

![屏幕快照 2024-02-23 下午10 22 52](https://github.com/tauri-apps/tauri/assets/36318960/b7d2eb87-7e95-48dc-abbd-d8ff8d698bc3)

This is the default code generated and cannot be run.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 10.14.6 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 18.9.1
    - pnpm: 8.15.3
    - yarn: 1.22.10
    - npm: 8.19.1

[-] Packages
    - tauri [RUST]: 1.6.0
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.10

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by syirilrakhulh** [comment] 2024-03-05 11:17
Any update for this problem?

**Comment by ChuTingzj** [comment] 2024-03-08 09:28
I meet the same problem

**Comment by FabianLars** [comment] 2024-03-08 09:35
Can you 2 also post the output of the `tauri info` command please?

**Comment by ChuTingzj** [comment] 2024-03-08 09:40
<img width="684" alt="截屏2024-03-08 17 40 04" src="https://github.com/tauri-apps/tauri/assets/89344405/419ff555-81f1-4ac6-a062-48fa633fa445">

**Comment by 8beeeaaat** [comment] 2024-03-09 03:58
```
% bun run tauri info 
$ tauri info
WARNING: Only one package manager should be used, but found npm and bun.
         Please remove unused package manager lock files, will use npm for now!

[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.4.0
    - npm: 10.2.4
    - bun: 1.0.18

[-] Packages
    - tauri [RUST]: 2.0.0-beta.10
    - tauri-build [RUST]: 2.0.0-beta.8
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 1.5.1 (outdated, latest: 1.5.3)
    - @tauri-apps/cli [NPM]: 2.0.0-beta.8

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React (Next.js)
    - bundler: Vite
```

**Comment by 8beeeaaat** [comment] 2024-03-09 04:07
I am having the same problem.
Only `__TAURI_INTERNALS__` is available in the main window and the @tauri-apps/api invoke() method is not available.

```
% bun run tauri info 
$ tauri info

[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 21.4.0
    - npm: 10.2.4
    - bun: 1.0.18

[-] Packages
    - tauri [RUST]: 2.0.0-beta.10
    - tauri-build [RUST]: 2.0.0-beta.8
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 2.0.0-beta.8

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React (Next.js)
    - bundler: Vite
```

![スクリーンショット 2024-03-09 13 00 19](https://github.com/tauri-apps/tauri/assets/4495546/005d4c4d-fe1f-41f5-96c8-bf23be176189)

**Comment by FabianLars** [comment] 2024-03-09 10:21
@8beeeaaat Your `@tauri-apps/api` package is outdated. If you update it to v2 beta it should work.

**Comment by FabianLars** [comment] 2024-03-13 15:02
I still can't reproduce this. I even dug out my macos catalina VM to almost match OP's tauri info output but it just works.

Anyone still seeing this, please upload the app that has this issue to github, and describe the exact steps you took that lead to this error.

Also, even though it doesn't seem apply to OP's screenshot, Tauri's ipc only works in actual tauri windows, so if you open your frontend in your normal browser then this error is to be expected...

**Comment by ChuTingzj** [comment] 2024-03-15 09:24
> I still can't reproduce this. I even dug out my macos catalina VM to almost match OP's tauri info output but it just works.
> 
> Anyone still seeing this, please upload the app that has this issue to github, and describe the exact steps you took that lead to this error.
> 
> Also, even though it doesn't seem apply to OP's screenshot, Tauri's ipc only works in actual tauri windows, so if you open your frontend in your normal browser then this error is to be expected...

I have resolved my problem!

**Comment by lienahu9** [comment] 2024-06-13 09:10
Uncaught (in promise) TypeError: window.__TAURI_IPC__ is not a function  ,这个问题解决了吗？

**Comment by Aeolun** [comment] 2024-07-21 13:25
I ran into this because I set all my Tauri packages to install the `latest` tag, but the Tauri `@tauri-apps/api` package doesn't use `latest` to mean the 2.0.0 version, and instead requires `next` to install the 2.0.0 version.

**Comment by FabianLars** [comment] 2024-07-22 11:12
I will close this issue since some people resolved their issues and the others didn't react to my messages. If you're still facing this issue, feel free to keep commenting (ideally with those instructions in mind https://github.com/tauri-apps/tauri/issues/8961#issuecomment-1994607248 ) or open a new issue.

**Closed as completed by FabianLars** 2024-07-22 11:12 UTC
Labels: type: bug, status: needs triage

**Comment by kvbops** [comment] 2024-11-06 04:53
I encountered the same problem and have not solved it. If someone has a solution, could you provide the solution?

**Comment by harikt** [comment] 2025-02-11 14:29
> Are you trying to open the app in a browser?

https://stackoverflow.com/a/76083271/487878
