### ISSUE TITLE
[bug] Linux HIDPI字体显示很小

### ISSUE THREAD

**Issue by trulyliu** [tauri-apps/tauri#12072] opened 2024-12-29 03:29 UTC
### Describe the bug

Linux HIDPI字体显示很小

### Full `tauri info` output

```text
Linux HIDPI字体显示很小
```

**Comment by FabianLars** [comment] 2024-12-29 16:42
I assume this is a duplicate of https://github.com/tauri-apps/tauri/issues/5600 - if not, please explain a bit more, ideally showing screenshots as well.

**Closed as not planned by FabianLars** 2024-12-29 16:42 UTC
Labels: type: bug, status: needs triage
