### ISSUE TITLE
Cannot Build Api Example Application on Debian 11

### ISSUE THREAD

**Issue by tataDan** [tauri-apps/tauri#2848] opened 2021-11-08 16:52 UTC
### Describe the bug

When attempting to build the examples/api application on Debian 11 (Bullseye) the build fails with an error message:

```
    cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'libappindicator3 library not found!', /home/daniel/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-libappindicator-sys-0.1.2/build.rs:6:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

```

### To Reproduce

Execute the command `yarn tauri dev` while in the example/api directory.

### Expected behavior

It was expected that the build would be successful.

### Platform and Versions (required):
```

Operating System - Debian, version 11 X64

Node.js environment
  Node.js - 17.0.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.0
  pnpm - Not installed
  yarn - 1.22.15

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/public
/src-tauri
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: asset: customprotocol: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:5000
  framework - Svelte
  bundler - Rollup

```
This issue might be related somewhat to #2799.

Debian 11 does not support libappindicator3.  However, I have the following packages installed:

`libayatana-appindicator3-1`

`libayatana-appindicator3-dev`

Might it be possible to change the configuration files to somehow substitute the libayatana for the libappindicator files to allow the build to succeed when libappindicator is not supported by the operating system?

**Comment by FabianLars** [comment] 2021-11-08 17:52
duplicate of #2647.
others reported that you can add `buster` to your `sources.list` as a workaround for now ([source on discord](https://discordapp.com/channels/616186924390023171/625037620996734986/890975495779409942))

**Closed as completed by FabianLars** 2021-11-08 17:52 UTC
Labels: status: invalid
