### ISSUE TITLE
[bug] tauri 2.0 android init failed due to path issues on Windows

### ISSUE THREAD

**Issue by paradox8599** [tauri-apps/tauri#8715] opened 2024-01-31 13:46 UTC
### Describe the bug

`cargo tauri android init` fails when the path is linked.
I am not sure what is the correct way to describe it, but basically it is a `dir` under path `A` but actually linked to path `B`, just like a symlink created by the command `ln -s B A/dir` on linux.

I found a working way but the problem is still there.

I have my repos in `E:\para\Repos`, and linked it to `C:\Users\para\Repos`:

```sh
$ ls -l C:\Users\para\Repos
lrwxrwxrwx    8 para     para            14 Nov 06 21:17 C:\Users\para\Repos -> E:/para/Repos/
```

First, I cd into `C:\Users\para\Repos\tapp`, and executing `tauri android init` gives me such error:

```
thread 'main' panicked at C:\Users\para\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-2.0.0-alpha.21\src\mobile\mod.rs:317:6:
called `Result::unwrap()` on an `Err` value: AssetDirOutsideOfAppRoot { asset_dir: "assets", root_dir: "C:\\Users\\para\\Repos\\tapp\\src-tauri" }
```

I looked into the mentioned file, and found a function takes the linked path `C:\Users\para\Repos\tapp` correctly at start, but translates it to the original path `E:\para\Repos\tapp` when actually comparing, which introduces inconsistency.

Then I tried to execute `tauri android init` from `E:\para\Repos`, which is the original path with no symlink, but got a different error:

```
thread 'main' panicked at C:\Users\para\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cargo-mobile2-0.8.0\src\util\path.rs:136:13:
internal error: entered unreachable code: `abs_src` and `abs_dest` have no common root
```
Looked into the code again, I guess it is using `C:\` as `abs_src` and `E:\` as `abs_dest` (or vice versa, they are different anyway), results in the `no common root` error.

Finally, I moved the project folder to a directory under  `C:\`, and it works.

### Reproduction

As described above.

Issue 1:
1. On windows, create a symlink and use it as the parent folder.
2. `cd` into the symlinked path, and create a tauri 2.0 app `cargo create-tauri-app --alpha` here, run `cargo tauri android init`

Issue 2:
1. On windows, create a tauri 2.0 app `cargo create-tauri-app --alpha` on non-C drive (I am not very sure about this, maybe system drive? or the drive rust/cargo is installed?)
2. run `cargo tauri android init`

### Expected behavior

```log
        Info "C:\\Users\\para\\.cargo\\bin\\cargo-tauri.exe" relative to "C:\\Users\\para\\Documents\\tapp\\src-tauri" is "..\\..\\..\\.cargo\\bin\\cargo-tauri.exe"
Generating Android Studio project...
        Info "C:\\Users\\para\\Documents\\tapp\\src-tauri" relative to "C:\\Users\\para\\Documents\\tapp\\src-tauri\\gen/android\\app" is "..\\..\\..\\"
victory: Project generated successfully!
    Make cool apps! 🌻 🐕 🎉
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 120.0.2210.144
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.77.0-nightly (5518eaa94 2024-01-29)
    ✔ cargo: 1.77.0-nightly (7bb7b5395 2024-01-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.19.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.21
    - tauri-build [RUST]: 2.0.0-alpha.14
    - wry [RUST]: 0.35.2
    - tao [RUST]: 0.24.1
    - tauri-cli [RUST]: 2.0.0-alpha.21
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.21

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Webpack
```

### Stack trace

1.

```text
thread 'main' panicked at C:\Users\para\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-cli-2.0.0-alpha.21\src\mobile\mod.rs:317:6:
called `Result::unwrap()` on an `Err` value: AssetDirOutsideOfAppRoot { asset_dir: "assets", root_dir: "C:\\Users\\para\\Repos\\tapp\\src-tauri" }
stack backtrace:
   0:     0x7ff648ffeae2 - <unknown>
   1:     0x7ff649028f4d - <unknown>
   2:     0x7ff648ff7ea1 - <unknown>
   3:     0x7ff648ffe90a - <unknown>
   4:     0x7ff649001ac9 - <unknown>
   5:     0x7ff649001785 - <unknown>
   6:     0x7ff649001fe4 - <unknown>
   7:     0x7ff649001eb9 - <unknown>
   8:     0x7ff648fff3e9 - <unknown>
   9:     0x7ff649001b86 - <unknown>
  10:     0x7ff64908a3c7 - <unknown>
  11:     0x7ff64908a903 - <unknown>
  12:     0x7ff6480f8af1 - <unknown>
  13:     0x7ff6482ab710 - <unknown>
  14:     0x7ff6480f17b4 - <unknown>
  15:     0x7ff6480baf90 - <unknown>
  16:     0x7ff6480b7827 - <unknown>
  17:     0x7ff6480bc6f6 - <unknown>
  18:     0x7ff6480b703c - <unknown>
  19:     0x7ff648fee8a2 - <unknown>
  20:     0x7ff6480b79ec - <unknown>
  21:     0x7ff64903c1b0 - <unknown>
  22:     0x7fff8f5e7344 - BaseThreadInitThunk
  23:     0x7fff911a26b1 - RtlUserThreadStart
```

2.

```text
thread 'main' panicked at C:\Users\para\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cargo-mobile2-0.8.0\src\util\path.rs:136:13:
internal error: entered unreachable code: `abs_src` and `abs_dest` have no common root
stack backtrace:
   0:     0x7ff648ffeae2 - <unknown>
   1:     0x7ff649028f4d - <unknown>
   2:     0x7ff648ff7ea1 - <unknown>
   3:     0x7ff648ffe90a - <unknown>
   4:     0x7ff649001ac9 - <unknown>
   5:     0x7ff649001785 - <unknown>
   6:     0x7ff649001fe4 - <unknown>
   7:     0x7ff649001e7b - <unknown>
   8:     0x7ff648fff3e9 - <unknown>
   9:     0x7ff649001b86 - <unknown>
  10:     0x7ff64908a3c7 - <unknown>
  11:     0x7ff64876de65 - <unknown>
  12:     0x7ff64832b855 - <unknown>
  13:     0x7ff6482ac520 - <unknown>
  14:     0x7ff6480f17b4 - <unknown>
  15:     0x7ff6480baf90 - <unknown>
  16:     0x7ff6480b7827 - <unknown>
  17:     0x7ff6480bc6f6 - <unknown>
  18:     0x7ff6480b703c - <unknown>
  19:     0x7ff648fee8a2 - <unknown>
  20:     0x7ff6480b79ec - <unknown>
  21:     0x7ff64903c1b0 - <unknown>
  22:     0x7fff8f5e7344 - BaseThreadInitThunk
  23:     0x7fff911a26b1 - RtlUserThreadStart
```

### Additional context

I am not sure if I should combine these together or create two separate issues.
Please let me know if I did anything wrong. Thank you!

**Comment by amrbashir** [comment] 2024-02-26 15:42
Closing as duplicate of https://github.com/tauri-apps/tauri/issues/8531

**Closed as completed by amrbashir** 2024-02-26 15:42 UTC
Labels: type: bug, status: needs triage
