### ISSUE TITLE
[feat] Implement automatic conversion of command argument types to typescript types

### ISSUE THREAD

**Issue by campbellcole** [tauri-apps/tauri#6275] opened 2023-02-15 04:56 UTC
### Describe the problem

Using structs and enums as parameters in a command function requires recreating the exact types in TypeScript. This repeats code and requires updating at least two places when your structs change.

For example, when working with SQLite in the Rust side of a Tauri app, each model must be duplicated into typescript to effectively work with it.

### Describe the solution you'd like

Structs and enums which implement JsonSchema from `schemars` can be effectively converted to TypeScript types using minimal effort. Once the JSON schemas have been generated, they can be converted into TypeScript types using the `json-schema-to-typescript` NPM package.

While this can be done manually with relatively low effort, it is still manual and is something I imagine could be built into the Tauri development tools. Svelte, for example, generates quite a few type declarations based on how you use things such as `+page.ts` files (which can export a `function load( { params } )`. This `params` destructure is automatically assigned a type by Svelte (perhaps this is unique to SvelteKit, I can't remember). Also, the return value of this function is automatically turned into a type and is available to the `+page.svelte` file corresponding to the aforementioned TypeScript file.

A system similar to this could be implemented by the context generator, since it is a proc macro that runs at compile time, it is perfectly positioned to run this entire process, which would enable incremental compiles with typing maintained between builds.

### Alternatives considered

Currently, this can be manually accomplished by writing an extra crate which has access to all of the types which you plan to use in your TypeScript project. A complete example is as follows:

```rs
use std::{fs, path::PathBuf};

use anyhow::Result;
use schemars::{schema_for, JsonSchema};

#[inline(always)]
fn write_schema<T: JsonSchema>(path: PathBuf) -> Result<()> {
    let schema = schema_for!(T);
    let output = serde_json::to_string_pretty(&schema)?;
    fs::write(path, output)?;

    Ok(())
}

fn main() -> Result<()> {
    let mut args = std::env::args();
    args.next(); // pop executable

    let output_dir = args
        .next()
        .expect("must supply output directory as an argument");

    let output_dir = PathBuf::from(output_dir);
    if !output_dir.try_exists()? {
        fs::create_dir_all(&output_dir)?;
    }

    write_schema::<StructNameHere>(output_dir.join("structnamehere.json"))?;

    Ok(())
}
```

This code will generate the schemas necessary for generating the types. Then, a secondary program can be run which generates these types:

```js
import * as fs from 'fs/promises';
import * as path from 'path';
import * as url from 'url';
import { compile } from 'json-schema-to-typescript';

const dirname = path.dirname(url.fileURLToPath(import.meta.url));

async function main() {
  let schemaDir = process.argv.at(2);
  if (!schemaDir) {
    throw 'Missing schema directory, must be passed as the first argument';
  }

  let schemaFiles = await fs
    .readdir(schemaDir)
    .then((read) => read.filter((x) => x.endsWith('.json')));

  let compiledTypes = new Set();

  for (let filename of schemaFiles) {
    let filePath = path.join(schemaDir, filename);
    let schema = await fs.readFile(filePath).then((f) => JSON.parse(f));
    let compiled = await compile(schema, schema.title, { bannerComment: '' });

    let types = compiled.split('export');
    for (let type of types) {
      if (!type) {
        continue;
      }

      compiledTypes.add('export ' + type.trim());
    }
  }

  let output = Array.from(compiledTypes).join('\n\n');
  let outputPath = path.join(dirname, 'src', 'lib', 'types.d.ts');

  try {
    let existing = await fs.readFile(outputPath);
    if (existing == output) {
      // skip writing if no changes,
      // prevents triggering a file watcher
      console.log('Schemas are up to date.');
      return;
    }
  } catch (err) {
    if (err.code !== 'ENOENT') {
      throw err;
    }
  }

  await fs.writeFile(outputPath, output);
  console.log(`Wrote TypeScript types to ${outputPath}`);
}

main().catch((e) => {
  console.error(e);
});
```

Then, these two programs can be executed sequentially using npm scripts:
```json
"gen:schema": "cargo run --manifest-path ./src-tauri/Cargo.toml --package build-schema -- ./schema",
"gen:types": "node generate-types.js ./schema",
"gen": "pnpm run gen:schema && pnpm run gen:types"
```

### Additional context

I am not very knowledgeable about the internal architecture of Tauri yet, though I do hope to familiarize myself with it eventually, so I apologize if this is out of scope or unachievable.

**Comment by FabianLars** [comment] 2023-02-15 08:53
I _think_ this counts as a duplicate of https://github.com/tauri-apps/tauri/issues/1514 🤔 
Thank you for the really extensive write up and example though!

**Comment by campbellcole** [comment] 2023-02-15 10:01
I agree that it's a duplicate. I should have searched better, my bad.

**Comment by nothingismagick** [comment] 2023-02-15 10:35
This might be useful:

https://lib.rs/crates/specta
https://lib.rs/crates/tauri-specta

**Comment by ajmcquilkin** [comment] 2023-02-22 20:59
Yeah I would second @nothingismagick, the `specta` crate seems super promising, especially given its integration within the [rspc](https://crates.io/crates/rspc) crate. I was about to file a feature request, glad someone beat me to it! Happy to help out with implementation if need be.

**Comment by amrbashir** [comment] 2023-04-27 15:49
Closing as duplicate of #1514

**Closed as not planned by amrbashir** 2023-04-27 15:49 UTC
Labels: type: feature request
