### ISSUE TITLE
[bug] alpha.14 failed to create webview: WebView2 error: WindowsError

### ISSUE THREAD

**Issue by fanchenio** [tauri-apps/tauri#7826] opened 2023-09-13 01:05 UTC
### Describe the bug

failed to create webview: WebView2 error: WindowsError(Error { code: HRESULT(0x8007139F), message: "组或资源的状态不是执行请求操作的正确状态。" })

I use pnpm create tauri-app. After creating a new project, run pnpm update, then enter the src-tauri directory, run cargo update, make sure it is the latest alpha version, and then use new Window to create a window on the page. This error will occur.

![gif](https://github.com/tauri-apps/tauri/assets/88647148/ec8acc49-afb6-4954-a71e-bb144696bca1)

### Platform and versions

```text
[✔] Environment
    
OS: Windows 10.0.19045 X64
  ✔ WebView2: 116.0.1938.76
  ✔ MSVC: Visual Studio Community 2022
  ✔ rustc: 1.70.0 (90c541806 2023-05-31)
  ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
  ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
  ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
node: 18.17.1
pnpm: 8.6.9
yarn: 1.22.19
npm: 8.7.0

[-] Packages
    
tauri [RUST]: 2.0.0-alpha.14
tauri-build [RUST]: 2.0.0-alpha.8
wry [RUST]: 0.33.0
tao [RUST]: 0.22.2
@tauri-apps/api [NPM]: 2.0.0-alpha.8
@tauri-apps/cli [NPM]: 2.0.0-alpha.14

[-] App
    
build-type: bundle
CSP: unset
distDir: ../dist
devPath: http://localhost:1420/
framework: Vue.js
bundler: Vite
```

**Comment by amrbashir** [comment] 2023-09-13 13:55
I wasn't able to reproduce this, could you make a minimal repro and link it here?

**Comment by fanchenio** [comment] 2023-09-14 01:14
> I wasn't able to reproduce this, could you make a minimal repro and link it here?

I used the create-tauri-app project and did not do any other unnecessary operations. Because crates and node_modules cannot be uploaded, I am not sure whether it can be reproduced. Here are my steps.

```
pnpm create tauri-app --alpha
cd tauri-app
pnpm install
pnpm update
cd src-tauri
cargo update
```

Then using `new Window` to create a new window will cause an error.

**Comment by budaestew** [comment] 2023-09-14 08:29
Same for me. I often get an error when creating a new multi-window in Windows. This used to be a non-issue, but has been happening since the recent WebView2 update.

This seems to be related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/3757

**Comment by Bukmopbl4** [comment] 2023-09-22 17:24
Starting from today, I suddenly began receiving the same error, and I haven't figured out how to fix it yet. The main builds work properly. New ones don't work at all when creating a second window. Neither release builds nor debug ones.

**Comment by amrbashir** [comment] 2024-01-18 03:17
Seems like this has been fixed on webview2 side, see https://github.com/tauri-apps/tauri/issues/8196#issuecomment-1897674662

Please update your webview2 version and try again.

**Closed as completed by amrbashir** 2024-01-18 03:17 UTC
Labels: type: bug, platform: Windows, status: needs triage
