### ISSUE TITLE
[Feature] How to custom default install directory to user directory instead of administrator directory?

### ISSUE THREAD

**Issue by halo-apps** [tauri-apps/tauri#4459] opened 2022-06-24 14:03 UTC
### Describe the bug

How to custom default install directory to user directory instead of administrator directory with segment or sth.?

### Platform and versions

```shell
1.0.0
```

**Comment by lucasfernog** [comment] 2022-07-04 17:40
Duplicate of #2319

**Closed as completed by lucasfernog** 2022-07-04 17:40 UTC
Labels: type: bug, status: invalid
