### ISSUE TITLE
[bug] tauri-2.0.rc can not run on windows7 32bit

### ISSUE THREAD

**Issue by Gofive** [tauri-apps/tauri#10834] opened 2024-08-30 09:40 UTC
### Describe the bug

tauri-2.0.rc can not run on windows7 32bit.
I have tested with 'yarn create tauri-app --rc'. It is crashed on my win7 bit32 ,dont have any problem hint, but tauri-v1 can run perfectly. 

### Full `tauri info` output

```text
null
```

**Comment by FabianLars** [comment] 2024-09-02 08:34
Do you see any error messages? Did you build the app with Rust 1.75 or below? (1.75 is the last version to properly support win7)

**Comment by Gofive** [comment] 2024-09-02 09:21
> Do you see any error messages? Did you build the app with Rust 1.75 or below? (1.75 is the last version to properly support win7)

release 32bit do not  have any error messages, rust 1.75.but tauri v1 can run on the win7 32bit device.

**Comment by FabianLars** [comment] 2024-09-02 09:22
Okay thanks. I don't have access to my VMs at the moment so it may take a while for me to get back to you.

**Comment by Gofive** [comment] 2024-09-04 06:54
> Okay thanks. I don't have access to my VMs at the moment so it may take a while for me to get back to you.

any update on this?

**Comment by eed-cn** [comment] 2024-10-12 02:20
I encountered the same issue. Windows 7 and 8 both don't work.

**Comment by FabianLars** [comment] 2024-10-12 19:01
Are we talking about `tauri dev` or the resulting app bundle (`tauri build` from another machine). If the latter, what was the _exact_ build command you used?

Furthermore, does anyone have any kind of error message for me? If not, did you try starting the exe from inside a Powershell/cmd.exe terminal? That sometimes helps.

**Comment by eed-cn** [comment] 2024-10-16 08:42
the same issue: #11381

**Comment by liigo** [comment] 2024-11-11 07:34
my issue: no `ProcessPrng` founded in `bcryptprimitives.dll`
tauri 2 + windows 7
I'v tried `embedBootstrapper`, still not working.

```
---------------------------
hi-tauri-dioxus.exe - 无法找到入口
---------------------------
无法定位程序输入点 ProcessPrng 于动态链接库 bcryptprimitives.dll 上。 
---------------------------
确定   
---------------------------
```

**Comment by eed-cn** [comment] 2024-11-11 07:40
@liigo 
Check out https://github.com/tauri-apps/tauri/issues/11381. 
It might be an issue related to the Rust version; Windows 7 only supports up to 1.77.2.
I’ve decided to give up on Windows 7—there are just too many issues with it.

----

查看 https://github.com/tauri-apps/tauri/issues/11381
可能是rust版本的问题 ,windows 7 最高支持到1.77.2
我已经放弃了windows 7, windows 7下面问题太多了

**Comment by liigo** [comment] 2024-11-12 01:51
@kingyang I see, thank you. 

明白了，谢谢。只因Tauri说了支持Win7，我想试试而已，不支持也无所谓啦。

https://tauri.app/distribute/windows-installer/#supporting-windows-7

**Comment by liigo** [comment] 2024-11-12 02:03
@kingyang I see, thank you. 

明白了，谢谢。只因Tauri说了支持Win7，我想试试而已，不支持也无所谓啦。

https://tauri.app/distribute/windows-installer/#supporting-windows-7

**Comment by FabianLars** [comment] 2024-11-27 19:14
Sooo, i assuming #11381 is really the same is this one here then it seems like the issue is this line https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/windows/dark_mode.rs#L24

I didn't test yet if skipping this line at runtime instead of removing it at compile time works, but if it does i think it'd be fine to disable it on windows 7 in 32bit binaries, that should be an extremely small userbase, right @amrbashir ?

**Comment by amrbashir** [comment] 2024-11-28 03:01
I don't think loading `uxtheme.dll` is the cause of the issue since we had that in v1 (https://github.com/tauri-apps/tao/blob/6f02103ca4869f082a0072e6ef0aa8424ec416bb/src/platform_impl/windows/dark_mode.rs#L163).

This issue maybe related to https://github.com/tauri-apps/tauri/issues/11674 and hopefully fixed by https://github.com/tauri-apps/tao/pull/1022/files

**Comment by eed-cn** [comment] 2024-11-28 04:20
@FabianLars  @amrbashir 
This is what I found during my test:
subclass_event_target_window throws exception on Windows 7 x86
https://github.com/tauri-apps/tao/issues/990

**Comment by FabianLars** [comment] 2024-11-28 09:25
> I don't think loading uxtheme.dll is the cause of the issue since we had that in v1 ([tauri-apps/tao@6f02103/src/platform_impl/windows/dark_mode.rs#L163](https://github.com/tauri-apps/tao/blob/6f02103ca4869f082a0072e6ef0aa8424ec416bb/src/platform_impl/windows/dark_mode.rs#L163)).

It was the last thing i commented out (or rather replaced with `HMODULE::Default()`) before it started to work. I'll double check again and record it. It's also the line windbg steered me into (or maybe not, that's shit too complicated for me)

> This issue maybe related to https://github.com/tauri-apps/tauri/issues/11674 and hopefully fixed by [tauri-apps/tao#1022 (files)](https://github.com/tauri-apps/tao/pull/1022/files)

I already tested the first commit and it didn't help. I'll test the new one from a few hours ago.

> This is what I found during my test:
> subclass_event_target_window throws exception on Windows 7 x86

Maybe there are multiple errors then 🤔

**Comment by FabianLars** [comment] 2024-11-28 11:14
Okay, double checked the first commit `2c03515` and it did not help, but the new one `1f62329` works.

**Comment by mcitem** [comment] 2024-11-30 04:16
Taurii 2 can be said to have almost no support for Windows 7
And Some dependencies are not supported by Rust 1.75.0 version.
how to create a lower version of TAURI that supports Windows 7, such as fixed TAURI v1?

**Comment by FabianLars** [comment] 2024-11-30 11:17
> Taurii 2 can be said to have almost no support for Windows 7

Why not? Apart from this 32-bit specific issue here tauri v2 works on my win 7 machine. We even downgraded the MSRV and conflicting dependencies to 1.77.2 a while back (the last version with built-in windows 7 support - yes, they changed it from 1.75 to that, i had it wrong for a while too).

> And Some dependencies are not supported by Rust 1.75.0 version.

Changing that to 1.77.2 all current deps should work though you may have to use cargo `update -p <pkg> --precise <ver>` to downgrade things (for me it was only bitstream-io)

> how to create a lower version of TAURI that supports Windows 7, such as fixed TAURI v1?

Yes, Tauri 1 should also still support windows 7.

----

That all said, don't expect Tauri to support windows 7 for that much longer. I expect us to drop it by v3 because it gets harder to support day by day.

**Comment by Gofive** [comment] 2024-12-09 02:04
will be fixed in next verison?

**Comment by FabianLars** [comment] 2024-12-09 09:55
should be, yes

**Closed as completed** 2024-12-09 10:16 UTC
Labels: type: bug, platform: Windows, status: needs triage

**Comment by jiangkaifree** [comment] 2025-05-09 01:42
I'm using Tauri v1, but my application still doesn't work on Windows 7 x86.， this is error message：not found processPrng ofbcryptprimitives.dll .
