### ISSUE TITLE
Frameless window is not frameless

### ISSUE THREAD

**Issue by lynxionxs** [tauri-apps/tauri#3466] opened 2022-02-15 13:56 UTC
On Ubuntu, when setting window decorations to false, there's an ugly black bar at the top. 

![frameless-tauri](https://user-images.githubusercontent.com/7606938/154075521-ec3ccc97-cd44-455a-b5e3-6eecbda3b3fd.png)

```
// tauri.conf.json

"allowlist": {
    "window": {
      "all": true, 
      "create": true
    }
}

"windows": {
    "resizable": false,
    "decorations": false
}
```
```
Operating System - Ubuntu, version 18.04 X64

Node.js environment
  Node.js - 15.14.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.7.6
  yarn - 1.22.5

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/node_modules
/src-tauri
/dist
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:4500
```

**Comment by decahedron1** [comment] 2022-02-27 20:29
Also noticing something similar to this on Windows, but only with transparent windows. The bar also appears to have acrylic effects.

![image](https://user-images.githubusercontent.com/61946759/155898663-cda40584-47a8-4783-b37e-bc4b9f8c50af.png)

**Comment by amrbashir** [comment] 2022-03-01 13:56
can you guys provide a minimal repro? I can't reproduce this.

**Comment by decahedron1** [comment] 2022-03-01 16:50
My repro is just the Tauri hello world application, but I set the window to transparent. I believe (99% sure) that this fixes my issue:

```rs
DwmSetWindowAttribute(hwnd, DWMWA_SYSTEMBACKDROP_TYPE, DWMSBT_DISABLE, 4);
```

Was playing around with the Tauri vibrancy plugin and accidentally used `DWMSBT_DISABLE`, which removed the bar. I also don't see the bar when enabling acrylics.

Not sure what could be causing OP's issue though...

**Comment by amrbashir** [comment] 2022-03-01 17:13
> My repro is just the Tauri hello world application, but I set the window to transparent. I believe (99% sure) that this fixes my issue:
> 
> ```rust
> DwmSetWindowAttribute(hwnd, DWMWA_SYSTEMBACKDROP_TYPE, DWMSBT_DISABLE, 4);
> ```
> 
> Was playing around with the Tauri vibrancy plugin and accidentally used `DWMSBT_DISABLE`, which removed the bar. I also don't see the bar when enabling acrylics.

This the tauri repo not the vibrancy plugin repo so I expected all issues here are related to tauri and not the plugin. Anyways, The helloworld in this repo doesn't have this black border at all. Tested on Win11 build 22000.

**Comment by decahedron1** [comment] 2022-03-01 17:15
The issue *is* related to Tauri. I'm experiencing this on the Tauri default hello world example without the vibrancy plugin even installed.

**Comment by amrbashir** [comment] 2022-03-01 17:19
Ah I misunderstood, anyways, Since Any Win11 build other than 22000 is not stable yet, I can't investigate any issues related to it and will consider this bug doesn't exist on Windows.

I will be investigating Linux when I switch to my Linux machine since that's where OP had the issue.

**Comment by amrbashir** [comment] 2022-05-02 11:27
do you still have this issue? I just tested on my Linux (not Ubuntu) and it works fine.

**Comment by lynxionxs** [comment] 2022-05-02 19:11
> do you still have this issue? I just tested on my Linux (not Ubuntu) and it works fine.

Not anymore. It only shows in development

**Comment by amrbashir** [comment] 2022-05-02 19:30
That's a bit better but I will wait for another Ubuntu user to confirm before looking into it.

**Comment by ghost** [comment] 2022-05-12 05:24
I'm on Fedora and encountering a similar-ish issue with this tiny line at the top of this transparent, frameless window. Maybe this could be helpful?
[image](https://i.imgur.com/k1uXpRz.png)

**Closed as completed** 2022-05-14 16:47 UTC
Labels: type: bug, status: upstream, platform: Linux

**Comment by amrbashir** [comment] 2022-05-14 16:48
fixed in https://github.com/tauri-apps/tao/pull/389 and will be available in the next release, if it happens again, let me know.
