### ISSUE TITLE
[feat] File drag and drop problem, why can't it be the same as Electron?

### ISSUE THREAD

**Issue by fanchenio** [tauri-apps/tauri#7551] opened 2023-08-04 02:09 UTC
### Describe the problem

Electron can obtain the path of the dragged file by listening to the drop event in the HTML page, and can manipulate the DOM element during this period, which is very important to me, because when the user drags the file to the window, I need to give a prompt, What element is the dragged file above, and then modify the style, but Tauri can’t, tauri://file-drop can’t operate HTML at all, and can’t get the coordinates, and the original drop event can’t get the full path of the file, please Are there plans to address this issue in the future?

### Describe the solution you'd like

The Drop event can get the file path.

**Comment by fanchenio** [comment] 2023-08-04 02:31
![1](https://github.com/tauri-apps/tauri/assets/88647148/03832fdf-260f-4fd9-82ff-2f1c0d669a8c)

Like this, you can manipulate HTML element styles while dragging and dropping files.

**Comment by ashutosh887** [comment] 2023-08-05 01:41
@fanchenio Let me work on this issue

**Comment by FabianLars** [comment] 2023-08-07 09:52
> Are there plans to address this issue in the future?

We're mainly waiting for Microsoft here actually: https://github.com/tauri-apps/wry/issues/904.

But at least adding the coordinates for tauri's own drag drop api is possible and the groundwork is already done, we just need to expose it.

Also, going to close this as a duplicate of https://github.com/tauri-apps/tauri/issues/3063

**Closed as not planned by FabianLars** 2023-08-07 09:52 UTC
Labels: type: feature request
