### ISSUE TITLE
[bug] [macOS] [assets://] can't play large size videos

### ISSUE THREAD

**Issue by kzhui125** [tauri-apps/tauri#8589] opened 2024-01-11 12:13 UTC
### Describe the bug

I am writing a local video player, but I find that `Tauri` can't play local large size video, it can only play small size videos.

Open the local file with Chrome or Edge works.

### Reproduction

[tauri-app.zip](https://github.com/tauri-apps/tauri/files/13902919/tauri-app.zip)

generate a large video for testing:

```sh
ffmpeg -f concat -i videos.txt -c copy output.mp4
```

change `src/app.rs`

<img width="621" alt="image" src="https://github.com/tauri-apps/tauri/assets/11925432/2faf384d-0db4-42b1-81ca-7ed5f1ed8938">

build and run

```sh
cd src-tauri
cargo tauri build
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 14.2.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0 (82e1608df 2023-12-21)
    ✔ cargo: 1.75.0 (1d8b05cdd 2023-11-20)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 16.17.1
    - yarn: 1.22.19
    - npm: 8.15.0

[-] Packages
    - tauri [RUST]: 1.5.4
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.9
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: ../dist
```
```


### Stack trace

_No response_

### Additional context

_No response_

**Comment by FabianLars** [comment] 2024-01-11 20:15
Duplicate of https://github.com/tauri-apps/tauri/issues/7355, thanks for the report and the reproduction example!

**Closed as not planned by FabianLars** 2024-01-11 20:15 UTC
Labels: type: bug, status: needs triage
