### ISSUE TITLE
[bug] "invoke" is occupying "cmd callback" and "error"

### ISSUE THREAD

**Issue by wyhaya** [tauri-apps/tauri#6897] opened 2023-05-08 07:09 UTC
### Describe the bug

When using `invoke`, we cannot pass parameters named `cmd` `callback` and `error`.

```js
invoke('plugin:name|test', {
    error: '123'
})
// Error
// [Error] JSON error: invalid type: string "123", expected usize at line 1 column 82
// Global Code (Script Element 20:1)
```

### Expected behavior

Any legal parameter can be passed

---

https://github.com/tauri-apps/tauri/blob/422b48179856504e980a156500afa8e22c44d357/tooling/api/src/tauri.ts#L90-L96

It appears that `invoke` merge `args` with `cmd` `callback`, and `error`, but these parameters are consumed by `invoke`, and we cannot use these keys anymore, or we will get an error.

These are very common names in javascript, but one gets a vague error.

I suggest releasing these names and changing them to something like `__TAURI_ERROR`, or reflecting this clearly in the documentation.

Tauri is great, thank you for all your efforts.

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 13.3.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
    ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
    ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.0.0
    - pnpm: 8.4.0
    - yarn: 1.22.19
    - npm: 9.6.4

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist/
    - devPath: http://localhost/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2023-05-08 07:13
Thanks for the extensive report! I'd count this as a duplicate of https://github.com/tauri-apps/tauri/issues/4875, but we can't fix this in 1.X since it would be a breaking change that would require users to sync the rust and js package versions to not break their IPC.

**Closed as not planned by FabianLars** 2023-05-08 07:13 UTC
Labels: type: bug, status: needs triage
