### ISSUE TITLE
[bug] Pixi.js in Svelte stopped to work after upgrading the application to RC

### ISSUE THREAD

**Issue by icewind** [tauri-apps/tauri#3438] opened 2022-02-13 14:35 UTC
### Describe the bug

I was playing with Tauri & Pixi.js for some time in beta 8. Everything was just fine. But after Tauri updated to RC Pixi.js doesn't work anymore. I tried it in updated to RC project as well as in the newly created one. 
The problem is only in Tauri. Running the same application in the browser works.
Tauri application starts(`npm run tauri dev`) with the white screen and an error in the logs

<img width="676" alt="Screenshot 2022-02-13 at 17 30 12" src="https://user-images.githubusercontent.com/575985/153757874-c2af02b3-b4ab-4d96-80a8-665985158bdc.png">
And it happens within pixi.js library
<img width="1172" alt="Screenshot 2022-02-13 at 17 32 58" src="https://user-images.githubusercontent.com/575985/153757958-c1dc620e-2c4b-4984-b1ba-a1f01db3d3d1.png">
Meanwhile if I run the app in the browser using `npm run dev` it is working just fine.

### Reproduction

Create an empty application using Svelte template
```
npx create-tauri-app
```
Install pixi.js 
```
npm i pixi.js
```
Disable `preferBuiltins` in the rollup config
```json
resolve({
    browser: true,
    dedupe: ["svelte"],
    preferBuiltins: false,
}),
```
Add the following code to `App.svelte`
```svelte
<script lang="ts">
    import { Application } from "pixi.js";
    import { onMount } from "svelte";

    onMount(() => {
        const container = document.querySelector(
            "#pixi-viewport"
        ) as HTMLElement;
        const application = new Application({
            autoStart: true,
            resizeTo: container,
            backgroundColor: 0x556677,
        });

        container.appendChild(application.view);
    });
</script>

<main>
    <div id="pixi-viewport" />
</main>

<style>
    #pixi-viewport {
        width: 80vw;
        height: 50vh;
    }
</style>
```

### Expected behavior

The application runs the same in browser and in Tauri

### Platform and versions

```shell
➜  test-pixi npm run tauri info

> test-pixi@1.0.0 tauri
> tauri "info"


Operating System - Mac OS, version 11.6.0 X64

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.2
  @tauri-apps/api - 1.0.0-rc.0

Global packages
  npm - 8.3.1
  pnpm - Not installed
  yarn - 1.22.17

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-apple-darwin

App directory structure
/node_modules
/public
/src-tauri
/.vscode
/src

App
  tauri.rs - 1.0.0-rc.1
  build-type - bundle
  CSP - default-src 'self'
  distDir - ../public
  devPath - http://localhost:8080/
  framework - Svelte
  bundler - Rollup
```
```


### Stack trace

```
[Error] TypeError: Attempted to assign to readonly property.
	(anonymous function) (bundle.js:5967)
	(anonymous function) (bundle.js:5971)
	Global Code (bundle.js:41687)
```

### Additional context

_No response_

**Comment by FabianLars** [comment] 2022-02-13 14:39
Duplicate of #3424, #3416, #3406.
We released a fix of it already, try running `cargo update` in your src-tauri dir (make sure your tauri-build dependency in Cargo.toml is updated too).
If that doesn't work you can manually set tauri.conf.json > security > freezePrototype to false. Note that you should freeze the prototype later if possible.

**Closed as completed by FabianLars** 2022-02-13 14:39 UTC
Labels: status: invalid

**Comment by icewind** [comment] 2022-02-13 14:41
Oh. Thank you. I see. I was looking in issues for pixi.js and math.js :) So missed those. 
Will try
