### ISSUE TITLE
[bug] Command+a shortcut not working on macOS with unstable feature enabled in Monaco Editor

### ISSUE THREAD

**Issue by xuchaoqian** [tauri-apps/tauri#12059] opened 2024-12-26 11:40 UTC
### Describe the bug

The `command+a `shortcut, which is typically used for "Select All" on macOS, does not function when the `unstable` feature is enabled in the Tauri application using the `Monaco editor`. The shortcut works as expected when the unstable feature is disabled.

### Reproduction

Clone the mini repo: [tauri-monaco](https://github.com/xuchaoqian/tauri-monaco)

1. Enable Unstable Feature: Ensure the `unstable` feature is enabled in your Tauri configuration.

2. Run the Application: Start the application using `pnpm tauri dev`

3. Attempt to Use command+a: Open the Monaco editor and try using `command+a` to select all text.

4. Disable Unstable Feature: Modify the configuration to disable the `unstable` feature.

5. Repeat Step 2 and 3: Run the application again and test `command+a`.

### Expected behavior

With the `unstable` feature enabled, `command+a` should select all text in the Monaco editor.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 13.7.2 x86_64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 20.12.2
    - pnpm: 9.15.0
    - yarn: 1.22.4
    - npm: 10.5.0
    - deno: deno 1.46.3

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 1.6.0
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
```

### Additional context

`Ctrl + a` works fine on Windows as expected.

**Comment by FabianLars** [comment] 2024-12-26 14:23
duplicate of https://github.com/tauri-apps/tauri/issues/9257

**Closed as not planned by FabianLars** 2024-12-26 14:23 UTC
Labels: type: bug, status: needs triage, scope: unstable flag
