### ISSUE TITLE
doubleclick top edge of the titlebar, the window is offset to the wrong position.[bug] 

### ISSUE THREAD

**Issue by Lucouse** [tauri-apps/tauri#4070] opened 2022-05-07 06:58 UTC
### Describe the bug

frameless window app, doubleclick top edge of the titlebar which has the attribute `data-tauri-drag-region`，the window is offset to the wrong position. ( sorry, because of network limitations, i can not upload pic of the bug)

### Reproduction

1. windows setting in tauri.conf.json decorations=false
2. create a custom titlebar which has attribute `data-tauri-drag-region`
3. doubleclick the top edge of titlebar

### Expected behavior

The upper and lower edges of the window extend to the edge of the screen.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19042 X64
  › Webview2: 101.0.1210.32
  › MSVC:
      - Visual Studio 15 ���ɹ��� 2017
      - Visual Studio ���ɹ��� 2019
  › Node.js: 14.17.6
  › npm: 6.14.15
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.4,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:8080/
  › framework: Vue.js (Vue CLI)    
  › bundler: Webpack

App directory structure
  ├─ .cid        
  ├─ .git        
  ├─ build       
  ├─ dist        
  ├─ doc
  ├─ node_modules
  ├─ src
  ├─ src-tauri   
  └─ test
```

**Comment by amrbashir** [comment] 2022-06-05 15:54
Can't reproduce, can you send a screenshot of this or better a video recording. Also a minimal repro would be great.

**Comment by lumenian** [comment] 2022-06-17 15:57
That's a duplicate of #2549, I believe.

**Closed as completed** 2022-06-17 17:17 UTC
Labels: type: bug, status: invalid
