### ISSUE TITLE
[feat] macOS -  Add a way to access Dock api

### ISSUE THREAD

**Issue by BillGoldenWater** [tauri-apps/tauri#4520] opened 2022-06-29 18:29 UTC
### Describe the problem

For show progress bars on dock icon.
For add item to right click menu for shortcut.
For listen "activate" event, for reopen window when all windows are closed.
etc.

### Describe the solution you'd like

some pseudocode

progress bar:
```rust
app.get_dock().unwrap().update_progress_bar(show: bool, percent: f32)
```

adding items:
```rust
app.get_dock().unwrap().setMenu(menu: Menu)
// like tauri::Menu
```

listen "activate" event:
```rust
app..get_dock().unwrap().addEventHandler(id: &str, |app_handle, event| match event {
  DockEvent::Activate {window_all_closed: bool} => {
    if (!window_all_closed) {
      show_main_window()
    }
  }

  _ => {}
})

app..get_dock().unwrap().removeEventHandler(id: &str)
```

**Comment by FabianLars** [comment] 2022-06-29 18:33
A little bit of context, i asked for this issue because i didn't find an existing issue for the **dock menu**.
On that note, #3084 is the tracking issue for the events and #4208 for the progress bar.

**Comment by amrbashir** [comment] 2022-06-29 19:02
duplicate of #2358

**Closed as completed by amrbashir** 2022-06-29 19:02 UTC
Labels: type: feature request

**Comment by FabianLars** [comment] 2022-06-29 19:03
Ah i thought that one is only about showing/hiding the icon and stuff, and not for the custom menu, my bad then.
