### ISSUE TITLE
[bug] Uncaught TypeError: Cannot assign to read only property 'valueOf' of object '#<Dayjs2>'

### ISSUE THREAD

**Issue by tomgao365** [tauri-apps/tauri#3424] opened 2022-02-12 13:50 UTC
### Describe the bug

When the project uses [dayjs](https://github.com/iamkun/dayjs), an error message appears.
```bash
index.js:151 
       Uncaught TypeError: Cannot assign to read only property 'valueOf' of object '#<Dayjs2>'
    at index.js:151:10
    at index.js:402:10
```

The error is triggered in the code below

https://github.com/iamkun/dayjs/blob/dev/src/index.js#L132

The latest Google Chrome and Microsoft Edge do not have this problem.

Because WebView2 uses strict mode? Is it possible to turn off this mode

https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/developer-guide#use-the-evergreen-runtime-recommended

If so, this might happen with other npm libraries as well.

### Platform and versions

```shell
Operating System - Windows, version 10.0.19044 X64
Webview2 - 98.0.1108.43
Visual Studio Build Tools:
   - Visual Studio ���ɹ��� 2019
   - Visual Studio Enterprise 2022

Node.js environment
  Node.js - 14.19.0
  @tauri-apps/cli - 1.0.0-rc.2
  @tauri-apps/api - 1.0.0-rc.0

Global packages
  npm - 6.14.16
  pnpm - 6.30.1
  yarn - 1.22.17

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc 

App directory structure
/.git
/.history
/.husky
/.idea
/config
/dist
/node_modules
/public
/scripts
/src
/src-tauri
/types

App
  tauri.rs - 1.0.0-rc.0
  build-type - bundle
  CSP - default-src 'self'
  distDir - ../dist
  devPath - http://localhost:3366/
  framework - Vue.js
PS D:\Work\atom\atom-tool>
```

**Comment by lucasfernog** [comment] 2022-02-12 13:56
Duplicate of #3406. Fix is being published.

**Closed as completed by lucasfernog** 2022-02-12 13:56 UTC
Labels: type: bug
