### ISSUE TITLE
[bug]  react-scripts doesn't not terminate on shutdown or Crtl-C interrupt for `npm run tauri dev`

### ISSUE THREAD

**Issue by SeedyROM** [tauri-apps/tauri#3577] opened 2022-03-01 01:08 UTC
### Describe the bug

When running the development command for tauri, the node react-scripts server never terminates and is orphaned.

### Reproduction

* `npm run tauri dev`
* Exit the window or sigint
* `lsof -n -i :3000 | grep LISTEN`
* `node    188304 USER   20u  IPv4 2590799      0t0  TCP *:hbci (LISTEN)`
* `npm run tauri dev` again
```
? Something is already running on port 3000. Probably:
  /usr/bin/node ${PROJECT_PATH}/node_modules/react-scripts/scripts/start.js (pid 196610)
  in {$PROJECT_PATH}

Would you like to run the app on another port instead? › (Y/n)
```

It always mangles the cursor as well in my terminal sessions, it disappears and answering Y or n to the prompt does nothing.

### Expected behavior

The `react-scripts` server should be shutdown when the window is closed or the dev server is stopped.

### Platform and versions

```shell
Operating System - Manjaro, version 21.2.2 X64

Node.js environment
  Node.js - 16.13.2
  @tauri-apps/cli - 1.0.0-rc.5
  @tauri-apps/api - 1.0.0-rc.1

Global packages
  npm - 8.3.0
  pnpm - 6.23.3
  yarn - 1.22.15

Rust environment
  rustup - 1.24.3
  rustc - 1.60.0-nightly
  cargo - 1.60.0-nightly
  toolchain - nightly-x86_64-unknown-linux-gnu 

App directory structure
/src
/node_modules
/build
/public
/src-tauri

App
  tauri - 1.0.0-rc.3 (no lockfile)
  tauri-build - no manifest (no lockfile)
  tao - no manifest (no lockfile)
  wry - no manifest (no lockfile)
  build-type - bundle
  CSP - unset
  distDir - ../build
  devPath - http://localhost:3000/
  framework - React
```

**Comment by amrbashir** [comment] 2022-03-01 01:11
duplicate of #2794

**Closed as completed by amrbashir** 2022-03-01 01:11 UTC
Labels: type: bug, status: invalid
