### ISSUE TITLE
The positioning problem of native color selector on win11

### ISSUE THREAD

**Issue by SnowGuest** [tauri-apps/tauri#3089] opened 2021-12-21 02:40 UTC
<input type="color"/>

After changing the position of the window, click the color selector again, the position of the selector is still the previous position

https://user-images.githubusercontent.com/59474029/146861626-8fd29125-1687-4cd4-beb1-102068426bbb.mp4

Operating System - Windows, version 10.0.22000 X64
Webview2 - 96.0.1054.62

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/.vscode
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:3000
  framework - Vue.js

**Comment by amrbashir** [comment] 2021-12-21 09:17
duplicate of #1911 , Microsoft needs to fix it on their own.

**Closed as completed** 2021-12-21 09:17 UTC
Labels: type: bug, status: invalid
