### ISSUE TITLE
[bug] compile failed on windows10 32bit env

### ISSUE THREAD

**Issue by nandy007** [tauri-apps/tauri#4321] opened 2022-06-12 12:56 UTC
### Describe the bug

when i  create a demo by https://github.com/tauri-apps/vue-cli-plugin-tauri on windows10 32bit env
i catch some error info:

```
memory allocation of 33554432 bytes failed
error: could not compile `windows`

Caused by:
  process didn't exit successfully: `rustc --crate-name windows --edition=2018 C:\Users\test\.cargo\registry\src\rsproxy.cn-3b63968a94b9a7b0\windows-0.37.0\src\lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg "feature=\"Win32\"" --cfg "feature=\"Win32_Devices\"" --cfg "feature=\"Win32_Devices_HumanInterfaceDevice\"" --cfg "feature=\"Win32_Foundation\"" --cfg "feature=\"Win32_Globalization\"" --cfg "feature=\"Win32_Graphics\"" --cfg "feature=\"Win32_Graphics_Dwm\"" --cfg "feature=\"Win32_Graphics_Gdi\"" --cfg "feature=\"Win32_System\"" --cfg "feature=\"Win32_System_Com\"" --cfg "feature=\"Win32_System_Com_StructuredStorage\"" --cfg "feature=\"Win32_System_DataExchange\"" --cfg "feature=\"Win32_System_Diagnostics\"" --cfg "feature=\"Win32_System_Diagnostics_Debug\"" --cfg "feature=\"Win32_System_LibraryLoader\"" --cfg "feature=\"Win32_System_Memory\"" --cfg "feature=\"Win32_System_Ole\"" --cfg "feature=\"Win32_System_SystemInformation\"" --cfg "feature=\"Win32_System_SystemServices\"" --cfg "feature=\"Win32_System_Threading\"" --cfg "feature=\"Win32_System_WinRT\"" --cfg "feature=\"Win32_System_WindowsProgramming\"" --cfg "feature=\"Win32_UI\"" --cfg "feature=\"Win32_UI_Accessibility\"" --cfg "feature=\"Win32_UI_Controls\"" --cfg "feature=\"Win32_UI_HiDpi\"" --cfg "feature=\"Win32_UI_Input\"" --cfg "feature=\"Win32_UI_Input_Ime\"" --cfg "feature=\"Win32_UI_Input_KeyboardAndMouse\"" --cfg "feature=\"Win32_UI_Input_Pointer\"" --cfg "feature=\"Win32_UI_Input_Touch\"" --cfg "feature=\"Win32_UI_Shell\"" --cfg "feature=\"Win32_UI_Shell_Common\"" --cfg "feature=\"Win32_UI_TextServices\"" --cfg "feature=\"Win32_UI_WindowsAndMessaging\"" --cfg "feature=\"alloc\"" --cfg "feature=\"default\"" --cfg "feature=\"implement\"" --cfg "feature=\"windows-implement\"" -C metadata=ae57e3ab66eb0656 -C extra-filename=-ae57e3ab66eb0656 --out-dir C:\jenkins\test\my-tauri-app\src-tauri\target\debug\deps -L dependency=C:\jenkins\test\my-tauri-app\src-tauri\target\debug\deps --extern windows_implement=C:\jenkins\test\my-tauri-app\src-tauri\target\debug\deps\windows_implement-c3df9b569dbf5075.dll --extern windows_i686_msvc=C:\jenkins\test\my-tauri-app\src-tauri\target\debug\deps\libwindows_i686_msvc-5b7f3d9b1cd07378.rmeta --cap-lints allow -L native=C:\Users\test\.cargo\registry\src\rsproxy.cn-3b63968a94b9a7b0\windows_i686_msvc-0.37.0\lib` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
warning: build failed, waiting for other jobs to finish...
🚀 A new version of Tauri CLI is avaliable! [1.0.0-rc.13]
error Command failed with exit code 101.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

how can i do?

### Platform and versions

```shell
C:\jenkins\test\my-tauri-app>yarn tauri info
yarn run v1.22.19
$ C:\jenkins\test\my-tauri-app\node_modules\.bin\tauri info

Environment
  › OS: Windows 10.0.19041 X32
  › Webview2: 102.0.1245.33
  › MSVC:
      - Visual Studio ���ɹ��� 2019
  › Node.js: 14.17.0
  › npm: 6.14.13
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-i686-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.11
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.12,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: Set automatically by Vue CLI plugin
  › devPath: Set automatically by Vue CLI plugin
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
Done in 30.53s.
```

**Comment by lucasfernog** [comment] 2022-06-12 21:43
```
memory allocation of 33554432 bytes failed
error: could not compile `windows`
```

Do you have enough memory to build this? Doesn't seem like a Tauri issue tbh.

**Comment by nandy007** [comment] 2022-06-13 07:12
> @lucasfernog 

My system mem is 4G.
And I try to set system env RUSTUP_UNPACK_RAM=4294967296, but the same error occured.
I think the mem is enough，but i do not know how to use.

**Comment by nandy007** [comment] 2022-06-13 08:33
@lucasfernog And I set the system mem from https://diamondlobby.com/tech-guides/how-to-allocate-more-ram-to-rust/ , the same error occured.

**Comment by lucasfernog** [comment] 2022-06-13 13:07
@wravery do you know what might be the cause for this issue?

**Comment by wravery** [comment] 2022-06-13 14:42
User processes can't see all of the RAM or address space. By default, I think they're limited to 2GB on 32-bit Windows, but there's an option you can set to get up to 3GB. It probably did run out of RAM in the compiler, or the address space was just too fragmented to perform the allocation, but either way, the solution is to perform the build from a 64-bit host.

**Comment by wravery** [comment] 2022-06-13 14:47
Actually, one other thing you could try is to limit the number of parallel build processes to 1. But IIRC, the last time I tested Windows 7 support I had to build on my 64-bit host OS and copy the binaries/packages to the 32-bit VM. So, I'm not sure limiting the parallel jobs is enough to make this work.

**Comment by nandy007** [comment] 2022-06-13 15:15
@wravery I got the error on windows 10 32bit, and i will try to build on windows 7 32bit.
I think that RAM usage is lower on windows 7.

**Comment by wravery** [comment] 2022-06-13 15:23
Just to clarify, I think the address space limitation is more important than the actual amount of RAM in use by the system. Virtual memory backed by the system page file (swap in Linux) should prevent RAM exhaustion. The OS can use the 4 GB of RAM to delay needing to swap, but if the address space in any process is exhausted or fragmented, there's nowhere to set the pointer for the allocation. So, I don't expect Windows 7 to work where Windows 10 didn't, but if you have that handy and it's not too much trouble it's worth a try.

**Comment by nandy007** [comment] 2022-06-13 15:34
@wravery thanks, I got it.
And next, I will try to build 32bit on windows10 64bit.

**Comment by lucasfernog** [comment] 2022-06-13 20:52
I'll close this since the proposed solution is to always build using a 64bit machine instead due to memory limitations.

**Closed as completed by lucasfernog** 2022-06-13 20:52 UTC
Labels: type: bug
