### ISSUE TITLE
[bug] File download works in Safari but does not work in Tauri on Mac

### ISSUE THREAD

**Issue by kirill-konshin** [tauri-apps/tauri#8452] opened 2023-12-20 22:02 UTC
### Describe the bug

Simple code to download as Blob does not work in Tauri, but works in Safari.

No dialog window to save file is shown, no errors in console.

I also tried `file-saver` NPM package, got error: `top frame not allowed to naigate to data URL` (also works well in Safari).

Safari version 17.1.2 (19616.2.9.11.12).

### Reproduction

```js
    const element = document.createElement("a");
    element.setAttribute("href", URL.createObjectURL(new Blob([text], { type: mimeType })));
    element.setAttribute("download", filename);

    element.style.display = "none";
    document.body.appendChild(element);

    element.click();

    document.body.removeChild(element);
```

### Expected behavior

File download dialog.

### Full `tauri info` output

```text
[⚠] Environment
    - OS: Mac OS 14.1.2 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.0 (79e9716c9 2023-11-13) (Homebrew)
    ✔ cargo: 1.74.0
    ⚠ rustup: not installed!
      If you have rust installed some other way, we recommend uninstalling it
      then use rustup instead. Visit https://rustup.rs/
    ⚠ Rust toolchain: couldn't be detected!
      Maybe you don't have rustup installed? if so, Visit https://rustup.rs/
    - node: 21.5.0
    - yarn: 4.0.2
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.5.9

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: public
    - devPath: http://localhost:3000/
```

**Comment by kirill-konshin** [comment] 2023-12-20 23:52
Found article https://davelage.com/posts/tauri-save-files/ which says "Possibly there [will be APIs](https://github.com/tauri-apps/wry/pull/530) that allow this to happen through the <a href="x" download="image.png"></a> browser interface in the future." — PR https://github.com/tauri-apps/wry/pull/530 has been merged, but looks like not yet supported.

**Comment by FabianLars** [comment] 2023-12-21 11:15
Duplicate of https://github.com/tauri-apps/tauri/issues/4633 - thanks for reaching out :)

**Closed as not planned by FabianLars** 2023-12-21 11:15 UTC
Labels: type: bug, status: needs triage
