### ISSUE TITLE
[bug][Tauri 2.0] Homebrew errors when running `tauri ios init` command on M1 Mac

### ISSUE THREAD

**Issue by widersky** [tauri-apps/tauri#6203] opened 2023-02-06 08:00 UTC
### Describe the bug

When executing the `yarn tauri ios init` command, an error appears as below:

![image](https://user-images.githubusercontent.com/45122321/216915850-cbb578b4-7f7f-477b-a2aa-37a5cac38906.png)

### Reproduction

1. Initialize Tauri 2.0 app with mobile workflow
2. Use `yarn tauri ios init` command
3. See the error

### Expected behavior

No errors - using Hombrew commands directly to install packages runs without any problems.

### Platform and versions

$ tauri info

Environment
  › OS: Mac OS 13.2.0 X64
  › Node.js: 16.19.0
  › npm: 8.19.3
  › pnpm: 7.18.2
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 2.0.0-alpha.2
  › @tauri-apps/api [NPM]: 2.0.0-alpha.0
  › tauri [RUST]: 2.0.0-alpha.3,
  › tauri-build [RUST]: 2.0.0-alpha.1,
  › tao [RUST]: 0.17.0,
  › wry [RUST]: 0.26.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
✨  Done in 9.17s.

**Comment by kxxoling** [comment] 2024-01-02 19:28
It says `Command "brew reinstall xcodegen" didn't complete successfully, exiting with code 1.: Command "brew reinstall xcodegen" didn't complete successfully`, just try to reinstall xcodegen again?

**Comment by slimandslam** [comment] 2024-02-20 00:57
Same thing here. $ brew reinstall xcodegen works fine.  Running xcodegen from the command line works fine. There is something wrong with the "yarn tauri ios init" command

**Comment by P5ina** [comment] 2024-02-21 10:30
Same issue, any workarounds?

**Comment by kasparv** [comment] 2024-02-21 21:01
I can confirm this happens on M2 too.

**Comment by ken0x0a** [comment] 2024-02-22 01:23
intel mac also.

**Comment by syirilrakhulh** [comment] 2024-02-22 09:17
Any solutions?

**Comment by lucasfernog** [comment] 2024-02-22 12:19
I'm working on the fix for this. Will be released today.

**Closed as completed** 2024-02-22 18:14 UTC
Labels: type: bug, status: needs triage

**Comment by kristianmandrup** [comment] 2024-03-13 23:39
It looks like the tauri CLI included in package.json by the project creator has not been updated to 2.0.
Try using this:

```json
  "devDependencies": {
    "@tauri-apps/cli": ">=2.0.0-beta.0",
  }
```

I figured it out by looking at https://github.com/atilafassina/quantum/blob/main/package.json based on this video https://www.youtube.com/watch?v=W539_PP4Y98
