### ISSUE TITLE
[bug] HTML `drop` event not firing

### ISSUE THREAD

**Issue by JulesGuesnon** [tauri-apps/tauri#5555] opened 2022-11-05 19:01 UTC
### Describe the bug

The `drop` event isn't triggered, and I tried in Safari to make sure and it works

### Reproduction

1. Create a new tauri app
2. Open the console
3. Paste and execute the following line: `location = "https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event"`
4. Go to the _Result_ section and the example isn't working

### Expected behavior

The `drop` event should be triggered

### Platform and versions

```
Environment
  › OS: Mac OS 12.6.0 X64
  › Node.js: 18.10.0
  › npm: 8.19.2
  › pnpm: 7.9.0
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.67.0-nightly
  › cargo: 1.67.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ temp.db
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
```

**Comment by FabianLars** [comment] 2022-11-05 19:27
Duplicate of a few issues like #3558, #3277 etc.

You need to disable Tauri's own file drop mechanism by either setting `fileDropEnabled` to `false` in tauri.conf.json or by using the respective Builder methods if you're dynamically creating the windows in code.
Alternatively you can use that file drag & drop mechanism (via the `tauri://file-drop` event) instead, if you only need the file _paths_ in your frontend and not the file contents.

**Closed as not planned by FabianLars** 2022-11-05 19:27 UTC
Labels: type: bug

**Comment by JulesGuesnon** [comment] 2022-11-05 19:56
Oh sorry, I searched through the issues, but I thought those weren't related, my bad. Thanks @FabianLars for the answer!
