### ISSUE TITLE
Tauri fails to detect `/usr/bin/node-18` subcommand

### ISSUE THREAD

**Issue by Lucifer25x** [tauri-apps/tauri#6520] opened 2023-03-21 18:42 UTC
### Describe the bug

When I try to run `pnpm tauri dev`, it fails and produces `error: The subcommand '/usr/bin/node-18' wasn't recognized` error.

### Reproduction

1. Open Terminal
2. Run `pnpm tauri dev` command

### Expected behavior

I expected the application to run successfully, without any error. Because I have `node-18` binary in my `/usr/bin` directory and it runs perfectly.

### Platform and versions

```text
`npm run tauri info` command is giving the same error.

OS: Fedora 37 Workstation
Node version: 18.5.0
Npm version: 9.4.0
Pnpm version: 7.26.3
Cargo version: 1.67.0
```

**Comment by amrbashir** [comment] 2023-03-21 19:01
duplicate of #6427

**Closed as not planned** 2023-03-21 19:01 UTC
Labels: type: bug, status: needs triage
