### ISSUE TITLE
[bug] Warning: altool has been deprecated

### ISSUE THREAD

**Issue by ImmaZoni** [tauri-apps/tauri#4839] opened 2022-08-02 21:20 UTC
### Describe the bug

When using the tauri bundler to sign a macOS application we are getting a warning about altool depreciation, no major bug just yet but wanted to document here so we can ensure this gets updated before becoming a breaking change. 

Full warning is 
```
Warning: altool has been deprecated and, starting in fall 2023, will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software.
```

### Reproduction

1. Configure full code-signing and notarization features for tauri bundler
2. build an application with code signing variables set
3. Error will come up in log, in the portion right after compile where it starts to work through code signing process

### Expected behavior

No errors

### Platform and versions

all versions

**Comment by FabianLars** [comment] 2022-08-02 21:20
Duplicate of https://github.com/tauri-apps/tauri/issues/4300.

**Comment by ImmaZoni** [comment] 2022-08-02 22:13
Refer to #4300

**Closed as completed** 2022-08-02 22:13 UTC
Labels: type: bug, status: needs triage
