### ISSUE TITLE
[feat] Shell scope option 'all'

### ISSUE THREAD

**Issue by BrilllianD** [tauri-apps/tauri#5841] opened 2022-12-15 14:00 UTC
### Describe the problem

Why Shell scope has no option 'all' or 'any' for run any programs by Command?

### Describe the solution you'd like

Make options for shell scope 'all' or without scope do not check the cmd in scope list

**Comment by LIMPIX31** [comment] 2022-12-25 18:04
I can't understand why it still doesn't work that way either. #5910

**Comment by JonasKruckenberg** [comment] 2022-12-26 08:22
Duplicate of #5910

**Closed as completed** 2022-12-26 08:22 UTC
Labels: type: feature request

**Comment by LIMPIX31** [comment] 2023-06-07 10:10
* https://github.com/tauri-apps/tauri/issues/5910

I fixed the shell plugin for tauri v2 a bit so that you can use it in tauri 1 and allow any commands. This is a temporary solution, but it preserves the tauri API, which ensures compatibility in the future.

Follow the instructions at https://github.com/tauri-apps/plugins-workspace/tree/v2/plugins/shell, but change the plugin repository:
```diff
- tauri-plugin-shell = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
+ tauri-plugin-unshell = { git = "https://github.com/LIMPIX31/tauri-plugin-unshell", branch = "unlocked" }
```
