### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by zebinfzu** [tauri-apps/tauri#6540] opened 2023-03-24 08:06 UTC
### Describe the bug

The touch event on windows will be caught by elastic overscroll first, making dragging invalid.

### Platform and versions

```text
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 111.0.1661.44
```

**Comment by FabianLars** [comment] 2023-03-24 12:45
As you noticed yourself this is a duplicate of #4746 so let's keep tracking it over there :)

**Closed as not planned by FabianLars** 2023-03-24 12:45 UTC
Labels: type: bug, status: needs triage
