### ISSUE TITLE
`maxWidth` used without `maxHeight` allows user to extend window beyond max width

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#8216] opened 2023-11-12 15:24 UTC
### Describe the bug

``` "windows": [   {     "fullscreen": false,     "resizable": true,     "title": "PassGuard",     "height": 700,     "width": 420,     "maxWidth": 420,     "minHeight": 600,     "minWidth": 420,     "contentProtected": true   } ] ``` 

is this intended or bug?

### Expected behavior

Setting `maxWidth` without `maxHeight` Should not allow user to expand window beyond max width.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 119.0.2151.58
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 8.10.2
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.5
    - @tauri-apps/api [NPM]: 1.5.1
    - @tauri-apps/cli [NPM]: 1.5.6

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../build
    - devPath: http://localhost:5173/
    - framework: Svelte
    - bundler: Vite
```

### Additional context

Please provide me work around for this untill this get fixed cause i need it urgently.

**Comment by amrbashir** [comment] 2023-11-13 15:36
duplicate of https://github.com/tauri-apps/tauri/issues/7075

**Closed as not planned by amrbashir** 2023-11-13 15:36 UTC
Labels: type: bug, status: needs triage
