### ISSUE TITLE
[feat] there are any chance to have the web platform supported?

### ISSUE THREAD

**Issue by Manuelito-Code** [tauri-apps/tauri#11704] opened 2024-11-15 23:01 UTC
### Describe the problem

i wish that Tauri become the all in one tool for create software for all platform in one single codebase, it would be awesome and handy for developers and companies.

### Describe the solution you'd like

i dont know

**Comment by FabianLars** [comment] 2024-11-16 17:30
Never say never, but there are no plans for the near future.

> all platform in one single codebase

which technically is already possible, you'd just need some logic that chooses between tauri apis and some web fallback. afaik there are already many apps doing exactly that.

Closing as a duplicate of https://github.com/tauri-apps/tauri/issues/8248

**Closed as not planned by FabianLars** 2024-11-16 17:30 UTC
Labels: type: feature request

**Comment by Manuelito-Code** [comment] 2024-11-16 17:34
Thank you for the help
