### ISSUE TITLE
[bug] Resizing doesn't work good on non decorative windows

### ISSUE THREAD

**Issue by CodeDoctorDE** [tauri-apps/tauri#9053] opened 2024-03-01 18:15 UTC
### Describe the bug

When resizing the app, the resizing options only appear on the top, top left and left border (but they are very buggy).
Showcase video:

https://github.com/tauri-apps/tauri/assets/20452814/034e268b-dbc4-41e4-8f1d-da4a43d9e534

### Reproduction

1. Create a tauri v2 project (using leptos template)
2. Change tauri.conf.json and add decoration:false to the window

This is my current github repo where the bug appears: https://github.com/LinwoodDev/Vulpine/tree/3fe1528756f982e1684558b43051d1b3a0db6c0f
(setup: `pnpm install` and then `cargo tauri dev`)

### Expected behavior

Simple resize cursor and functionality on the boundary of the window

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 122.0.2365.59
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.78.0-nightly (3246e7951 2024-02-19)
    ✔ cargo: 1.78.0-nightly (7b7af3077 2024-02-17)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 21.6.1
    - pnpm: 8.15.4
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 2.0.0-beta.8
    - tauri-build [RUST]: 2.0.0-beta.6
    - wry [RUST]: 0.37.0
    - tao [RUST]: 0.26.1
    - tauri-cli [RUST]: 2.0.0-beta.5
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 2.0.0-beta.6

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

### Stack trace

```text
No error found
```

### Additional context

Despite showing windows 10 in tauri info, I'm actually using the latest windows 11 23h2.
This is how it looks like in the dev tools:
![image](https://github.com/tauri-apps/tauri/assets/20452814/9df7426e-321f-41b8-9712-d0375e1a6d17)

Removing titlebar component and custom styles doesn't help

**Comment by yetone** [comment] 2024-03-02 07:03
same issue: https://github.com/tauri-apps/tauri/issues/9023

**Comment by CodeDoctorDE** [comment] 2024-03-02 08:09
Hmm, I think it describes something different.

1. In this issue it will be described that the width can only be adjusted, for me both can but only in the first corners.
2. In my example I don't use a data-tauri-drag-region element
3. In alt+tab the application will be displayed

![image](https://github.com/tauri-apps/tauri/assets/20452814/45de99cc-b7d2-4c6a-bd22-74b76c3dbaf3)

**Comment by yetone** [comment] 2024-03-02 17:17
‌‌`alt+tab` was caused by another issue, which I have already fixed.

**Comment by yetone** [comment] 2024-03-02 17:18
‌‌‌Yes, as I mentioned in that issue, only the top left corner can be dragged to resize. The bottom right corner cannot.

**Comment by amrbashir** [comment] 2024-03-04 01:11
duplicate of #9023

**Closed as not planned by amrbashir** 2024-03-04 01:11 UTC
Labels: type: bug, status: needs triage
