### ISSUE TITLE
[bug] el-calendar raise error: TypeError: date5.value.format is not a function

### ISSUE THREAD

**Issue by GuoBoy** [tauri-apps/tauri#6817] opened 2023-04-28 13:00 UTC
### Describe the bug

When I use vue3+element-plus, the el-calendar component raised error: TypeError: date5.value.format is not a function.

### Reproduction

1. component
```vue
<template>
  <el-calendar></el-calendar>
</template>
```
2. pnpm tauri dev
3. raise error on the console

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 112.0.1722.58
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 18.15.0
  › npm: 9.6.2
  › pnpm: 7.29.3
  › yarn: Not installed!
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: tauri-apps
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.3,
  › wry [RUST]: 0.22.0
```

### Stack trace

```text
calendar.vue:85  Uncaught (in promise) TypeError: date5.value.format is not a function
    at ReactiveEffect.fn (calendar.vue:85:56)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at get value [as value] (reactivity.esm-bundler.js:1171:39)
    at unref (reactivity.esm-bundler.js:1074:29)
    at Proxy.<anonymous> (calendar.vue:98:2)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
```

**Comment by amrbashir** [comment] 2023-05-02 15:22
I couldn't reproduce, I am using `ElementPlus` in a personal project and `el-calendar` worked just fine.

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as not planned by amrbashir** 2023-05-02 15:22 UTC
Labels: type: bug, status: needs triage
