### ISSUE TITLE
Comms broken since beta.3

### ISSUE THREAD

**Issue by DBTaylor** [tauri-apps/tauri#2342] opened 2021-08-02 19:44 UTC
Using tauri 1.0.0-beta.3 (or beta.4 or beta.5), invoke is throwing an error, and events triggered in the backend are not being emitted in the frontend. I've had to revert to beta.1 to get everything to work (couldn't seem to get beta.2 to build).

The issue doesn't occur when I run ```tauri dev```, only in the release build.

window.emit is returning Ok(). invoke returns ```ReferenceError: __TAURI_INVOKE_KEY__ is not defined```.

```
Operating System - Windows, version 10.0.17763 X64
Webview2 - 92.0.902.62

Node.js environment
  Node.js - 14.8.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - 1.0.0-beta.5

Global packages
  npm - 6.14.7
  yarn - Not installed

Rust environment
  rustc - 1.54.0
  cargo - 1.54.0

App directory structure
/.git
/.vscode
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - unset
  distDir - ./dist
  devPath - http://localhost:8081/
  framework - React
  bundler - Webpack
```

**Comment by amrbashir** [comment] 2021-08-02 19:46
try
1. remove `target` folder
2. run `cargo update` in `src-tauri`
3. build your app

**Comment by DBTaylor** [comment] 2021-08-02 19:56
> 
> 
> try
> 
>     1. remove `target` folder
> 
>     2. run `cargo update` in `src-tauri`
> 
>     3. build your app

just tried this, but I still have the issue

**Comment by amrbashir** [comment] 2021-08-02 20:04
can you provide a minimal repro ?

**Comment by DBTaylor** [comment] 2021-08-03 13:58
> 
> 
> can you provide a minimal repro ?

Minimalish:
https://github.com/DBTaylor/tauri-comms

**Comment by nothingismagick** [comment] 2021-08-03 14:33
Internally `invoke` now requires the use of the `__TAURI_INVOKE_KEY__` which is a random string injected into an IIFE or ESM at runtime. By doing this manually, you are not passing in that private value.

**Comment by amrbashir** [comment] 2021-08-03 14:38
The comms are working fine. I didn't see any errors related to `__TAURI_INVOKE_KEY__` and the reason why your front-end shows `Ok: undefined` is because your `test` function in `src-tauri/src/main.rs` doesn't return anything if you change it to something like this, it will work.
```rs
#[tauri::command]
fn test(window: Window) -> String {
	println!("test");
 	"test".into()
} 
``` 

Note: the repo had a typescript errors due to `@tauri-apps/api` package (which is fixed in dev and will be available in the next release), so I had to remove the typescript files from `node_modules/@tauri-apps/api`, and with this your front-end builds fine.

**Comment by DBTaylor** [comment] 2021-08-03 15:20
> 
> 
> The comms are working fine. I didn't see any errors related to `__TAURI_INVOKE_KEY__` and the reason why your front-end shows `Ok: undefined` is because your `test` function in `src-tauri/src/main.rs` doesn't return anything if you change it to something like this, it will work.
> 
> ```rust
> #[tauri::command]
> fn test(window: Window) -> String {
> 	println!("test");
>  	"test".into()
> } 
> ```
> 
> Note: the repo had a typescript errors due to `@tauri-apps/api` package (which is fixed in dev and will be available in the next release), so I had to remove the typescript files from `node_modules/@tauri-apps/api`, and with this your front-end builds fine.

@amrbashir, did the comms work fine for you in the release build? The "Ok: undefined" is expected, but only shows up for me in dev. In release I get the error.

I also saw the typescript error and fixed it locally. I didn't have an issue building after fixing it.

**Comment by DBTaylor** [comment] 2021-08-03 15:23
> 
> 
> Internally `invoke` now requires the use of the `__TAURI_INVOKE_KEY__` which is a random string injected into an IIFE or ESM at runtime. By doing this manually, you are not passing in that private value.

What do you mean by "by doing this manually"? I'm attempting to use the invoke function, and getting this exception in the release build. Is there some other mechanism to send commands?

**Comment by nothingismagick** [comment] 2021-08-03 15:40
@lucasfernog - am I mistaken, or is the `__TAURI_INVOKE_KEY__` injection not needed when `invoke("myFunc")` is called?

**Comment by lucasfernog** [comment] 2021-08-03 15:43
The injection is handled by the tauri protocol. I'll check this repo today.

**Comment by DBTaylor** [comment] 2021-08-03 15:45
@nothingismagick I think whatever sets __TAURI_INVOKE_KEY__ is failing in my release build for some reason. The invoke function is attempting to use it, but it doesn't exist.

**Comment by amrbashir** [comment] 2021-08-03 16:01
I can confirm it happens on release.

**Comment by lucasfernog** [comment] 2021-08-03 16:02
I'll take care of this. Might be some detection issue on the custom protocol resolver.

**Comment by lucasfernog** [comment] 2021-08-03 16:17
Found the issue. Our resolver ignores `<script></script>` tags assuming that it'll use the global tauri API (`window.__TAURI__`), and handles only scripts with `type="module"`. I'll make a PR changing that so your app will work.

**Closed as completed** 2021-08-03 16:53 UTC
Labels: type: bug
