### ISSUE TITLE
[bug] Resources are not found if Linux bundle is installed anywhere else other than /usr

### ISSUE THREAD

**Issue by absassi** [tauri-apps/tauri#9111] opened 2024-03-07 10:09 UTC
### Describe the bug

Relative paths to resources in Linux should resolve to the `../lib/<name>/` directory relative to the executable location, instead of assuming the executable is always in `/usr/lib/<name>/`.

This was fixed for AppImage bundle (#1308) by [looking for `$APPDIR` env var](https://github.com/tauri-apps/tauri/blob/1.x/core/tauri-utils/src/platform.rs#L179), and there's a "trick" to make it work when running from the deb bundle directory, by [checking whether it's running from `/data/usr/bin`](https://github.com/tauri-apps/tauri/blob/1.x/core/tauri-utils/src/platform.rs#L173). Otherwise, it is simply assumed that the application was installed in `/usr`, which is not necessarily true.

That trick of making it work from the bundle directory causes confusion, because if we try to run it from there after we build it, it appears that the application works from anywhere, but when it is actually placed somewhere else (like `/usr/local/` or `/opt`), resources are not found anymore.

It is work noting that, both for Windows and MacOS, the resource directory is resolved to a path relative to the executable. So, doing the same for Linux would be a simple change, and it could also work for the AppImage case without needing to special-case it, and of course, it would continue to work just as fine for standard bundle installations.

### Reproduction

* Create an application that accesses a resource file.
* Build the deb bundle.
* Copy the contents of the bundle data directory to somewhere else or unpack the deb file in a non-standard root.
* Run the application from the new location.

### Expected behavior

The application should find the resource file.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Ubuntu 22.04 X64
    ✔ webkit2gtk-4.0: 2.42.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.11.1
    - yarn: 1.22.21
    - npm: 10.2.4

[-] Packages
    - tauri [RUST]: 1.6.0
    - tauri-build [RUST]: 1.5.1
    - wry [RUST]: 0.24.7
    - tao [RUST]: 0.16.7
    - @tauri-apps/api [NPM]: 1.5.3
    - @tauri-apps/cli [NPM]: 1.5.10

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-03-07 10:17
Thanks for the report. This is a duplicate of #8679 though i really appreciate the extensive write up!

**Closed as not planned by FabianLars** 2024-03-07 10:17 UTC
Labels: type: bug, status: needs triage
