### ISSUE TITLE
"CoInitializeEx failed." when calling open() API function

### ISSUE THREAD

**Issue by virtualgraham** [tauri-apps/tauri#1054] opened 2020-10-17 10:27 UTC
On Windows 10 with WebView2. This is not an issue with Mac or Ubuntu.

When calling `open({directory: true})` I get the error `CoInitializeEx failed.`
When calling `open()` I get the error `Could not initialize COM.`

However, if I call  `open()`, ignore the error and THEN call `open({directory: true})`, it will work.

**Comment by AustinBreslinDev** [comment] 2021-01-31 16:39
I am getting the same issue. open() then open({directory: true}) does seem to work as a workaround. Altough this exact same setup, with the exact same codebase worked perfectly fine yesterday.

Update 1: Changing the javascirpt code to delay the invokation of open, seems to have resolved the issue for me. I wrapped the function that used open with another empty function. I'm not sure why this would resolve the issue. Functionally my code is absolutely identical.

Update 2: Appears to be an issue with upstream project https://github.com/webview/webview. Code comments say to invoke CoInitializeEx before calling CreateCoreWebView2EnvironmentWithOptions but in all references to this create web view 2 CoInitializeEx is never called. Could someone look into if this is correct? CoInitializeEx doesn't have to be called 100% of the time, but it is considered best practice to avoid errors according to https://stackoverflow.com/a/55754377

The searches I used to find these 2 methods.
* https://github.com/webview/webview/search?q=CoInitializeEx
* https://github.com/webview/webview/search?q=CreateCoreWebView2EnvironmentWithOptions

Taru info:

Operating System - Windows_NT(10.0.19042) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 10.23.1
  tauri.js - 0.14.1

Rust environment
  rustc - 1.49.0
  cargo - 1.49.0
  tauri-bundler - 0.9.4

Global packages
  NPM - 6.14.10
  yarn - Not installed

App directory structure
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.11.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:3000

**Comment by lucasfernog** [comment] 2021-02-14 20:54
I'm thinking about moving the dialog API to [tinyfiledialogs-rs](https://github.com/jdm/tinyfiledialogs-rs). Maybe that will help.

**Comment by nklayman** [comment] 2021-02-25 21:01
@lucasfernog now that we've switched to rfd, can this be closed?

**Comment by lucasfernog** [comment] 2021-02-25 21:02
I'm not sure that fixes the problem here, but I think we should close this issue and maybe @virtualgraham or @AustinBreslinDev can test it again after we release.

**Comment by rohanray** [comment] 2021-03-22 13:30
Facing same issue on Windows 10 with Tauri Dialog. `.save({})` method throws an error ` Could not initialize COM.`

**Comment by AustinBreslinDev** [comment] 2021-04-23 15:48
Hi @lucasfernog,

I haven't had time to do anything with my project since I reported this issue, has their been any updates to the project that so I can test this again?

And I honestly don't even think this is a problem with this project, I think it's a upstream issue. Like maybe the issue belongs in the upstreams Github Issues?

**Comment by lucasfernog** [comment] 2021-04-23 16:57
We changed almost everything so it would be great if you could try it again when you have time. We just released our beta rc.

**Comment by lucasfernog** [comment] 2021-04-24 21:19
Please reopen if you see the issue with our beta-rc release. I hope the move to [rfd](https://github.com/PolyMeilex/rfd) fixed the problem.

**Closed as completed by lucasfernog** 2021-04-24 21:19 UTC
Labels: type: bug

**Comment by andreszorro** [comment] 2021-04-28 16:20
Hello @lucasfernog. Is the Beta RC available in Yarn/NPM? I can only find version 0.14.1, and I can still see this issue using `.save({})`. Even with the `directory: true` reported workaround. This is happening, as reported in Windows 10 with WebView2.

**Comment by lucasfernog** [comment] 2021-04-28 16:21
We're going to merge the migration guide soon, but here's the docs: https://github.com/tauri-apps/tauri-docs/pull/198
@andreszorro

**Comment by lucasfernog** [comment] 2021-04-28 16:28
Seems like the migration guide is ready so i'll merge it. It'll be available on the docs site.

**Comment by andreszorro** [comment] 2021-04-28 18:16
Hi. After the update and migration, I am unable to reproduce the error. Seems like the new dependency worked like a charm. Thank you. Looking forward to seeing more of this project!
