### ISSUE TITLE
[feat] Inset Window Controls on macOS

### ISSUE THREAD

**Issue by appinteractive** [tauri-apps/tauri#8113] opened 2023-10-26 12:52 UTC
### Describe the problem

For a a lot of Apps on macOS the window controls an inset (see screenshot) so they have margin applied to them when the app uses a custom title bar.

**VS Code** (left), **Tauri** (right)
<img width="191" alt="grafik" src="https://github.com/tauri-apps/tauri/assets/432828/c5b0ef8a-e80e-484d-914c-b0624330d519">

You see the difference in the positioning. This is very common on macOS.

Faking the buttons is not a good solution as on macOS the buttons can be extended by other apps so for a native feeling its essential to have the native buttons in place.

### Describe the solution you'd like

Please provide a solution via the Tauri config to inset the native buttons (extended Titlebar)

**Comment by amrbashir** [comment] 2023-10-26 13:09
duplicate of https://github.com/tauri-apps/tauri/issues/4789

**Closed as not planned by amrbashir** 2023-10-26 13:09 UTC
Labels: type: feature request
