### ISSUE TITLE
[feat] Use messagepack instead of json for rpc

### ISSUE THREAD

**Issue by yuanyan3060** [tauri-apps/tauri#11989] opened 2024-12-17 10:00 UTC
### Describe the problem

json is not friendly to transmitting byte arrays. So I want to use messagepack instead of json for front-end and back-end interaction

### Describe the solution you'd like

Use messagepack instead of json for rpc

### Alternatives considered

other data format(bson or proto)

**Comment by FabianLars** [comment] 2024-12-18 18:56
Thank you for the request! I'll close this as a duplicate of https://github.com/tauri-apps/tauri/issues/7706.

Btw, you don't have to send json, you can send binary data as well (encoding/decoding the data yourself) https://v2.tauri.app/develop/calling-rust/#returning-array-buffers / https://v2.tauri.app/develop/calling-rust/#accessing-raw-request

**Closed as not planned by FabianLars** 2024-12-18 18:56 UTC
Labels: type: feature request
