### ISSUE TITLE
[feat] [v2] How to create a child web view

### ISSUE THREAD

**Issue by gusxodnjs** [tauri-apps/tauri#10079] opened 2024-06-18 04:45 UTC
### Describe the problem

In v1, I made a child webview as below. 
```rust
 #[cfg(target_os = "macos")]
 let _ = child_window.parent_window(main_window.ns_window().unwrap());

 #[cfg(windows)]
 let _ = child_window.owner_window(main_window.hwnd().unwrap());
```

In v2, I think I can make it using the [parent method](https://docs.rs/tauri/2.0.0-beta.22/tauri/webview/struct.WebviewWindowBuilder.html#method.parent). But it doesn't seem to work in a Windows environment.  And, it seems that the method used in v1 is no longer available. Is that right?

Also, I found [add_child](https://docs.rs/tauri/2.0.0-beta.22/tauri/window/struct.Window.html#method.add_child), which is currently an unstable function. However, this API does not support some of the methods that were previously supported by `webviewWindows` using `Window` and `Webview`. (For example, create a window border when creating webview.)

I'm using v2 and still want to create a child webview in a windows environment. Is `add_child` the only way?

### Describe the solution you'd like

-

**Comment by amrbashir** [comment] 2024-06-26 05:53
> In v2, I think I can make it using the [parent method](https://docs.rs/tauri/2.0.0-beta.22/tauri/webview/struct.WebviewWindowBuilder.html#method.parent). But it doesn't seem to work in a Windows environment. And, it seems that the method used in v1 is no longer available. Is that right?

`owner_window` have been renamed to just `owner`, seems like the documentation for Windows have failed to build but it exists.

You can still use [parent method](https://docs.rs/tauri/2.0.0-beta.22/tauri/webview/struct.WebviewWindowBuilder.html#method.parent) which is more cross-platform, not sure how is it not working for you, could you explain more? and provide a minimal repro

**Comment by gusxodnjs** [comment] 2024-07-01 01:58
@amrbashir
https://github.com/gusxodnjs/tauri-issues/tree/bug/parent-window

In Windows, the web views created by the parent method act like separate web views. Is there something I missed?
 
- macos
![Monosnap screencast 2024-07-01 10-58-11](https://github.com/tauri-apps/tauri/assets/27146546/7b57bb18-fbdf-49ee-a8fc-e3fcd5647b78)




- windows

https://github.com/tauri-apps/tauri/assets/27146546/8b65b13e-225a-497d-95f1-5e6ddf59df09

**Comment by amrbashir** [comment] 2024-07-02 06:23
The macOS behavior doesn't have any equivalent on Windows. The nearest thing is Owned windows, which you can read about their behavior here https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features#owned-windows

Closing as this is the intended behavior.

**Closed as not planned by amrbashir** 2024-07-02 06:23 UTC
Labels: type: question

**Comment by gusxodnjs** [comment] 2024-07-02 08:09
@amrbashir 
Thank you, but I think users expect the same behavior for each os when using the way the platform provides it. Can't it be abstracted in Tauri even if the specifications are different for each os? 
Finally, how do I implement macos-like behavior in a v2 window environment? Should I change the location of my child's window directly whenever the location of the parent window changes?

**Comment by amrbashir** [comment] 2024-07-03 01:47
> @amrbashir Thank you, but I think users expect the same behavior for each os when using the way the platform provides it. Can't it be abstracted in Tauri even if the specifications are different for each os? 

I understand the sentiment but not everything can be abstracted to behave the same on each OS.

> Finally, how do I implement macos-like behavior in a v2 window environment? Should I change the location of my child's window directly whenever the location of the parent window changes?

You can try to listen for parent move events and update the child location.

**Comment by gusxodnjs** [comment] 2024-07-03 02:51
@amrbashir 
Thank you for your reply.
