### ISSUE TITLE
Child webviews

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#2972] opened 2021-11-26 21:46 UTC
**Is your feature request related to a problem? Please describe.**
I'm trying to create a browser. Tauri fits all my needs except that it hasn't support for webviews in windows. See for example [Electron's BrowserView](https://www.electronjs.org/docs/latest/api/browser-view).

**Describe the solution you'd like**
Webview support.

**Comment by FabianLars** [comment] 2021-11-26 22:03
Duplicate of #2709.

**Closed as completed** 2021-11-26 22:04 UTC
Labels: type: feature request, status: invalid

**Comment by ghost** [comment] 2021-11-26 22:06
Oh! Sorry. Forgot to check for duplicates.
