### ISSUE TITLE
[mac updater]The app cannot be opened after it is updated

### ISSUE THREAD

**Issue by dibadibadiudiu** [tauri-apps/tauri#1883] opened 2021-05-21 03:38 UTC
**Describe the bug**
The app cannot be opened after it is updated.

I wonder if it has something to do with Mac's signature certificate (MAC applications must sign to update on electron), but I can't find Mac's signature document. What should I do if I want to publish it to the MAC app store?

my code:
```
try {
        const { appContext } = getCurrentInstance();
        const { shouldUpdate } = await checkUpdate();
        if (shouldUpdate) {
          await installUpdate();
          appContext.config.globalProperties.$alert(
            "update?",
            "has update!",
            {
              confirmButtonText: "ok",
              callback: async () => {
                await relaunch();
              },
            }
          );
        }
      } catch (error) {
        console.log(error);
      }
```

**To Reproduce**
1. If there is an update detected, click OK
2. app relaunch
3. app crash（The app will exit at the moment of opening and appear repeatedly）
4. Restart the computer, the app has been updated

yarn tauri info:

```
Operating System -M1 Mac OS, version 11.2.3 X64

Node.js environment
  Node.js - 15.8.0
  @tauri-apps/cli - 1.0.0-beta.1
  @tauri-apps/api - 1.0.0-beta.1

Global packages
  npm - 7.5.1
  yarn - 1.22.10

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/dist
/node_modules
/public
/src-tauri
/.git
/src

App
  tauri.rs - 1.0.0-beta.1
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline' 'self'
distDir - ../dist
devPath - http://localhost:8080
framework - Vue.js (Vue CLI)
bundler - Webpack
```

**Comment by lemarier** [comment] 2021-05-22 10:39
Thanks for reporting,

Is there any way i can test it?
Could you provide a old version of the app so we can trigger the update from our end and test the flow?

thanks!

**Comment by lemarier** [comment] 2021-05-24 14:43
I can't reproduce the issue

Could you share an example pls?

Thanks

**Comment by dibadibadiudiu** [comment] 2021-05-25 07:15
After installation, wait for a while until the system prompts you to install and click OK.

[0.0.1_x64.dmg.zip](https://github.com/tauri-apps/tauri/files/6537224/0.0.1_x64.dmg.zip)

**Comment by lemarier** [comment] 2021-05-31 12:10
Hi @dibadibadiudiu

The problem as you spotted first, comes from the binary signature. 
I'll make more tests from my side but I've done a little PR who could also help with the binary corruption with the latest macOS update.

I'll keep this issue open till we release it and got confirmation it works fine.

Also, signing the binary should prevent this out of the box.

Thanks

**Comment by lemarier** [comment] 2021-07-26 12:05
Hi @dibadibadiudiu 
I'll close this issue as it's been fixed in the latest version.
If you still encounter problems, please let us know.

Thanks

**Closed as completed by lemarier** 2021-07-26 12:05 UTC
Labels: type: bug
