### ISSUE TITLE
Generating typescript definitions on compilation

### ISSUE THREAD

**Issue by thomas-k-cameron** [tauri-apps/tauri#6812] opened 2023-04-27 15:29 UTC
### Describe the problem

Currently, you need to specify the name of the command you want to invoke by passing the name of the cmd in string.
e.g. 
```typescript
await invoke("greet", { name });
```

I think it would be more empowering if the macro could generate typescript interface on compilation.
e.g. 
```typescript
function greet(name: string): Promise<string> {
  return invoke("greet", { name });
}
```

```rust
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![greet, greet2])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

I've seen some library do this and it really helps avoid small basic mistakes like typos.

### Describe the solution you'd like

Generate typescript definition during compilation from macro(`tauri::generate_handler` or `tauri::command`).

### Alternatives considered

```typescript
function invoke(cmd: "greet" | "greet")
```

However, this way it we can't check if the parameters are right.

### Additional context

If you wouldn't mind, I'd love to implement this feature.

**Comment by amrbashir** [comment] 2023-04-27 15:49
Closing as duplicate of #1514

**Closed as not planned by amrbashir** 2023-04-27 15:49 UTC
Labels: type: feature request
