### ISSUE TITLE
NSIS Installer - Process Still Running Error and Cannot Kill Process

### ISSUE THREAD

**Issue by B0NECH0P** [tauri-apps/tauri#6984] opened 2023-05-17 20:10 UTC
### Describe the bug

Hello!

Our application is utilizing the auto-start plugin and runs from the task tray (which we're using an invisible window to keep alive), noticing that if we try to manually install updates on top, the NSIS installer warns that the process is still running and when it attempts to kill the process, it fails.

When you force quit the app from task manager and even when you uninstall, the NSIS installer still believes the process is running and "fails" to kill the process.

![image](https://github.com/tauri-apps/tauri/assets/61718417/bee42101-0d5e-4b8d-9c69-c39000c42924)
This is the error message that is displayed when attempting to kill the process from the NSIS installer, retrying throws the same error.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22000 X64
    ✔ WebView2: 113.0.1774.42
    ✔ MSVC:
        - Visual Studio Community 2022
        - Visual Studio Build Tools 2019
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.9.0
    - yarn: 1.22.19
    - npm: 8.19.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1
```

**Comment by amrbashir** [comment] 2023-05-18 01:21
> which we're using an invisible window to keep alive

you don't need to do that, see https://tauri.app/v1/guides/features/system-tray#preventing-the-app-from-closing

**Comment by amrbashir** [comment] 2023-05-18 01:37
Could you make a repro or at least clear steps to reproduce? The kill function seems to be working fine for me.

**Closed as not planned** 2024-12-05 14:09 UTC
Labels: type: bug, platform: Windows, status: needs repro
