### ISSUE TITLE
[bug] Failed to load resource using `asset:` or `https://asset.localhost` protocol

### ISSUE THREAD

**Issue by danloh** [tauri-apps/tauri#6962] opened 2023-05-14 16:55 UTC
### Describe the bug

I want to display local image in the app built with Tauri. So I generate the local image path using `asset:` or `https://asset.localhost` protocol. For example:

* on Windows: `https://asset.localhost/D:/doc/example.png`,
* on Ubuntu22.04 / macOS:  `asset:///home/pictures/example.png`.

It cannot display but with the error message:

* on Windows: `Failed to load resource: the server responded with a status of 403`;
* on Ubutun/macOS: `Failed to load resource: Could not get uri.`

**Tauri version related** 

On windows, using Tauri 1.2.1, it works well, but not on 1.2.2+ or 1.3.0. On Ubuntu/macOS, does not work on any Tauri version. 

### Reproduction

The repo: https://github.com/mdSilo/mdSilo-app

### Expected behavior

Can dispaly the local image using `asset:` or `https://asset.localhost` protocol

### Platform and versions

```text
* OS: Windows 10.0.19044 X64
 › Webview2: 113.0.1774.35
 › MSVC:
 - Visual Studio Build Tools 2022
 › Node.js: 18.8.0
 › npm: 8.18.0
 › pnpm: 8.5.0
 › yarn: 1.22.19
 › rustup: 1.26.0
 › rustc: 1.69.0
 › cargo: 1.69.0
 › Rust toolchain: stable-x86_64-pc-windows-msvc


* OS: Ubuntu 22.04 X64
  ✔ webkit2gtk-4.0: 2.38.6
  ✔ rsvg2: 2.52.5
  ✔ rustc: 1.68.2 (9eb3afe9e 2023-03-27)
  ✔ Cargo: 1.68.2 (6feb7c9cf 2023-03-26)
  ✔ rustup: 1.25.2 (17db695f1 2023-02-01)
  ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
  * node: 18.16.0
  * pnpm: 8.5.0
  * yarn: 1.22.18
  * npm: 9.5.1
```

### Additional context

in `tauri.conf.json`:

```
"allowlist": {
     ...
      "protocol": {
		"all": true,
	       "asset": true,
		"assetScope": ["*"]
	}
 },

"csp": "default-src blob: data: filesystem: wss: https: tauri: 'unsafe-inline' asset: https://asset.localhost 'self'; script-src 'self'"
```

**Comment by FabianLars** [comment] 2023-05-15 10:21
1.2.2 had a security related fix which also changed how glob patterns are applied. `*` is not recursive anymore. Can you try again using `**` instead?

**Comment by tranxuanthang** [comment] 2023-05-16 19:45
I have the same issue on up-to-date Arch Linux.

![image](https://github.com/tauri-apps/tauri/assets/15942946/7e2c6fdf-fcd3-45bb-8434-94b0aa72c344)

Error log from webview:

```
[Log] asset://localhost/%2Frun%2Fmedia%2Fthang%2FDATA2%2FMusic%2FTaylor%20Swift%2FTaylor%20Swift%20-%20Red%20(Deluxe%20Edition)%20(2018)%2F06.%20Taylor%20Swift%20-%2022.flac (player.js, line 16)
[Error] Origin http://localhost:1420 is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] Failed to load resource: Origin http://localhost:1420 is not allowed by Access-Control-Allow-Origin. Status code: 200 (/run/media/thang/DATA2/Music/Taylor Swift/Taylor Swift - Red (Deluxe Edition) (2018)/06. Taylor Swift - 22.flac, line 0)
[Error] XMLHttpRequest cannot load asset://localhost/%2Frun%2Fmedia%2Fthang%2FDATA2%2FMusic%2FTaylor%20Swift%2FTaylor%20Swift%20-%20Red%20(Deluxe%20Edition)%20(2018)%2F06.%20Taylor%20Swift%20-%2022.flac due to access control checks.
```

`npm run tauri info`:

```
> tauri info


[✔] Environment
    - OS: Arch Linux Unknown X64
    ✔ webkit2gtk-4.0: 2.40.1
    ✔ rsvg2: 2.56.0
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 18.16.0
    - npm: 9.5.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.1
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost; media-src 'self' asset: https://asset.localhost
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

Seems like it is related to #2327 and #4496 and should be fixed in webkit2gtk 2.34.0, why are we still facing this issue?

**Comment by FabianLars** [comment] 2023-05-17 08:02
@tranxuanthang This is _not_ the same issue. Please open a new issue with a reproduction example. (Yours _could_ potentially also be related to https://github.com/tauri-apps/tauri/issues/3725 i guess?)

**Closed as not planned** 2023-05-17 11:48 UTC
Labels: type: bug, status: needs triage

**Comment by danloh** [comment] 2023-05-19 18:43
> 1.2.2 had a security related fix which also changed how glob patterns are applied. `*` is not recursive anymore. Can you try again using `**` instead?

Thanks, using `**`  works on Windows  for Tauri 1.2/1.3.  but no solution on Mac/Linux.

**Comment by amrbashir** [comment] 2023-05-19 22:38
for mac and Linux, unless your path contains a leading `.` you'll need to wait for 1.4 where [`require_literal_leading_dot`](https://github.com/tauri-apps/tauri/commit/acc36fe1176cc8aa9063bde932abeb94796c5c72) can be disabled, otherwise it should be working.

**Comment by samsze1** [comment] 2023-06-13 13:09
Not sure if this is related. But I am trying to load some images stored locally inside `~/Documents` but I am encountering 403 error

<img width="689" alt="image" src="https://github.com/tauri-apps/tauri/assets/115963458/4e0e6086-a58f-405f-9d43-a871f0c58861">

<img width="469" alt="image" src="https://github.com/tauri-apps/tauri/assets/115963458/2ed1f962-290c-477f-ab0f-9195d1590b77">

<img width="220" alt="image" src="https://github.com/tauri-apps/tauri/assets/115963458/b0d5885d-9285-4377-8ee6-fbb2f3344cc0">

Thank you 🙏

**Comment by samsze1** [comment] 2023-06-13 13:15
> Not sure if this is related. But I am trying to load some images stored locally inside `~/Documents` but I am encountering 403 error
> <img alt="image" width="689" src="https://user-images.githubusercontent.com/115963458/245485289-4e0e6086-a58f-405f-9d43-a871f0c58861.png"> <img alt="image" width="469" src="https://user-images.githubusercontent.com/115963458/245485592-2ed1f962-290c-477f-ab0f-9195d1590b77.png"> <img alt="image" width="220" src="https://user-images.githubusercontent.com/115963458/245485694-b0d5885d-9285-4377-8ee6-fbb2f3344cc0.png">
> 
> Thank you 🙏

Ok I realised that the problem is that the asset scope glob pattern needs to be recursive (`"**/*"`)
