### ISSUE TITLE
[bug] The tauri sidecar failed to execute binary

### ISSUE THREAD

**Issue by heningyuan6256** [tauri-apps/tauri#7100] opened 2023-06-01 00:47 UTC
### Describe the bug

The tauri sidecar failed to execute binary
<img width="780" alt="截屏2023-06-01 上午8 39 08" src="https://github.com/tauri-apps/tauri/assets/64188102/3262a1e5-ad51-4f5b-a66d-334fb5a6c8fa">
<img width="803" alt="截屏2023-06-01 上午8 42 45" src="https://github.com/tauri-apps/tauri/assets/64188102/fe578070-99ee-4953-9721-2c3fdafccc89">
<img width="762" alt="截屏2023-06-01 上午8 43 29" src="https://github.com/tauri-apps/tauri/assets/64188102/97574953-8e0f-4587-8231-dfb3b7aab9b0">

### Platform and versions

```text
platform：windows
versions:  tauri 1.2.0
```

**Comment by amrbashir** [comment] 2023-06-05 14:15
I'll temporarily close this due to the lack of enough information.

Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and fill the appropriate information fields to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as not planned by amrbashir** 2023-06-05 14:15 UTC
Labels: type: bug, status: needs triage
