### ISSUE TITLE
`pnpm run tauri info` panic

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#2931] opened 2021-11-22 03:04 UTC
### **Describe the bug**
Running `pnpm tauri info` panics, same thing with `npm run tauri info`.

### **To Reproduce**
1. Go to existing project, Vite with SSR for instance;
2. In the template project, install @tauri-apps/cli with `pnpm i -D`;
3. In the template project, install @tauri-apps/api with `pnpm i`;
4. In the template project, execute `pnpm tauri init`;
5. Follow steps to initialize the project;
6. In the template project, execute: `npm run tauri info`;
7. See error.

"In the template project" refers to the base project, before tauri and peer dependencies were installed, the aforementioned project, "Vite with SSR", used as an example, initialized with `pnpm init vite-plugin-ssr@latest`. See: https://vite-plugin-ssr.com/scaffold

### **Expected behavior**
Log environment informations, as described, with example in ["Tauri Docs - Make sure everything is setup properly"](https://tauri.studio/en/docs/usage/development/integration/#3-check-tauri-info-to-make-sure-everything-is-set-up-properly).

### **Screenshots**
![grafik](https://user-images.githubusercontent.com/23178554/142794483-82aa6fc7-0541-4a8a-87c9-9058ed41f834.png)

### **Platform and Versions (required):**

Well... before a crash, it logs:
```
Operating System - Manjaro, version 21.2.0 X64

Node.js environment
  Node.js - 17.1.0
  @tauri-apps/cli - 1.0.0-beta.10
```

<details>
<summary>Directory structure</summary>

```bash
.
├── package.json
├── pnpm-lock.yaml
├── src
│   ├── pages
│   │   ├── about
│   │   │   ├── index.css
│   │   │   └── index.page.tsx
│   │   └── index
│   │       ├── Counter.tsx
│   │       └── index.page.tsx
│   ├── preact.d.ts
│   ├── renderer
│   │   ├── _default.page.client.tsx
│   │   ├── _default.page.server.tsx
│   │   ├── _error.page.tsx
│   │   ├── Link.tsx
│   │   ├── logo.svg
│   │   ├── PageShell.css
│   │   ├── PageShell.tsx
│   │   ├── types.ts
│   │   └── usePageContext.tsx
│   └── vite-env.d.ts
├── src-tauri
│   ├── Cargo.lock
│   ├── Cargo.toml
│   ├── icons
│   │   ├── 128x128@2x.png
│   │   ├── 128x128.png
│   │   ├── 32x32.png
│   │   ├── icon.icns
│   │   ├── icon.ico
│   │   ├── icon.png
│   │   ├── Square107x107Logo.png
│   │   ├── Square142x142Logo.png
│   │   ├── Square150x150Logo.png
│   │   ├── Square284x284Logo.png
│   │   ├── Square30x30Logo.png
│   │   ├── Square310x310Logo.png
│   │   ├── Square44x44Logo.png
│   │   ├── Square71x71Logo.png
│   │   ├── Square89x89Logo.png
│   │   └── StoreLogo.png
│   ├── rustfmt.toml
│   ├── src
│   │   ├── build.rs
│   │   └── main.rs
│   └── tauri.conf.json
├── tsconfig.json
├── vite.config.ts
└── vite-server
    └── index.ts

```

</details>

### **Stack Trace**

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character 't' while parsing major version number")', src/info.rs:323:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   3: cargo_tauri::info::VersionBlock::display
   4: cargo_tauri::info::Info::run
   5: cargo_tauri::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  @tauri-apps/api - tauri-apps
 app:spawn Command "/mnt/spare/dev/web/vite-ssr-project/node_modules/.pnpm/@tauri-apps+cli@1.0.0-beta.10/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 101 +0ms
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ghost** [comment] 2021-11-22 03:18
`pnpm run tauri dev` runs fine.

**Comment by FabianLars** [comment] 2021-11-22 09:30
duplicate of #2509

**Closed as completed by FabianLars** 2021-11-22 09:30 UTC
Labels: type: bug, status: invalid
