### ISSUE TITLE
bundler hates projects not named "app"

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri#123] opened 2019-12-01 21:06 UTC
**Describe the bug**
If you name your project something other than "app" in `src-tauri/Cargo.toml`, the build fails.

**To Reproduce**
1. Init a project.
2. edit src-tauri/Cargo.toml:
```
[package]
name = "QuasarDemo"
```
3. Finish the build, get this error:  
```
Finished release [optimized] target(s) in 4m 19s
    Bundling QuasarDemo.app
error: Failed to copy binary from "/[redacted]/tauri/examples/quasar-app/src-tauri/target/release/QuasarDemo"
  Caused by: "/[redacted]/tauri/examples/quasar-app/src-tauri/target/release/QuasarDemo" does not exist
```

**Expected behavior**
The app should be built.

**Platform (please complete the following information):**
This is probably happening for all platforms.

**Comment by lucasfernog** [comment] 2019-12-01 21:25
Can you try to change the output name under [[bin]]? This issue is known, but I think the problem is when you try to use the updater, not the bundler.

**Comment by nothingismagick** [comment] 2019-12-01 21:48
can confirm that your suggestion works.

**Comment by nothingismagick** [comment] 2019-12-01 22:13
I guess this is not a bug - but something we will have to track in the docs. Leaving open and will close it once the docs page is written about the `src-tauri/Cargo.toml` caveats

**Comment by nothingismagick** [comment] 2020-02-22 10:26
This has been resolved. Proved by guijs.

**Comment by jwenjian** [comment] 2020-06-22 14:28
I faced the problem too, resolved by changing below item to the customized name in `Cargo.toml`:

- package.name
- package.default-run
- bin.name

**Comment by lucasfernog** [comment] 2020-06-22 14:33
We should have this under our docs. Gonna arrange it with @Laegel

**Comment by nothingismagick** [comment] 2020-06-22 14:34
Good point. This should (IMHO) be done from `tauri.conf.json` - even if it modifies the Cargo.toml

**Comment by lucasfernog** [comment] 2020-07-16 20:55
Can we close this one since the app name is now prompted by `tauri init`?

**Comment by nklayman** [comment] 2021-02-01 01:38
Not only is the app name prompted for, but changing the name worked fine for me as long as `default-run` and `bin.name` are the same.

**Closed by nklayman** 2021-02-01 01:38 UTC
Labels: bug

**Comment by The-True-Hooha** [comment] 2022-12-13 13:47
Leaving a comment cos I'm facing this same challenge:

ran into the error: `Caused by: default-run target `app` not found`
had to change the name in `Cargo.toml` to "app" back to resolve the issue. 

How can I use my desired name to fix the issue?

**Comment by FabianLars** [comment] 2022-12-13 13:57
remove or update the `default-run` field in cargo.toml (it must match the name, or not exist at all)

**Comment by The-True-Hooha** [comment] 2022-12-13 14:02
> remove or update the `default-run` field in cargo.toml (it must match the name, or not exist at all)

@FabianLars thank you, resolved.
