### ISSUE TITLE
[bug] Blank window  after running app

### ISSUE THREAD

**Issue by holdxen** [tauri-apps/tauri#11076] opened 2024-09-20 13:06 UTC
### Describe the bug

The project was created by `cargo create-tauri-app` and I didn't change anything, just run `cargo tauri dev`

`export WEBKIT_DISABLE_DMABUF_RENDERER=1` doesn't work for me

![截图 2024-09-20 21-00-00](https://github.com/user-attachments/assets/9d2a7cf4-c06c-4e0d-bdaa-d4194eb07d01)

![截图 2024-09-20 21-04-23](https://github.com/user-attachments/assets/83217741-ad6b-48f9-9f61-b3c3b472dace)

### Full `tauri info` output

```text
[✔] Environment
    - OS: EndeavourOS Rolling Release X64
    ✔ webkit2gtk-4.0: 2.46.0
    ✔ rsvg2: 2.59.0
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - node: 22.9.0
    - pnpm: 9.10.0
    - yarn: 1.22.22
    - npm: 10.8.3

[-] Packages
    - tauri [RUST]: 1.8.0
    - tauri-build [RUST]: 1.5.5
    - wry [RUST]: 0.24.11
    - tao [RUST]: 0.16.10
    - tauri-cli [RUST]: 1.6.0
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli [NPM]: 1.6.0 (outdated, latest: 1.6.2)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

**Comment by FabianLars** [comment] 2024-09-20 13:08
duplicate of https://github.com/tauri-apps/tauri/issues/10626

**Closed as not planned by FabianLars** 2024-09-20 13:08 UTC
Labels: type: bug, status: upstream, platform: Linux
