### ISSUE TITLE
Regarding the adaptation of HarmonyOS system

### ISSUE THREAD

**Issue by baosj627** [tauri-apps/tauri#11112] opened 2024-09-24 09:26 UTC
### Describe the problem

The official team can consider supporting the adaptation of Tauri v2 to the HarmonyOS system.

### Describe the solution you'd like

Hello, the HarmonyOS Next version no longer supports the Android system. Many Chinese developers are currently waiting for the existing technology stack to be adapted to the HarmonyOS system, while some are considering switching to a new technology stack. Tauri v2 stands out. I personally appreciate the innovation of combining Tauri with Rust, but since it has not yet been adapted to the HarmonyOS system, it essentially limits the options for many Chinese developers. Personally, I also hope to utilize Tauri v2 as our technology stack, so I would like to inquire about the potential timeline for its adaptation.

**Comment by FabianLars** [comment] 2024-09-24 15:30
Duplicate of #7287 - There are currently no plans, but we welcome any kind of contributions. We just don't have time to work on it ourselves at the moment.

**Closed as not planned by FabianLars** 2024-09-24 15:30 UTC
Labels: type: feature request
