### ISSUE TITLE
[bug] cargo install tauri-cli --version ^1.0.0-beta

### ISSUE THREAD

**Issue by 5icoding** [tauri-apps/tauri#3221] opened 2022-01-15 13:00 UTC
### Describe the bug

when Installing the Tauri cli tool，“cargo install tauri-cli --version ^1.0.0-beta”，prompt Error。

### Platform and versions

```shell
Os:win11
rustc 1.58.0 (02072b482 2022-01-11)
cargo 1.58.0 (7f08ace4f 2021-11-24)
```

### Stack trace

```shell
error[E0432]: unresolved import `clap::crate_version`
 --> C:\Users\5icod\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-cli-1.0.0-beta.7\src/main.rs:6:12
  |
6 | use clap::{crate_version, load_yaml, App, AppSettings, ArgMatches};
  |            ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_version`
   --> C:\Users\5icod\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-cli-1.0.0-beta.7\src/main.rs:265:14
    |
265 |     .version(crate_version!())
    |              ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
   --> C:\Users\5icod\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-cli-1.0.0-beta.7\src/main.rs:264:23
    |
264 |   let app = App::from(yaml)
    |                       ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: failed to compile `tauri-cli v1.0.0-beta.7`, intermediate artifacts can be found at `C:\Users\5icod\AppData\Local\Temp\cargo-installhBWakz`
```

**Comment by lucasfernog** [comment] 2022-01-15 13:02
Duplicate of #3050. Until the next release, please install with `cargo install tauri-cli --git https://github.com/tauri-apps/tauri`.

**Closed as completed by lucasfernog** 2022-01-15 13:02 UTC
Labels: type: bug
