### ISSUE TITLE
[bug] http api memory leak

### ISSUE THREAD

**Issue by qu1ck** [tauri-apps/tauri#4038] opened 2022-05-03 08:30 UTC
### Describe the bug

Response objects of http api calls never get cleaned up.

### Reproduction

Do this in an empty page
```js
import { fetch, ResponseType } from '@tauri-apps/api/http';
...
async function run() {
    for(var i = 0; i < 100000; i++) {
        var response = await fetch(
            "https://gist.githubusercontent.com/khaykov/a6105154becce4c0530da38e723c2330/raw/41ab415ac41c93a198f7da5b47d604956157c5c3/gistfile1.txt",
            {responseType: ResponseType.Text, method: 'GET', timeout: 10});
        console.log(response.status);
    }
}
window.onload = (event) => {
    run();
}
```

Observe in memory profiler as megabytes of RAM are sacrificed to the gods of RAM.

### Expected behavior

No memory leak.

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.19044 X64
  › Webview2: 101.0.1210.32
  › MSVC: 
      - Visual Studio Community 2019
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: git+https://github.com/tauri-apps/tauri.git?rev=220e746#220e7460148df476171579878c3cfffcdb1423d8 (1.0.0-rc.8),
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,
```

**Comment by lucasfernog** [comment] 2022-05-03 16:42
I'll close this since the issue is not in the HTTP API itself, it's the same issue as #4026 and #3921 (I tested this by changing the backend response to `null` while keeping the requests firing).

It's also important to note that the memory leak is happening in the webview2 process :(

**Closed as completed by lucasfernog** 2022-05-03 16:42 UTC
Labels: type: bug
