### ISSUE TITLE
[bug] the safari started by tauri is different with the safari on macos 10.15.7

### ISSUE THREAD

**Issue by coderup2021** [tauri-apps/tauri#6044] opened 2023-01-12 09:07 UTC
### Describe the bug

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/93026018/212011921-cab6371f-61b8-4fb0-8555-186d9eb39524.png">

at first, when I use "web3.storage", I meet a error on the web:     "ReferenceError: Can't find variable: BigInt"
I found BigInt is indeed used in a small js library.
I got "BigInt" is ES2020 version after searched in google.
so I open the console pane both in the safari opened by tauri and by macos, and print the BigInt in both 2 console, but get different result, BigInt is not defined in the one open by tauri, also I tried the file.stream, got the same result as showed in th above picture. and this is indeed the reason of the error.

I think the safari opened by tauri should be the same with the one which opened by me, anyone know the reason?

I put the code into github: 
https://github.com/coderup2021/my-test-tauri.git
after download, reset to the commit: "29149b76196ca818d674ebc45436319b2d041e16",  
exec the command followed cat repeat the error
```sh
pnpm install
pnpm dev
```

my computer ENV:
```
macos  Catalina 10.15.7, 
safari is version 15.6.1 (15613.3.9.1.16, 15613)
rustc 1.66.1 (90743e729 2023-01-10)
```
package.json:
```
{
  "name": "web3.storage-desktop",
  "version": "0.1.0",
  "private": true,
  "author": {
    "name": "coderup2021",
    "email": "coderup@163.com"
  },
  "scripts": {
    "next-start": "cross-env BROWSER=none next dev",
    "next-build": "next build && next export",
    "tauri": "tauri",
    "build": "tauri build",
    "dev": "tauri dev",
    "lint": "next lint",
    "prepare": "husky install"
  },
  "dependencies": {
    "@tauri-apps/api": "^1.2.0",
    "clsx": "^1.2.1",
    "next": "^13.1.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.4.1",
    "@commitlint/config-conventional": "^17.4.0",
    "@prettier/plugin-xml": "^2.2.0",
    "@tauri-apps/cli": "^1.2.2",
    "@testing-library/dom": "^8.19.1",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/jest": "^29.2.5",
    "@types/node": "^18.11.18",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.10",
    "@typescript-eslint/eslint-plugin": "^5.47.1",
    "@typescript-eslint/parser": "^5.47.1",
    "autoprefixer": "^10.4.13",
    "cross-env": "^7.0.3",
    "cssnano": "^5.1.14",
    "eslint": "^8.30.0",
    "eslint-config-next": "^13.1.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-simple-import-sort": "^8.0.0",
    "husky": "^8.0.2",
    "lint-staged": "^13.1.0",
    "postcss": "^8.4.20",
    "postcss-import": "^15.1.0",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.1",
    "sass": "^1.57.1",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.4"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "lint-staged": {
    "*.{js,jsx,css,md,ts,tsx,json,less,scss}": "prettier --write"
  }
}
```
Cargo.toml
```
[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.66"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.3", features = ["api-all"] }

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]
```

tauri.conf.json
```
{
  "$schema": "../node_modules/@tauri-apps/cli/schema.json",
  "build": {
    "beforeBuildCommand": "pnpm next-build",
    "beforeDevCommand": "pnpm next-start",
    "devPath": "http://localhost:3000",
    "distDir": "../out"
  },
  "package": {
    "productName": "tauri-nextjs-template",
    "version": "0.1.0"
  },
  "tauri": {
    "allowlist": {
      "all": true
    },
    "bundle": {
      "active": true,
      "category": "DeveloperTool",
      "copyright": "",
      "deb": {
        "depends": []
      },
      "externalBin": [],
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "com.tauri.dev",
      "longDescription": "",
      "macOS": {
        "entitlements": null,
        "exceptionDomain": "",
        "frameworks": [],
        "providerShortName": null,
        "signingIdentity": null
      },
      "resources": [],
      "shortDescription": "",
      "targets": "all",
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "security": {
      "csp": null
    },
    "updater": {
      "active": false
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": true,
        "title": "Tauri NextJS App",
        "width": 1280,
        "height": 800
      }
    ]
  }
}
```

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "src-tauri", "*.js"]
}
```

Hope to resolve it!

### Reproduction

❯ pnpm dev

> web3.storage-desktop@0.1.0 dev /Users/lj/Study/web3.0/web3.storage-desktop
> tauri dev

     Running BeforeDevCommand (`pnpm next-start`)

> web3.storage-desktop@0.1.0 next-start /Users/lj/Study/web3.0/web3.storage-desktop
> cross-env BROWSER=none next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
        Info Watching /Users/lj/Study/web3.0/web3.storage-desktop/src-tauri for changes...
event - compiled client and server successfully in 964 ms (164 modules)
   Compiling app v0.1.0 (/Users/lj/Study/web3.0/web3.storage-desktop/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 8.09s
wait  - compiling / (client and server)...
event - compiled client and server successfully in 734 ms (354 modules)

### Platform and versions

❯ pnpm run tauri info
> web3.storage-desktop@0.1.0 tauri /Users/lj/Study/web3.0/web3.storage-desktop
> tauri "info"
Environment
  › OS: Mac OS 10.15.7 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.17.1
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.66.1
  › cargo: 1.66.1
  › Rust toolchain: stable-x86_64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../out
  › devPath: http://localhost:3000/
  › framework: React (Next.js)
  › bundler: Webpack

App directory structure
  ├─ .husky
  ├─ out
  ├─ node_modules
  ├─ .next
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ .git
  └─ src

### Stack trace

```shell
Unhandled Runtime Error
ReferenceError: Can't find variable: BigInt
Call Stack
eval

[native code]
./node_modules/.pnpm/cborg@1.10.0/node_modules/cborg/esm/lib/0uint.js

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/pages/index.js (981:5)
<unknown>

/_next/static/chunks/webpack.js (661:35)
__webpack_require__

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/cborg@1.10.0/node_modules/cborg/esm/lib/jump.js

/_next/static/chunks/pages/index.js (1135:5)
<unknown>

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (661:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/cborg@1.10.0/node_modules/cborg/esm/lib/encode.js

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/pages/index.js (1113:5)
<unknown>

/_next/static/chunks/webpack.js (661:35)
__webpack_require__

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/cborg@1.10.0/node_modules/cborg/esm/cborg.js

/_next/static/chunks/pages/index.js (970:5)
<unknown>

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (661:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/@ipld+dag-cbor@7.0.3/node_modules/@ipld/dag-cbor/esm/index.js

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/pages/index.js (783:5)
<unknown>

/_next/static/chunks/webpack.js (661:35)
__webpack_require__

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/@ipld+car@3.2.4/node_modules/@ipld/car/esm/lib/decoder.js

/_next/static/chunks/pages/index.js (684:5)
<unknown>

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (661:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/@ipld+car@3.2.4/node_modules/@ipld/car/esm/lib/reader-browser.js

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/pages/index.js (750:5)
<unknown>

/_next/static/chunks/webpack.js (661:35)
__webpack_require__

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/@ipld+car@3.2.4/node_modules/@ipld/car/esm/car-browser.js

/_next/static/chunks/pages/index.js (673:5)
<unknown>

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (661:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/ipfs-car@0.7.0/node_modules/ipfs-car/dist/esm/pack/index.js

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/pages/index.js (1190:5)
<unknown>

/_next/static/chunks/webpack.js (661:35)
__webpack_require__

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (37:37)
eval

[native code]
./node_modules/.pnpm/web3.storage@4.4.0_lz2mbwyw4zjrdfsro6cckkmnvm/node_modules/web3.storage/src/lib.js

/_next/static/chunks/pages/index.js (2026:5)
<unknown>

file:///Users/lj/Study/web3.0/web3.storage-desktop/.next/static/chunks/webpack.js (661:35)
__webpack_require__

/_next/static/chunks/webpack.js (37:37)
```

**Comment by FabianLars** [comment] 2023-01-12 09:11
Duplicate of https://github.com/tauri-apps/tauri/issues/4667 - the webview does _not_ match Safari's version.
Catalina's webview is the equivalent to safari v13, see https://tauri.app/v1/references/webview-versions

**Closed as not planned by FabianLars** 2023-01-12 09:11 UTC
Labels: type: bug, status: needs triage
