### ISSUE TITLE
[feat] window with wry navigation events

### ISSUE THREAD

**Issue by ctaggart** [tauri-apps/tauri#5411] opened 2022-10-16 14:33 UTC
### Describe the problem

I'm building a Tauri app. For oauth, I want to create a new window where I can listen to the navigation events.  After the user authentications, the code is passed to the return url. This workflow is implemented in this wry example:
https://github.com/tauri-apps/wry/blob/dev/examples/navigation_event.rs

### Describe the solution you'd like

I'd like the same solution, but using the Tauri API. When I tried using that wry example with my Tauri app, I end up closing the entire application when I close the auth window. I'm a little lost at this lower level.

### Alternatives considered

`on_page_load` looks like it applies to just pages with Tauri JavaScript #4037.  I started looking at Tauri Plugins, but not sure what the right extension point is for integrating a custom wry window and getting Tauri to manage it.

**Comment by FabianLars** [comment] 2022-10-17 13:01
I'd count this as a duplicate of https://github.com/tauri-apps/tauri/issues/4080.

In the meantime you could use a small localhost listener, which would also allow using the default browser for logging in, or if you wanna get your hands dirty you could use the webview bindings yourself via https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.with_webview

**Closed as not planned by FabianLars** 2022-10-17 13:01 UTC
Labels: type: feature request
