### ISSUE TITLE
[bug] Window focus loss event fired when trying to move/resize the window on Windows 10.

### ISSUE THREAD

**Issue by jbongseo** [tauri-apps/tauri#5864] opened 2022-12-19 09:29 UTC
### Describe the bug

`tauri::WindowEvent::Focused(false)` window event is fired when trying to move/resize the window on Windows 10 as of tauri 1.2.
tauri 1.1 works fine.

### Reproduction

1. clone https://github.com/jondot/tauri-tray-app
2. change tauri version to "1.2" from "src-tauri/Cargo.toml"
3. run dev (yarn run tauri dev) (if not using `pnpm`, change  `pnpm` -> `npm run` from `src-tauri/tauri.conf.json`
4. Drag window title to move it.
5. `tauri::WindowEvent::Focus(false)` fires and the window is closed by the window focus event handler.

### Expected behavior

With taur version 1.1,  the window is being moved.

### Platform and versions

Environment
  › OS: Windows 10.0.19045 X64
  › Webview2: 108.0.1462.54
  › MSVC:
      - Visual Studio Build Tools 2022
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.2,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.7,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

### Stack trace

```shell
no crash.
```

**Comment by metkm** [comment] 2023-03-06 13:32
This is probably related to `webview-com` crate `tauri-runtime-wry` uses. Both events I linked down here are getting triggered as the issue says.

The `webview-com` library version seems like 0.19.0, kinda old. This might be fixed in newer versions.

https://github.com/tauri-apps/tauri/blob/cfcc7f3c204af8a62d066e84defb9e9c03ef8092/core/tauri-runtime-wry/src/lib.rs#L3184-L3210

**Comment by Pylogmon** [comment] 2023-03-27 03:15
Is there any way to solve this problem?

**Comment by FabianLars** [comment] 2024-12-05 10:44
Clsoing as duplicate of https://github.com/tauri-apps/tauri/issues/10767 (even though it's newer, sry)

**Closed as not planned by FabianLars** 2024-12-05 10:44 UTC
Labels: type: bug, status: needs triage
