### ISSUE TITLE
[bug] Port does not close if window closed.

### ISSUE THREAD

**Issue by bicarlsen** [tauri-apps/tauri#3292] opened 2022-01-27 13:53 UTC
### Describe the bug

It appears that the port does not close if the tauri app is closed form the window close button rather than the command line.

### Reproduction

1. Start tauri in dev mode, e.g. `yarn tauri dev`
2. Close the app window with the close button rather than terminating the process in the command line. The command line process  terminates as well
3. Start tauri in dev mode again, it now asks to use a different port because the original one is in use.

### Expected behavior

Port should close when process terminates, regardless of how it terminates.

### Platform and versions

```shell
Operating System - Ubuntu, version 21.04 X64

Node.js environment
  Node.js - 17.1.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.2
  yarn - 1.22.17

Rust environment
  rustc - 1.56.1
  cargo - 1.56.0

App directory structure
/.vscode
/.git
/node_modules
/src-tauri
/src
/dist
/.angular

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist/thot-desktop
  devPath - http://localhost:4200
  framework - Angular
  bundler - Webpack
```

**Comment by amrbashir** [comment] 2022-01-27 14:44
duplicate of #2794

**Closed as completed** 2022-01-27 14:45 UTC
Labels: type: bug, status: invalid
