### ISSUE TITLE
backdrop filter not working

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#2976] opened 2021-11-28 05:55 UTC
### **Describe the bug**
The backdrop filter not working in Tauri. but it works in chrome. I use react and Tauri together

### **Expected behavior**
the `modal` component must be blurred and it is on chrome, but when I run Tauri it's just transparent.

### **Screenshots**
It is expected (correct on chrome):

it is what happens on Tauri:

### **Platform and Versions (required):**
```
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.3
  yarn - 1.22.17

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/src-tauri
/.vscode
/src
/node_modules
/.git
/public

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../src
  devPath - http://localhost:3000
  framework - React
```

**Comment by FabianLars** [comment] 2021-11-28 06:22
On Mac and Linux it's `-webkit-backdrop-filter`. Please reopen if this doesn't work either.

Also, duplicate of #2826.

**Closed as completed** 2021-11-28 06:22 UTC
Labels: type: bug
