### ISSUE TITLE
[bug] cargo install tauri-cli --version ^1.0.0-beta Error

### ISSUE THREAD

**Issue by donworld** [tauri-apps/tauri#3175] opened 2022-01-06 07:23 UTC
### Describe the bug

 Compiling tauri-cli v1.0.0-beta.7
error[E0432]: unresolved import `clap::crate_version`
 --> C:\Users\Don\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tauri-cli-1.0.0-beta.7\src/main.rs:6:12
  |
6 | use clap::{crate_version, load_yaml, App, AppSettings, ArgMatches};
  |            ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_version`
    |
265 |     .version(crate_version!())
    |              ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
   --> C:\Users\Don\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\tauri-cli-1.0.0-beta.7\src/main.rs:264:23
    |
264 |   let app = App::from(yaml)
    |                       ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: failed to compile `tauri-cli v1.0.0-beta.7`, intermediate artifacts can be found at `C:\Users\Don\AppData\Local\Temp\cargo-installzK2Z9D`

Caused by:
  could not compile `tauri-cli` due to 3 previous errors

### Reproduction

cargo install tauri-cli --version ^1.0.0-beta doesn't work

### Platform and versions

```shell
rust version ： rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by FabianLars** [comment] 2022-01-06 08:15
duplicate of #3050.
You can install from git for now: `cargo install tauri-cli --git https://github.com/tauri-apps/tauri`

**Closed as completed** 2022-01-06 08:15 UTC
Labels: type: bug, status: invalid
