### ISSUE TITLE
Crash when clicking on image on macOS: NSInvalidArgumentException [bug]

### ISSUE THREAD

**Issue by hydrogen602** [tauri-apps/tauri#5901] opened 2022-12-23 14:31 UTC
### Describe the bug

I made a new tauri repository using tauri `1.2.3` (on an M1 Mac with Monterey 12.2.1), selected `npm` as the package manager and then chose `solid-ts` as the frontend template. Now when I run the default demo, clicking on images results in a crash of the app.

```
2022-12-23 15:19:37.955 render[71942:2007514] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]'
*** First throw call stack:
(
        0   CoreFoundation                      0x00000001a84f81cc __exceptionPreprocess + 240
        1   libobjc.A.dylib                     0x00000001a82497b8 objc_exception_throw + 60
        2   CoreFoundation                      0x00000001a85c8488 -[__NSCFString characterAtIndex:].cold.1 + 0
        3   CoreFoundation                      0x00000001a85d50c4 -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
        4   CoreFoundation                      0x00000001a83ffed0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
        5   CoreFoundation                      0x00000001a83ffd64 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 60
        6   VisionKitCore                       0x000000021f203e08 -[VKAnalyticsAnalyzerEvent coreAnalyticsDictionary] + 1208
        7   VisionKitCore                       0x000000021f1c6b00 -[VKAnalyticsProcessor processAndSendEvent:] + 92
        8   VisionKitCore                       0x000000021f1bc7d8 __69-[VKImageAnalyzer _processRequest:progressHandler:completionHandler:]_block_invoke_2 + 1200
        9   libdispatch.dylib                   0x00000001a81ece60 _dispatch_call_block_and_release + 32
        10  libdispatch.dylib                   0x00000001a81eebac _dispatch_client_callout + 20
        11  libdispatch.dylib                   0x00000001a81f6330 _dispatch_lane_serial_drain + 672
        12  libdispatch.dylib                   0x00000001a81f6ea4 _dispatch_lane_invoke + 392
        13  libdispatch.dylib                   0x00000001a8201708 _dispatch_workloop_worker_thread + 656
        14  libsystem_pthread.dylib             0x00000001a83a9304 _pthread_wqthread + 288
        15  libsystem_pthread.dylib             0x00000001a83a8018 start_wqthread + 8
)
libc++abi: terminating with uncaught exception of type NSException
```

### Reproduction

1. Make a new tauri repo with `cargo create-tauri-app` on an M1 Mac (Monterey 12.2.1)
2. Select `npm` and then `solid-ts` for package manager and frontend, respectively.
3. Run the default demo: `npm run tauri dev`
4. Click on any of the three logos: Vite, Tauri, or Solid
5. App crashes (new browser window is still created that shows the docs of the chosen tool)

### Expected behavior

It shouldn't crash

### Platform and versions

Not sure why it says X64, cargo, rustc, and rust-produced executables are arm64 and `process.arch` in node is arm64.
```
Environment
  › OS: Mac OS 12.2.1 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: SolidJS
  › bundler: Vite

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ .vscode
  └─ src
```

### Stack trace

```shell
2022-12-23 15:29:50.227 render[73972:2023944] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]'
*** First throw call stack:
(
        0   CoreFoundation                      0x00000001a84f81cc __exceptionPreprocess + 240
        1   libobjc.A.dylib                     0x00000001a82497b8 objc_exception_throw + 60
        2   CoreFoundation                      0x00000001a85c8488 -[__NSCFString characterAtIndex:].cold.1 + 0
        3   CoreFoundation                      0x00000001a85d50c4 -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
        4   CoreFoundation                      0x00000001a83ffed0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
        5   CoreFoundation                      0x00000001a83ffd64 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 60
        6   VisionKitCore                       0x000000021f203e08 -[VKAnalyticsAnalyzerEvent coreAnalyticsDictionary] + 1208
        7   VisionKitCore                       0x000000021f1c6b00 -[VKAnalyticsProcessor processAndSendEvent:] + 92
        8   VisionKitCore                       0x000000021f1bc7d8 __69-[VKImageAnalyzer _processRequest:progressHandler:completionHandler:]_block_invoke_2 + 1200
        9   libdispatch.dylib                   0x00000001a81ece60 _dispatch_call_block_and_release + 32
        10  libdispatch.dylib                   0x00000001a81eebac _dispatch_client_callout + 20
        11  libdispatch.dylib                   0x00000001a81f6330 _dispatch_lane_serial_drain + 672
        12  libdispatch.dylib                   0x00000001a81f6ea4 _dispatch_lane_invoke + 392
        13  libdispatch.dylib                   0x00000001a8201708 _dispatch_workloop_worker_thread + 656
        14  libsystem_pthread.dylib             0x00000001a83a9304 _pthread_wqthread + 288
        15  libsystem_pthread.dylib             0x00000001a83a8018 start_wqthread + 8
)
libc++abi: terminating with uncaught exception of type NSException
```
```


### Additional context

Also I modified nothing after creating the app

**Comment by lucasfernog** [comment] 2022-12-23 14:52
Duplicate of #2934. You need to update macOS to 12.3.

**Closed as not planned by lucasfernog** 2022-12-23 14:52 UTC
Labels: type: bug, status: needs triage
