### ISSUE TITLE
[bug]  libc++abi: terminating with uncaught exception of type NSException

### ISSUE THREAD

**Issue by ahqrt** [tauri-apps/tauri#4913] opened 2022-08-11 09:07 UTC
### Describe the bug

2022-08-11 16:59:57.804 tauri-demo[21190:7222319] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001871d41cc __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000186f257b8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001872a4488 -[__NSCFString characterAtIndex:].cold.1 + 0
	3   CoreFoundation                      0x00000001872b10c4 -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
	4   CoreFoundation                      0x00000001870dbed0 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 320
	5   CoreFoundation                      0x00000001870dbd64 +[NSDictionary dictionaryWithObjects:forKeys:count:] + 60
	6   VisionKitCore                       0x00000001fddb3e08 -[VKAnalyticsAnalyzerEvent coreAnalyticsDictionary] + 1208
	7   VisionKitCore                       0x00000001fdd76b00 -[VKAnalyticsProcessor processAndSendEvent:] + 92
	8   VisionKitCore                       0x00000001fdd6c7d8 __69-[VKImageAnalyzer _processRequest:progressHandler:completionHandler:]_block_invoke_2 + 1200
	9   libdispatch.dylib                   0x0000000186ec8e60 _dispatch_call_block_and_release + 32
	10  libdispatch.dylib                   0x0000000186ecabac _dispatch_client_callout + 20
	11  libdispatch.dylib                   0x0000000186ed2330 _dispatch_lane_serial_drain + 672
	12  libdispatch.dylib                   0x0000000186ed2ea4 _dispatch_lane_invoke + 392
	13  libdispatch.dylib                   0x0000000186edd708 _dispatch_workloop_worker_thread + 656
	14  libsystem_pthread.dylib             0x0000000187085304 _pthread_wqthread + 288
	15  libsystem_pthread.dylib             0x0000000187084018 start_wqthread + 8
)
libc++abi: terminating with uncaught exception of type NSException

when I use Tauri and vite to create a demo app.  
This crash was happening to me when I clicked on an image.
I'm on macOS 12.1 M1 

### Platform and versions

Environment
  › OS: Mac OS 12.1.0 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: 7.0.0-rc.6
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.62.1
  › cargo: 1.62.1
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: React

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  └─ src

**Comment by lucasfernog** [comment] 2022-08-11 12:35
Duplicate of #2934 the only way to fix this is to update your macOS version to 12.3. This won't affect your users, only development.

**Closed as completed by lucasfernog** 2022-08-11 12:35 UTC
Labels: type: bug, status: invalid

**Comment by shery** [comment] 2022-09-04 09:38
for me, just run `cargo tauri build`, the error just disappears

Here are my steps to reproduce:

```bash
cargo install create-tauri-app
cargo create-tauri-app --template vue
cargo install tauri-cli

cargo tauri dev # Exception occurs shortly after app launch

cargo tauri build # error disappears
```

This looks like another bug @lucasfernog 
```
2022-09-04 17:05:25.190 tiny-img[78957:1526941] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[15]'
```

In the tauri main file: `src-tauri/src/main.rs`:
<img width="945" alt="image" src="https://user-images.githubusercontent.com/12773365/188307218-685e0e83-f5e0-4a04-bc80-e1965f7bd0fa.png">
