### ISSUE TITLE
Open child window

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#2936] opened 2021-11-22 13:22 UTC
Are tauri supports new opening child window from application and if yes, how to do it?

**Comment by xuchaoqian** [comment] 2021-11-22 14:09
Tauri does support it.  Code sample as following:

```
  tauri::async_runtime::spawn(async move {
    app_handle
      .clone()
      .create_window(
        "sample",
        WindowUrl::App("sample.html".into()),
        |window_builder, webview_attributes| {
          let builder = window_builder.inner_size(400.0, 200.0).decorations(true).visible(true);
          (builder, webview_attributes)
        },
      )
      .unwrap();
});

**Comment by amrbashir** [comment] 2021-11-22 16:24
duplicate of #1643

**Closed as completed** 2021-11-22 16:24 UTC
Labels: status: invalid

**Comment by amrbashir** [comment] 2021-11-22 16:26
@xuchaoqian  that's just creating normal windows programmatically, not child windows.

**Comment by xuchaoqian** [comment] 2021-11-22 16:54
Thank you. I've learned that now:).

> @xuchaoqian that's just creating normal windows programmatically, not child windows.

**Comment by rdwnsjjd** [comment] 2021-11-22 17:25
@amrbashir I don't know why but I cannot use import statement in my app and it leads to import error. something like cannot use import out of module and like this.

now I don't have access to my system but will share complete error msg.

**Comment by rdwnsjjd** [comment] 2021-11-22 17:26
@xuchaoqian tnx for your help 🙏😊

**Comment by amrbashir** [comment] 2021-11-22 17:27
@rdwnsjjd it is porbably because you're using vanillajs and your script tag doesn't have `type="module"` attribute on it.

This is irrelevant to this issue so in the future please, either create a new issue or comment on related issues or even better try posting in our discord server.

**Comment by rdwnsjjd** [comment] 2021-11-22 17:38
@amrbashir I use pure js with jquery

**Comment by amrbashir** [comment] 2021-11-22 18:15
@rdwnsjjd This is not a Tauri issue but with how you have your html/js setup. please ask for Tauri issues only and on related issues that relate to the problem. Other stuff can be asked in our discord server.
