### ISSUE TITLE
[bug] Using WebviewWindowBuilder with `focused` `false` doesn't seem to do anything

### ISSUE THREAD

**Issue by omerdn1** [tauri-apps/tauri#12055] opened 2024-12-26 04:34 UTC
### Describe the bug

I'm experiencing the same behavior described here https://github.com/tauri-apps/tauri/issues/11566
But when creating a new window via Rust with `WebviewWindowBuilder`.

When a new window is created with `.focused(false)`, it still gains focus.

Here's my snippet:
```rust
    let countdown_window = tauri::WebviewWindowBuilder::new(
        &app_handle,
        "countdown",
        tauri::WebviewUrl::App("countdown.html".into()),
    )
    .title("Break Countdown")
    .focused(false)
    .inner_size(220.0, 40.0)
    .build()
    .unwrap();
```

### Full `tauri info` output

```text
❯ pnpm tauri info

> tauri "info"


[✔] Environment
    - OS: Mac OS 13.6.4 x86_64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.82.0 (f6e511eec 2024-10-15)
    ✔ cargo: 1.82.0 (8f40fc59f 2024-08-21)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 23.1.0
    - pnpm: 9.15.1
    - yarn: 1.22.22
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-12-26 14:26
duplicate of https://github.com/tauri-apps/tauri/issues/9065

**Closed as not planned by FabianLars** 2024-12-26 14:26 UTC
Labels: type: bug, status: needs triage
