### ISSUE TITLE
[bug] MacOS: maximized without dock area covered.

### ISSUE THREAD

**Issue by itswakkana** [tauri-apps/tauri#11396] opened 2024-10-17 09:28 UTC
### Describe the bug

Hi,

I’m currently trying to build a screenshot application and I need a transparent area for selecting a region to capture. When I use the WebviewWindowBuilder with maximized = true, the dock and top status bar are not covered.

Here is the code snippet I’m using:
```
let win_builder = WebviewWindowBuilder::new(
    app,
    "screenshot_mask",
    WebviewUrl::App("/screenshot_mask.html".parse().unwrap()),
)
.decorations(false)
.always_on_top(true)
.closable(false)
.transparent(true)
.maximized(true);

let window = win_builder.build().unwrap();
window.show()?;
```

### Full `tauri info` output

```text
[✔] Environment
    - OS: Mac OS 15.0.1 arm64 (X64)
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.10.0
    - pnpm: 9.12.1
    - npm: 10.2.4
    - bun: 1.1.30

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.1
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.3
    - @tauri-apps/api : 2.0.2
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : 2.0.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite

[-] iOS
    - Developer Teams: None
```

**Comment by itswakkana** [comment] 2024-10-17 09:30
![1](https://github.com/user-attachments/assets/da836253-ce32-4de6-8f72-2778c757e7cf)

**Comment by FabianLars** [comment] 2024-10-17 20:03
I think this counts as a duplicate of https://github.com/tauri-apps/tauri/issues/9987 (since this is how maximization works on macos i wouldn't call this a bug)

**Closed as not planned by FabianLars** 2024-10-17 20:03 UTC
Labels: type: bug, status: needs triage
