### ISSUE TITLE
[bug] ask & confirm Dialog returns true in all cases

### ISSUE THREAD

**Issue by martin-opensky** [tauri-apps/tauri#8399] opened 2023-12-14 16:33 UTC
### Describe the bug

For the 'ask' and 'confirm' dialogs the response is always true

### Reproduction

The code from line 34 - 53 in this file covers the issue: https://github.com/martin-opensky/create-tauri-2-next-14-app/blob/tauri-alpha-bug-1/src/components/ActionBar.tsx

In all cases the response is true.

### Expected behavior

The expected behaviour would be:
- Confirm: cancel is false, ok is true
- Ask: No is false, Yes is true

### Platform and versions

```text
[✔] Environment
    - OS: Mac OS 14.1.2 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-aarch64-apple-darwin (default)
    - node: 20.5.1
    - pnpm: 8.6.3
    - yarn: 1.22.19
    - npm: 9.8.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.18
    - tauri-build [RUST]: 2.0.0-alpha.12
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - @tauri-apps/api [NPM]: 2.0.0-alpha.12
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.18

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:3000/
    - framework: React (Next.js)
    - bundler: Vite
```

**Comment by amrbashir** [comment] 2023-12-14 16:36
I think this is a duplicate of https://github.com/tauri-apps/plugins-workspace/issues/711 and so has been fixed in https://github.com/tauri-apps/plugins-workspace/pull/769 and will be available in the next release.

**Closed as completed by amrbashir** 2023-12-14 16:36 UTC
Labels: type: bug, status: needs triage

**Comment by martin-opensky** [comment] 2023-12-14 16:43
@amrbashir Thanks for the quick response.  Whats the best channel to keep up to date with minor releases related to Tauri v2? So I can see when this has been pushed?

**Comment by amrbashir** [comment] 2023-12-14 16:45
I'd say just subscribe to releases notifications on `tauri` and `plugins-workspace` repos
