### ISSUE TITLE
[feat] I think Huawei Harmony Next needs Tauri

### ISSUE THREAD

**Issue by RiverBreaker** [tauri-apps/tauri#11833] opened 2024-11-30 13:53 UTC
### Describe the problem

I think Huawei Harmony Next needs Tauri,This will be very interesting,I think this system will be an important part of the Tauri ecosystem, just like Android

### Describe the solution you'd like

Adapt Tauri to HarmonyOS NEXT system

**Comment by FabianLars** [comment] 2024-11-30 15:14
Duplicate of https://github.com/tauri-apps/tauri/issues/7287

**Closed as not planned by FabianLars** 2024-11-30 15:14 UTC
Labels: type: feature request

**Comment by RiverBreaker** [comment] 2024-11-30 15:20
> #7287 的副本

thanks
