### ISSUE TITLE
[bug] Tauri fails to build inside a workspace with workspace overrides

### ISSUE THREAD

**Issue by cogsandsquigs** [tauri-apps/tauri#6252] opened 2023-02-13 00:17 UTC
### Describe the bug

While building a tauri project inside a Cargo workspace using `cargo build`, with `src-tauri/Cargo.toml` containing workspace overrides (such as `authors = { workspace = true }`), the message "This manifest requires workspace inheritance, but `inherit_workspace` hasn't been called yet" appears. 
![image](https://user-images.githubusercontent.com/59457601/218345427-fe650b10-d91b-42c2-b59e-6a7656f1f838.png)
Additionally, using the command `cargo tauri dev` inside the same workspace, the message "Error failed to load cargo settings: failed to parse Cargo.toml: invalid type: map, expected a sequence for key `package.authors` at line 8 column 16" appears.
![image](https://user-images.githubusercontent.com/59457601/218345667-9142c47b-79de-41af-ac91-095098dfcdc6.png)

### Reproduction

1. Create a new Tauri application in a cargo workspace (adding `src-tauri` to the members of the workspace) with `workspace.package` keys such as `authors = { workspace = true }`.
2. Add workspace overrides such as `authors = { workspace = true }` in `src-tauri/Config.toml`.
3. Run `cargo build`
4. Run `cargo tauri dev`

### Expected behavior

The application should have built correctly and without errors while running `cargo build` , and `cargo tauri dev` should have built and started the application.

### Platform and versions

Environment
  › OS: EndeavourOS Rolling Release X64
  › Node.js: 19.6.0
  › npm: 9.4.2
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.67.1
  › cargo: 1.67.1
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4 (no manifest),
  › tauri-build [RUST]: 1.2.1 (no manifest),
  › tao [RUST]: 0.15.8 (no manifest),
  › wry [RUST]: 0.23.4 (no manifest),

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../frontend/build
  › devPath: http://localhost:5173/
  › framework: Svelte
  › bundler: Vite

App directory structure
  ├─ node_modules
  ├─ src
  ├─ static
  ├─ build
  └─ .svelte-kit

### Stack trace

```shell
❯ cargo build
   Compiling phennel v0.0.0 (/home/ianp/Projects/phennel/src-tauri)
error: failed to run custom build command for `phennel v0.0.0 (/home/ianp/Projects/phennel/src-tauri)`

Caused by:
  process didn't exit successfully: `/home/ianp/Projects/phennel/target/debug/build/phennel-a82e079ebcf46626/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rerun-if-changed=Tauri.toml
  cargo:rustc-cfg=desktop
  This manifest requires workspace inheritance, but `inherit_workspace` hasn't been called yet

❯ cargo tauri dev
       Error failed to load cargo settings: failed to parse Cargo.toml: invalid type: map, expected a sequence for key `package.authors` at line 8 column 16
```

### Additional context

The (temporary) solution for this is to replace the workspace overrides with their actual values. This makes everything build and run correctly. However, it would be really nice to be able to have the workspace overrides.

**Comment by FabianLars** [comment] 2023-02-13 09:00
Duplicate of #6122 and #5070. Was fixed on git and will be part of v1.3. Thank you.

**Closed as not planned by FabianLars** 2023-02-13 09:00 UTC
Labels: type: bug, status: needs triage

**Comment by cogsandsquigs** [comment] 2023-02-13 15:01
Ah, I didn't know. Can't wait for v1.3 then!

**Comment by alexgladd** [comment] 2024-01-29 00:21
I'm seeing this same issue in the `2.0.0` alpha. Has this fixed been pulled forward into 2.0?

**Comment by FabianLars** [comment] 2024-01-29 09:09
@alexgladd yes, but v2 has many new features that may not be compatible with this. Could you open a new issue with the full error message and if possible a minimal reproduction example?
Unless your issue is about the license field, this was fixed here https://github.com/tauri-apps/tauri/pull/8672 (too recent to have made it in any release yet)

**Comment by alexgladd** [comment] 2024-01-30 02:11
@FabianLars I tested the `package` fields one-by-one and it does indeed just seem to be an issue with the `license` field.
