### ISSUE TITLE
[bug] Visual bugs while resizing windows

### ISSUE THREAD

**Issue by TheButlah** [tauri-apps/tauri#4012] opened 2022-04-30 07:03 UTC
### Describe the bug

Resizing the window causes strange visual bugs. Some of these happen on electron too.

Here are a few examples:
![](https://user-images.githubusercontent.com/6969415/166095505-a31f39e3-213f-4e27-b342-1484f5a371b1.gif)

https://user-images.githubusercontent.com/6969415/166095615-35693867-2a11-4340-baec-4ea636303207.mp4

https://user-images.githubusercontent.com/6969415/166095635-d3df7769-7d8a-44f4-9759-f26ad9989a8f.mp4

### Reproduction

Create an application, and resize the window. You can try our specific application out here: https://github.com/Futurabeast/slimevr-ui/tree/fb3057b80ae5246e408b341227c37568bb819c60

### Expected behavior

Window should resize normally

### Platform and versions

```shell
We observe the same problems on both machines we tested on:

> slimevr-ui@0.1.0 tauri
> tauri "info"


Environment
  › OS: Windows 10.0.19043 X64
  › Webview2: 100.0.1185.50
  › MSVC: 
      - Visual Studio Community 2019
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.9)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.4)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ config
  ├─ docs
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ src
  ├─ src-tauri
  └─ target
```
and the below one is the gif shown, but **its actually on windows 11 not windows 10. Not sure why it reports windows 10.**
```
> slimevr-ui@0.1.0 tauri
> tauri "info"


Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 101.0.1210.32
  › MSVC: 
      - Visual Studio Build Tools 2017
      - Visual Studio Build Tools 2019
      - Visual Studio Community 2019
      - Visual Studio Community 2017
  › Node.js: 16.13.0
  › npm: 8.1.3
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.7(outdated, latest: 1.0.0-rc.9)
  › @tauri-apps/api [NPM]: 1.0.0-rc.3(outdated, latest: 1.0.0-rc.4)
  › tauri [RUST]: 1.0.0-rc.6,
  › tauri-build [RUST]: 1.0.0-rc.5,
  › tao [RUST]: 0.7.0,
  › wry [RUST]: 0.14.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React
  › bundler: Webpack

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ build
  ├─ config
  ├─ docs
  ├─ node_modules
  ├─ public
  ├─ scripts
  ├─ src
  ├─ src-tauri
  └─ target
```

**Comment by bgtor** [comment] 2022-04-30 15:54
I can confirm this bug in MacOS 11.5 also. Just a HelloWorld Vuetify app (I'm kinda looking for an electron alternative).

Edit: The bug in MacOS seems to be only with vertical and diagonal resizing. 

https://user-images.githubusercontent.com/41304880/166114170-30b2019b-2de0-43e4-ac00-378aba3f2141.mp4

**Comment by lucasfernog** [comment] 2022-05-01 17:32
@bgtor can you share the output of `yarn tauri info`? I can't reproduce that one.

**Comment by bgtor** [comment] 2022-05-01 20:44
@lucasfernog  Sure

Environment
  › OS: Mac OS 11.5.0 X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:8080/
  › framework: Vue.js (Vue CLI)
  › bundler: Webpack

App directory structure
  ├─ node_modules
  ├─ public
  ├─ src-tauri
  ├─ dist_electron
  ├─ .git
  ├─ .idea
  └─ src

**Comment by TheButlah** [comment] 2022-05-11 18:15
Is there any workaround for this?

**Comment by XiaoXianThis** [comment] 2022-05-17 02:47
This seems to be a common problem😭. If you use chromium kernel browsers, they will have this problem when they change size, including edge and chrome. Not only that, I have tried many frameworks that also have this problem, such as QT quick, electron and compose desktop.

**Comment by TheButlah** [comment] 2022-05-29 03:41
Can confirm, some of these (or all of these?) happen in electron apps too.

**Comment by Pyroglyph** [comment] 2022-06-26 15:55
This does seem to be a Chromium issue, as I've personally experienced this issue with a number of Chromium-based browsers for a few years at least.
It does seem to be particularly bad with Tauri apps though. I've made a test app and I'm getting about the same resize performance as TheButlah despite having very little on the page.

Oddly enough, [this project](https://github.com/modrinth/theseus) appears to perform resizing _much better_ than any other Tauri app, Electron app, or Chromium-based browser I've ever seen. At least on my machine (Windows 11 build 22000). Can anyone confirm this?
I should add that in that project the issue is still there (because Chromium), but it's _much_ less noticable.

**Comment by amrbashir** [comment] 2022-06-26 16:04
Closing as this is an issue in chromium itself and inherently Webview2.

**Closed as completed by amrbashir** 2022-06-26 16:04 UTC
Labels: type: bug

**Comment by metkm** [comment] 2022-08-24 13:02
@Pyroglyph I tried that app and It really works way better than other apps that use chromium. Do you have any idea how they did it now?

**Comment by Pyroglyph** [comment] 2022-08-24 14:04
> @Pyroglyph I tried that app and It really works way better than other apps that use chromium. Do you have any idea how they did it now?

I did a little bit of experimenting a while ago and found that including the menu bar at the top seems to alleviate this issue for some reason. It's not completely gone, but it's noticeably better.
I would test this further on my Linux machine but I've yet to get Tauri working properly on it (some issues with gdk-3.0 and fixesproto, whatever they are).

**Comment by metkm** [comment] 2022-08-24 14:20
@Pyroglyph You are actually right the with menu It really works way better. Thanks!

@amrbashir Hey, I wonder if this issue can be opened again as adding a menu makes the resizing way better. Is this really related to webview? Here is a small comparision

**With Menu**


https://user-images.githubusercontent.com/54271295/186442358-d59c6b9e-6a6c-4c39-a325-00f94aa6819b.mp4


**Without Menu**


https://user-images.githubusercontent.com/54271295/186442382-917aebd9-3bd3-4dd0-9755-77347a29ceb4.mp4

**Comment by amrbashir** [comment] 2022-08-24 14:28
I am afraid we can't do anything about this, it is out of our control. Whenever the window is resized, we tell the webview to resize too, the resizing part is done by the webview itself and as I mentioned earlier this is a common issue with Chromium and inherently Webview2.

If you want, you can open a bug report at https://github.com/MicrosoftEdge/WebView2Feedback.

**Comment by Djaymare** [comment] 2022-11-30 13:57
Hello ! It seems related to this issue : [Nasty visual artefacts on resize](https://github.com/MicrosoftEdge/WebView2Feedback/issues/906)

But we can't change the background color for now since #1564

**Comment by amrbashir** [comment] 2023-02-28 13:01
For whatever reason, putting the thread to sleep while resizing seems to improve the resizing behavior on Windows see #6322

you can test using this example
```rs
 tauri::Builder::default()
        .on_window_event(|e| {
            if let WindowEvent::Resized(_) = e.event() {
                std::thread::sleep(std::time::Duration::from_nanos(1));
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```

**Comment by TheButlah** [comment] 2023-03-01 07:47
> For whatever reason, putting the thread to sleep while resizing seems to improve the resizing behavior on Windows see #6322
> 
> you can test using this example
> 
> ```rust
>  tauri::Builder::default()
>         .on_window_event(|e| {
>             if let WindowEvent::Resized(_) = e.event() {
>                 std::thread::sleep(std::time::Duration::from_nanos(1));
>             }
>         })
>         .run(tauri::generate_context!())
>         .expect("error while running tauri application");
> ```

here is a demo of this suggested change. The left is with the sleep, the right is without.

https://user-images.githubusercontent.com/6969415/222076263-40429839-5f1f-4b29-b80f-a982f21911ba.mp4

Its not a perfect fix, but definitely an improvement.

**Comment by FabianLars** [comment] 2023-03-01 07:54
Hmm, the difference for decorated windows was much bigger than this from what i've seen so far. i never checked undecorated windows tbh.

Could you try `std::time::Duration::from_millis(1)` (millis instead of nanos) just to double check?

**Comment by TheButlah** [comment] 2023-03-01 08:03
> Could you try `std::time::Duration::from_millis(1)` (millis instead of nanos) just to double check?

Hard to tell if there is a difference:

https://user-images.githubusercontent.com/6969415/222079625-df55b053-e878-418c-9f41-1089cea044d9.mp4
