### ISSUE TITLE
error: failed to run custom build command for `webview_official v0.0.2`

### ISSUE THREAD

**Issue by tinybright** [tauri-apps/tauri#928] opened 2020-08-06 05:24 UTC
**Describe the bug**
failed to run custom build command for `webview_official v0.0.2`

**To Reproduce**
1.run 
`yarn tauri build --debug`
2. See error 
`failed to run custom build command for `webview_official v0.0.2``

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8720949/89494085-0a18bf80-d7e8-11ea-8e05-08de923279fa.png)

**Platform and Versions (please complete the following information):**

OS:Windows_NT(10.0.18363) - win32/x64
Node:12.10.0
NPM: 6.9.0
Yarn:1.19.1
Rustc:1.45.2

**Additional context**
PS Y:\a_project\a_php\d1> yarn tauri info
yarn run v1.19.1
warning package.json: No license field
$ Y:\a_project\a_php\d1\node_modules\.bin\tauri info
[tauri]: running info

Operating System - Windows_NT(10.0.18363) - win32/x64
Microsoft Edge - 44.18362.449.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.10.0
  tauri.js - 0.11.1

Rust environment
  rustc - 1.45.2
  cargo - 1.45.1
  tauri-bundler - 0.9.1

Global packages
  NPM - 6.9.0
  yarn - 1.19.1

App directory structure
/.idea
/dist
/node_modules
/src-tauri

App
  tauri.rs - 0.9.1
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - ../dist
  devPath - http://localhost:4000
Done in 6.11s.

**Stack Trace**

PS Y:\a_project\a_php\d1> yarn tauri build --debug
yarn run v1.19.1
warning package.json: No license field
$ Y:\a_project\a_php\d1\node_modules\.bin\tauri build --debug
[tauri]: running build
 app:spawn Running "cargo tauri-bundler --features embedded-server" +0ms

   Compiling webview_official v0.0.2
   Compiling d-1 v0.1.0 (Y:\a_project\a_php\d1\src-tauri)
   Compiling tauri v0.9.1
error: failed to run custom build command for `webview_official v0.0.2`

Caused by:
  process didn't exit successfully: `Y:\a_project\a_php\d1\src-tauri\target\debug\build\webview_official-2ced1dda416ff47
5\build-script-build` (exit code: 1)
--- stdout
cargo:rustc-link-lib=windowsapp
cargo:rustc-link-lib=user32
cargo:rustc-link-lib=oleaut32
cargo:rustc-link-lib=ole32
cargo:rustc-link-search=C:\Users\shijun\.cargo\registry\src\github.com-1ecc6299db9ec823\webview_official-0.0.2\webview-o
fficial/script/Microsoft.Web.WebView2.0.9.488/build/native\x64
cargo:rustc-link-lib=WebView2Loader.dll
cargo:rerun-if-changed=webview-official/webview.h
cargo:rerun-if-changed=webview-official/webview.cc
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-pc-windows-msvc")
CXX_x86_64-pc-windows-msvc = None
CXX_x86_64_pc_windows_msvc = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-pc-windows-msvc = None
CXXFLAGS_x86_64_pc_windows_msvc = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
DEBUG = Some("true")
CXX_x86_64-pc-windows-msvc = None
CXX_x86_64_pc_windows_msvc = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-pc-windows-msvc = None
CXXFLAGS_x86_64_pc_windows_msvc = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
CXX_x86_64-pc-windows-msvc = None
CXX_x86_64_pc_windows_msvc = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-pc-windows-msvc = None
CXXFLAGS_x86_64_pc_windows_msvc = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
CXX_x86_64-pc-windows-msvc = None
CXX_x86_64_pc_windows_msvc = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-pc-windows-msvc = None
CXXFLAGS_x86_64_pc_windows_msvc = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro"
 "-I" "webview-official/webview.h" "-I" "webview-official/script" "-W4" "-FoY:\\a_project\\a_php\\d1\\src-tauri\\target\
\debug\\build\\webview_official-348073e42499b04c\\out\\webview-official/webview.o" "-c" "webview-official/webview.cc"
webview.cc
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\ppltasks.h(1807): warning C4530: C++ exception handler us
ed, but unwind semantics are not enabled. Specify /EHsc
c:\users\shijun\.cargo\registry\src\github.com-1ecc6299db9ec823\webview_official-0.0.2\webview-official\webview.h(195):
warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt\winrt/base.h(19): fatal error C1083: Cannot open in
clude file: 'optional': No such file or directory
exit code: 2

--- stderr

error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe" "-nologo" "-MD"
"-Z7" "-Brepro" "-I" "webview-official/webview.h" "-I" "webview-official/script" "-W4" "-FoY:\\a_project\\a_php\\d1\\src
-tauri\\target\\debug\\build\\webview_official-348073e42499b04c\\out\\webview-official/webview.o" "-c" "webview-official
/webview.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).

error: `Result of `cargo build` operation was unsuccessful: exit code: 101`

 app:spawn Command "cargo" failed with exit code: 1 +3ms

 app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +15ms

 app:tauri Shutting down tauri process... +16ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by EmNudge** [comment] 2020-08-15 07:26
Reinstalled the tooling on Windows 10 (npm) and got this error. Working fine on a MacBook.

**Comment by jbolda** [comment] 2020-08-15 13:20
I ran @EmNudge's project and it worked fine. Did you have any luck resolving this @tinybright?

**Comment by jbolda** [comment] 2020-08-15 13:53
Just as a double check, here is the output of `cargo tree` so you can see what deps I have.

```shell
❯ cargo tree
color-picker v0.1.0 (C:\Users\Jacob\Documents\dev\tauri\tauri-color-picker\src-tauri)
├── serde v1.0.115
│   └── serde_derive v1.0.115
│       ├── proc-macro2 v1.0.19
│       │   └── unicode-xid v0.2.1
│       ├── quote v1.0.7
│       │   └── proc-macro2 v1.0.19 (*)
│       └── syn v1.0.38
│           ├── proc-macro2 v1.0.19 (*)
│           ├── quote v1.0.7 (*)
│           └── unicode-xid v0.2.1
├── serde_json v1.0.57
│   ├── itoa v0.4.6
│   ├── ryu v1.0.5
│   └── serde v1.0.115 (*)
└── tauri v0.9.1
    ├── anyhow v1.0.32
    ├── base64 v0.12.3
    ├── envmnt v0.8.4
    │   ├── fsio v0.1.3
    │   └── indexmap v1.5.1
    │       └── hashbrown v0.8.2
    │           [build-dependencies]
    │           └── autocfg v1.0.0
    │       [build-dependencies]
    │       └── autocfg v1.0.0
    ├── lazy_static v1.4.0
    ├── once_cell v1.4.0
    ├── phf v0.8.0
    │   └── phf_shared v0.8.0
    │       └── siphasher v0.3.3
    ├── runas v0.2.1
    │   └── which v3.1.1
    │       ├── failure v0.1.8
    │       │   └── backtrace v0.3.50
    │       │       ├── addr2line v0.13.0
    │       │       │   └── gimli v0.22.0
    │       │       ├── cfg-if v0.1.10
    │       │       ├── libc v0.2.74
    │       │       ├── miniz_oxide v0.4.0
    │       │       │   └── adler v0.2.3
    │       │       ├── object v0.20.0
    │       │       └── rustc-demangle v0.1.16
    │       └── libc v0.2.74
    │   [build-dependencies]
    │   └── cc v1.0.58
    ├── serde v1.0.115 (*)
    ├── serde_json v1.0.57 (*)
    ├── tauri-api v0.7.3
    │   ├── anyhow v1.0.32
    │   ├── attohttpc v0.15.0
    │   │   ├── flate2 v1.0.16
    │   │   │   ├── cfg-if v0.1.10
    │   │   │   ├── crc32fast v1.2.0
    │   │   │   │   └── cfg-if v0.1.10
    │   │   │   ├── libc v0.2.74
    │   │   │   └── miniz_oxide v0.4.0 (*)
    │   │   ├── http v0.2.1
    │   │   │   ├── bytes v0.5.6
    │   │   │   ├── fnv v1.0.7
    │   │   │   └── itoa v0.4.6
    │   │   ├── log v0.4.11
    │   │   │   └── cfg-if v0.1.10
    │   │   ├── native-tls v0.2.4
    │   │   │   └── schannel v0.1.19
    │   │   │       ├── lazy_static v1.4.0
    │   │   │       └── winapi v0.3.9
    │   │   ├── serde v1.0.115 (*)
    │   │   ├── serde_json v1.0.57 (*)
    │   │   ├── serde_urlencoded v0.6.1
    │   │   │   ├── dtoa v0.4.6
    │   │   │   ├── itoa v0.4.6
    │   │   │   ├── serde v1.0.115 (*)
    │   │   │   └── url v2.1.1
    │   │   │       ├── idna v0.2.0
    │   │   │       │   ├── matches v0.1.8
    │   │   │       │   ├── unicode-bidi v0.3.4
    │   │   │       │   │   └── matches v0.1.8
    │   │   │       │   └── unicode-normalization v0.1.13
    │   │   │       │       └── tinyvec v0.3.3
    │   │   │       ├── matches v0.1.8
    │   │   │       └── percent-encoding v2.1.0
    │   │   └── url v2.1.1 (*)
    │   ├── dirs v3.0.1
    │   │   └── dirs-sys v0.3.5
    │   │       └── winapi v0.3.9
    │   ├── either v1.6.0
    │   ├── flate2 v1.0.16 (*)
    │   ├── http v0.2.1 (*)
    │   ├── nfd v0.0.4
    │   │   [build-dependencies]
    │   │   └── gcc v0.3.55
    │   ├── notify-rust v4.0.0
    │   │   └── winrt-notification v0.2.2
    │   │       ├── strum v0.8.0
    │   │       ├── strum_macros v0.8.0
    │   │       │   ├── quote v0.3.15
    │   │       │   └── syn v0.11.11
    │   │       │       ├── quote v0.3.15
    │   │       │       ├── synom v0.11.3
    │   │       │       │   └── unicode-xid v0.0.4
    │   │       │       └── unicode-xid v0.0.4
    │   │       ├── winapi v0.3.9
    │   │       ├── winrt v0.4.0
    │   │       │   └── winapi v0.3.9
    │   │       └── xml-rs v0.6.1
    │   │           └── bitflags v0.9.1
    │   ├── once_cell v1.4.0
    │   ├── rand v0.7.3
    │   │   ├── getrandom v0.1.14
    │   │   │   └── cfg-if v0.1.10
    │   │   ├── rand_chacha v0.2.2
    │   │   │   ├── ppv-lite86 v0.2.8
    │   │   │   └── rand_core v0.5.1
    │   │   │       └── getrandom v0.1.14 (*)
    │   │   ├── rand_core v0.5.1 (*)
    │   │   └── rand_pcg v0.2.1
    │   │       └── rand_core v0.5.1 (*)
    │   ├── semver v0.10.0
    │   │   └── semver-parser v0.7.0
    │   ├── serde v1.0.115 (*)
    │   ├── serde_json v1.0.57 (*)
    │   ├── serde_repr v0.1.6
    │   │   ├── proc-macro2 v1.0.19 (*)
    │   │   ├── quote v1.0.7 (*)
    │   │   └── syn v1.0.38 (*)
    │   ├── tar v0.4.29
    │   │   └── filetime v0.2.12
    │   │       ├── cfg-if v0.1.10
    │   │       └── winapi v0.3.9
    │   ├── tauri-dialog v0.1.0
    │   │   └── tauri-dialog-sys v0.1.0
    │   │       [build-dependencies]
    │   │       ├── cc v1.0.58
    │   │       └── pkg-config v0.3.18
    │   ├── tauri-utils v0.5.1
    │   │   ├── anyhow v1.0.32
    │   │   ├── sysinfo v0.10.5
    │   │   │   ├── cfg-if v0.1.10
    │   │   │   ├── doc-comment v0.3.3
    │   │   │   ├── libc v0.2.74
    │   │   │   ├── ntapi v0.3.4
    │   │   │   │   └── winapi v0.3.9
    │   │   │   ├── rayon v1.3.1
    │   │   │   │   ├── crossbeam-deque v0.7.3
    │   │   │   │   │   ├── crossbeam-epoch v0.8.2
    │   │   │   │   │   │   ├── cfg-if v0.1.10
    │   │   │   │   │   │   ├── crossbeam-utils v0.7.2
    │   │   │   │   │   │   │   ├── cfg-if v0.1.10
    │   │   │   │   │   │   │   └── lazy_static v1.4.0
    │   │   │   │   │   │   │   [build-dependencies]
    │   │   │   │   │   │   │   └── autocfg v1.0.0
    │   │   │   │   │   │   ├── lazy_static v1.4.0
    │   │   │   │   │   │   ├── maybe-uninit v2.0.0
    │   │   │   │   │   │   ├── memoffset v0.5.5
    │   │   │   │   │   │   │   [build-dependencies]
    │   │   │   │   │   │   │   └── autocfg v1.0.0
    │   │   │   │   │   │   └── scopeguard v1.1.0
    │   │   │   │   │   │   [build-dependencies]
    │   │   │   │   │   │   └── autocfg v1.0.0
    │   │   │   │   │   ├── crossbeam-utils v0.7.2 (*)
    │   │   │   │   │   └── maybe-uninit v2.0.0
    │   │   │   │   ├── either v1.6.0
    │   │   │   │   └── rayon-core v1.7.1
    │   │   │   │       ├── crossbeam-deque v0.7.3 (*)
    │   │   │   │       ├── crossbeam-queue v0.2.3
    │   │   │   │       │   ├── cfg-if v0.1.10
    │   │   │   │       │   ├── crossbeam-utils v0.7.2 (*)
    │   │   │   │       │   └── maybe-uninit v2.0.0
    │   │   │   │       ├── crossbeam-utils v0.7.2 (*)
    │   │   │   │       ├── lazy_static v1.4.0
    │   │   │   │       └── num_cpus v1.13.0
    │   │   │   │           └── libc v0.2.74
    │   │   │   │   [build-dependencies]
    │   │   │   │   └── autocfg v1.0.0
    │   │   │   └── winapi v0.3.9
    │   │   └── thiserror v1.0.20
    │   │       └── thiserror-impl v1.0.20
    │   │           ├── proc-macro2 v1.0.19 (*)
    │   │           ├── quote v1.0.7 (*)
    │   │           └── syn v1.0.38 (*)
    │   ├── tempfile v3.1.0
    │   │   ├── cfg-if v0.1.10
    │   │   ├── rand v0.7.3 (*)
    │   │   ├── remove_dir_all v0.5.3
    │   │   │   └── winapi v0.3.9
    │   │   └── winapi v0.3.9
    │   ├── thiserror v1.0.20 (*)
    │   └── zip v0.5.6
    │       ├── bzip2 v0.3.3
    │       │   ├── bzip2-sys v0.1.9+1.0.8
    │       │   │   └── libc v0.2.74
    │       │   │   [build-dependencies]
    │       │   │   ├── cc v1.0.58
    │       │   │   └── pkg-config v0.3.18
    │       │   └── libc v0.2.74
    │       ├── crc32fast v1.2.0 (*)
    │       ├── flate2 v1.0.16 (*)
    │       ├── podio v0.1.7
    │       └── time v0.1.43
    │           ├── libc v0.2.74
    │           └── winapi v0.3.9
    ├── tauri_includedir v0.6.0
    │   ├── flate2 v1.0.16 (*)
    │   └── phf v0.8.0 (*)
    ├── thiserror v1.0.20 (*)
    ├── threadpool v1.8.1
    │   └── num_cpus v1.13.0 (*)
    ├── urlencoding v1.1.1
    ├── uuid v0.8.1
    │   └── rand v0.7.3 (*)
    ├── webbrowser v0.5.5
    │   ├── widestring v0.4.2
    │   └── winapi v0.3.9
    └── webview_official v0.0.2
        [build-dependencies]
        ├── cc v1.0.58
        └── pkg-config v0.3.18
    [build-dependencies]
    ├── cfg_aliases v0.1.0
    └── tauri_includedir_codegen v0.6.2
        ├── flate2 v1.0.16 (*)
        ├── phf_codegen v0.8.0
        │   ├── phf_generator v0.8.0
        │   │   ├── phf_shared v0.8.0 (*)
        │   │   └── rand v0.7.3 (*)
        │   └── phf_shared v0.8.0 (*)
        └── walkdir v2.3.1
            ├── same-file v1.0.6
            │   └── winapi-util v0.1.5
            │       └── winapi v0.3.9
            ├── winapi v0.3.9
            └── winapi-util v0.1.5 (*)
[build-dependencies]
└── winres v0.1.11
    └── toml v0.5.6
        └── serde v1.0.115 (*)
```

**Comment by tinybright** [comment] 2020-08-17 02:18
@jbolda I'm new bee.I searched the error and found no solutiuon.

**Comment by jbolda** [comment] 2020-08-28 21:13
We pushed a new version a handful of days ago with an updated webview_rust. Would be worth giving a test 🤞

**Comment by tinybright** [comment] 2020-09-03 08:43
@jbolda I will have a try.

**Comment by jswhisperer** [comment] 2020-10-03 00:05
Broken on Ubuntu 20.04

tauri -v 0.12.0
tauri-bundler v0.9.3
rustc 1.46.0

```
❯ tauri dev     
[tauri]: running dev
 app:spawn Running "cargo run" +0ms

   Compiling libc v0.2.78
   Compiling cfg-if v0.1.10
   Compiling autocfg v1.0.1
   Compiling pkg-config v0.3.18
   Compiling cc v1.0.60
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling getrandom v0.1.15
   Compiling syn v1.0.42
   Compiling lazy_static v1.4.0
   Compiling maybe-uninit v2.0.0
   Compiling ppv-lite86 v0.2.9
   Compiling crc32fast v1.2.0
   Compiling adler32 v1.2.0
   Compiling siphasher v0.3.3
   Compiling rayon-core v1.8.1
   Compiling scopeguard v1.1.0
   Compiling serde_derive v1.0.116
   Compiling tinyvec v0.3.4
   Compiling matches v0.1.8
   Compiling serde v1.0.116
   Compiling bitflags v1.2.1
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.30
   Compiling log v0.4.11
   Compiling itoa v0.4.6
   Compiling doc-comment v0.3.3
   Compiling ryu v1.0.5
   Compiling serde_json v1.0.58
   Compiling percent-encoding v2.1.0
   Compiling byteorder v1.3.4
   Compiling sysinfo v0.10.5
   Compiling either v1.6.1
   Compiling gcc v0.3.55
   Compiling same-file v1.0.6
   Compiling anyhow v1.0.32
   Compiling native-tls v0.2.4
   Compiling bytes v0.5.6
   Compiling dtoa v0.4.6
   Compiling once_cell v1.4.1
   Compiling openssl-probe v0.1.2
   Compiling fnv v1.0.7
   Compiling tauri-api v0.7.4
   Compiling remove_dir_all v0.5.3
   Compiling cfg_aliases v0.1.0
   Compiling hashbrown v0.9.1
   Compiling semver-parser v0.7.0
   Compiling fsio v0.1.3
   Compiling urlencoding v1.1.1
   Compiling tauri-nuxt v0.1.0 (/home/gnb/Sites/tests/tauri-nuxt/src-tauri)
   Compiling base64 v0.12.3
   Compiling webbrowser v0.5.5
   Compiling miniz_oxide v0.3.7
   Compiling phf_shared v0.8.0
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.6
   Compiling crossbeam-epoch v0.8.2
   Compiling rayon v1.4.1
   Compiling indexmap v1.6.0
   Compiling unicode-bidi v0.3.4
   Compiling foreign-types v0.3.2
   Compiling libdbus-sys v0.2.1
   Compiling unicode-normalization v0.1.13
   Compiling walkdir v2.3.1
   Compiling http v0.2.1
   Compiling semver v0.10.0
   Compiling openssl-sys v0.9.58
   Compiling bzip2-sys v0.1.9+1.0.8
   Compiling tauri-dialog-sys v0.1.0
   Compiling webview-official-sys v0.1.0
   Compiling phf v0.8.0
   Compiling nfd v0.0.4
   Compiling idna v0.2.0
error: failed to run custom build command for `tauri-dialog-sys v0.1.0`

Caused by:
  process didn't exit successfully: `/home/gnb/Sites/tests/tauri-nuxt/src-tauri/target/debug/build/tauri-dialog-sys-aded46d949c2da5b/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=GTK+_3.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GTK+_3.0_STATIC
  cargo:rerun-if-env-changed=GTK+_3.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"gtk+-3.0\" \"gtk+-3.0 >= 2.8\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package gtk+-3.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `gtk+-3.0.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'gtk+-3.0\' found\nPackage gtk+-3.0 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `gtk+-3.0.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'gtk+-3.0\' found\n" } }', /home/gnb/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-dialog-sys-0.1.0/build.rs:17:8
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jswhisperer** [comment] 2020-10-03 01:15
found my issue... had to set PKG_CONFIG a bunch of deps weren't found this stackoverflow was helpful
https://stackoverflow.com/a/50038996/1151520
Also had to remove "gcc" from homebrew installation and use apt install instead

**Closed as completed** 2020-10-04 13:56 UTC
Labels: type: bug

**Comment by jswhisperer** [comment] 2021-11-15 13:47
Hitting the same or similar issue when trying to use the system tray
`error: failed to run custom build command for `tauri-libappindicator-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/ziggy/Sites/my-tauri-app/src-tauri/target/debug/build/tauri-libappindicator-sys-8d66f8fa8dba885f/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=appindicator3
  cargo:rerun-if-env-changed=APPINDICATOR3_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=APPINDICATOR3_STATIC
  cargo:rerun-if-env-changed=APPINDICATOR3_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=APPINDICATOR3_0.1_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=APPINDICATOR3_0.1_STATIC
  cargo:rerun-if-env-changed=APPINDICATOR3_0.1_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'libappindicator3 library not found!', /home/ziggy/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-libappindicator-sys-0.1.2/build.rs:6:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
`
Similar to https://githubmemory.com/repo/qdot/systray-rs/issues/47

I think my PKG_CONFIG is set correctly, but even after installing libappindicator-gtk3-devel the .pc file is not created,

I'm using Pop_os instead of vanilla Ubuntu

**Comment by nothingismagick** [comment] 2021-11-15 14:42
Please file a new issue @gregpalaci - this is something entirely different. :)
