### ISSUE TITLE
[bug] MacOS Keyboard Shortcuts ignored in Tauri 1.2.0

### ISSUE THREAD

**Issue by Layendan** [tauri-apps/tauri#5586] opened 2022-11-09 00:09 UTC
### Describe the bug

Using default keyboard shortcuts for Tauri apps (such as <kbd>⌘Q</kbd> or <kbd>⌘W</kbd>) result in the mouse disappearing until moved again and the window not changing.
Clicking on the option in the menu dropdown works correctly, only the keyboard shortcuts do not work as intended.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/46062388/200702337-abff0849-62b1-4f2e-b04c-c80d32425acc.png">

### Reproduction

1. Update to latest Tauri version
2. Run app on MacOS
3. Use keyboard shortcuts such as <kbd>⌘Q</kbd>, <kbd>⌘W</kbd>, <kbd>⌘H</kbd>, or <kbd>⌘M</kbd>...

### Expected behavior

App should respond to keyboard shortcut accordingly and run appropriate action.

### Platform and versions

```
Environment
  › OS: Mac OS 13.0.0 X64
  › Node.js: 18.0.0
  › npm: 8.6.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.2.0
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.0,
  › tauri-build [RUST]: 1.2.0,
  › tao [RUST]: 0.15.2,
  › wry [RUST]: 0.22.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ Misc
  ├─ node_modules
  ├─ static
  ├─ .github
  ├─ src-tauri
  ├─ .svelte-kit
  ├─ build
  ├─ .git
  ├─ .vscode
  └─ src
```

### Additional context

Correctly runs in Tauri 1.1.1
Previous platform information (this runs as intended):
```
Environment
  › OS: Mac OS 13.0.0 X64
  › Node.js: 18.0.0
  › npm: 8.6.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.65.0
  › cargo: 1.65.0
  › Rust toolchain: stable-aarch64-apple-darwin 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ Misc
  ├─ node_modules
  ├─ static
  ├─ .github
  ├─ src-tauri
  ├─ .svelte-kit
  ├─ build
  ├─ .git
  ├─ .vscode
  └─ src
```

**Comment by FabianLars** [comment] 2022-11-09 00:11
Duplicate of https://github.com/tauri-apps/tauri/issues/5579 - thanks for the report

**Closed as not planned by FabianLars** 2022-11-09 00:11 UTC
Labels: type: bug, status: upstream, status: needs triage

**Comment by lucasfernog** [comment] 2022-11-09 03:56
Fixed in tao v0.15.3. Please run `cargo update` in the `src-tauri` folder.

**Comment by tw93** [comment] 2022-11-25 06:20
when i run `npm run tauri build -- --target universal-apple-darwin`, the bug still exists.
but when i run `npm run tauri build -- --target x86_64-apple-darwin` and m1 is ok
and `npm run dev` is ok

**Comment by JonasKruckenberg** [comment] 2022-11-25 06:26
> when i run `npm run tauri build -- --target universal-apple-darwin`, the bug still exists.
> 
> but when i run `npm run tauri build -- --target x86_64-apple-darwin` and m1 is ok
> 
> and `npm run dev` is ok

Please don't spam please plus these issues are closed, so if you're experiencing a bug please file a new issue referencing these existing ones instead.
