### ISSUE TITLE
[feat] Ability to enable SharedArrayBuffer

### ISSUE THREAD

**Issue by FacoBackup** [tauri-apps/tauri#5320] opened 2022-10-01 17:11 UTC
### Describe the problem

Since the spectre thing, most (if not all) browsers disabled SharedArrayBuffer support by default, but since we are working to make a desktop app I think the ability to re-enable it is necessary.

### Describe the solution you'd like

Ability to enable SharedArrayBuffer support before window loads.

### Alternatives considered

Ability to load browser flags.

**Comment by amrbashir** [comment] 2022-10-01 17:53
duplicate of #1522

**Closed as not planned by amrbashir** 2022-10-01 17:53 UTC
Labels: type: feature request
