### ISSUE TITLE
[bug] Windows Installer package on Windows 7 32-bit

### ISSUE THREAD

**Issue by calvinludwig** [tauri-apps/tauri#4461] opened 2022-06-24 17:31 UTC
### Describe the bug

I am testing tauri on Windows 7 32-bit.
After generating the release in a Windows 11 64-bit machine with
`tauri build --target i686-pc-windows-msvc`
and executing the .msi in a 32-bit win7 machine, I got the error bellow.

![image](https://user-images.githubusercontent.com/31071765/175611553-37e2ae52-0821-43fd-a3f1-5c993c0d9ab6.png)

### Platform and versions

```shell
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 102.0.1245.44
  › MSVC: 
      - Visual Studio Build Tools 2019
      - Visual Studio Community 2022
  › Node.js: 16.15.1
  › npm: 8.12.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
```

**Comment by lucasfernog** [comment] 2022-06-24 17:35
Duplicate of #2882. I'll be investigating this next week.

**Closed as completed by lucasfernog** 2022-06-24 17:35 UTC
Labels: type: bug
