### ISSUE TITLE
[bug] html drag and drop works in MacOS but fail in Linux

### ISSUE THREAD

**Issue by GuCarpenter** [tauri-apps/tauri#12052] opened 2024-12-25 12:48 UTC
### Describe the bug

I'm developing a simple calendar where I can drag and drop a event in a calendar column, I use react DragEvent, I have set "dragDropEnabled" to false, however I find it works in browser and macos, but fails in Linux.
No message in console or in debug mode.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Linux Mint 22.0.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.46.4
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.83.0 (90b35a623 2024-11-26)
    ✔ cargo: 1.83.0 (5ffbef321 2024-10-29)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 23.3.0
    - npm: 10.9.0

[-] Packages
    - tauri 🦀: 2.1.1
    - tauri-build 🦀: 2.0.3
    - wry 🦀: 0.47.2
    - tao 🦀: 0.30.8
    - tauri-cli 🦀: 2.1.0
    - @tauri-apps/api : 2.1.1
    - @tauri-apps/cli : 2.1.0

[-] Plugins
    - tauri-plugin-fs 🦀: 2.2.0
    - @tauri-apps/plugin-fs : 2.2.0
    - tauri-plugin-store 🦀: 2.2.0
    - @tauri-apps/plugin-store : 2.2.0
    - tauri-plugin-dialog 🦀: 2.2.0
    - @tauri-apps/plugin-dialog : 2.2.0
    - tauri-plugin-shell 🦀: 2.0.2
    - @tauri-apps/plugin-shell : 2.0.1 (outdated, latest: 2.2.0)
    - tauri-plugin-sql 🦀: 2.2.0
    - @tauri-apps/plugin-sql : 2.2.0

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-12-25 22:24
Closing as duplicate of #6695

**Closed as not planned by FabianLars** 2024-12-25 22:24 UTC
Labels: type: bug, platform: Linux, status: needs triage
