### ISSUE TITLE
[feat] Wish tauri not limit backend language

### ISSUE THREAD

**Issue by joebnb** [tauri-apps/tauri#7411] opened 2023-07-12 06:04 UTC
### Describe the problem

current use tauri to devlop a apps the developer need learn tauri API and some Rust programming basics.and it design a permission system like fs/folder etc.but i think we use Rust to programming backend need learn a lot of things,althought learning this is interesting,but it take a lot of work. if we can use any language as backend language it would be better.

### Describe the solution you'd like

as title say, i wish taurl v2 not limit backend by design.

### Alternatives considered

just like tauri frontend  inject tauri service into page,backend we can provide a service for developers.

if we make some step to this，we'll use kotlin/rust in android also we can use swift in ios app develop

**Comment by FabianLars** [comment] 2023-07-12 07:42
Duplicate of https://github.com/tauri-apps/tauri/issues/4670 - it's planned but won't be implemented anytime soon. So if you need it asap you'll have to use the sidecar feature fow now :/

**Closed as not planned by FabianLars** 2023-07-12 07:42 UTC
Labels: type: feature request
