### ISSUE TITLE
[bug] Something needs to be done to limit Roaming size exceeding 200MB

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri#8145] opened 2023-10-30 20:01 UTC
### Describe the bug

The webview folder per Tauri app `C:\Users\maste\AppData\Local\R2-T2\EBWebView\` exceed 200MB. A lot is do to cache dirs. 
For example, in EBWebView\GrShaderCache\GPUCache, 

![image](https://github.com/tauri-apps/tauri/assets/21298211/83a6393f-1ec0-40fc-9160-439307c1d434)

10MB just when I first started working on the app last year.

![image](https://github.com/tauri-apps/tauri/assets/21298211/f87399ce-fde4-4afa-911d-e4c052b0234c)

10MB just in the parent directory after deleting files from 2022.

There's many files like this but it's actually making Tauri seem just as careless about user's hard drives. My SSD of 512GB can easily fill up due to death by a thousand cuts.

![image](https://github.com/tauri-apps/tauri/assets/21298211/c94e9e36-3228-46fe-a2af-97cdb0554d21)

### Reproduction

Install any Tauri app, and just keep checking the cache directory:
![image](https://github.com/tauri-apps/tauri/assets/21298211/52ba2d59-a98d-4884-993c-9792d96b0473)
This app is just a website wrapper over Google Keep! 
https://github.com/elibroftw/google-keep-desktop-app

### Expected behavior

Reasonable cache dir less than 50MB.

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.8.1
    - pnpm: 8.10.0
    - yarn: 1.22.19
    - npm: 10.1.0
```

### Additional context

It's the Default/Cache dir that takes up the most space by the way.
![image](https://github.com/tauri-apps/tauri/assets/21298211/9903d70b-905f-4f5d-b561-2513bca92d86)

**Comment by Tek-Ce** [comment] 2023-11-01 11:29
On 30 Oct 2023 11:02 pm, Elijah Lopez ***@***.***> wrote:
Describe the bug
The webview folder per Tauri app C:\Users\maste\AppData\Local\R2-T2\EBWebView\ exceed 200MB. A lot is do to cache dirs.
For example, in EBWebView\GrShaderCache\GPUCache,

10MB just when I first started working on the app last year.

10MB just in the parent directory after deleting files from 2022.
There's many files like this but it's actually making Tauri seem just as careless about user's hard drives. My SSD of 512GB can easily fill up due to death by a thousand cuts.

Reproduction
Install any Tauri app, and just keep checking the cache directory:

This app is just a website wrapper over Google Keep!
https://github.com/elibroftw/google-keep-desktop-app
Expected behavior
Reasonable cache dir less than 50MB.
Platform and versions
[✔] Environment
    - OS: Windows 10.0.19045 X64
    ✔ WebView2: 118.0.2088.76
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.73.0 (cc66ad468 2023-10-03)
    ✔ Cargo: 1.73.0 (9c4383fb5 2023-08-26)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.8.1
    - pnpm: 8.10.0
    - yarn: 1.22.19
    - npm: 10.1.0

Stack trace
No response
Additional context
No response

**Comment by ReactorScram** [comment] 2023-12-07 19:35
For now would the workaround be to just periodically delete that whole cache folder when Rust `main` starts, before initializing Tauri? (assuming single-instance)

I think this happens to anything that inherits from Chromium - I've seen similar behavior with Chromium itself on Linux. It just gradually accumulates shader caches and never gets rid of them. That "Default" folder is the default browser profile. Probably happens to Electron apps, too, they might have a go-to workaround you could borrow?

**Comment by SmilerRyan** [comment] 2024-11-16 06:23
if it was me i would have an option to disable cache, for most apps it's fine to just delete the whole folder and it works just fine as settings are stored in localstorage, cookies or seperately.

**Comment by amrbashir** [comment] 2024-11-18 17:55
I honestly don't think tauri should delete this on its own as it contains data of your application, like localstorage, indexeddb and cookies which alot of our users to store different types of data.

I am gonna go ahead and close this issue and leave it up to you to decide whether to delete it or not. 

There is also a new API in v2 that is relevant to this https://docs.rs/tauri/latest/tauri/webview/struct.Webview.html#method.clear_all_browsing_data

**Closed as completed by amrbashir** 2024-11-18 17:55 UTC
Labels: type: bug, status: needs triage
