### ISSUE TITLE
[bug] Module not found @tauri-apps/cli-win32-arm64-msvc

### ISSUE THREAD

**Issue by MassimilianoMontagni** [tauri-apps/tauri#6846] opened 2023-05-03 13:41 UTC
### Describe the bug

I can't compile a Tauri app on Windows 11 ARM64 (VM on a MacBookPro M1) because the `@tauri-apps/cli-win32-arm64-msvc` module is not found

### Reproduction

1. create a new project (for convenience I used `iwr -useb https://create.tauri.app/ps | iex`
2. `cd tauri-app`
3. `npm i`
4.  `npm run tauri dev`

### Expected behavior

Successful compilation

### Platform and versions

```text
I can't run those commands but I can create the output by my self

  › nodejs: v20.0.0 (I even tried with the 18.16 LTS)
  › npm: 9.6.5
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.26.0 (5af9b9484 2023-04-05)
  › rustc: 1.69.0 (84c898d65 2023-04-16)
  › cargo: 1.69.0 (6e9a83356 2023-04-12)
  › Rust toolchain: stable-aarch64-pc-windows-msvc

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Rollup

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

### Stack trace

```text
PS C:\Users\user\tauri-app> npm run tauri dev

> tauri-app@0.0.0 tauri
> tauri dev

C:\Users\user\tauri-app\node_modules\@tauri-apps\cli\index.js:234
    throw loadError
    ^

Error: Cannot find module '@tauri-apps/cli-win32-arm64-msvc'
Require stack:
- C:\Users\user\tauri-app\node_modules\@tauri-apps\cli\index.js
- C:\Users\user\tauri-app\node_modules\@tauri-apps\cli\main.js
- C:\Users\user\tauri-app\node_modules\@tauri-apps\cli\tauri.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Module._load (node:internal/modules/cjs/loader:928:27)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (C:\Users\user\tauri-app\node_modules\@tauri-apps\cli\index.js:93:29)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\tauri-app\\node_modules\\@tauri-apps\\cli\\index.js',
    'C:\\Users\\user\\tauri-app\\node_modules\\@tauri-apps\\cli\\main.js',
    'C:\\Users\\user\\tauri-app\\node_modules\\@tauri-apps\\cli\\tauri.js'
  ]
}

Node.js v20.0.0
```

**Comment by FabianLars** [comment] 2023-05-03 13:45
This is caused by missing arm64 support in the `ring` crate which means we can't provide prebuilt binaries for arm-on-windows until they release a new version :/

One possible workaround would be to install the x86_64 cargo based tauri-cli version and use that via emulation instead (windows should automatically do that hopefully)

**Comment by Massimiliano-solutiontech** [comment] 2023-05-03 14:04
So we have to wait for `ring 0.17` in order to have a full native Windows ARM support?

**Comment by FabianLars** [comment] 2023-05-03 14:05
yep

**Comment by Massimiliano-solutiontech** [comment] 2023-05-03 14:05
Gotcha, thanks anyway. I’m gonna close this one

**Closed as completed** 2023-05-29 16:17 UTC
Labels: type: bug, scope: cli, status: upstream, platform: Windows

**Comment by ReactorScram** [comment] 2024-10-15 22:10
I see this exists: https://www.npmjs.com/package/@tauri-apps/cli-win32-arm64-msvc

And `main.wxs` mentions arm64 now in Tauri v2. Any chance MSI bundling for aarch64 works in v2?

**Comment by FabianLars** [comment] 2024-10-16 07:45
If the app itself compiles fine (some crates don't support windows arm) then yes. The wix update was back ported to v1 too, so both v1 and v2 should work.

**Comment by ReactorScram** [comment] 2024-10-16 15:54
I think pnpm was just glitching out on my system. I did a `pnpm store prune` and `pnpm install --force` and then finally was able to get `pnpm tauri --version` to return 2.x instead of an error.

It had got hung up on 1.6 somehow.

**Comment by ectrc** [comment] 2025-02-26 04:19
Still not fixed. This is a step back for tauri

**Comment by FabianLars** [comment] 2025-02-26 08:26
@ectrc 

It is fixed. I literally tried it out yesterday to fix another arm specific issue.

One thing I had to do though was to tell pnpm to install arm64 packages when I installed node via winget and pnpm via the Powershell script (I assume one or both were installed as x86_64)
https://pnpm.io/package_json#pnpmsupportedarchitectures
