### ISSUE TITLE
[feat] "activate" event

### ISSUE THREAD

**Issue by martpie** [tauri-apps/tauri#9063] opened 2024-03-04 12:30 UTC
### Describe the problem

Electron supports an activate event (macOS-specific), triggered for example when calling the app from the doc or spotlight.

> Emitted when the application is activated. Various actions can trigger this event, such as launching the application for the first time, attempting to re-launch the application when it's already running, or clicking on the application's dock or taskbar icon.

This event is really useful when, instead of destroying the window when user want to close it, we hide instead. In my case, I have an `<audio />` playing in the background I need to keep playing. So destroying the window is not a good solution, and minimizing the app instead of maximizing is slow and does not feel native.

### Describe the solution you'd like

An app or window "activate" event that can be listened to (from the back-end at least).

**Comment by amrbashir** [comment] 2024-03-04 15:31
I believe this is duplicate of #3084

**Closed as not planned by amrbashir** 2024-03-04 15:31 UTC
Labels: type: feature request
