### ISSUE TITLE
error: failed to run custom build command for `javascriptcore-rs-sys v0.4.0` ubuntu mate 24.04LTS

### ISSUE THREAD

**Issue by learncodingforweb** [tauri-apps/tauri#10218] opened 2024-07-08 10:02 UTC
### Describe the bug

**npm run tauri dev**
```
The following warnings were emitted during compilation:

warning: javascriptcore-rs-sys@0.4.0: 

error: failed to run custom build command for `javascriptcore-rs-sys v0.4.0`

Caused by:
  process didn't exit successfully: `/home/dfmd/dev/caliberation/dfmd_camera_recoder/rust/desktop/dfmd_cam_zustand/src-tauri/target/debug/build/javascriptcore-rs-sys-623ef5bb16fe089c/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=JAVASCRIPTCOREGTK_4.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=
  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags javascriptcoregtk-4.0 javascriptcoregtk-4.0 >= 2.24

  The system library `javascriptcoregtk-4.0` required by crate `javascriptcore-rs-sys` was not found.
  The file `javascriptcoregtk-4.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `javascriptcoregtk-4.0.pc`.

warning: build failed, waiting for other jobs to finish...
```
even 
```
sudo apt search javascriptcoregtk-4.0
Sorting... Done
Full Text Search... Done
libjavascriptcoregtk-4.0-bin/noble-updates,now 2.44.2-0ubuntu0.24.04.2 all [installed]
  WebKitGTK JavaScript command-line interpreter (transitional dummy package)
```

```@tauri-apps/cli": "^1.5.14"```
 uname -a
Linux camera 6.8.0-36-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun 10 10:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Note if i try to install Prerequisites (https://tauri.app/v1/guides/getting-started/prerequisites) 
sudo apt install libwebkit2gtk-4.0-dev 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libwebkit2gtk-4.0-dev
E: Couldn't find any package by glob 'libwebkit2gtk-4.0-dev'

so i installed sudo apt install libwebkit2gtk-4.1-dev. after that i am getting above error. How can i install sudo apt install libwebkit2gtk-4.0-dev on ubuntu mate 22.04LTS or resolve above error

### Reproduction

1. npm create tauri-app@latest
2. cd myapp
3. npm i
4. npm run tauri dev

### Expected behavior

Tauri app should run on ubuntu 22.04LTS

### Full `tauri info` output

```text
npm run tauri info

> myapp@0.0.0 tauri
> tauri info


[✘] Environment
    - OS: Ubuntu 24.04 X64
    ✘ webkit2gtk-4.0: not installed
      Visit https://tauri.app/v1/guides/getting-started/prerequisites to learn more about tauri prerequisites
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.79.0 (129f3b996 2024-06-10)
    ✔ cargo: 1.79.0 (ffa9cf99a 2024-06-03)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 20.15.0
    - npm: 10.7.0

[-] Packages
    - tauri [RUST]: 1.7.1
    - tauri-build [RUST]: 1.5.3
    - wry [RUST]: 0.24.10
    - tao [RUST]: 0.16.9
    - @tauri-apps/api [NPM]: 1.6.0
    - @tauri-apps/cli [NPM]: 1.6.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-07-08 11:37
Duplicate of the pinned issue https://github.com/tauri-apps/tauri/issues/9662

**Closed as not planned by FabianLars** 2024-07-08 11:37 UTC
Labels: type: bug, status: needs triage
