### ISSUE TITLE
[bug] no method named `to_str` found

### ISSUE THREAD

**Issue by jane-212** [tauri-apps/tauri#9085] opened 2024-03-05 15:39 UTC
### Describe the bug

no method named `to_str` found when install tauri-cli with cargo

### Reproduction

run command `cargo install tauri-cli`

### Full `tauri info` output

```text
I doesn't install the tauri yet.
```

### Stack trace

```text
error[E0599]: no method named `to_str` found for struct `log::kv::Value` in the current scope
   --> /Users/jane/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-cli-1.5.10/src/lib.rs:132:29
    |
132 |         let action = action.to_str().unwrap();
    |                             ^^^^^^ help: there is a method with a similar name: `to_cow_str`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `tauri-cli` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tauri-cli v1.5.10`, intermediate artifacts can be found at `/var/folders/5w/4f5ls3qd1jx_3g46f5n6z1dh0000gn/T/cargo-install61VX9a`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

### Additional context

cargo version
`cargo 1.75.0 (1d8b05cdd 2023-11-20)`

**Comment by amrbashir** [comment] 2024-03-05 16:20
duplicate of #9050, until the fix is released, install with `--locked` flag

**Closed as completed by amrbashir** 2024-03-05 16:20 UTC
Labels: type: bug, status: needs triage

**Comment by Deliorg** [comment] 2024-03-06 22:55
> duplicate of #9050, until the fix is released, install with `--locked` flag

Thank you! Solved my problem.
