### ISSUE TITLE
[bug] In transparent windows, hidden elements appear afterimages

### ISSUE THREAD

**Issue by lecepin** [tauri-apps/tauri#5241] opened 2022-09-20 02:45 UTC
### Describe the bug

When the window is set to transparent mode, hidden elements such as `display:none` in the webview will cause high-frequency afterimage problems, and you need to make the window out of focus before removing it.

Normal:

![Kapture 2022-09-20 at 10 36 45](https://user-images.githubusercontent.com/11046969/191154908-cb2016f3-9439-47e0-9416-755d1c29a9ce.gif)

Abnormal:

![Kapture 2022-09-20 at 10 38 54](https://user-images.githubusercontent.com/11046969/191155150-03220771-9380-4574-9b42-787f01dcf6fe.gif)

CSS code:

```css
xxx {
 ...
  border-radius: 50%;
  background-color: #fff;
  box-shadow: 0 0 5px;
};

xxx:hover {
  display: none !important;
};
```

After calling `appWindow.setSize(...)`, the frequency will be very high.

### Expected behavior

No afterimages will appear.
Or provide a refresh function that re-renders.

### Platform and versions

```
Environment
  › OS: Mac OS 12.4.0 X64
  › Node.js: 18.3.0
  › npm: 8.11.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.64.0-nightly
  › cargo: 1.64.0-nightly
  › Rust toolchain: nightly-aarch64-apple-darwin 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.1.0 (outdated, latest: 1.1.1)
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.1.0,
  › tauri-build [RUST]: 1.1.0,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ node_modules
  ├─ src-tauri
  ├─ .vscode
  └─ src
```

**Comment by amrbashir** [comment] 2022-09-20 11:13
duplicate of #4243

**Closed as not planned by amrbashir** 2022-09-20 11:13 UTC
Labels: type: bug, status: needs triage
