### ISSUE TITLE
[bug]  Updating system tray menu with invoke / tauri command -> unexpected output

### ISSUE THREAD

**Issue by dgu87** [tauri-apps/tauri#3642] opened 2022-03-08 15:27 UTC
### Describe the bug

Updating the tray menu with a tauri command adds unexpected suffixes to the updated titles.

![tray1](https://user-images.githubusercontent.com/55397234/157268920-fda420da-5e58-4617-aeb6-f78f67131d3e.png)
![tray2](https://user-images.githubusercontent.com/55397234/157268948-18a90560-2a63-46b0-b4b4-b254f2a204b9.png)
![tray3](https://user-images.githubusercontent.com/55397234/157268956-adeb2f62-3438-4110-8c3f-f5b345356063.png)

### Reproduction

```
#[tauri::command]
fn locale_de(app: tauri::AppHandle) {
  app.tray_handle().get_item("hide").set_title("Ausblenden").unwrap();
  app.tray_handle().get_item("quit").set_title("Beenden").unwrap();
  app.tray_handle().get_item("open").set_title("Einblenden").unwrap();
}

(...)

.system_tray(system_tray)
.invoke_handler(tauri::generate_handler![locale_de, locale_en, locale_it, locale_es, locale_fr])
```

### Platform and versions

```shell
Operating System - Windows, version 10.0.19043 X64
(...)
Node.js environment
  Node.js - 17.5.0
  @tauri-apps/cli - 1.0.0-rc.4 (outdated, latest: 1.0.0-rc.7)
  @tauri-apps/api - 1.0.0-rc.2

Global packages
  npm - 8.4.1
 (...)

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-pc-windows-msvc
(...)
App
  tauri - git+https://github.com/tauri-apps/tauri?branch=dev#f5efc248da511e0924c9673b947d5de7ef69ac45 (1.0.0-rc.4)
  tauri-build - 1.0.0-rc.4
  tao - 0.6.4
  wry - 0.13.3
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:5000/
  framework - Svelte
  bundler - Rollup
```

### Additional context

**Note:**  The code posted under "Reproduction" works 100% fine in macOS environments.

**Comment by amrbashir** [comment] 2022-03-08 15:30
Will be fixed once https://github.com/tauri-apps/tao/pull/297 is merged and published.

**Comment by FabianLars** [comment] 2022-03-08 15:42
Are you sure? Because i can't repro that issue in tao directly, only in tauri. But i could be doing it wrong, not a tao guy 🤷

**Comment by amrbashir** [comment] 2022-03-08 15:49
Yeah I came across this issue when I was refactoring menus (see [here](https://github.com/tauri-apps/tao/blob/b0395925a1fe9f73d4b3646e622138598d5b1bc3/src/platform_impl/windows/menu.rs#L198-L201)). It was because of a missing `\0`(null character). `windows-rs` used to automatically add it but I think there was a regression in one of their recent version so I am gonna make sure it won't break again by manually checking and adding it.

To confirm if this is indeed the issue, try using current tauri version and add `\0`(null character) in the end. e.g. `item.set_title("your new tilte\0")` .

**Comment by FabianLars** [comment] 2022-03-08 15:56
Ahh i see, thanks.

And yes appending `\0` fixes it (on my end).
What it doesn't fix tho, is `ÄÖÜ`. These chars work fine if you create the item with it, but not in the command above. Any idea if that's auto fixed by that PR too?

**Comment by amrbashir** [comment] 2022-03-08 18:24
> What it doesn't fix tho, is `ÄÖÜ`. These chars work fine if you create the item with it, but not in the command above. Any idea if that's auto fixed by that PR too?

Can you leave a comment there with this info so I don't forget? 

 Sorry, I can't test it for another 3 weeks but the Windows portion of that PR is done so you can just check the tao PR locally and try.

**Comment by lucasfernog** [comment] 2022-03-08 19:34
Can that PR even be part of tauri v1? Probably not, so we'd need a patch specific to this issue anyway.

**Comment by amrbashir** [comment] 2022-03-08 20:42
It definitely can, I just couldn't put more work in it this vacation due to some IRL issues, but I should be able to finish it on my next vacation.

But yeah I agree, tao can make a patch for it until the PR is finished. I will make a quick patch for it tomorrow once I get settled, if no one beats me to it.

**Comment by lucasfernog** [comment] 2022-03-09 03:41
Tao patch: https://github.com/tauri-apps/tao/pull/340

**Closed as completed** 2022-03-09 07:20 UTC
Labels: type: bug, status: upstream, platform: Windows
