### ISSUE TITLE
[bug] WebviewWindow::set_fullscreen in event handler freezes app [v2]

### ISSUE THREAD

**Issue by tjol** [tauri-apps/tauri#11254] opened 2024-10-07 15:05 UTC
### Describe the bug

When I call `set_fullscreen` in an event handler (registered using `app.listen_any`), the window decorations vanish and then the app freezes. `set_fullscreen` never returns.

This is using Tauri v2.0.1 on Windows. The equivalent code worked in v1.6 (I found the issue during migration)

### Reproduction

See the minimal app in this repo: https://github.com/tjol/tauri-v2-bug-fullscreen-freezes

[lib.rs](https://github.com/tjol/tauri-v2-bug-fullscreen-freezes/blob/main/src-tauri/src/lib.rs) sets up this simple event listener:

```rust
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            let main_window = app.get_webview_window("main").unwrap();
            app.listen_any("toggle-fullscreen", move |_| {
                let is_fullscreen = main_window.is_fullscreen().unwrap();
                println!("toggle fullscreen  (current: {is_fullscreen})");
                main_window.set_fullscreen(!is_fullscreen).unwrap();
                println!("is_fullscreen: {} -> {}", is_fullscreen, main_window.is_fullscreen().unwrap());
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
```

and the front-end sends the event `"toggle-fullscreen"`.

The first `println!` call shows up in the console; the second `println!` call does not, indicating that `set_fullscreen` never returns

### Expected behavior

`set_fullscreen` returns, and the window goes fullscreen.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 129.0.2792.79
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.80.1 (3f5fd8dd4 2024-08-06)
    ✔ cargo: 1.80.1 (376290515 2024-07-16)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)
    - node: 20.14.0
    - pnpm: 9.2.0
    - npm: 10.7.0

[-] Packages
    - tauri 🦀: 2.0.1
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.44.1
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.1

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

**Comment by 1111mp** [comment] 2024-10-11 08:24
I have an application developed using `tauri v2`: [nvm-desktop](https://github.com/1111mp/nvm-desktop), but some users have also encountered the problem that the software freezes after startup and loses the ability to interact. Related questions can be found here: https://github.com/1111mp/nvm-desktop/issues/124
The following is the information obtained from the log:
```text
[2024-10-11][07:26:21][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationSupportsSecureRestorableState`
[2024-10-11][07:26:21][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationSupportsSecureRestorableState`
[2024-10-11][07:26:21][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationDidFinishLaunching`
[2024-10-11][07:26:21][tao::platform_impl::platform::app_state][TRACE] Activating visible window
[2024-10-11][07:26:21][app][ERROR] file not found "/Users/xxx/.nvmd/setting.json"
[2024-10-11][07:26:21][app][ERROR] failed to read the file "/Users/xxx/.nvmd/default"
[2024-10-11][07:26:21][app][ERROR] file not found "/Users/xxx/.nvmd/versions.json"
[2024-10-11][07:26:21][app][ERROR] file not found "/Users/xxx/.nvmd/groups.json"
[2024-10-11][07:26:21][app][ERROR] file not found "/Users/xxx/.nvmd/projects.json"
[2024-10-11][07:26:21][tao::platform_impl::platform::window][TRACE] Creating new window
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2024-10-11][07:26:21][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2024-10-11][07:26:21][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2024-10-11][07:26:21][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationDidFinishLaunching`
[2024-10-11][07:26:21][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidBecomeKey:`
[2024-10-11][07:26:21][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidBecomeKey:`
[2024-10-11][07:26:21][reqwest::connect][DEBUG] starting new connection: https://github.com/
[2024-10-11][07:26:21][reqwest::connect][DEBUG] proxy(http://127.0.0.1:7890) intercepts 'https://github.com/'
[2024-10-11][07:26:21][reqwest::connect][TRACE] tunneling HTTPS over proxy
[2024-10-11][07:26:22][reqwest::async_impl::client][DEBUG] redirecting 'https://github.com/1111mp/nvm-desktop/releases/download/updater/update.json' to 'https://objects.githubusercontent.com/github-production-release-asset-2e65be/668801742/938a720d-0a96-447a-92db-0c12f9781ef0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241011T072622Z&X-Amz-Expires=300&X-Amz-Signature=27bf2421314c77b1928521e647c75d996ab26eca51f5b485096261ed17a5e350&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3Dupdate.json&response-content-type=application%2Foctet-stream'
[2024-10-11][07:26:22][reqwest::connect][DEBUG] starting new connection: https://objects.githubusercontent.com/
[2024-10-11][07:26:22][reqwest::connect][DEBUG] proxy(http://127.0.0.1:7890) intercepts 'https://objects.githubusercontent.com/'
[2024-10-11][07:26:22][reqwest::connect][TRACE] tunneling HTTPS over proxy
[2024-10-11][07:26:23][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidResignKey:`
[2024-10-11][07:26:23][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidResignKey:`
[2024-10-11][07:28:45][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidBecomeKey:`
[2024-10-11][07:28:45][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidBecomeKey:`
[2024-10-11][07:28:45][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationShouldHandleReopen`
[2024-10-11][07:28:45][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationShouldHandleReopen`
[2024-10-11][07:28:47][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowShouldClose:`
[2024-10-11][07:28:47][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowShouldClose:`
[2024-10-11][07:28:47][tao::platform_impl::platform::window][TRACE] Dropping `UnownedWindow` (0x600003ac9aa0)
[2024-10-11][07:28:47][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowWillClose:`
[2024-10-11][07:28:47][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowWillClose:`
[2024-10-11][07:28:49][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationWillTerminate`
[2024-10-11][07:28:49][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationWillTerminate`
[2024-10-11][07:29:02][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationDidFinishLaunching`
[2024-10-11][07:29:02][tao::platform_impl::platform::app_state][TRACE] Activating visible window
[2024-10-11][07:29:02][app][ERROR] file not found "/Users/xxx/.nvmd/setting.json"
[2024-10-11][07:29:02][app][ERROR] failed to read the file "/Users/xxx/.nvmd/default"
[2024-10-11][07:29:02][app][ERROR] file not found "/Users/xxx/.nvmd/versions.json"
[2024-10-11][07:29:02][app][ERROR] file not found "/Users/xxx/.nvmd/groups.json"
[2024-10-11][07:29:02][app][ERROR] file not found "/Users/xxx/.nvmd/projects.json"
[2024-10-11][07:29:02][tao::platform_impl::platform::window][TRACE] Creating new window
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2024-10-11][07:29:02][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `validAttributesForMarkedText`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Triggered `viewDidMoveToWindow`
[2024-10-11][07:29:02][tao::platform_impl::platform::view][TRACE] Completed `viewDidMoveToWindow`
[2024-10-11][07:29:02][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationDidFinishLaunching`
[2024-10-11][07:29:02][reqwest::connect][DEBUG] starting new connection: https://github.com/
[2024-10-11][07:29:02][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidBecomeKey:`
[2024-10-11][07:29:02][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidBecomeKey:`
[2024-10-11][07:29:03][tao::platform_impl::platform::window_delegate][TRACE] Triggered `windowDidResignKey:`
[2024-10-11][07:29:03][tao::platform_impl::platform::window_delegate][TRACE] Completed `windowDidResignKey:`
[2024-10-11][07:29:03][tao::platform_impl::platform::app_delegate][TRACE] Triggered `applicationSupportsSecureRestorableState`
[2024-10-11][07:29:03][tao::platform_impl::platform::app_delegate][TRACE] Completed `applicationSupportsSecureRestorableState`
```
The "file not found error" does not affect the program's operation because the code captures it. Like this:
![image](https://github.com/user-attachments/assets/66811816-08f4-41a9-a9ad-47317f7d419a)

Some additional information:
```toml
[package]
name = "nvm-desktop"
version = "4.0.0"
description = "Node Version Manager Desktop - A desktop application to manage multiple active node.js versions."
authors = ["The1111mp@outlook.com"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
anyhow = "1.0"
dotenvy = "0.15"
dirs = "5.0"
futures = "0.3"
get-node = { path = "crates/get-node" }
log = "0.4"
once_cell = "1.19"
open = "5"
parking_lot = "0.12"
tauri = { version = "2.0", features = [
	"image-ico",
	"image-png",
	"macos-private-api",
	"protocol-asset",
	"tray-icon",
	"devtools",
] }
tauri-plugin-dialog = "2.0"
tauri-plugin-log = { version = "2.0", features = ["colored"] }
tauri-plugin-shell = "2.0"
tauri-plugin-single-instance = "2.0"
tauri-plugin-updater = "2.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
version-compare = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed.

```

**Comment by tjol** [comment] 2024-10-11 08:32
@1111mp is this the issue you meant to comment on? Because I fail to see the connection.

**Comment by 1111mp** [comment] 2024-10-11 08:38
@tjol  Sorry, maybe I should open a new issue by myself. I'm commenting here because from what I've gathered the issue seems to be very similar to what you're describing here, so I'm wondering if I can provide more information. If this bothers you please let me know and I will delete the comments.
```
[2024-10-11][07:29:02][tao::platform_impl::platform::window][TRACE] Locked shared state in `set_fullscreen`
[2024-10-11][07:29:02][tao::platform_impl::platform::window][TRACE] Unlocked shared state in `set_fullscreen`
```

**Comment by tjol** [comment] 2024-10-11 14:45
@1111mp I don't see much reason to believe how what you're describing is related. As I understand it you're not even calling `set_fullscreen`. It sounds to me like at this point you're just guessing where your problem might be — this is a good start, but a poor basis for a bug report.

I recommend you spend more time isolating the source of the issue you're seeing in your code. With the information you have provided here, even somebody who knows a lot about tauri will find it hard to understand what is going on unless they also happen to know your code very well.

Work on creating a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example)* which reproduces the problem on your machine (*not* simply your full app) and demonstrates as precisely as possible how the issue is connected to tauri. The minimal example will be a better basis with which to submit a bug report, or add useful information to an existing bug report (possibly this one). The less of your own code you need to demonstrate the problem you're having, the more likely it is that somebody will be able (and willing) to help.

*Read the article at the link: https://stackoverflow.com/help/minimal-reproducible-example — this is also linked in the bug report form for this repository.

**Comment by amrbashir** [comment] 2024-10-17 03:15
I couldn't reproduce, probably fixed by https://github.com/tauri-apps/tauri/pull/11355

**Closed as completed by amrbashir** 2024-10-17 03:15 UTC
Labels: type: bug, status: needs triage
