### ISSUE TITLE
[bug] gaining access to the camera and microphone after being blocked not working 

### ISSUE THREAD

**Issue by Eyoel-T** [tauri-apps/tauri#5042] opened 2022-08-25 16:59 UTC
### Describe the bug

I'm converting my webRTC-based video conference app from electron to tauri. The issue is that if I click block after being prompted to allow a camera and microphone, there is no way to be prompted to allow again. 

How am I going to deploy to production knowing that if the user clicks block for the first time, the app won't do anything after that

If it is in development mode, I can remove the Preferences file from **"C:\Users\myUserName\AppData\Local\com.tauri.dev\EBWebView\Default\Preferences"** and it will prompt me again. However, the app must be closed in order to remove the file; otherwise, it will be automatically added after deletion and is not going to work 

I used this method to delete the Preferences file so that it would prompt me once more but the file would be automatically added afterward.
```
import { removeFile, BaseDirectory, removeDir } from "@tauri-apps/api/fs";
const getLocalPreview = async () => {
    try {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: true,});
        return stream; 
    } catch (error) {
      //this is when user don't allow media devices
      console.log(error);
      await removeFile("com.tauri.dev/EBWebView/Default/Preferences", {
        dir: path.BaseDirectory.LocalData,
      });
    }
  };
```

### Reproduction

1: create a Tauri app with vanilla js  
2: add this function 
```
const getLocalPreview = async () => {
    try {
        const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: true,});
        return stream; 
    } catch (error) {
      //this is when user don't allow media devices
      console.log(error);
    }
  };
```
3: call the function `getLocalPreview()`
4: a prompt will appear and select block.
![image](https://user-images.githubusercontent.com/71425416/186722399-f5fb5370-af55-4a8a-bbe2-4e876c13edfc.png)
5: call the function `getLocalPreview()` again It never displays a prompt to allow the camera or the mic.

### Expected behavior

to re-ask  for permission to use the camera and microphone again
![image](https://user-images.githubusercontent.com/71425416/186722399-f5fb5370-af55-4a8a-bbe2-4e876c13edfc.png)

### Platform and versions

Environment
  › OS: Windows 10.0.25120 X64
  › Webview2: 104.0.1293.63
  › MSVC:
      - Visual Studio Enterprise 2019
  › Node.js: 16.16.0
  › npm: 8.11.0
  › pnpm: 7.9.3
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../build
  › devPath: https://localhost:3000/
  › framework: React

App directory structure
  ├─ .git
  ├─ node_modules
  ├─ public
  ├─ src
  ├─ src-tauri
  └─ ssl

**Comment by amrbashir** [comment] 2022-08-25 17:45
duplicate of https://github.com/tauri-apps/tauri/issues/4434

**Closed as completed by amrbashir** 2022-08-25 17:45 UTC
Labels: type: bug, status: needs triage

**Comment by WeiChens** [comment] 2024-08-05 16:24
I also have OCD, it took me several days to find it

tauri version v2
 dependencies：
 webview2-com = "0.31.0"
 windows = "0.57.0"
```rust
use webview2_com::Microsoft::Web::WebView2::Win32::{
    ICoreWebView2Profile4, ICoreWebView2_13, COREWEBVIEW2_PERMISSION_KIND_MICROPHONE,
    COREWEBVIEW2_PERMISSION_STATE_DEFAULT,
};
use windows::core::{Interface, PCWSTR};

/**
 *
 * Reset microphone permissions
 */
#[tauri::command]
fn reset_permission(origin: &str, app: AppHandle) {
    let webview = app.get_webview_window("main").unwrap();
    let mut origin = origin.to_string();
    origin.push('\0');
    let origin = origin.encode_utf16().collect::<Vec<u16>>();
    webview
        .with_webview(move |webview| unsafe {
            let core = webview.controller().CoreWebView2().unwrap();
            let core = Interface::cast::<ICoreWebView2_13>(&core).unwrap();
            let profile = core.Profile().unwrap();
            let profile = Interface::cast::<ICoreWebView2Profile4>(&profile).unwrap();
            let origin = PCWSTR::from_raw(origin.as_ptr());
            profile
                .SetPermissionState(
                    COREWEBVIEW2_PERMISSION_KIND_MICROPHONE,
                    origin,
                    COREWEBVIEW2_PERMISSION_STATE_DEFAULT,
                    None,
                )
                .unwrap();
        })
        .unwrap();
}
```
