### ISSUE TITLE
The host function under wasm32-wasi cannot be used in release mode[bug] 

### ISSUE THREAD

**Issue by maoly1012** [tauri-apps/tauri#7404] opened 2023-07-11 11:57 UTC
### Describe the bug

The host function under wasm32-wasi cannot be used in release mode, but it can be used in debug mode. The release mode is also available in a pure rust environment.
I'm using wamedge-sdk and the error is "Core(Execution(Unreachable))"

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 114.0.1823.67
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.11.1
    - pnpm: 6.11.0
    - yarn: 1.22.11
    - npm: 8.0.0

[-] Packages
    - tauri [RUST]: 1.4.1
    - tauri-build [RUST]: 1.4.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by amrbashir** [comment] 2023-07-11 13:33
I'll temporarily close this due to the lack of enough information and reproduction.

Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) and fill the appropriate information fields to reopen the issue. Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as not planned by amrbashir** 2023-07-11 13:33 UTC
Labels: type: bug, status: needs triage
