### ISSUE TITLE
How do I turn off CORS

### ISSUE THREAD

**Issue by yizhiyan** [tauri-apps/tauri#6320] opened 2023-02-20 06:04 UTC
### Describe the problem

I need to request pictures from other websites. I want to be able to close the application's cors

### Describe the solution you'd like

I hope you can add custom startup parameters or relevant configurations
`--disable-web-security`

**Comment by FabianLars** [comment] 2023-02-20 09:11
Duplicate of https://github.com/tauri-apps/tauri-docs/issues/26. Would be nice if you could provide a reproducible example over there too.

p.s. a `--disable-web-security` feature is highly unlikely, especially since only the windows webview theoretically supports it. Also i guess you could argue that it conflicts with Tauri's high-security approach idk.

**Closed as not planned by FabianLars** 2023-02-20 09:11 UTC
Labels: type: feature request
