### ISSUE TITLE
[bug] Opening the dev-tools crashes the APP on ubuntu

### ISSUE THREAD

**Issue by kubijo** [tauri-apps/tauri#3407] opened 2022-02-11 17:44 UTC
### Describe the bug

Can't open dev-tools to inspect why app that was working on beta version doesn't load anything anymore… that crashes the app though

### Reproduction

1. `yarn add @tauri-apps/api` 
2. `yarn tauri dev`
3. right click → inspect element

### Expected behavior

Dev tools open up & I'm able to debug why my pre-rc doesn't load anymore

### Platform and versions

```shell
$ tauri info

Operating System - Ubuntu, version 21.10 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-rc.0
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.2
  pnpm - 6.11.0
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - 1.57-x86_64-unknown-linux-gnu 

App directory structure
/dist
/node_modules
/src-tauri

App
  tauri.rs - 1.0.0-rc.0
  build-type - bundle
  CSP - default-src 'self'
  distDir - ../dist
  devPath - ../dist
Done in 11.04s.
```

### Stack trace

```shell
(WebKitWebProcess:257115): Gdk-ERROR **: 18:35:48.710: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 320 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

### Additional context

I did try things hinted in the error message & even tried to get into `gdb` to break at the error handler describe, however that doesn't work (presumably because the function doesn't exist anymore in `gtk-3-0` & debug symbols package functionally doesn't exist for my distro & neither of `GDK_SYNCHRONIZE=1` or `GTK_DEBUG=interactive` help in any way … but then again, I don't have ANY experience with debugging of these things).

I am willing to go further however, if you'd be able to give pointers because we are seemingly at a stage of choosing the new project base tech.

**Comment by lucasfernog** [comment] 2022-02-13 04:16
@wusyong any ideas here?

**Comment by kt215** [comment] 2022-02-13 14:20
FYI: I don't see this issue on Linux Mint (Ubuntu). The devtools open up without error.
```
Operating System - Linux Mint, version 20.3 X64

Node.js environment
  Node.js - 16.14.0
  @tauri-apps/cli - 1.0.0-rc.3
  @tauri-apps/api - 1.0.0-rc.0

Global packages
  npm - 8.3.1
  pnpm - Not installed
  yarn - Not installed

Rust environment
  rustc - 1.58.1
  cargo - 1.58.0

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-unknown-linux-gnu 
```

**Comment by kubijo** [comment] 2022-02-14 11:03
Good day gentleman… so according to what @kt215 posted above I have tried setting the rust version to `stable` and while I was at it also bumping the project deps… resulting in an app that now works again…

I concur to you as to what to do with that information & how to potentially address this in the library code…

```shell
❯ yarn run tauri info
yarn run v1.22.11
$ /opt/dev/braiins/pool/app-rs/toolbox/node_modules/.bin/tauri info

Operating System - Ubuntu, version 21.10 X64

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-rc.4
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.2
  pnpm - Not installed
  yarn - 1.22.11

Rust environment
  rustup - 1.24.3
  rustc - 1.58.1
  cargo - 1.58.0
  toolchain - stable-x86_64-unknown-linux-gnu 

App directory structure
/node_modules
/.yarn
/.venv
/src-tauri

App
  tauri - 1.0.0-rc.1
  tauri-build - 1.0.0-rc.1
  tao - 0.6.2
  wry - 0.13.1
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../../../web-ui/build/js/bundle/toolbox-tauri
  devPath - http://localhost:9001/
Done in 7.77s.
```

**Comment by kubijo** [comment] 2022-02-14 11:04
…oh and I have also upgraded `serde_json` & `serde` to the latest available version if that should be of any consequence.

**Comment by amrbashir** [comment] 2022-02-14 18:02
Looks like it might be unstable rust issue, closing this for now.

**Closed as completed** 2022-02-14 18:02 UTC
Labels: type: bug, platform: Linux

**Comment by kubijo** [comment] 2022-02-14 18:20
well … I didn't have unstable as my target before as far as I can tell…

**Comment by amrbashir** [comment] 2022-02-14 19:51
sorry about that, I read you set your rust to stable in an earlier message and assumed you were using unstable rust.

Seeing that you upgraded from 1.57 to 1.58 and the error is gone also makes me think it was an issue in rust itself maybe?

Anyways, this issue seems suprr random tbh and I highly doubt we can do anything about it so I will keep the issue closed for now but feel free to reopen the issue if it happened again.

**Comment by lisiur** [comment] 2022-08-13 00:22
I had the same problem.

Steps to reproduce:

1. pnpm create tauri-app
2. pnpm tauri dev

```
(WebKitWebProcess:419471): Gdk-ERROR **: 08:18:19.731: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 220 error_code 2 request_code 152 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

tauri info:

```
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.15.1
  › npm: 8.11.0
  › pnpm: 7.9.0
  › yarn: Not installed!
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: ../dist

App directory structure
  ├─ src-tauri
  ├─ node_modules
  └─ dist
```

**Comment by FlerioEU** [comment] 2022-10-09 10:31
I got the same error. But i am working on WSL2 with Ubuntu 20.04 using vcxsrv.

I was able to resolve it by setting this:

`export WEBKIT_DISABLE_COMPOSITING_MODE=1`

---

My environment: 

```
Environment
  › OS: Ubuntu 20.04 X64
  › Node.js: 16.14.2
  › npm: 8.5.0
  › pnpm: Not installed!
  › yarn: 1.22.10
  › rustup: 1.25.1
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: 1.59.0-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.1.1
  › @tauri-apps/api [NPM]: 1.1.0
  › tauri [RUST]: 1.1.1,
  › tauri-build [RUST]: 1.1.1,
  › tao [RUST]: 0.14.0,
  › wry [RUST]: 0.21.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js

App directory structure
  ├─ node_modules
  ├─ src
  ├─ src-tauri
  ├─ .vscode
  └─ public
```

It also works with rust v1.64.0 which is the latest version currently

**Comment by evbo** [comment] 2023-02-26 21:55
@FlerioEU I less often see this issue on Ubuntu but it is definitely reproducible on Centos7, which your fix applies to nicely, Cheers!

**Comment by evbo** [comment] 2023-03-04 19:58
@FlerioEU a wonderful solution, however anyone that uses this should be aware:

`WEBKIT_DISABLE_COMPOSITING_MODE=1` appears to disable special CSS/graphics effects, such as "backdrop" (e.g. bluring/darkening the background of a modal, etc.). 

Other than that, this stops the errors so for dev mode it's a life saver!

**Comment by Silzinc** [comment] 2025-02-04 23:16
Well, even the latter solution does not work for me. The devtools just make the app crash without any error in the terminal. Here is my tauri info:
```
[✔] Environment
    - OS: Pop!_OS 22.4.0 x86_64 (X64) (pop on x11)
    ✔ webkit2gtk-4.1: 2.46.5
    ✔ rsvg2: 2.52.5
    ✔ rustc: 1.84.1 (e71f9a9a9 2025-01-27)
    ✔ cargo: 1.84.1 (66221abde 2024-11-19)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: stable-x86_64-unknown-linux-gnu (default)
    - node: 22.10.0
    - pnpm: 10.2.0
    - yarn: 1.22.22
    - npm: 10.9.0
    - deno: deno 2.1.7

[-] Packages
    - tauri 🦀: 2.2.5
    - tauri-build 🦀: 2.0.5
    - wry 🦀: 0.48.1
    - tao 🦀: 0.31.1
    - @tauri-apps/api : 2.2.0
    - @tauri-apps/cli : 2.2.7

[-] Plugins
    - tauri-plugin-opener 🦀: 2.2.5
    - @tauri-apps/plugin-opener : 2.2.5

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```
Thanks in advance if you have a tip for this!
