### ISSUE TITLE
[feat] Configuration to override default NSIS install directory

### ISSUE THREAD

**Issue by tareqimbasher** [tauri-apps/tauri#11015] opened 2024-09-16 00:14 UTC
### Describe the problem

It's currently not possible to override the default NSIS configuration directory. Currently the NSIS template used by the Tauri bundler installs the app to `$LOCALAPPDATA\${PRODUCTNAME}` when `INSTALLMODE` is `currentUser` ([here](https://github.com/tauri-apps/tauri/blob/b1dacd539a59d5fd358fc1ed4a2b4632d43f44da/crates/tauri-bundler/src/bundle/windows/templates/installer.nsi#L491)). This directory is often used for app config, cache, temp files..etc. I'd much prefer to have the app installed under `$LOCALAPPDATA\Programs\${PRODUCTNAME}` which is typically dedicated to current-user installed applications.

Currently there is no way to change this that I could find besides copying [the template](https://github.com/tauri-apps/tauri/blob/b1dacd539a59d5fd358fc1ed4a2b4632d43f44da/crates/tauri-bundler/src/bundle/windows/templates/installer.nsi) used by the Tauri bundler, making the change and then adding the custom script to the tauri config file.

### Describe the solution you'd like

Either change the default user install directory to `$LOCALAPPDATA\Programs\${PRODUCTNAME}` or provide a way to configure this (ideally in the tauri config file) without having to completely take ownership of the NSIS install script.

**Comment by FabianLars** [comment] 2024-09-16 08:44
Thanks for the request, i think this counts as a duplicate of https://github.com/tauri-apps/tauri/issues/7853

**Closed as not planned by FabianLars** 2024-09-16 08:44 UTC
Labels: type: feature request
