### ISSUE TITLE
[feat] notification click event

### ISSUE THREAD

**Issue by RustLoverTheCoder** [tauri-apps/tauri#4770] opened 2022-07-26 07:31 UTC
### Describe the problem

How to get notified of click events

### Describe the solution you'd like

appWindow.on('notification',(e) => {
// todo
})

**Comment by FabianLars** [comment] 2022-07-26 10:07
Duplicate of tauri-apps/plugins-workspace#2150.

**Closed as completed by FabianLars** 2022-07-26 10:07 UTC
Labels: type: feature request
