### ISSUE TITLE
[bug] Sidecar is not signed when signing the app

### ISSUE THREAD

**Issue by cloudsolace** [tauri-apps/tauri#7381] opened 2023-07-08 14:37 UTC
It seems sidecar is not signed while packaging the app which results in being blocked in mac

Fatal error in , line 0
Check failed: reservation_.SetPermissions(unprotect_start, unprotect_size, FLAG_write_code_using_rwx ? PageAllocator::kReadWriteExecute : PageAllocator::kReadWrite).
FailureMessage Object: 0x3132e8ce0
 1: 0x1023f01a2 node::PerIsolatePlatformData::RunForegroundTask(std::__1::unique_ptr<v8::Task, std::__1::default_delete<v8::Task>>) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
 2: 0x103682a7b V8_Fatal(char const*, ...) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
 3: 0x1027c75eb v8::internal::MemoryChunk::SetReadAndWritable() [//app/src-tauri/target/debug/bundle/macos/Sprint.app/Contents/MacOS/sidecar]
 4: 0x1027491a1 v8::internal::Heap::UnprotectAndRegisterMemoryChunk(v8::internal::MemoryChunk*, v8::internal::UnprotectMemoryOrigin) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
 5: 0x1027113d8 v8::internal::Factory::TryNewFixedArray(int, v8::internal::AllocationType) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
 6: 0x102751701 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
 7: 0x10270f79e v8::internal::Factory::CodeBuilder::AllocateCode(bool) [/app/src-tauri/target/debug/bundle/macos/Sprint.app/Contents/MacOS/sidecar]
 8: 0x10270ee02 v8::internal::Factory::CodeBuilder::BuildInternal(bool) [/app/src-tauri/target/debug/bundle/macos/Sprint.app/Contents/MacOS/sidecar]
 9: 0x1025b44c8 v8::internal::GenerateBaselineCode(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
10: 0x102600ee8 v8::internal::Compiler::CompileSharedWithBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
11: 0x1026042b0 v8::internal::Compiler::CompileBaseline(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag, v8::internal::IsCompiledScope*) [/app/src-tauri/target/debug/bundle/macos/Sprint.app/Contents/MacOS/sidecar]
12: 0x10258ec9b v8::internal::baseline::BaselineBatchCompiler::CompileBatch(v8::internal::Handle<v8::internal::JSFunction>) [//app/src-tauri/target/debug/bundle/macos/Sprint.app/Contents/MacOS/sidecar]
13: 0x10258ea50 v8::internal::baseline::BaselineBatchCompiler::EnqueueFunction(v8::internal::Handle<v8::internal::JSFunction>) [//app/src-tauri/target/debug/bundle/macos/Sprint.app/Contents/MacOS/sidecar]
14: 0x102b50780 v8::internal::Runtime_BytecodeBudgetInterruptWithStackCheckFromBytecode(int, unsigned long*, v8::internal::Isolate*) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
15: 0x102b5099c v8::internal::Runtime_BytecodeBudgetInterruptFromBytecode(int, unsigned long*, v8::internal::Isolate*) [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
16: 0x1020fe359  [/app/src-tauri/target/debug/bundle/macos/makeshift.app/Contents/MacOS/sidecar]
zsh: trace trap 

[✔] Environment
    - OS: Mac OS 13.4.1 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.67.1 (d5a82bbd2 2023-02-07)
    ✔ Cargo: 1.67.1 (8ecd4f20a 2023-01-10)
    ✔ rustup: 1.25.2 (fae52a197 2023-02-01)
    ✔ Rust toolchain: stable-x86_64-apple-darwin (default)
    - node: 16.15.1
    - yarn: 1.22.19
    - npm: 8.11.0

[-] Packages
    - tauri [RUST]: 1.2.5
    - tauri-build [RUST]: 1.2.1
    - wry [RUST]: 0.23.4
    - tao [RUST]: 0.15.8
    - @tauri-apps/api [NPM]: 1.4.0
    - @tauri-apps/cli [NPM]: 1.4.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: ../dist
    - framework: Vue.js
    - bundler: Rollup

**Comment by FabianLars** [comment] 2023-07-09 18:35
Duplicate of https://github.com/tauri-apps/tauri/issues/6888 - thanks for the report :)

**Closed as not planned by FabianLars** 2023-07-09 18:35 UTC
Labels: type: bug, status: needs triage
