### ISSUE TITLE
[bug] Error when build with "embedBootstrapper" option

### ISSUE THREAD

**Issue by Zipexpo** [tauri-apps/tauri#6882] opened 2023-05-06 17:01 UTC
### Describe the bug

When I build without "embedBootstrapper" option, everything is fine. But if I use the "embedBootstrapper", I got error below:

>  Finished release [optimized] target(s) in 10.38s
        Info Target: x64
 Downloading https://go.microsoft.com/fwlink/p/?LinkId=2124703
     Running candle for "main.wxs"
     Running light to produce C:\STORE\project\TxDOT-v4-tauri\src-tauri\target\release\bundle\msi\TxCRCPME_2.9.0_x64_en-US.msi
        Info Target: x64
 Downloading https://go.microsoft.com/fwlink/p/?LinkId=2124703
     Running makensis.exe to produce C:\STORE\project\TxDOT-v4-tauri\src-tauri\target\release\bundle\nsis\TxCRCPME_2.9.0_x64-setup.exe
File: output name must not begin with a quote, use "/oname=name with spaces".
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "C:\STORE\project\TxDOT-v4-tauri\src-tauri\target\release\nsis\x64\installer.nsi" on line 355 -- aborting creation process
       Error failed to bundle project: `The system cannot find the file specified. (os error 2)`

### Reproduction

using bundle setting:

"bundle": {
      "active": true,
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "identifier": "org.idvl.TxCRCPME",
      "targets": "all",
      "publisher": "iDVL",
      "category": "Education",
      "shortDescription": "Small app for TxCRCPME",
      "windows": {
        "webviewInstallMode": {
          "type": "embedBootstrapper"
        },
        "nsis": {
          "installerIcon": "icons/icon.ico"
        }
      }
    }

### Expected behavior

It should success build

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 112.0.1722.68
    ✔ MSVC:
        - Visual Studio Build Tools 2017
        - Visual Studio Build Tools 2022
    ✔ rustc: 1.62.0 (a8314ef7d 2022-06-27)
    ✔ Cargo: 1.62.0 (a748cf5a3 2022-06-08)
    ✔ rustup: 1.24.3 (ce5817a94 2021-05-31)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.15.1
    - yarn: 1.22.19
    - npm: 9.3.1

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.1
    - tao [RUST]: 0.16.0
    - @tauri-apps/api [NPM]: 1.3.0
    - @tauri-apps/cli [NPM]: 1.3.0

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2023-05-06 17:03
Duplicate of https://github.com/tauri-apps/tauri/issues/6878, that issue also shows a workaround you can use until we release a hotfix.

thx for the report :)

**Closed as not planned by FabianLars** 2023-05-06 17:03 UTC
Labels: type: bug, status: needs triage

**Comment by Zipexpo** [comment] 2023-05-06 17:49
It is not work for me I got other error:

>  Finished release [optimized] target(s) in 9.67s
>         Info Target: x64
>  Downloading https://go.microsoft.com/fwlink/p/?LinkId=2124703
>        Error failed to bundle project: `TLS is disabled, activate one of the tls- features`

**Comment by FabianLars** [comment] 2023-05-06 17:54
ah forgot about the TLS change, try this then please:
```
cargo install tauri-cli --git https://github.com/tauri-apps/tauri --features rustls
```
if that doesn't work either then this
```
cargo install tauri-cli --git https://github.com/tauri-apps/tauri --features native-tls-vendored
```

**Comment by Zipexpo** [comment] 2023-05-06 18:10
I got stuck then runing cargo install tauri-cli --git https://github.com/tauri-apps/tauri --features rustls

   Compiling zip v0.6.5                                                                                                                                                                
   Compiling reqwest v0.11.17                                                                                                                                                          
   Compiling axum v0.5.17
   Compiling tauri-bundler v1.2.0 (C:\Users\nvtng\.cargo\git\checkouts\tauri-9dcc2f9152472c1a\422b481\tooling\bundler)                                                                 
   Compiling jsonschema v0.16.1                                                                                                                                                        
    Building [=======================> ] 485/486: cargo-tauri(bin)

**Comment by FabianLars** [comment] 2023-05-06 18:11
yeah building the cli can take a while, just wait a few minutes, it _should_ finish at some point.

**Comment by FabianLars** [comment] 2023-05-06 18:11
or if not, and you have to cancel anyway you can try adding the `--debug` flag, that will be way faster.

**Comment by Zipexpo** [comment] 2023-05-06 18:38
None of those options works for me. Please be more specific about the step when running those commands.
I run that comand under "tauri\tooling\cli\node" and then "yarn build"
And I run "node ../tauri/tooling/cli/node/tauri.js build" in my app project dir.
What did I do wrong?

**Comment by FabianLars** [comment] 2023-05-06 18:46
apologies, i always assume people use the cargo cli since that's easier to use so what _i_ had in mind was this flow:
```sh
cargo install tauri-cli --git https://github.com/tauri-apps/tauri --features rustls

# in your project:
cargo tauri build
```

Using the second option from the website you mentioned now it would be as described there but with the feature flag added:
```sh
git clone https://github.com/tauri-apps/tauri
git checkout dev
cd tauri/tooling/cli/node
yarn
yarn build --features rustls
```
Then `node ../tauri/tooling/cli/node/tauri.js build` that you used should work (assuming the path is correct of course)

**Comment by Zipexpo** [comment] 2023-05-06 19:02
Thank you. It is finally worked
The : `cargo tauri build` saved me
