### ISSUE TITLE
[feat] Taskbar progress indicator (Windows)

### ISSUE THREAD

**Issue by nathanbabcock** [tauri-apps/tauri#4386] opened 2022-06-17 20:59 UTC
### Describe the problem

A user of my application requested this feature. Here's the equivalent feature in Electron: https://www.electronjs.org/docs/latest/tutorial/progress-bar

### Describe the solution you'd like

Convenient API exposed on `Tauri::window` from Rust to `set_taskbar_progress()`, or something equivalent.

### Alternatives considered

I attempted to use other rust crates such as `winapi-easy` and `winsafe`. They gave COM errors about conflicts with the window already managed by Tauri.

I couldn't find a way to do this using the underlying gtk `ApplicationWindow` instance either. Please advise if you know of a way.

**Comment by FabianLars** [comment] 2022-06-17 21:02
Duplicate of #4208. Thanks for the request!

**Closed as completed by FabianLars** 2022-06-17 21:02 UTC
Labels: type: feature request

**Comment by nathanbabcock** [comment] 2022-06-17 21:15
Thanks @FabianLars. I searched "taskbar progress" but didn't see that one. Cheers! 🍻
