### ISSUE TITLE
[feat] Support IPC for custom protocol

### ISSUE THREAD

**Issue by seokju-na** [tauri-apps/tauri#5632] opened 2022-11-16 08:11 UTC
### Describe the problem

Hello 👋

Ipc communication not working when create a webview using a custom protocol.

For example, add `myscheme://` protocol and create window with `myscheme://test` url.

```rust
fn protocol(_: &AppHandle, req: &Request) -> Result<Response, Box<dyn std::error::Error>> {
  let pathname = req
    .uri()
    .replace("myscheme://, "");

  let resp = reqwest::blocking::get(format!(
    "http://localhost:3000{pathname}",
    pathname = pathname
  ))?
  .text()?;

  ResponseBuilder::new()
    .status(200)
    .mimetype("text/html")
    .header("Access-Control-Allow-Origin", "*")
    .body(resp.into())
}

fn main() {
  tauri::Builder::default()
    .register_uri_scheme_protocol("myscheme", protocol)
    .setup(|app| {
      WindowBuilder::new(
        app,
        "main",
        WindowUrl::App("myscheme://test".into()),
      )
      .inner_size(1024_f64, 768_f64)
      .resizable(true)
      .visible(true)
      .build()?;
    })
    .invoke_handler(tauri::generate_handler![...])
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
```

---

After debugging, the following part was a problem.

Tauri initialize script only works when `window.location.origin` contains `__TEMPLATE_origin__` value.

`__TEMPLATE_origin__` is from `struct InitJavascript` (inside `initialize_script` function). But the `origin` value seems to only accept `tauri://`. (below code)

core/scripts/init.js
```js
;(function () {
  if (window.location.origin.startsWith(__TEMPLATE_origin__)) {    // only initialize if origin is same
    __RAW_freeze_prototype__
```

core/src/manager.rs (L932)
```rust
  fn initialization_script(
    &self,
    ipc_script: &str,
    pattern_script: &str,
    plugin_initialization_script: &str,
    with_global_tauri: bool,
  ) -> crate::Result<String> {
    #[derive(Template)]
    #[default_template("../scripts/init.js")]
    struct InitJavascript<'a> {
      origin: String,
```

```rust
  /// Get the origin as it will be seen in the webview.
  fn get_browser_origin(&self) -> String {
    match self.base_path() {
      AppUrl::Url(WindowUrl::External(url)) => url.origin().ascii_serialization(),
      _ => format_real_schema("tauri"),
    }
  }
```

```rust
#[allow(dead_code)]
pub(crate) fn format_real_schema(schema: &str) -> String {
  if cfg!(windows) {
    format!("https://{}.localhost", schema)
  } else {
    format!("{}://localhost", schema)
  }
}
```

### Describe the solution you'd like

Support IPC for custom protocol not only `tauri://`. Or, wonder if it is intended.

**Comment by amrbashir** [comment] 2022-11-16 10:37
duplicate of https://github.com/tauri-apps/tauri/issues/5478

**Closed as not planned by amrbashir** 2022-11-16 10:37 UTC
Labels: type: feature request
