### ISSUE TITLE
[feat] Make @tauri-apps/api available from WASM like web-sys

### ISSUE THREAD

**Issue by RagibHasin** [tauri-apps/tauri#11229] opened 2024-10-05 09:19 UTC
### Describe the problem

It is frustrating having to create Rust bindings for Tauri APIs when using a Rust frontend framework.

### Describe the solution you'd like

Tauri should provide a Rust glue crate defining all built-in APIs like `web-sys`.

**Comment by FabianLars** [comment] 2024-10-13 15:23
Duplicate of https://github.com/tauri-apps/tauri/issues/5354

**Closed as not planned by FabianLars** 2024-10-13 15:23 UTC
Labels: type: feature request
