### ISSUE TITLE
[feat] Sync version between Cargo.toml, package.json and tauri.conf.json

### ISSUE THREAD

**Issue by origin-coding** [tauri-apps/tauri#8265] opened 2023-11-20 12:32 UTC
### Describe the problem

In Tauri's configuration documentation, I saw a that **package.version** option can be specified to a path to **package.json** to sync both versions. But it seems there is no way to sync **Cargo.toml**'s version. So I want to ask is there a way to make these versions the same?

### Describe the solution you'd like

A functionality to automatically update version in **Cargo.toml**, and a configuration option to sync these three versions.

**Comment by FabianLars** [comment] 2023-11-20 12:35
If you remove the version field from tauri.conf.json completely it will fall back to the Cargo.toml version.

**Comment by origin-coding** [comment] 2023-11-20 12:40
> If you remove the version field from tauri.conf.json completely it will fall back to the Cargo.toml version.

Well, I use npm package standard-version, so I mainly use the version in **package.json**, and I'm looking for a method to update Cargo.toml's version automatically.

**Comment by amrbashir** [comment] 2023-11-20 12:45
Looks like a duplicate of https://github.com/tauri-apps/tauri/issues/4643

**Closed as not planned by amrbashir** 2023-11-20 12:45 UTC
Labels: type: feature request

**Comment by FabianLars** [comment] 2023-11-20 12:48
Agreed on the duplicate, but would you mind sharing _why_ you want this? Like what do you use the Cargo.toml version for when you set it in tauri.conf.json anyway? Just wanting to understand use cases :)

**Comment by origin-coding** [comment] 2023-11-21 03:47
> Agreed on the duplicate, but would you mind sharing _why_ you want this? Like what do you use the Cargo.toml version for when you set it in tauri.conf.json anyway? Just wanting to understand use cases :)

I just want them to be the same, not for other reasons. Fortunately, I fond a new way of doing this, using another semantic version tool.

**Comment by FabianLars** [comment] 2023-11-21 09:38
That's a valid reason too (and I think the only one I was told so far in this context), thanks :)

**Comment by theodore-evans** [comment] 2025-02-12 14:56
@origin-coding could you share what solution you ended up using? It would be helpful for others (like me) who are trying to solve the same problem.

**Comment by origin-coding** [comment] 2025-02-13 08:46
> [@origin-coding](https://github.com/origin-coding) could you share what solution you ended up using? It would be helpful for others (like me) who are trying to solve the same problem.

No, I didn't find a solution. I found that the compiled application's version is synced to that in package.json, so I thought this could not be a serious problem and I stopped finding the solution.
