### ISSUE TITLE
[bug] on_web_resource_request not work in prod mode

### ISSUE THREAD

**Issue by yang4515** [tauri-apps/tauri#7374] opened 2023-07-06 16:08 UTC
### Describe the bug

#1522 on_web_resource_request not invoked in macos prod mode

### Platform and versions

```text
Environment
  › OS: Mac OS 13.4.1 X64
  › Node.js: 18.16.1
  › npm: 9.5.1
  › pnpm: 8.6.5
  › yarn: 1.22.19
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-aarch64-apple-darwin
```

**Comment by amrbashir** [comment] 2023-07-08 01:15
Closing to lack of information, please provide more info. I will also consider this as duplicate of https://github.com/tauri-apps/tauri/issues/1522 as you specifically mentioned it.

**Closed as not planned by amrbashir** 2023-07-08 01:15 UTC
Labels: type: bug, status: needs triage
