### ISSUE TITLE
Error  cargo install tauri-cli --version ^1.0.0-beta

### ISSUE THREAD

**Issue by abedarev** [tauri-apps/tauri#3054] opened 2021-12-10 13:19 UTC
Version
 cargo 1.58.0-nightly (294967c53 2021-11-29)
 rustc 1.59.0-nightly (e2116acae 2021-12-05)
 
cargo install tauri-cli --version ^1.0.0-beta

 Compiling tauri-bundler v1.0.0-beta.4
error[E0432]: unresolved import `clap::crate_version`
 --> C:\Users\aa\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-cli-1.0.0-beta.7\src/main.rs:6:12
  |
6 | use clap::{crate_version, load_yaml, App, AppSettings, ArgMatches};
  |            ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_version`
   --> C:\Users\aa\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-cli-1.0.0-beta.7\src/main.rs:265:14
    |
265 |     .version(crate_version!())
    |              ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
   --> C:\Users\aa\.cargo\registry\src\github.com-1ecc6299db9ec823\tauri-cli-1.0.0-beta.7\src/main.rs:264:23
    |
264 |   let app = App::from(yaml)
    |                       ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: failed to compile `tauri-cli v1.0.0-beta.7`, intermediate artifacts can be found at `C:\Temp\cargo-installWLfkXS`

Caused by:
  could not compile `tauri-cli` due to 3 previous errors

**Comment by FabianLars** [comment] 2021-12-10 13:21
duplicate of #3050.
You can install from git for now: `cargo install tauri-cli --git https://github.com/tauri-apps/tauri`.

**Closed as completed by FabianLars** 2021-12-10 13:21 UTC
Labels: type: bug, status: invalid
