### ISSUE TITLE
[bug] window.unminimize() not working on Linux

### ISSUE THREAD

**Issue by matthme** [tauri-apps/tauri#5974] opened 2023-01-03 20:11 UTC
### Describe the bug

Calling `window.unminimize()` (https://docs.rs/tauri/latest/tauri/window/struct.Window.html#method.unminimize) does not seem to work on Ubuntu 22.04.

### Reproduction

1. Create a window with `WindowBuilder`
2. Call `.unminimize()` on it from the Rust backend.

### Expected behavior

uniminimize() unminimizes the window.

### Platform and versions

```
Environment
  › OS: Ubuntu 22.04 X64
  › Node.js: 16.11.1
  › npm: 8.0.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.3,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ scripts
  ├─ tests
  ├─ .git
  ├─ crates
  ├─ target
  ├─ docs
  ├─ dist
  ├─ node_modules
  ├─ src-tauri
  ├─ dist-isolation
  ├─ src
  ├─ .github
  ├─ .vscode
  └─ public
```

### Additional context

~~`.show()` doesn't seem to work either~~, although there I'm not exactly sure what it's actually supposed to do based on the documentation...

**Comment by FabianLars** [comment] 2023-01-03 22:11
> .show() doesn't seem to work either, although there I'm not exactly sure what it's actually supposed to do based on the documentation...

`.show()` is the counter-part to `.hide()` - both are unrelated to minimizing

**Comment by amrbashir** [comment] 2023-01-10 14:06
Can't seem to reproduce on my KDE, it works perfectly fine here, please share a reproducible repo.

**Comment by matthme** [comment] 2023-01-10 14:36
Check out `unminimize` branch: https://github.com/matthme/menu-stuck-tauri-macos/tree/unminimize

**Comment by amrbashir** [comment] 2023-01-10 15:01
works fine here, I am afraid this might be a problem specific to the Window manager which we don't have any control over. @FabianLars if you have an ubuntu or any gnome-based distro, could test this?

**Comment by FabianLars** [comment] 2023-01-10 15:19
using the linked repo/branch, both wsl2+wslg and fedora+gnome don't work. (even after changing the allowlist to allow unminimize)

Edit: doesn't work in a x11 session either

**Comment by amrbashir** [comment] 2023-01-10 15:24
How about calling `window.set_focus` afterwards?

**Comment by FabianLars** [comment] 2023-01-10 15:29
Same behavior, with the addition that gnome sends a "xy window is ready" notification lol

**Comment by amrbashir** [comment] 2023-01-10 15:35
Alright, I will close this issue as it seems dependent on the window manager in use which is something that we don't control.

**Closed as not planned by amrbashir** 2023-01-10 15:35 UTC
Labels: type: bug, status: needs triage

**Comment by matthme** [comment] 2023-01-10 16:12
That's sad. I'm not familiar with linux window managers, can we communicate this upstream?

**Comment by Wombosvideo** [comment] 2023-09-04 10:15
Using a default window manager on a supported operating system should always be in-scope for the development team in my opinion. I am using Ubuntu 22.04 with GNOME 42.9 and I am also facing this issue.

My window manager: [^1]

```yaml
Name: GNOME Shell
Class: N/A
PID: N/A
Window manager's "showing the desktop" mode: OFF
```

My desktop and session: [^2]

```yaml
Desktop: GNOME
Session: gnome
```

[^1]: https://askubuntu.com/a/92948
[^2]: https://askubuntu.com/a/227669

**Comment by amrbashir** [comment] 2023-09-04 11:51
We do support GNOME, and we do have an API to use, the problem is in GNOME itself, if you're using an older version of GNOME, these API works but newer versions don't, so it is really incorrect to say that we don't support it.

**Comment by Crypto-Darth** [comment] 2023-11-30 03:19
Any updates on this issue yet? 
I'm kinda new to Tauri and i want to use it but as stated above - GNOME isn't letting me (my app works fine in windows as expected but not on ubuntu 23.10 with wayland)


Is their anyway we can help solve this problem or any workaround this ?
I'd like to help in any way possible

**Comment by davidchalifoux** [comment] 2025-03-01 18:33
> We do support GNOME, and we do have an API to use, the problem is in GNOME itself, if you're using an older version of GNOME, these API works but newer versions don't, so it is really incorrect to say that we don't support it.

I'm trying to replicate how 1Password's tray icon works. Clicking "open" from their tray menu will either show the window if hidden, or unminimize it if minimized. I've been able to get most of this working with Tauri by hiding the window on `CloseRequested`, but unminimizing is the missing piece. Surely there's a way to do this with newer versions of Gnome if 1Pass is doing it with Electron on GNOME 47, no?

**Comment by NiklasEi** [comment] 2025-04-21 10:15
I faced the same issue on Ubuntu 24. Running, one after the other, `unminimize` -> `show` -> `set_focus` worked if the window was just behind something else, but did not work when it was minimized.

The workaround for me was to hide the window first. Running `hide` -> `unminimize` -> `show` -> `set_focus` seems to work in all scenarios.

**Comment by KiselevAlexander** [comment] 2025-06-05 12:15
> I faced the same issue on Ubuntu 24. Running, one after the other, `unminimize` -> `show` -> `set_focus` worked if the window was just behind something else, but did not work when it was minimized.
> 
> The workaround for me was to hide the window first. Running `hide` -> `unminimize` -> `show` -> `set_focus` seems to work in all scenarios.

This helped me solve the same problem on Ubuntu 25.04 with Gnome 48
