### ISSUE TITLE
[bug] Bad performance on linux

### ISSUE THREAD

**Issue by aalhitennf** [tauri-apps/tauri#3988] opened 2022-04-27 17:58 UTC
### Describe the bug

I'm experiencing very bad performance on linux when handling lots of DOM elements. In my project you can drag select items, and selecting lots of them causes ui to lag/freeze on linux.

I made repo that demonstrates the problem:  https://github.com/aalhitennf/tauri-performance  

### Reproduction

1. Clone the repo
2. Install packages with npm install
3. Build with npm run build
4. Run the executable from src-tauri/target/release
5. Start drag selecting items with left mouse button (default file manager behaviour) from up to down and let the autoscroll happen on window border
6. UI starts to lag a lot

### Expected behavior

App runs flawlessly in firefox (linux), electron (linux) and when built on windows, problem happens only on my linux installation.

### Platform and versions

```shell
Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 17.9.0
  › npm: 8.5.5
  › pnpm: 6.32.11
  › yarn: Not installed!
  › rustup: 1.24.3
  › rustc: 1.60.0
  › cargo: 1.60.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu  

webkit2gtk 2.36.1-1
```

**Comment by amrbashir** [comment] 2022-04-27 18:50
At first glance at your code, you're creating about 3000 DOM element and that is expected to have lags and ui freezes for two reasons:
1. DOM operations are slow and expensive
2. you're using react which performs the worst among frameworks in terms of performance

What you should do:
1. test your app on some browsers, like epiphany (especially this one), firefox and chrome and see if you still have lags or not. If not, please let me know.
2. When dealing with these humongous number of DOM elements, it is my recommendation to always use a virtual scroller. It greatly helps performance.
3. (Highly optional and a mere suggestion) Choose a faster framework. I'd recommend preact or solidjs, they both has a similar style to react but much faster especially solidjs.

**Comment by aalhitennf** [comment] 2022-04-27 19:06
Yes i tested the app on Firefox and Vivaldi (Chromium based) and also wrapped it on Electron for testing purposes and in every one of those it performed without problems. Also built it on Windows 10 and it ran without lag/freezing. 

Edit. installed and tested with Epiphany, same lag happens with it, so its webkit on linux that can't handle lots of elements?  

I can try with solidjs if that makes any difference.

**Comment by amrbashir** [comment] 2022-04-27 21:00
It probably won't. And since it is a webkit issue, I hardly think we can fix it, idk maybe enable hardware-accelration if that's a thing?

 Anyways, for now, your best bet is to use a virtual scroller.

**Comment by lucasfernog** [comment] 2022-04-27 21:02
We do enable this one: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-set-enable-accelerated-2d-canvas

Though maybe it helps if we use this one too: https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#webkit-settings-set-hardware-acceleration-policy

**Comment by aalhitennf** [comment] 2022-04-27 21:59
SolidJS actually improved performance greatly. There is still slight "lag" or choppiness, doesn't feel as smooth as in other browsers/platforms but i guess that is fine for now since handling that large amount of elements is very rare case. I'll look into the virtual scroller too.

**Comment by aalhitennf** [comment] 2022-04-28 09:03
@lucasfernog Is there a way i can set the hardware acceleration to "always"? I tried with env variable WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS=1 but i dont think that did nothing.

**Comment by FabianLars** [comment] 2022-04-28 09:44
`WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS` is the default value (and it's also not an env var if i got that right).
I guess it's just webkit(gtk) not holding up that well🤷
Oh and hardware acceleration in a browser context was/is generally in a bad state on linux, so maybe that adds up too.

**Comment by amrbashir** [comment] 2022-04-29 10:25
I guess we can't do anything to improve this situation so I will close this and hope webkit2gtk makes improvements in future releases.

**Closed as completed by amrbashir** 2022-04-29 10:25 UTC
Labels: type: bug

**Comment by LifeIsStrange** [comment] 2022-05-11 10:37
@amrbashir you can improve the performance and correctness situation by bringing support for a chromium webview in Linux. This would allow cross platform consistency with windows.
You might leverage e.g the QT webengine

**Comment by amrbashir** [comment] 2022-05-11 10:43
@LifeIsStrange we are looking into making using Servo, read about it here https://twitter.com/TauriApps/status/1505618001126731781?t=I9IYzsJCURN0TN10MW_L2A&s=19

**Comment by LifeIsStrange** [comment] 2022-05-11 10:54
@amrbashir You can't be serious.. I've actively followed servo development since the day it was opensourced and while an interesting technical project it is nowhere near a real browser, it has broken rendering/funcionality on countless websites. Even its development has mostly stalled.
Tauri has a real value proposition over electron, to not duplicate the webview per app and only download it if not already present on the system. the windows/linux webview inconsistency of using webkit is a major flaw for end users that brings so many limitations, missing features, inconsistencies, correctness and performance bugs. Using the qtwebengine would enable consistent chromium support, which is not a lot to ask, and you could retain support for webkit on linux optionally.
Bringing support for servo will solve nothing for end users. Although I understand it is an opensource project and maybe a hobby project so if that's what personally interest you, go for it! But as for end users needs, that's not the actual need.

@lucasfernog friendly ping

**Comment by amrbashir** [comment] 2022-05-11 11:11
> it has broken rendering/funcionality on countless websites. Even its development has mostly stalled.

We obviously won't ship in its current state, a lot of work needed and this will be offered as an alternative to system webviews.

> Tauri has a real value proposition over electron, to not duplicate the webview per app and only download it if not already present on the system. 

We are still gonna do that with Servo.

> the windows/linux webview inconsistency of using webkit is a major flaw for end users that brings so many limitations, missing features, inconsistencies, correctness and performance bugs.

You have to deal with these consistencies with normal web apps. It is not something new to web dev and macOS also uses webkit not chromium.

> Using the qtwebengine would enable consistent chromium support, which is not a lot to ask

This is not a trivial task and I am not sure if their license will suit us (not my field of expertise).

> Bringing support for servo will solve nothing for end users.

How so? if it is done right then users get a consistent experience while maintaining a low bundle size.

**Comment by LifeIsStrange** [comment] 2022-05-11 12:29
> a lot of work needed

yeah that's a lot of work indeed.
I didn't knew you had a billion dollar budget to spend on fundamental R&D.

> This is not a trivial task

You must be joking, if you manage to make servo become a functional web standard compliant browser, integrating QT webengine should feel very easy

**Comment by nothingismagick** [comment] 2022-05-11 13:33
Hey @LifeIsStrange - we are not planning on making Servo into a browser. The research right now is to turn it into a webview, which is a much different value proposition.

**Comment by infogulch** [comment] 2022-06-18 21:57
Hi! I'm curious how the development of servo as an alternative target webview is going.

I don't see any more mentions of servo in the github org or on twitter. There is a [servo discussion](https://github.com/servo/servo/discussions/28582#discussioncomment-1250764) where tauri was mentioned late last year, but nothing since.

Is this design still being considered? Is the development public?

**Comment by zoicho** [comment] 2022-11-30 20:39
personally tested same functionality of inflating div elements on scroll + some calculation logic with React and Vue. React + Tauri start to stutter very soon because of React´s expensive lists recalculations, both keyed and nonkeyed, same functionality on Vue is smooth like butter
I think you can implement same functionality dozens ways in these frameworks, so try to optimize expensive big lists iterations

**Comment by ghost** [comment] 2022-12-16 01:53
Any guides on how to improve the performance on linux?

I recently turned to Asahi linux on a MBP Max, the basic tauri app built with Solid.js is basically unusable on linux, even the css animation is laggy, while on macOS it's all good.

**Comment by Blquinn** [comment] 2023-02-27 21:14
I don't think this issue should be closed. 

I don't mean to sound rude, but performance on linux is currently atrocious due to webkitgtk.

I have a very basic app, interacting with a content editable in the app causes paints to take between 70-300ms, just to enter a single character. I'm using a 2021 Dell XPS, needless to say anything else performs just fine. It also performs great on all other platforms, never dropping below 60fps, never a dropped frame. (Including macOS which is also webkit :/ )

I think there are a couple possible paths forward:

1. Using gtk4 and webkitgtk5 (A lot of people are saying big performance improvements there)
2. Use a different webview (Qt WebEngine, CEF, other...)

**Comment by buxx** [comment] 2023-03-13 11:19
Hello, for information, I have terrible performance too. This performance problem is reproducible with `epiphany-browser`. My system is Ubuntu 20.04, so a little bit dated. I can add more information if needed (ask me command lines to execute).

**Comment by worapolbpan** [comment] 2023-08-11 14:44
Problem occurred same here. Performance is bad with simple app too.

**Comment by lizheng2018CC** [comment] 2023-09-06 07:37
I've encountered a similar situation as well. Our company initially started front-end development using Electron, but later on, we considered improving application performance with Tauri. However, when we ported the Tauri-developed application to ARM Linux, its smoothness was even worse than Electron. Additionally, I don't believe the WebKit version on our system is very low; it's webkit2gtk-4.0.

**Comment by JohnYepthomi** [comment] 2023-10-16 14:08
> I've encountered a similar situation as well. Our company initially started front-end development using Electron, but later on, we considered improving application performance with Tauri. However, when we ported the Tauri-developed application to ARM Linux, its smoothness was even worse than Electron. Additionally, I don't believe the WebKit version on our system is very low; it's webkit2gtk-4.0.

Have you tried it on windows? I think the issue is with webkit on Linux from what ive read so far but i don't now first hand. In my case there's stuttering or frame lag any time there's any animation. Its very annoying and i have to turn animation off. The same application runs like butter on Linux Chrome.

I think the issue is with webkit on Linux. Is anyone experienceing lags because of animations?

**Comment by Blquinn** [comment] 2023-10-16 18:15
@JohnYepthomi There's no issue on windows, that's why this issue is about Linux specifically and the webkit backend.

**Comment by mrmelon54** [comment] 2024-04-18 23:03
I get the same bad performance and unresponsiveness from tauri apps
I have tried 2 so far: [Wootomation](https://wooting.io/wootomation) and [JellyPlayer](https://github.com/prayag17/JellyPlayer) and have the same laggy stuttering bad performance from both of them

**Comment by saverioscagnoli** [comment] 2024-04-23 23:19
Same here. I have to virtualize a list of a couple thousand elements. On Windows it goes smooth as butter. Tested it on Chrome and Firefox, and smooth there too; on Linux (Fedora 40) it is atrocious: entries disappearing, lagging animations, even simple functions take a noticeable amount of time. Using webkit2gtk4.1

**Comment by pikdum** [comment] 2024-05-18 19:58
I was hoping to use Tauri for a simple application, but the performance was so bad I had to port it over to Electron instead.
Hope there's some plan for improving this, since the rest of Tauri seemed nice.

**Comment by mrmelon54** [comment] 2024-05-19 23:24
Can we reopen this issue?

**Comment by ansirotenko** [comment] 2024-10-31 00:55
My app is really slow on linux. Windows and mac are fine. It seems that rendering of css is somewhat slow in webgtk. Also I have noticed that css rules works differently on linux, due to that I have to do a lot of exceptions for linux rendering.

**Comment by oatmealproblem** [comment] 2024-10-31 03:14
Just to let other here know, this is apparently something on the radar of the Tauri team, [according to their blog](https://tauri.app/blog/tauri-20/):

> Things on our radar for the future we feel we should mention at least:
> - Providing or Bundling Chromium Embedded Framework (CEF) for Linux as an alternative to WebKit2GTK
> - [Servo](https://github.com/servo/servo) as Tauri WebView ([POC in Wry](https://github.com/tauri-apps/wry/tree/servo-wry-demo))

See also: https://github.com/tauri-apps/tauri/issues/14963

**Comment by uxobsessed** [comment] 2025-04-03 08:48
Browser [Left] on both images
![Image](https://github.com/user-attachments/assets/24733fc5-47b3-44e7-b65c-7dbf3793432b)
![Image](https://github.com/user-attachments/assets/69c65461-1496-4bf3-b7fb-964bb3500e66)

Experiencing direct 50% FPS drops on dev and build both on linux.
tested on React tsx + Rust and Solid tsx + Rust. 

72fps on Charge ((dev/build) binary) vs 144fps consistent on Browser (Zen)
32fps on battery vs 120fps on browser

Maybe it's a issue specific to my laptop. But there seems to be no discussion about this being a thing besides this one. So i had to bring this to attention.
Apologies if this was a dead bump and a silly mistake on my part.

**Comment by FabianLars** [comment] 2025-04-03 08:56
Nah, all good. We don't mind further examples of bad webkitgtk performance. It won't change our plans though (we still want to replace it / offer alternatives, it just takes time especially with such a small team that's busy elsewhere). I heard the gtk4 version performs _slightly_ better though and that upgrade is also underway as a stepping stone so maybe that'll help as well.

**Comment by m4yc3x** [comment] 2025-07-21 04:47
Not trying to add to the echo chamber here, but I wanted to provide information about my issue in case it helps anyone.

- Using ThreeJS WebGL with Vanilla React + Tauri.
- Tested with `libwebkitgtk-6.0-4` and `libwebkit2gtk4.1`
- Windows & Mac work great with good performance
- Ubuntu & Arch Linux can run the application but FPS drops down to 2 frames per sometimes
- Trying to set the following build environment variables and installing 'wry' **helped with FPS slightly** but other CSS elements like absolute positions can break.

`build.rs`:
```rust
#[cfg(target_os = "linux")]
{
    // multiple environment variable combinations for chromium webview
    std::env::set_var("WRY_WEBVIEW_BACKEND", "chromium");
    std::env::set_var("TAURI_WEBVIEW_BACKEND", "chromium");
    std::env::set_var("WEBVIEW_BACKEND", "chromium");
    
    // try to disable compositing and use hardware acceleration
    std::env::set_var("WEBKIT_DISABLE_COMPOSITING_MODE", "0");
    std::env::set_var("WEBKIT_FORCE_HARDWARE_ACCELERATION", "1");
    
    // flags that might help with chromium detection
    std::env::set_var("CHROME_DEVEL_SANDBOX", "/usr/lib/chromium-browser/chrome-sandbox");
    std::env::set_var("CHROME_WRAPPER", "/usr/bin/chromium-browser");
}
```
`cargo.toml`:
```
#...

[dependencies]
#...
wry = { version = "0.52", features = [] }
```

I cannot get the application to run at an acceptable FPS and am wondering if there is any way to bundle a chromium-browser wrapper with Tauri while maintaining backend Rust functionality. I know webkit support in Linux is lackluster but Chrome and Firefox can run the localhost address in window at perfect 60 FPS on Ubuntu. Anyways, I guess I will just wait and maybe play with some ideas on a fork. Thanks to the maintainers for working through these issues!

**Comment by montecassino** [comment] 2025-10-01 09:11
Thought I was the only one experiencing this issue, damn. Using Ubuntu 25.04 right now. I'm building a PDF Reader. Adding shadow to a component is also a pain since it makes the experience laggy.

**Comment by Blquinn** [comment] 2025-10-01 13:49
> // multiple environment variable combinations for chromium webview
> std::env::set_var("WRY_WEBVIEW_BACKEND", "chromium");
> std::env::set_var("TAURI_WEBVIEW_BACKEND", "chromium");
> std::env::set_var("WEBVIEW_BACKEND", "chromium");

@m4yc3x Please don't make people read and spend time thinking about AI hallucinated code.

Wry is the webview library that tauri uses, adding it to your dependencies likely accomplished nothing because it was already there. It only supports webkit on linux which is the entire point of this issue, so if changing an environment variable fixed this issue, then it wouldn't exist.

**Comment by m4yc3x** [comment] 2025-10-01 14:17
@Blquinn Well forgive me for being _thorough_ in my rhetoric, even though others have stated they wouldn't mine more examples of bad webkit performance. Immediately assuming AI generated environment variables says a lot more about you that it does me. Even though they didn't work, those environment variables are present across the web and are not from AI.

**Comment by FabianLars** [comment] 2025-10-01 14:54
I can see a bit where Blquinn is coming from tbh. The first 3 vars were never a thing and i can't find any mention of them anywhere.

`WEBKIT_DISABLE_COMPOSITING_MODE` is the only correct one.
`WEBKIT_FORCE_HARDWARE_ACCELERATION` doesn't exist but it would be the opposite of the other one.

I can understand where the 2 chrome wrapper ones come from if you don't know that the first 3 are hallucinations.

But yeah, thanks for providing more examples of bad performance as we asked for :)

**Comment by Blquinn** [comment] 2025-10-02 01:57
Sorry, I know this is a bit petty, and I don't want to personally attack anybody, but I just don't understand why you're lying about this. Also, I think there is a lesson here that affects all of us in the new LLM based world.

There is no documentation of these variables anywhere on the searchable internet:

https://www.google.com/search?q=%22WRY_WEBVIEW_BACKEND%22
https://www.google.com/search?q=%22TAURI_WEBVIEW_BACKEND%22

And nowhere in the tauri repos:

https://github.com/search?q=org%3Atauri-apps%20WRY_WEBVIEW_BACKEND%20&type=code
https://github.com/search?q=org%3Atauri-apps%20TAURI_WEBVIEW_BACKEND%20&type=code
https://github.com/search?q=org%3Atauri-apps%20WEBVIEW_BACKEND%20&type=code

And just to show how misinformation can rapidly affect others, see how many people copied your code verbatim already: https://github.com/search?q=WRY_WEBVIEW_BACKEND+&type=code

All this to say, please just validate any code that is generated by LLMs, if you choose to use them, and certainly before posting it to github.
