### ISSUE TITLE
[bug] The tauri application runs as an administrator on the Windows system, and the file-drop event fails.

### ISSUE THREAD

**Issue by escfex** [tauri-apps/tauri#9271] opened 2024-03-26 00:36 UTC
### Describe the problem

`await listen(
      'tauri://file-drop',
      async (event) => { }
       
    );`

### Describe the solution you'd like

..

**Comment by FabianLars** [comment] 2024-05-10 17:29
Duplicate of https://github.com/tauri-apps/tauri/issues/8218

**Closed as not planned by FabianLars** 2024-05-10 17:29 UTC
Labels: type: feature request, platform: Windows
