### ISSUE TITLE
[bug] error ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by hhtower** [tauri-apps/tauri#7383] opened 2023-07-08 15:21 UTC
### Describe the bug

error info：
- error node_modules\@tauri-apps\api\chunk-V5J25SYE.js (1:13) @ n
- error ReferenceError: navigator is not defined

the key code (react):
import { appWindow } from "@tauri-apps/api/window";
register(keys.join("+"), () => {
   appWindow.show();
   appWindow.setFocus();
  });
  
useEffect(() => {
  console.log("registerKey init", typeof window )
  if(clientConfig?.isApp) {
    registerKey(keyStore.get() || []);
  }
});

### Platform and versions

```text
tauri: 1.4.0
react: 18.2.0
next: 13.4.6
```

**Comment by amrbashir** [comment] 2023-07-08 15:24
duplicate of https://github.com/tauri-apps/tauri/issues/6226 and many others

Tauri api package is not intended to be used in server side code, as in next.js or other SSR frameworks. If you must use an SSR frameworks, either guard the import in a client side code, by using `await import` or disable the SSR capabilites.

**Closed as not planned by amrbashir** 2023-07-08 15:24 UTC
Labels: type: bug, status: needs triage
