### ISSUE TITLE
[feat] Please bring code support for python

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri#5335] opened 2022-10-03 16:35 UTC
### Describe the problem

Python is used by a lot of individuals and hence there is  a great demand for support of python in Tauri.

### Describe the solution you'd like

Can you please build support for python in tauri apps. It would be great to build web browser based python apps using tauri and there will be a lot of users who will use this library.

**Comment by amrbashir** [comment] 2022-10-03 16:39
duplicate of #4670

**Closed as not planned by amrbashir** 2022-10-03 16:39 UTC
Labels: type: feature request
