### ISSUE TITLE
[feat] I want a configuration that ignores https certificates.

### ISSUE THREAD

**Issue by maoyutofu** [tauri-apps/tauri#6359] opened 2023-02-25 14:36 UTC
### Describe the problem

Most of the time I use a self-signed ssl certificate. I used axios to request an interface, but now I got an error.

`net::ERR_SSL_PROTOCOL_ERROR`

### Describe the solution you'd like

```
"security": {
      "trustSSL": true
}
```

**Comment by FabianLars** [comment] 2023-02-25 14:51
Duplicate of https://github.com/tauri-apps/tauri/issues/4039.
Currently you have to resort to proper certificates or using rust for the requests (tauri's js http module works too since it uses the rust backend under the hood)

**Closed as not planned by FabianLars** 2023-02-25 14:51 UTC
Labels: type: feature request

**Comment by tjz101** [comment] 2023-02-25 14:59
> Duplicate of #4039. Currently you have to resort to proper certificates or using rust for the requests (tauri's js http module works too since it uses the rust backend under the hood)

It is appropriate for a small number of interfaces to use rust proxy requests. When the number of interfaces increases, it becomes very troublesome to use rust to do http requests. Unless I start an http server in rust to reverse proxy to the https interface.

**Comment by tonyxiang1120** [comment] 2025-03-22 17:12
you can try this method:
1.open src-tauri\target\debug\deps\wry-*******.d file, figure out the wry source file location;
2.for  windows system, edit wry source file webview2.rs, search the string "no-user-gesture-required", in that method end, add "arguments.push_str(" --ignore-certificate-errors");" before return arguments;
3.clean src-tauri\target\ directory;
4.npx tauri dev

for other os , you can try edit correspond source file
