### ISSUE TITLE
[bug] Black bars when changing React and Tauri app window size

### ISSUE THREAD

**Issue by f1nked** [tauri-apps/tauri#7322] opened 2023-06-29 19:10 UTC
### Describe the bug

When I resize the app window with the cursor, a black bar appears. There seems to be a delay in rendering.  

https://github.com/tauri-apps/tauri/assets/23584686/c6f3dd7f-55d9-4249-a4bd-571f2be0bce2

### Reproduction

Resize application window

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22000 X64
    ✔ WebView2: 114.0.1823.58
    ✔ MSVC:
        - Visual Studio Build Tools 2022
        - Visual Studio Build Tools�2019
    ✔ rustc: 1.70.0 (90c541806 2023-05-31)
    ✔ Cargo: 1.70.0 (ec8a8a0ca 2023-04-25)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 18.14.0
    - npm: 9.3.1
```

**Comment by FabianLars** [comment] 2023-06-29 19:19
this is mostly just a chromium issue (try resizing any chromium browser and it will behave the same). That said, in many tauri apps it tends to be a bit weird but you can try this workaround: https://github.com/tauri-apps/tauri/issues/6322#issuecomment-1448141495 - and with that i'm also going to close this as a duplicate of that issue, thanks for the report.

**Closed as not planned by FabianLars** 2023-06-29 19:19 UTC
Labels: type: bug, status: needs triage

**Comment by f1nked** [comment] 2023-06-29 19:53
I didn't see the difference when I took your advice. The problem was smoothed by "transparent": true, but it still looks weird. Is there any way to set the background color?

**Comment by FabianLars** [comment] 2023-06-29 20:11
> I didn't see the difference when I took your advice

That's good to know. We did expect it to not work for everyone (which is also why we don't include it by default) but you're actually the first one where this is the case.

> Is there any way to set the background color?

Not yet, no.

**Comment by f1nked** [comment] 2023-06-29 20:27
A good solution would be to set transparency, but a black bar appears under the window menu. This is not how it works in the Edge browser. Is there a way to make the window behave like Edge? 
![image](https://github.com/tauri-apps/tauri/assets/23584686/9b4051fe-3c3e-4772-80de-5fcdcdcf5b38)

**Comment by FabianLars** [comment] 2023-06-29 20:28
Only by disabling decorations and drawing your own titlebar with html/css/js which apparently seems to be what edge is doing concept-wise.
