### ISSUE TITLE
yarn tauri dev failed on aarch64/arm64 OS

### ISSUE THREAD

**Issue by sousukerai** [tauri-apps/tauri#2625] opened 2021-09-22 03:23 UTC
### **Describe the bug**
yarn tauri dev failed on aarch64/arm64 Linux OS

### **To Reproduce**

1. yarn add -D @tauri-apps/cli
2.  yarn tauri info
3. error: 
```bash
 app:spawn Running "/home/alexlai/tauri-proj/my-first-react-tauri-app/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms

/home/alexlai/tauri-proj/my-first-react-tauri-app/node_modules/@tauri-apps/cli/bin/tauri-cli: 1: ELF: not found
/home/alexlai/tauri-proj/my-first-react-tauri-app/node_modules/@tauri-apps/cli/bin/tauri-cli: 1: Syntax error: word unexpected (expecting ")")

 app:spawn Command "/home/alexlai/tauri-proj/my-first-react-tauri-app/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 2 +1ms
```

### **Platform and Versions (required):**

```
Operating System

Ubuntu 5.11.18-202107261522~focal (2021-07-26) aarch64 aarch64 aarch64 GNU/Linux

### **Additional context**

The installed tauri-cli with `file tauri-cli` command will show, 

 ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=bdbb7aa0a0dbc921643108314fd166e6d410ac8e, with debug_info, not stripped

**Comment by sousukerai** [comment] 2021-10-13 07:18
On 2021-10-13. I did the same process again, and it went through without any errors.  I must have done something wrong, please ignore the above comment!  Thanks.

**Comment by kristiandupont** [comment] 2021-10-17 20:13
I am still getting:
```
> yarn tauri build
yarn run v1.22.15
warning package.json: No license field
$ tauri build
 app:spawn Running "/usr/workspace/repositories/app-new/node_modules/@tauri-apps/cli/bin/tauri-cli tauri build" +0ms

x86_64-binfmt-P: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

 app:spawn Command "/usr/workspace/repositories/app-new/node_modules/@tauri-apps/cli/bin/tauri-cli" failed with exit code: 255 +1ms
error Command failed with exit code 1.
```

On a brand new install. Ubuntu arm64.

**Comment by sousukerai** [comment] 2021-10-19 08:31
Our company is experimenting  to use Tauri Studio to package  our software to see it will be better than using electron. If you follow https://tauri.studio/en/docs/development/integration, using `yarn add -D @tauri-apps/cli`, the error on arm64 is still there.

If you could read Japanese, please follow `https://www.klab.com/jp/blog/tech/2020/0914-tauri.html`.  Using `yarn tauri init` then `yarn tauri build` will be OK!

Hope this will help.

**Comment by leimantas** [comment] 2021-10-29 09:21
Same. Workaround: `cargo tauri dev` and all works.

**Comment by amrbashir** [comment] 2021-12-01 18:24
duplicate of #2421

**Closed as completed by amrbashir** 2021-12-01 18:24 UTC
Labels: status: invalid
