### ISSUE TITLE
[bug] Empty window of Leptos template

### ISSUE THREAD

**Issue by seongs1024** [tauri-apps/tauri#8028] opened 2023-10-17 08:36 UTC
### Describe the bug

It failed to render the Leptos template 

<img width="912" alt="image" src="https://github.com/tauri-apps/tauri/assets/56729421/b419234f-869c-4cf8-8db1-e199e977f59b">

### Reproduction

```
cargo binstall create-tauri-app
cargo create-tauri-app mango2 -t leptos -m cargo
cargo binstall trunk
cargo binstall tauri-cli
rustup target add wasm32-unknown-unknown
cd mango2
cargo tauri dev
```

### Expected behavior

solid-ts template is rendered well.

<img width="912" alt="image" src="https://github.com/tauri-apps/tauri/assets/56729421/fb99bdc2-56f6-438f-8c79-ad1d1c66c201">

### leptos template
```text
[✔] Environment
    - OS: Mac OS 10.15.7 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0-nightly (49691b1f7 2023-10-16)
    ✔ Cargo: 1.75.0-nightly (6fa6fdc76 2023-10-10)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-apple-darwin (environment override by RUSTUP_TOOLCHAIN)
    - node: 18.18.2
    - pnpm: 8.9.2
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: 1.5.3
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.5.3

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
```

### solid-ts template
```
[✔] Environment
    - OS: Mac OS 10.15.7 X64
    ✔ Xcode Command Line Tools: installed
    ✔ rustc: 1.75.0-nightly (49691b1f7 2023-10-16)
    ✔ Cargo: 1.75.0-nightly (6fa6fdc76 2023-10-10)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-apple-darwin (default)
    - node: 18.18.2
    - pnpm: 8.9.2
    - npm: 9.8.1

[-] Packages
    - tauri [RUST]: 1.5.2
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.4
    - tao [RUST]: 0.16.4
    - tauri-cli [RUST]: 1.5.3
    - @tauri-apps/api [NPM]: 1.5.0
    - @tauri-apps/cli [NPM]: 1.5.2

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: SolidJS
    - bundler: Vite
npm notice
npm notice New major version of npm available! 9.8.1 -> 10.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.0
npm notice Run npm install -g npm@10.2.0 to update!
npm notice
```

### Additional context

Inspecting elements is like:
```html
<html><head>
    <meta charset="utf-8">
    <title>Tauri + Leptos App</title>
    <link rel="stylesheet" href="/styles-8594f9560b2c9a3f.css">
    
    <script type="module">import init from '/mango2-ui-4f95f900c2efd226.js';init('/mango2-ui-4f95f900c2efd226_bg.wasm');</script>
  
<link rel="preload" href="/mango2-ui-4f95f900c2efd226_bg.wasm" as="fetch" type="application/wasm" crossorigin="">
<link rel="modulepreload" href="/mango2-ui-4f95f900c2efd226.js"></head>
<body>
<script>(function () {
    var protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    var url = protocol + '//' + window.location.host + '/_trunk/ws';
    var poll_interval = 5000;
    var reload_upon_connect = () => {
        window.setTimeout(
            () => {
                // when we successfully reconnect, we'll force a
                // reload (since we presumably lost connection to
                // trunk due to it being killed, so it will have
                // rebuilt on restart)
                var ws = new WebSocket(url);
                ws.onopen = () => window.location.reload();
                ws.onclose = reload_upon_connect;
            },
            poll_interval);
    };

    var ws = new WebSocket(url);
    ws.onmessage = (ev) => {
        const msg = JSON.parse(ev.data);
        if (msg.reload) {
            window.location.reload();
        }
    };
    ws.onclose = reload_upon_connect;
})()
</script></body></html>
```

<img width="1489" alt="image" src="https://github.com/tauri-apps/tauri/assets/56729421/9a183882-353c-4724-bd5a-225c0ccc3709">

**Comment by seongs1024** [comment] 2023-10-17 08:45
#5143 

Not solved(still empty page) with this command
 
```
WEBKIT_DISABLE_COMPOSITING_MODE=1 cargo tauri dev
```

**Comment by FabianLars** [comment] 2023-10-17 09:51
The WEBKIT_... env var only works on Linux. I could imagine that your macos version is too old for Leptos 🤔 macos 10.15 is basically Safari 13. To somewhat confirm this, can you run `cargo tauri dev` and then open http://localhost:1420/ in the actual Safari browser? (it should be a newer version than what the webview uses)

**Comment by seongs1024** [comment] 2023-10-17 10:53
It rendered on the Safari browser by that URL
```
Safari: Version 15.6.1 (15613.3.9.1.16, 15613)
``` 

<img width="2653" alt="image" src="https://github.com/tauri-apps/tauri/assets/56729421/d4caf242-de80-498e-a40c-5660f0a99cb5">

~~How can I check which webview version did I use for tauri?~~

**Comment by seongs1024** [comment] 2023-10-17 11:53
[From this article](https://tauri.app/v1/references/webview-versions#macos--ios), I can find out that my Webview version is `15609.4.1.1.1`

```
awk '/CFBundleVersion/{getline;gsub(/<[^>]*>/,"");print}' /System/Library/Frameworks/WebKit.framework/Resources/Info.plist
```

**Comment by SeaIsCoder** [comment] 2023-10-19 03:07
i meet the same scence,not work

**Comment by sshine** [comment] 2024-09-21 20:36
I confirmed today that the `tauri-leptos-example` still has a blank screen on both MacOS and NixOS.

The Leptos app advertised in the terminal, and running in the background, works fine:

```
2024-09-21T20:32:26.366620Z  INFO 📡 server listening at:
2024-09-21T20:32:26.366624Z  INFO     🏠 http://127.0.0.1:1420/
```

While broken, it still respects the OS'es darkmode settings (blank white on MacOS, blank dark on NixOS).

**Comment by devklick** [comment] 2024-10-04 10:19
Seeing the same issue on Linux Mint and Ubuntu. Setting the `WEBKIT_DISABLE_COMPOSITING_MODE` env var does not help.

While it _does_ display in browser, the template doesnt seem to work. Adding a name into the "Enter a name..." input box and hitting submit logs a console error:
> `Uncaught TypeError: window.__TAURI__ is undefined`

<details>
<summary>Full error</summary>

```
Uncaught TypeError: window.__TAURI__ is undefined
    __wbg_invoke_2248ef9a055baf9e http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:443
tauri_leptos-ui-4b8232689e3a6505.js:443:21
    __wbg_invoke_2248ef9a055baf9e http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:443
    h879737e07214334c http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:509048
    h54fbf7671b1fe1b1 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:374569
    h52d0dc2f925eb3fd http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:586907
    h7618b93a87b9f735 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:520430
    hecfe696c73401af0 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1002501
    tauri_leptos_ui-0878ccc4d226cc29.wasm.<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h2c9112b610497e94 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:919401
    __wbg_adapter_36 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:223
    real http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:200
    (Async: VoidFunction)
    __wbg_queueMicrotask_12a30234db4045d3 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:674
    he5dce69c8c24b9e9 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1097444
    hb23bea0ab17f104f http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:666877
    h9e7e3c79d035f1c3 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1138985
    h391400f021751573 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:810366
    h9a70801afc31025e http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:924384
    h3552c8e96f7d6739 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:508002
    h776226b1125a9136 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:718941
    h78c9420b8143b62f http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1187762
    h8e9c4927bbadcd29 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:759090
    tauri_leptos_ui-0878ccc4d226cc29.wasm.<alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::hf44d2b1f2815e9df http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1067968
    hf7ed4a7fd4ac8e66 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:801915
    tauri_leptos_ui-0878ccc4d226cc29.wasm.<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h7c1e2d243d8612b5 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:918291
    __wbg_adapter_30 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:215
    real http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:200
    __wbg_call_89af060b4e1523f2 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:699
    handleError http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:236
    __wbg_call_89af060b4e1523f2 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:698
    h2a08a88c1ade1deb http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:670560
    h041812f34b625b88 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:274317
    he0043e4fef381232 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:842501
    tauri_leptos_ui-0878ccc4d226cc29.wasm.<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h1683f429950d2fbe http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:918849
    __wbg_adapter_33 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:219
    real http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:200
    (Async: EventListener.handleEvent)
    __wbg_addEventListener_e167f012cbedfa4e http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:605
    handleError http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:236
    __wbg_addEventListener_e167f012cbedfa4e http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:603
    h10d349e9cba952b1 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:652007
    h59fdf3d6b081cbec http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:335500
    h1c50aab31c522847 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:699051
    h70880d968958e4a2 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:932356
    h26b3a6f6d9aa668e http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:896591
    hf923102eef42a81c http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:261171
    hf1d1418e9c44fba8 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:25756
    h4edf10916d44de3f http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1173175
    tauri_leptos_ui-0878ccc4d226cc29.wasm.<leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::{{closure}}::h0b269ea8bbeae3fe http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:172039
    h51d1f1c7610dec6c http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:800554
    h098f2575c9031549 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1131703
    h57dac09a6be21b77 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:822482
    hc8d2737fcf78344d http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:819666
    tauri_leptos_ui-0878ccc4d226cc29.wasm.<leptos_dom::components::Component<F,V> as leptos_dom::IntoView>::into_view::hefcb3af68d924ad3 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:42981
    tauri_leptos_ui-0878ccc4d226cc29.wasm.<Func as leptos::ComponentConstructor<()>>::construct::h5a36ca2fbca87e25 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1045107
    hb38d4c95af485549 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1149630
    hf8f2d74928396e75 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1131514
    hea1f3469141e77f8 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:647173
    h7067ceed65132271 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1105022
    h254e5f4814e5b95c http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:982477
    h1a700ac04ec7439b http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1187772
    hf894678335498066 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1152561
    h7376f893b98ca804 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1152457
    he7e28ddac2c88836 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1001069
    hd11826c8b61b0248 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:845042
    he721df8f2160d393 http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:992421
    main http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1185113
    wasm http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505_bg.wasm:1187376
    __wbg_finalize_init http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:842
    __wbg_init http://127.0.0.1:1420/tauri_leptos-ui-4b8232689e3a6505.js:890
    AsyncFunctionNext self-hosted:799
    (Async: async)
    <anonymous> http://127.0.0.1:1420/:11
```

</details>

Edit: although based on [this SO answer](https://stackoverflow.com/a/73818815/6236042), this error is probably expected when running in a browser.

**Comment by Artvenn** [comment] 2024-10-19 00:33
The same bug. Also tried with stable rust but didn't help

```
[✔] Environment
    - OS: Ubuntu 24.4.0 x86_64 (X64)
    ✔ webkit2gtk-4.1: 2.44.3
    ✔ rsvg2: 2.58.0
    ✔ rustc: 1.84.0-nightly (3ed6e3cc6 2024-10-17)
    ✔ cargo: 1.84.0-nightly (8c30ce536 2024-10-15)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: nightly-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)
    - bun: 1.1.31
    - deno: deno 2.0.2

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.2
    - tao 🦀: 0.30.3
    - tauri-cli 🦀: 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
```

**Comment by SakiiCode** [comment] 2024-10-24 19:58
Possible duplicate of https://github.com/tauri-apps/tauri/issues/10626

**Comment by FabianLars** [comment] 2024-10-24 20:22
Only the last comment(s) i guess. The initial comments were about another issue older than the one that caused 10626.

**Closed as not planned** 2024-12-05 15:12 UTC
Labels: type: bug, status: upstream, status: needs triage
