### ISSUE TITLE
`@tauri-apps/cli` has un-declared dependencies

### ISSUE THREAD

**Issue by kubijo** [tauri-apps/tauri#2256] opened 2021-07-20 13:23 UTC
### **Describe the bug**
When running under yarn with PNP & trying to use the `tauri icon` command I get the following error:

```
 λ yarn tauri icon --log --icon ~/Downloads/icon.png --compression="zopfli"
[tauri]: running icon
(node:136357) UnhandledPromiseRejectionWarning: Error: @tauri-apps/cli tried to access graceful-fs, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: graceful-fs
Required by: @tauri-apps/cli@npm:1.0.0-beta.6 (via …/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/)
```

### **Platform and Versions (required):**
```
app:spawn Running "…/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/bin/tauri-cli tauri info" +0ms

Operating System - Ubuntu, version 21.04 X64

Node.js environment
  Node.js - 14.17.0
  @tauri-apps/cli - 1.0.0-beta.6
  @tauri-apps/api - Not installed

Global packages
  npm - 6.14.13
  yarn - 3.0.0-rc.12.git.20210720.hash-0bb4746e

Rust environment
  rustc - 1.53.0
  cargo - 1.53.0

App directory structure
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.5
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../../../build/js/bundle/toolbox
  devPath - http://localhost:3000
  framework - React
```

### **Additional context**
- https://classic.yarnpkg.com/en/docs/pnp/troubleshooting/#toc-is-trying-to-require-without-it-being-listed-in-its-dependencies

### **Stack Trace**
```
Require stack:
- …/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/tauricon.js
- …/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/bin/tauri-icon.js
- …/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/bin/tauri.js
    at Function.external_module_.Module._resolveFilename (…/.pnp.cjs:48645:55)
    at Function.external_module_.Module._load (…/.pnp.cjs:48465:48)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.729 (…/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/tauricon.js:2:348)
    at __webpack_require__ (…/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/tauricon.js:2:37418)
    at Object.333 (…/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/tauricon.js:2:24153)
    at __webpack_require__ (…/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/tauricon.js:2:37418)
    at …/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/tauricon.js:2:37911
    at …/.yarn/unplugged/@tauri-apps-cli-npm-1.0.0-beta.6-ae47f770e1/node_modules/@tauri-apps/cli/dist/api/tauricon.js:2:37964
```

**Comment by kubijo** [comment] 2021-07-20 13:38
After adding the one above-mentioned dependency to yarn's dependency injection, I've encountered several other missing ones.
I've been able to hotfix it by:
- changing the command to: `yarn tauri icon ./icon.png --compression="zopfli" --log`
  - which means that the site docs are not in sync with the actual command 
- adding the following to `.yarnrc.yml`, but that's a dirty solution… you should declare those yourselves:
    ```yml
    packageExtensions:
      "@tauri-apps/cli@*":
        dependencies:
          graceful-fs: "^4.2.6"
          strtok3: "^6.2.2"
          token-types: "^4.1.0"
          replace-ext: "^2.0.0"
          junk: "^3.1.0"
    ```

**Comment by amrbashir** [comment] 2021-07-20 15:52
`graceful-fs` is a nested dependency of some of `@tauri-apps/cli` dependencies, we don't have control over that. 

And yarn2 has issues with some of npm packages and don't think yarn3 is any different.

**Comment by kubijo** [comment] 2021-07-20 16:10
Come on, man, is that really it?
Can you, @arcanis, please give some pointer on what would be the way to approach this a find the issue?

**Comment by amrbashir** [comment] 2021-07-20 16:12
just to be clear, I am not sure if it is a problem with yarn2/yarn3 or not, I closed this issue because we have no control over the nested dependency.

**Comment by arcanis** [comment] 2021-07-20 16:20
> I closed this issue because we have no control over the nested dependency.

From a quick look (I don't use Tauri, so I can only rely on the error message), the problem is in tauri, not a transitive dependency. You don't declare `graceful-fs` as a dependency, even though your own source files `import` from it (same thing for a few other packages, as per https://github.com/tauri-apps/tauri/issues/2256#issuecomment-883400565). As a result, the behavior is unsafe, hence the error:

```
Error: @tauri-apps/cli tried to access graceful-fs, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by amrbashir** [comment] 2021-07-20 16:38
To be even more clear, we never really put any effort in officially supporting yarn2 (haven't even used it personally).

> even though your own source files import from it

I looked at all of our source files and not a single line contains an `import` or `require` from `graceful-fs` however I looked at our `yarn.lock` file generated by yarn1 and `graceful-fs` is used by number of our dependency, some note-wroth are `jest`, `fs-extra` and `imagemin` so it is a transitive dependency.

Also worth noting that the command mentioned above works in yarn1

**Comment by arcanis** [comment] 2021-07-20 16:51
> To be even more clear, we never really put any effort in officially supporting yarn2 (haven't even used it personally).

To be even clearer (😛), properly listing dependencies isn't about Yarn. All package managers, including npm, are affected when that happens. In their cases, the differences are often very subtle - one package being at the wrong place, one resolution being hoisted when it shouldn't ... it usually works, but causes very cryptic and difficult to debug issues pseudo-randomly. Very annoying for users, very frustrating for maintainers. Yarn simply does its best to completely prevent these issues by *telling you* when something is wrong. Something that npm doesn't know how to do.

So in short, don't see it as "Yarn 2 compatibility", but rather a regular bugfix for npm - highlighted by Yarn.

> I looked at all of our source files and not a single line contains an `import` or `require` from `graceful-fs` however I looked at our `yarn.lock` file generated by yarn1 and `graceful-fs` is used by number of our dependency, some note-wroth are `jest`, `fs-extra` and `imagemin` so it is a transitive dependency.

Looking at the package file (and not the source code, I should have checked before), you can see that `graceful-fs` is actually required by your code in this file:

https://cdn.jsdelivr.net/npm/@tauri-apps/cli@1.0.0-beta.6/dist/api/tauricon.js

![image](https://user-images.githubusercontent.com/1037931/126363652-69eed1f2-1953-45a5-92cb-d1f9c3159761.png)

I'm not sure why exactly (perhaps you bundle something and mark transitive dependencies as externals?), but the end result is the same: if you don't list them, package managers (all of them) **will** be subject to generating incorrect dependency trees, and nothing will guarantee that the version of `graceful-fs` used by your app is the one you'd want. Same thing for any other mismatching `require` call (and the more you have, the more likely this case is to happen).

> Also worth noting that the command mentioned above works in yarn1

Yarn 1 had the same issue as npm: it also has problems when packages don't list their dependencies, it's just that it has no way to detect when that happens.

**Comment by amrbashir** [comment] 2021-07-20 17:02
Thanks for the detailed explanation, I was dumb not to check the bundled package.

> perhaps you bundle something and mark transitive dependencies as externals?)

you're right, we are using webpack externals. I will re-open the issue. 

Thanks for help, @arcanis , we really appreciate it.

**Comment by amrbashir** [comment] 2021-07-23 13:49
Alright, I tried declaring `graceful-fs` as a direct dependency but that wasn't enough, a lot more undeclared dependencies emerged and declaring all of these dependencies doesn't seem the right way to do it and I am not an expert enough in this to find a fix for it.

So since we are focusing on stability of the core tauri code base, this issue will remain as is until one of two things happen, either someone from the community can help fix this or we re-write `tauri icon` command in our rust cli if possible.

**Comment by kubijo** [comment] 2021-07-23 13:57
I've given you a list of dependencies in the second comment... It's the `.yarnrc.yml` file

**Comment by amrbashir** [comment] 2021-07-23 14:01
Sorry I missed that list but what happens if in the future we add another dependency, we are gonna have to trial and error to see what dependencies need to be also declared and we have to maintain that list, if there is a better solution I'd be happy to do it.

**Comment by kubijo** [comment] 2021-07-23 15:03
I'd say go for yarn2 ... With all that @arcanis said it only makes sense
and I'm sure they have some examples of automatic checks...

**Comment by arcanis** [comment] 2021-07-23 15:14
Without going to a full change of package manager, perhaps an intermediary solution would be to setup a cron GitHub Action job that would periodically run a quick test using Yarn 2? Something simple, like running --version on your CLI or such.

It wouldn't notify you on PRs, but it's low effort and should notify you fairly fast if something happens (we actually do that on our side as well, just to be kept updated about potential compat issues in the ecosystem).

**Comment by amrbashir** [comment] 2021-07-23 15:32
> I'd say go for yarn2 ... With all that @arcanis said it only makes sense

It is not that we don't want to support yarn2, we just have much higher priority tasks right now so unless someone wants to fix this issue and make a PR, this is gonna have to wait.
And in the future we are most likely gonna re-write the `tauri icon` command in rust (don't worry, you can still use `tauri icon` with the npm packge, it will just forward it to our rust cli).

> Without going to a full change of package manager, perhaps an intermediary solution would be to setup a cron GitHub Action job that would periodically run a quick test using Yarn 2? Something simple, like running --version on your CLI or such.
> 
> It wouldn't notify you on PRs, but it's low effort and should notify you fairly fast if something happens (we actually do that on our side as well, just to be kept updated about potential compat issues in the ecosystem).

yeah that would work.

**Closed as completed** 2021-08-11 17:00 UTC
Labels: type: bug, help wanted
