### ISSUE TITLE
[bug] When cross compiling to windows the build script fails to rename the target binary.

### ISSUE THREAD

**Issue by JavaDerg** [tauri-apps/tauri#3992] opened 2022-04-28 14:31 UTC
### Describe the bug

Trying to cross compile to windows (x86_64-pc-windows-gnu) from Linux the compilation successes but it tries to rename the resulting binary but because it has a `.exe` extension and the build script doesn't know that it fails.

### Expected behavior

```
### Other build output...

Error running CLI: failed to rename `/pathtoproject/target/x86_64-pc-windows-gnu/release/app` to `/pathtoproject/target/x86_64-pc-windows-gnu/release/rift-desktop`: No such file or directory (os error 2)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Platform and versions

```shell
Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: 17.9.0
  › npm: 8.5.5
  › pnpm: 7.0.0-rc.9
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.59.0
  › cargo: 1.59.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.9
  › @tauri-apps/api [NPM]: 1.0.0-rc.4
  › tauri [RUST]: 1.0.0-rc.8,
  › tauri-build [RUST]: 1.0.0-rc.7,
  › tao [RUST]: 0.8.3,
  › wry [RUST]: 0.15.1,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Svelte

App directory structure
  ├─ src
  ├─ public
  ├─ .vscode
  ├─ src-tauri
  ├─ .idea
  ├─ dist
  └─ node_modules
```

**Comment by FabianLars** [comment] 2022-04-28 14:54
Duplicate of #3870. Thx for the report nonetheless :)

**Closed as completed by FabianLars** 2022-04-28 14:54 UTC
Labels: type: bug, status: invalid
