### ISSUE TITLE
[bug] The bug of resizing the window in the javascript API

### ISSUE THREAD

**Issue by 57321** [tauri-apps/tauri#4551] opened 2022-07-01 09:43 UTC
### Describe the bug

First, it was normal in v1.0.0.

In v1.0.1

When I resize the window height it always gets 20px more.

![image](https://user-images.githubusercontent.com/38900476/176869396-12d11cc3-f6c0-4d27-aad7-03e4e6a1f128.png)

 before

![image](https://user-images.githubusercontent.com/38900476/176869767-95f327a1-3bda-479b-b8a1-fc546c1c2c57.png)

after

![image](https://user-images.githubusercontent.com/38900476/176869798-c00565c0-60e0-4f11-938c-753ec3f32c22.png)

so. Is this a feature or a bug? 

### Platform and versions

```shell
Operating System - Windows, version 10.0.18362 X64
Webview2 - 103.0.1264.37
Visual Studio Build Tools - Not installed

Node.js environment
  Node.js - 14.18.0
  @tauri-apps/cli - 1.0.0-beta.10 (outdated, latest: 1.0.1)
  @tauri-apps/api - 1.0.1

Global packages
  npm - 6.14.15
  pnpm - 7.3.0
  yarn - 1.22.10

Rust environment
  rustc - 1.61.0
  cargo - 1.61.0

Rust environment
  rustup - 1.24.3
  rustc - 1.61.0
  cargo - 1.61.0
  toolchain - stable-x86_64-pc-windows-msvc (environment override by RUSTUP_TOOLCHAIN)

App directory structure
/.git
/.vscode
/dist
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.2
`tauri.conf.json` error on ``: Additional property '$schema' is not allowed
`tauri.conf.json` error on `tauri > bundle > macOS`: Additional property 'providerShortName' is not allowed
```

**Comment by FabianLars** [comment] 2022-07-01 09:49
Looks like https://github.com/tauri-apps/tao/issues/194 is back 👀 

p.s. you should update your tauri cli

**Comment by 57321** [comment] 2022-07-01 10:09
update cli.

```
Environment
  › OS: Windows 10.0.18362 X64
  › Webview2: 103.0.1264.37
  › MSVC: 
      - Visual Studio ���ɹ��� 2019
  › Node.js: 14.18.0
  › npm: 6.14.15
  › pnpm: 7.3.0
  › yarn: 1.22.10
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.0,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by amrbashir** [comment] 2022-07-01 11:07
I can't reproduce this at all. Please open the devtools console, and check `window.innerWidth` and `window.innerHeight`

**Comment by 57321** [comment] 2022-07-02 03:01
I changed to another computer, but it's win11 system.
Create new project.

![image](https://user-images.githubusercontent.com/38900476/176984190-39e4da7f-a685-4f29-b553-37a8107528f8.png)

What would you want other?

```
Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 100.0.1185.29
  › MSVC:
      - Visual Studio ���ɹ��� 2019
  › Node.js: 17.4.0
  › npm: 8.3.1
  › pnpm: 7.4.0
  › yarn: 1.22.4
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.2
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.2,
  › tauri-build [RUST]: 1.0.2,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: Vue.js

App directory structure
  ├─ .vscode
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri
```

**Comment by amrbashir** [comment] 2022-07-02 03:16
Are you using custom scaling?

**Comment by 57321** [comment] 2022-07-02 04:17
> Are you using custom scaling?

Do you mean windows custom scaling？ The setting is 100%

**Comment by amrbashir** [comment] 2022-07-02 13:17
I can definitely reproduce this with Tauri and tauri only. It works fine in tao, it works fine in wry but not in tauri. 

tao uses [`AdjustWindowRectEx`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-adjustwindowrectex) from win32 APIs [here](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/windows/util.rs#L105) to determine how big the window should be based on required client size, titlebars and borders.

I tried tracking the results of this function call and here is what I found:
1. Initially set the size in tauri.conf.json to `800,60` and `AdjustWindowRect` will return
	  ```sh
	  [D:\dev\tao\src\platform_impl\windows\util.rs:116] &rect = RECT {
	      left: -8, # left border
	      top: -31, # titlebar height + menu bar if it exists + top border which is 8
	      right: 808, # window inner width + right border which is 8
	      bottom: 68, # window inner height + bottom border which is 8
	  }
	  ```
2. Then we try to set the window size through the API to `800,60` (same size as before) and here is what I don't understand
	  ```sh
	  [D:\dev\tao\src\platform_impl\windows\util.rs:116] &rect = RECT {
	      left: -8, # left border -> same as above
	      top: -51, # titlebar height + top border -> NOT THE SAME !!!!
	      right: 808, # window inner width + right border -> same as above
	      bottom: 68, # window inner height + bottom border -> same as above
	  }
	  ```
you can see that the titlebar height has increased, hello Windows? why?

Anyhow, you'd expect if you try to set the size again, the titlebar size will increase even more but NO, the titlebar height stays as `-51` and for the entirety of the window life span, `setSize` will actually work as expected, So the bug is only in the first invocation but I have no idea what is going on.

**Comment by amrbashir** [comment] 2022-07-02 13:41
I think I found the issue, it was this commit https://github.com/tauri-apps/tauri/commit/5105b428c4726b2179cd4b3244350d1a1ee73734 which adds an empty menu bar on Windows, and `AdjustWindowRect` will account for its size.

It doesn't happen initially because the menu is added after the window has been created so the first call to `AdjustWindowRect` it won't add the menu bar size but subsequent calls which happens after the empty menubar has been added, will add the menu bar size. 

I will push the fix soon but for your current project, you need to add the menu on macOS only, use `Menu::os_default` for all paltforms, not just macOS or remove the menu bar altogether.

Something like this
```rs
let mut app = tauri::Builder::default();
#[cfg(target_os = "macOS")]
{
  app = app.menu(tauri::Menu::os_default(&context.package_info().name));
}
app
  .run(context)
  .expect("error while running tauri application");
```

**Comment by amrbashir** [comment] 2022-07-02 16:24
when https://github.com/tauri-apps/tauri/pull/4570 is merged, you can just remove the `.menu()` call from your `main.rs`

**Comment by 57321** [comment] 2022-07-03 07:02
thanks.
It is indeed caused by this default menu.
The previous scaffolding did not have this menu.

![image](https://user-images.githubusercontent.com/38900476/177028940-0db3c7e4-b56a-425e-b387-120c134aa57a.png)

**Closed as completed** 2022-07-03 07:03 UTC
Labels: type: bug, priority: 1 high, platform: Windows
