### ISSUE TITLE
[bug] 'visible' property of window config no longer respected in tauri 1.2

### ISSUE THREAD

**Issue by Raphiiko** [tauri-apps/tauri#5583] opened 2022-11-08 20:00 UTC
### Describe the bug

Context: In my Tauri application, I use two windows:

- The main window
- A splash screen window. 

The main window has the `visible` property in its config set to `false`. When my application is done loading, I hide the splash screen window and show the main window.

After upgrading to Tauri 1.2, this `visible` option no longer seems to have an effect. The main window spawns right away, before the application is finished loading, even though it is set to `false`.

<details>
  <summary>tauri.conf.json window configurations</summary>

```json
{
  ...
  "tauri": {
   ...
    "windows": [
      {
        "fullscreen": false,
        "height": 600,
        "resizable": true,
        "title": "[Redacted]",
        "width": 960,
        "minWidth": 960,
        "minHeight": 600,
        "visible": false,
        "center": true,
        "theme": "Dark",
        "transparent": true,
        "userAgent": "[Redacted]"
      },
      {
        "width": 500,
        "height": 275,
        "decorations": false,
        "url": "assets/splashscreen/splashscreen.html",
        "label": "splashscreen",
        "resizable": false,
        "center": true,
        "theme": "Dark",
        "transparent": true,
        "userAgent": "[Redacted]"
      }
    ]
  }
}
```
</details>

Main window spawned before its being shown:
![chrome_QlshJWC03S](https://user-images.githubusercontent.com/111654848/200661949-4736afb6-d823-4817-af44-532fe2f8219b.png)

### Reproduction

1. Create a new vanilla-js tauri app
2. Set `visible` to `false` for the window in `tauri.conf.json`.
3. Launch with `tauri dev`

The window will still be visible. 

### Expected behavior

I would expect a window to remain hidden when its `visible` property is set to false, until it is shown programatically. (Tauri 1.1 behaviour).

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 107.0.1418.35
  › MSVC: 
      - Visual Studio Build Tools 2019
      - Visual Studio Community 2022
  › Node.js: 16.14.0
  › npm: 8.3.1
  › pnpm: Not installed!
  › yarn: 1.22.17
  › rustup: 1.25.1
  › rustc: 1.64.0
  › cargo: 1.64.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc

**Comment by Bukmopbl4** [comment] 2022-11-08 20:58
I trying to reproduce the bug but main window disappeared in my PC (macOS ventura 13.0)

**Comment by FabianLars** [comment] 2022-11-08 20:58
@amrbashir As weird as it sounds, this pr https://github.com/tauri-apps/tao/pull/605 seems to be the issue. If i comment out this line https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/windows/window.rs#L1079 it works again

**Comment by amrbashir** [comment] 2022-11-08 21:43
A fix will be released soon. Make sure to run `cargo update` after `tao` 0.15.1 has been released.

**Closed as completed by amrbashir** 2022-11-08 21:43 UTC
Labels: type: bug, status: needs triage

**Comment by Bukmopbl4** [comment] 2022-11-08 22:38
> A fix will be released soon. Make sure to run `cargo update` after `tao` 0.15.1 has been released.

 tao 0.15.1 has been released but has no compile on win10. On MacOS yes it works.
 `Compiling tao v0.15.1
 errors
...0.15.1\src\platform_impl\windows\system_tray.rs:104:39
...\tao-0.15.1\src\platform_impl\windows\system_tray.rs:112:39`

**Comment by amrbashir** [comment] 2022-11-08 22:41
thanks @Bukmopbl4 I will publish another fix soon, it was weird that our CI didn't catch that.

**Comment by Raphiiko** [comment] 2022-11-09 09:10
Can confirm the issue's gone after updating tao 👍 

That was very quick, thanks a lot for the fix! ❤️

**Comment by carlocorradini** [comment] 2023-09-29 10:24
My window is visible even though I have the `visible` property set to `false`.
Here is my configuration:

![Screenshot 2023-09-29 122207](https://github.com/tauri-apps/tauri/assets/21266147/7fa5573a-6cf6-4e92-a4ee-8d4e0cdc76bf)

Any thoughts? Thanks 🥳🤗

PS: `Tauri v1.4` on Windows 10 Pro 10.0.19045 Build 19045

**Comment by brendanosborne** [comment] 2024-05-23 02:04
It [appears to still be an issue](https://github.com/TunnlTo/desktop-app/issues/159) for Windows 10 Pro 22H2.
