### ISSUE TITLE
[feat] Easy way to get window size

### ISSUE THREAD

**Issue by WesWeCan** [tauri-apps/tauri#11820] opened 2024-11-28 13:26 UTC
### Describe the problem

There is a bug or feature (don't know which) that makes it when you use the drag-drop event the size of window is wierdly calculated, the titlebar is included in the size which is different from the window size.

### Describe the solution you'd like

getCurrentScreen().getSize() // { width: 500, height: 600}

### Alternatives considered

I have tried lots of ways but the documentation doesn't point me somewhere

### Additional context

There is just a mismatch between how javascript interprets the height of the window (getClientRect() gives a different Y than the drag-drop event payload) which leads to wierd bugs.

Do you come to this problem the height difference is 28px for mac webview titlebar.

**Comment by FabianLars** [comment] 2024-11-28 13:35
duplicate of https://github.com/tauri-apps/tauri/issues/10744 and/or https://github.com/tauri-apps/tauri/issues/6333

**Closed as not planned by FabianLars** 2024-11-28 13:35 UTC
Labels: type: feature request, platform: macOS
