### ISSUE TITLE
<select> opens outside window on first try

### ISSUE THREAD

**Issue by mq1** [tauri-apps/tauri#1911] opened 2021-05-27 12:13 UTC
`<select>` elements open outside the application window. When opened a second time, they open in the correct position. The problem occurs again when moving the window to a new location.

OS: Windows, version 10.0.19043 X64
Node: 15.14.0
Rustc: 1.52.1

**Comment by lucasfernog** [comment] 2021-06-05 01:37
Can you provide a HTML example to reproduce it?

**Comment by mq1** [comment] 2021-06-05 10:54
> 
> 
> Can you provide a HTML example to reproduce it?

I created this repo https://github.com/mq1/tauri-issue

**Comment by lucasfernog** [comment] 2021-06-05 11:58
The issue doesn't happen on my end. What's the output of `tauri info`? I'd try updating the webview runtime to latest. Mine is `Webview2 - 91.0.864.41`.

**Comment by lucasfernog** [comment] 2021-06-05 11:59
I'm closing this issue since it seems like an old Windows webview issue. Please reopen if you find something else.

**Comment by mq1** [comment] 2021-06-05 12:05
I reopened the issue (https://github.com/tauri-apps/tauri/issues/1953)
My Webview2 version is the same as yours

**Comment by mq1** [comment] 2021-06-05 12:06
Maybe we'll find other people with the same issue

**Comment by lucasfernog** [comment] 2021-06-05 15:26
Also, do you see this issue when opening the HTML on the chromium Edge?

**Comment by mq1** [comment] 2021-06-05 17:06
> 
> 
> Also, do you see this issue when opening the HTML on the chromium Edge?

No, it works correctly

**Comment by BenoitRanque** [comment] 2021-06-23 22:15
I was able to reproduce this issue on windows.

**Comment by euphbriggs** [comment] 2021-06-27 11:58
Is this related to DPI scaling?

Are the folks who experience this using a DPI scale factor other than 100% in their Windows display settings?

**Comment by lucasfernog** [comment] 2021-06-27 12:32
I can reproduce this on my laptop with stock configuration.

**Comment by euphbriggs** [comment] 2021-06-27 12:40
Is there any chance your machine defaults to a scale factor other than 100%?

**Comment by lucasfernog** [comment] 2021-06-27 12:41
It's 100%. Seems like the webview isn't recognizing the window position change.

**Comment by euphbriggs** [comment] 2021-06-27 12:42
Oh ok, thanks for checking.

**Comment by lucasfernog** [comment] 2021-06-27 12:56
@amrbashir just posted this on Discord:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/780
https://github.com/MicrosoftEdge/WebView2Feedback/issues/780#issuecomment-808306938

**Comment by nicholasdgoodman** [comment] 2021-06-30 22:57
I have just put a code sample of a hacky but functioning workaround for this issue over on https://github.com/MicrosoftEdge/WebView2Feedback/issues/780 if you are looking for a quick fix.

*tl;dr*

If you "wiggle" the bounds of the WebView2 it will correctly recalibrate its dropdown positions.

**Comment by lucasfernog** [comment] 2021-06-30 23:06
Thanks for the help @nicholasdgoodman I'll patch this fix in our webview library.

**Comment by amrbashir** [comment] 2021-07-15 16:07
Re-opening this, since we reverted the workaround, because it introduced more bugs than it solved.

**Comment by FabianLars** [comment] 2022-03-24 20:46
This was fixed in webview2 directly a few months ago. There is still an issue with _opened_ dialogs not moving with the window.

**Closed as completed by FabianLars** 2022-03-24 20:46 UTC
Labels: type: bug, status: upstream, platform: Windows
