### ISSUE TITLE
`tauri-cli` fails to build and install from crates.io using `cargo install`

### ISSUE THREAD

**Issue by bnewbold** [tauri-apps/tauri#3064] opened 2021-12-14 02:48 UTC
### **Describe the bug**

The version of `tauri-cli` currently packaged on crates.io (https://crates.io/crates/tauri-cli, version `1.0.0-beta.7`) fails to build and install using `cargo`. Command and truncated error output:

```
$ cargo install tauri-cli --version 1.0.0-beta.7

[... many dependency packages skipped ...]

   Compiling tauri-cli v1.0.0-beta.7
   Compiling tauri-bundler v1.0.0-beta.4
error[E0432]: unresolved import `clap::crate_version`
 --> /home/bnewbold/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:6:12
  |
6 | use clap::{crate_version, load_yaml, App, AppSettings, ArgMatches};
  |            ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_version`
   --> /home/bnewbold/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:265:14
    |
265 |     .version(crate_version!())
    |              ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
   --> /home/bnewbold/.cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:264:23
    |
264 |   let app = App::from(yaml)
    |                       ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`

Some errors have detailed explanations: E0308, E0432.
For more information about an error, try `rustc --explain E0308`.
error: failed to compile `tauri-cli v1.0.0-beta.7`, intermediate artifacts can be found at `/tmp/cargo-installihgagI`

Caused by:
  could not compile `tauri-cli` due to 3 previous errors
```

Checking out this repo and running `cargo build` in the subdirectory `tooling/cli.rs/` works, so I suspect that the version in crates.io is just out of date. I would speculate that at some point the Rust dependencies were not locked or specified tightly enough.

### **To Reproduce**

1. Install current Rust toolchain, eg using `rustup`
2. Run the above install command

### **Expected behavior**

Rust package compiles and is installed for current user, and `cargo tauri` command works.

### **Platform and Versions (required):**

After building the rust CLI from a git checkout (`d56a7fc7f7d0575061da9ecd70ba23a5ee0bf8e2`), running `./target/debug/cargo-tauri info` gives:

```
Operating System - Debian, version 10 X64
WARNING: no lock files found, defaulting to npm

Node.js environment
  Node.js - 17.2.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - Not installed

Global packages
  npm - 8.1.4
  pnpm - Not installed
  yarn - 1.12.3

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

Rust environment
  rustup - 1.24.3
  rustc - 1.57.0
  cargo - 1.57.0
  toolchain - stable-x86_64-unknown-linux-gnu (d

App directory structure
/webview-src
/.changes
/examples
/.github
/webview-dist
/src

App
  tauri.rs - no manifest (no lockfile)
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: 
  distDir - ../public
  devPath - http://localhost:5000/
  bundler - Rollup
```

### **Additional context**

I searched for open issues here and in discussions before opening this bug. I encountered this following the "Getting Started" guide on https://tauri.studio. The exact command recommended there is:

```
cargo install tauri-cli --version ^1.0.0-beta
```

I narrowed to the exact version to confirm the problem existed with the latest published version.

By the way, thank you for developing/maintaining Tauri! The small install sizes are really impressive, and it is pretty cool that it targets Linux (both .deb and Appimage) out of the box.

**Comment by FabianLars** [comment] 2021-12-14 05:05
duplicate of #3050.
You can install from git for now: `cargo install tauri-cli --git https://github.com/tauri-apps/tauri`

**Closed as completed** 2021-12-14 05:06 UTC
Labels: type: bug, status: invalid

**Comment by bnewbold** [comment] 2021-12-14 06:01
Ah, thanks, and thanks for the quick reply!

I think I didn't see because I didn't search closed issues.
