### ISSUE TITLE
Command handler can't return data.

### ISSUE THREAD

**Issue by aalowlevel** [tauri-apps/tauri#3049] opened 2021-12-09 06:46 UTC
### **Describe the bug**
when i try to put a command in ./main.rs to return some data like:
`
#[tauri::command]
fn my_custom_command() -> String {
  "Hello from Rust!".into()
}
`
and i try to invoke it from js like:
`
invoke('my_custom_command').then((message) => console.log(message));
`
i get this rejection on the browser all the time:

> Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'notify')

### **To Reproduce**
1. Create a custom command in rust.
2. Invoke it at js.
3. See error

### **Expected behavior**
resolve returning data

### **Platform and Versions (required):**

```
Operating System - Windows, version 10.0.19044 X64
Webview2 - 96.0.1054.43

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.3
  yarn - 1.22.15

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure        
/.git
/build
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../build
  devPath - http://localhost:3000
  framework - React
```

**Comment by FabianLars** [comment] 2021-12-09 07:50
Edit: Nevermind lol. I didn't see that you said "in the browser", yeah the script won't get injected in that either, so that won't work.
If you _absolutely_ need that feature (for example because you need the react dev tools but don't want to use the standalone version...), then take a look at https://github.com/tauri-apps/tauri/issues/2849#issuecomment-970435644

And with that I'll close this issue. Please reopen it if I misunderstood what you want.

~~This error should mean that the tauri script wasn't injected into the window. This script adds stuff to the `window` object, needed by every tauri API function.
In general this script doesn't get injected into windows with **external** urls (at the time of the window creation).~~

~~So, as a first step please show us how you create your window or how it's configured.
Or if you already know it's an external urls, then a "workaround" would be to create an empty html file as the app entrypoint with a `window.location.replace` call to get to the actual url.
Also, keep in that, depending on what else you do, you most likely will end up breaching some kind of TOS of those sites~~

~~Btw, if that is the root cause, it's not a "bug". and it's not about returning the data but about invoking the command i think.~~

**Closed as completed** 2021-12-09 07:57 UTC
Labels: status: invalid

**Comment by aalowlevel** [comment] 2021-12-09 14:27
LOL sir. thank you for reply. I am still new to this framework and trying to get used to. you guys have done a nice job by doing this. it was just depressing to me after everything was going well, when i do "npm run tauri dev" and getting this rejection on the browser. now, i tried to mirror the promise on some notification react component on the app, is working. I appreciate it.
