### ISSUE TITLE
[feat] MacOS overlay style.

### ISSUE THREAD

**Issue by nyssance** [tauri-apps/tauri#11230] opened 2024-10-05 11:36 UTC
### Describe the problem

The current overlay is highly impractical, as its style cannot remain consistent with mainstream mac apps. Need a style with padding.

### Describe the solution you'd like

<img width="145" alt="59PMh" src="https://github.com/user-attachments/assets/e76bab0a-1049-45a6-ab45-6b073993304b">
<img width="145" alt="FvqaB" src="https://github.com/user-attachments/assets/a5b51a61-2995-4966-a040-774369b5b982">
<img width="305" alt="lAuTE" src="https://github.com/user-attachments/assets/093b7752-f134-4a45-8356-9b0754987426">

**Comment by FabianLars** [comment] 2024-10-13 16:01
duplicate of https://github.com/tauri-apps/tauri/issues/4789

**Closed as not planned by FabianLars** 2024-10-13 16:01 UTC
Labels: type: feature request, platform: macOS
