### ISSUE TITLE
[docs] Minimum version of Node JS required

### ISSUE THREAD

**Issue by Nejat** [tauri-apps/tauri#2714] opened 2021-10-05 14:37 UTC
Hi,

I just start working with Tauri and while following the Getting Started/Development instructions on the Tauri website I ran into an unexpected issue that seems to concern the active version of Node JS on the system.

I followed these steps on an up-to-date Windows 10 dev box

- `yarn create tauri-app`
  - app name `dashboard`
  - Svelte
  - `@tauri-apps/api` package added
  - Typescript
- `cd dashboard`
- `yarn install` _which was not necessary_
- `yarn tauri dev` _or_ `cargo tauri dev` produced the same result

The application window opened but I got the following message

```
Hmmm… can't reach this page

localhost refused to connect.
```

I tried several things before figuring out that the version of Node JS _14.17.4_ seems to be incompatible. 

Upgrading to _16.10.0_ got everything working.

```
cargo tauri info

Operating System - Windows, version 10.0.19043 X64
Webview2 - 94.0.992.31

Node.js environment
  Node.js - 16.10.0
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 7.24.0
  yarn - 1.22.15

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/.git
/.idea
/.vscode
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../public
  devPath - http://localhost:5000
  framework - Svelte
  bundler - Rollup
```

I haven't tried other versions but I thought it was interesting enough to point out.

**Comment by facklambda** [comment] 2021-10-21 00:33
Hello,

I'll need some guidance from senior contributors on this one.

I could write a few lines in the "/docs/getting-started/setup-windows.md" file emphasizing to users to ensure they are using the latest version of Node.js. Currently all "getting-started" docs guide the users to run ```nvm install latest```, which should already install the latest version of node.js.

Does it help to make this more explicit? Is there a known minimum version of Node.js required?

**Comment by amrbashir** [comment] 2021-10-21 08:00
This doesn't seem to be a problem with Tauri since you are saying the window showed up so the problem is with the devServer of your front-end. 

Anyhow, we should note that people should be using the latest minor version of Node.js At minimum Node.js 12.20, 14.14, or 16.0.

**Comment by antimatter96** [comment] 2021-10-21 23:20
I can verify that 14.17.6 works on Mac OS
```bash
Operating System - Mac OS, version 11.4.0 X64

Node.js environment
  Node.js - 14.17.6
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 6.14.15
  yarn - 1.22.10

Rust environment
  rustc - 1.55.0
  cargo - 1.55.0

App directory structure
/dist
/node_modules
/src-tauri
/.parcel-cache
/.git
/src

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - ../dist

```

**Comment by amrbashir** [comment] 2021-11-14 13:04
closing this as we already recommend using `nvm` to install latest Node.js version.

**Closed as completed by amrbashir** 2021-11-14 13:04 UTC
Labels: type: documentation, priority: 3 low
