### ISSUE TITLE
[feat] Application Multi-Opening

### ISSUE THREAD

**Issue by why0123** [tauri-apps/tauri#11681] opened 2024-11-14 01:56 UTC
### Describe the problem

I've reviewed a lot of documentation on the subject, but I don't seem to find anything on app multicasting.

I noticed that in Windows, the user data folder ([UDF](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=dotnet)) is stored in `<username>/AppData/Local/<appname>/EBWebView`, and I'm wondering if we can select a different user data folder at startup to enable app multi-opening.

That way, when users need to log in multiple accounts, they can avoid the hassle of having to log in repeatedly

### Describe the solution you'd like

Here is what I think is a possible kind of enablement step:
1. Be able to create the specified new udf in the default started tauri app using the command e.g. `app.createUDF('XXX)`
2. Create a shortcut on the desktop with the specified arg
3. Switch the UDF used by tauri to the corresponding folder when launched from the shortcut.

In addition, there may be an api to remove non-default udf, and all udf can be removed when uninstalling.

**Comment by amrbashir** [comment] 2024-11-14 15:44
Closing as duplicate of #9285, thanks.

**Closed as not planned by amrbashir** 2024-11-14 15:44 UTC
Labels: type: feature request
