### ISSUE TITLE
[feat] Enhanced WebView Isolation for Multi-User Login Support

### ISSUE THREAD

**Issue by longDan1991** [tauri-apps/tauri#11491] opened 2024-10-25 04:13 UTC
### Describe the problem

We are developing a Tauri application that requires support for multiple users to log in to the same website simultaneously, each with their own isolated session. While the current `data_directory` method provides some level of isolation, we are looking for a more granular control over WebView data storage, especially on macOS.

### Describe the solution you'd like

Specifically, we are seeking:

1. A way to create completely isolated WebView instances for each user session, ensuring that cookies, local storage, and other web data do not leak between sessions.

2. On macOS, the ability to leverage WebKit's WKWebsiteDataStore or similar APIs to create truly separate data stores for each WebView instance.

3. A cross-platform solution that maintains Tauri's abstraction layer while providing this enhanced isolation.

This feature would be particularly useful for applications that need to support multiple user accounts, testing environments, or any scenario where complete isolation of web sessions is crucial.

We understand that this might require changes at the wry level or even direct interaction with platform-specific WebView APIs. We're open to discussing the best approach to implement this feature in a way that aligns with Tauri's architecture and future plans.

**Comment by hut36** [comment] 2024-10-25 13:10
There is a proposal to add support for browser profiles, see #9285

**Comment by FabianLars** [comment] 2024-10-25 15:54
Closing as duplicate of #9285 then, thanks.

**Closed as not planned by FabianLars** 2024-10-25 15:54 UTC
Labels: type: feature request
