### ISSUE TITLE
[bug] thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by lingdu1234** [tauri-apps/tauri#4984] opened 2022-08-21 00:03 UTC
### Describe the bug

when the number of the   `invoke_handler` is up to 30+,
`taurri dev` thread 'main' has overflowed its stack  on windows 11, but  ` taurri dev  --release` is ok. 
 `taurri dev`  is  ok  on wsl2(ubuntu 20.04) 

### Platform and versions

Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 104.0.1293.54
  › MSVC: 
      - Visual Studio ���ɹ��� 2022
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: 7.1.7
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.63.0
  › cargo: 1.63.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.0.5
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.5,
  › tauri-build [RUST]: 1.0.4,
  › tao [RUST]: 0.12.2,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js

**Comment by amrbashir** [comment] 2022-08-31 21:26
I couldn't reproduce this, can you share a minimal repro?

I tested on Windows 11 with the following:
```rs
#![cfg_attr(
    all(not(debug_assertions), target_os = "windows"),
    windows_subsystem = "windows"
)]

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

#[tauri::command]
fn g0() {}
#[tauri::command]
fn g1() {}
#[tauri::command]
fn g2() {}
#[tauri::command]
fn g3() {}
#[tauri::command]
fn g4() {}
#[tauri::command]
fn g5() {}
#[tauri::command]
fn g6() {}
#[tauri::command]
fn g7() {}
#[tauri::command]
fn g8() {}
#[tauri::command]
fn g9() {}
#[tauri::command]
fn g10() {}
#[tauri::command]
fn g11() {}
#[tauri::command]
fn g12() {}
#[tauri::command]
fn g13() {}
#[tauri::command]
fn g14() {}
#[tauri::command]
fn g15() {}
#[tauri::command]
fn g16() {}
#[tauri::command]
fn g17() {}
#[tauri::command]
fn g18() {}
#[tauri::command]
fn g19() {}
#[tauri::command]
fn g20() {}
#[tauri::command]
fn g21() {}
#[tauri::command]
fn g22() {}
#[tauri::command]
fn g23() {}
#[tauri::command]
fn g24() {}
#[tauri::command]
fn g25() {}
#[tauri::command]
fn g26() {}
#[tauri::command]
fn g27() {}
#[tauri::command]
fn g28() {}
#[tauri::command]
fn g29() {}
#[tauri::command]
fn g30() {}
#[tauri::command]
fn g31() {}
#[tauri::command]
fn g32() {}
#[tauri::command]
fn g33() {}
#[tauri::command]
fn g34() {}
#[tauri::command]
fn g35() {}
#[tauri::command]
fn g36() {}
#[tauri::command]
fn g37() {}
#[tauri::command]
fn g38() {}
#[tauri::command]
fn g39() {}
#[tauri::command]
fn g40() {}
#[tauri::command]
fn g41() {}
#[tauri::command]
fn g42() {}
#[tauri::command]
fn g43() {}
#[tauri::command]
fn g44() {}
#[tauri::command]
fn g45() {}
#[tauri::command]
fn g46() {}
#[tauri::command]
fn g47() {}
#[tauri::command]
fn g48() {}
#[tauri::command]
fn g49() {}
#[tauri::command]
fn g50() {}
#[tauri::command]
fn g51() {}
#[tauri::command]
fn g52() {}
#[tauri::command]
fn g53() {}
#[tauri::command]
fn g54() {}
#[tauri::command]
fn g55() {}
#[tauri::command]
fn g56() {}
#[tauri::command]
fn g57() {}
#[tauri::command]
fn g58() {}
#[tauri::command]
fn g59() {}
#[tauri::command]
fn g60() {}
#[tauri::command]
fn g61() {}
#[tauri::command]
fn g62() {}
#[tauri::command]
fn g63() {}
#[tauri::command]
fn g64() {}
#[tauri::command]
fn g65() {}
#[tauri::command]
fn g66() {}
#[tauri::command]
fn g67() {}
#[tauri::command]
fn g68() {}
#[tauri::command]
fn g69() {}
#[tauri::command]
fn g70() {}
#[tauri::command]
fn g71() {}
#[tauri::command]
fn g72() {}
#[tauri::command]
fn g73() {}
#[tauri::command]
fn g74() {}
#[tauri::command]
fn g75() {}
#[tauri::command]
fn g76() {}
#[tauri::command]
fn g77() {}
#[tauri::command]
fn g78() {}
#[tauri::command]
fn g79() {}
#[tauri::command]
fn g80() {}
#[tauri::command]
fn g81() {}
#[tauri::command]
fn g82() {}
#[tauri::command]
fn g83() {}
#[tauri::command]
fn g84() {}
#[tauri::command]
fn g85() {}
#[tauri::command]
fn g86() {}
#[tauri::command]
fn g87() {}
#[tauri::command]
fn g88() {}
#[tauri::command]
fn g89() {}
#[tauri::command]
fn g90() {}
#[tauri::command]
fn g91() {}
#[tauri::command]
fn g92() {}
#[tauri::command]
fn g93() {}
#[tauri::command]
fn g94() {}
#[tauri::command]
fn g95() {}
#[tauri::command]
fn g96() {}
#[tauri::command]
fn g97() {}
#[tauri::command]
fn g98() {}
#[tauri::command]
fn g99() {}

fn main() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![
            greet, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14, g15, g16, g17,
            g18, g19, g20, g21, g22, g23, g24, g25, g26, g27, g28, g29, g30, g31, g32, g33, g34,
            g35, g36, g37, g38, g39, g40, g41, g42, g43, g44, g45, g46, g47, g48, g49, g50, g51,
            g52, g53, g54, g55, g56, g57, g58, g59, g60, g61, g62, g63, g64, g65, g66, g67, g68,
            g69, g70, g71, g72, g73, g74, g75, g76, g77, g78, g79, g80, g81, g82, g83, g84, g85,
            g86, g87, g88, g89, g90, g91, g92, g93, g94, g95, g96, g97, g98, g99,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

```

**Comment by lingdu1234** [comment] 2022-09-01 02:09
@amrbashir   https://github.com/lingdu1234/wkTools/tree/wktool
I have  Commented  every diffrent  `invoke_handler`  when  the  `invoke_handler`  is less ,its run ok

**Comment by amrbashir** [comment] 2022-09-01 17:15
I can't build your app on my Windows machine. can you just make a minimal repro instead of a full repo?

**Comment by lucasfernog** [comment] 2022-09-01 17:25
I've seen this issue too, though I didn't get a chance to see what's the reason.

**Comment by lucasfernog** [comment] 2022-09-01 17:25
I think the commands must be async @amrbashir

**Comment by amrbashir** [comment] 2022-09-01 17:39
Tried non-async, async, half and half, still can't reproduce it.

**Comment by lingdu1234** [comment] 2022-09-02 06:11
when i use 
```rust
use tokio::sync::OnceCell;
use sea_orm::{Database, DatabaseConnection};
pub static DB2: OnceCell<DatabaseConnection> = OnceCell::const_new();
pub async fn get_db() -> &'static DatabaseConnection {
    let db = DB2.get_or_init(|| async {
        Database::connect("sqlite::memory:").await.unwrap()
     }).await;
    db
}
```
thread 'main' has overflowed its stack

--------------------
```rust
use sea_orm::{Database, DatabaseConnection};
pub static DB2: OnceCell<DatabaseConnection> = OnceCell::new();
use once_cell::sync::OnceCell;
// is ok but may be return None

pub async fn set_db() {
    let db = Database::connect("sqlite::memory:").await.unwrap();
    DB2.set(db).unwrap();
}


pub async fn get_db() -> &'static DatabaseConnection {
   let v =  DB2.get().unwrap();
   v
}
```
run ok

---------------------------
```rust
use tokio::sync::OnceCell;
pub async fn get_db() -> &'static u32 {
    let db = DB.get_or_init(|| async { 23 + 233 }).await;
    db
}
```
run ok

-------------------

may be caused by sea-orm  OR  tokio::sync::OnceCell not by tauri;

-------------------
https://github.com/lingdu1234/wkTools/tree/tttt

**Comment by amrbashir** [comment] 2022-09-30 16:43
closing as it apparently not an issue with tauri. let me know if you can confirm it happens with tauri.

**Closed as not planned by amrbashir** 2022-09-30 16:43 UTC
Labels: type: bug, status: needs triage

**Comment by HuakunShen** [comment] 2024-05-25 02:09
I get the same error on Windows (not on ubuntu or mac) with Tauri V2 beta. I couldn't locate the problem. 
I tried to remove the code chunk by chunk to see what caused the overflow. 

At a certain point, adding a plugin, or custom command, or enabling a capability permission could result in overflow.
I think this is a pure memory problem. When too many plugins or commands added it will crash.

**Comment by thewh1teagle** [comment] 2024-11-20 13:32
```console
You can try increase the stack size
$env:RUSTFLAGS = "-C link-arg=/STACK:8000000" ; npx tauri dev
```
