### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by my-small-white** [tauri-apps/tauri#5833] opened 2022-12-14 08:54 UTC
### Describe the bug

错误代码: STATUS_INVALID_IMAGE_HASH
![image](https://user-images.githubusercontent.com/27253904/207547179-41c00873-16fa-4b93-874a-5b1e28743cf0.png)

### Reproduction

![image](https://user-images.githubusercontent.com/27253904/207547530-852cf6f9-fd8d-4b09-8a64-3f5821c6797b.png)

### Expected behavior

It's strange that such a problem occurs，
I think it can be displayed normally

### Platform and versions

![image](https://user-images.githubusercontent.com/27253904/207547416-c4cc9159-bde6-461e-8f6c-2ed3e670ec00.png)

### Additional context

I looked for other options

1: 
![image](https://user-images.githubusercontent.com/27253904/207548401-6dbcf5d6-6100-4322-a735-14b30a17fdd6.png)
2:
![image](https://user-images.githubusercontent.com/27253904/207548497-def1cf5c-f28b-402e-9e83-bc8448440acc.png)
3:
add to Edge folder
4：add to DWORD(32)  RendererCodeIntegrityEnabled  
![image](https://user-images.githubusercontent.com/27253904/207548940-fa7944fb-58e7-41d1-96d9-6c61179e25e1.png)
5:add to  WebView2 folder  and    add to DWORD(32)  
![image](https://user-images.githubusercontent.com/27253904/207549324-a7fe305f-57bc-467c-9920-e4ae34ac396a.png)
6:The program will run normally

![image](https://user-images.githubusercontent.com/27253904/207549609-18d1c4f0-c1ee-46fd-abeb-272fe708dda5.png)

so  
This temporary solution can solve the problem temporarily
but 
I send it to my work partner  They still can't use it
Please give suggestions and solutions 
thank you

**Comment by FabianLars** [comment] 2022-12-14 09:48
Thanks for the report :)

Duplicate of #4659 - to our knowledge there is nothing we can do on our side.

**Closed as not planned by FabianLars** 2022-12-14 09:48 UTC
Labels: type: bug, status: needs triage

**Comment by my-small-white** [comment] 2022-12-15 08:14
> 
Thank you for your answer

I found that running in compatibility mode can work normally
![image](https://user-images.githubusercontent.com/27253904/207807317-627e5429-8020-40ac-94b2-c731471d3b76.png)
It can also be accessed normally when it is sent to other work partners
