### ISSUE TITLE
[bug] yarn create tauri-app get error 

### ISSUE THREAD

**Issue by javaKhan** [tauri-apps/tauri#3394] opened 2022-02-11 02:48 UTC
### Describe the bug

(base)  ~/codeArea/rustCode  yarn create tauri-app

yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-tauri-app@1.0.0-rc.0" with binaries:
      - create-tauri-app

We hope to help you create something special with Tauri!
You will have a choice of one of the UI frameworks supported by the greater web tech community.
This tool should get you quickly started. See our docs at https://tauri.studio/

If you haven't already, please take a moment to setup your system.
You may find the requirements here: https://tauri.studio/en/docs/get-started/setup-macos/

Press any key to continue...
? What is your app name? tauri-app
? What should the window title be? Tauri App
? What UI recipe would you like to add? create-vite (vanilla, vue, react, svelte, preact, lit) (https://vitejs.dev/guide/#scaffolding-your-first-vite-project)
? Add "@tauri-apps/api" npm package? Yes
? Which vite template would you like to use? vue
>> Running initial command(s)
yarn install v1.22.17
info No lockfile found.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add create vite tauri-app" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error with command: yarn
Error: Error: Command failed with exit code 1: yarn  create vite tauri-app --template vue
    at /Users/mmtap/.config/yarn/global/node_modules/create-tauri-app/dist/index.js:62:15
    at Generator.throw (<anonymous>)
    at rejected (/Users/mmtap/.config/yarn/global/node_modules/create-tauri-app/dist/index.js:39:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
✨  Done in 15.41s.

### OS
Operating System - Mac OS, version 11.5.1 X64

### Platform and versions

```shell
Operating System - Mac OS, version 11.5.1 X64
```

**Comment by amrbashir** [comment] 2022-02-11 02:50
duplicate of #3393

**Closed as completed** 2022-02-11 02:51 UTC
Labels: type: bug, status: invalid
