### ISSUE TITLE
[bug] failed to bundle project: error running light.exe

### ISSUE THREAD

**Issue by trouvaille2023** [tauri-apps/tauri#8413] opened 2023-12-15 06:20 UTC
### Describe the bug

windows11上打包msi报错
<img width="1118" alt="image" src="https://github.com/tauri-apps/tauri/assets/44250675/03a0943c-e0a3-4f88-9e9b-7776feda270d">

系统环境
<img width="517" alt="image" src="https://github.com/tauri-apps/tauri/assets/44250675/5fdd3009-5870-4d8e-909a-e8fa88b04466">

tauri.config.json如下

```json
{
  "build": {
    "beforeDevCommand": "pnpm dev",
    "beforeBuildCommand": "pnpm build",
    "devPath": "http://localhost:1420",
    "distDir": "../dist"
  },
  "package": {
    "productName": "xxxxxx",
    "version": "0.0.1"
  },
  "tauri": {
    "allowlist": {
      "all": false,
      "shell": {
        "all": false,
        "open": true
      }
    },
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.xxx.xxx",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
    },
    "security": {
      "csp": null
    },
    "windows": [
      {
        "fullscreen": false,
        "resizable": false,
        "title": "XXX",
        "width": 800,
        "height": 400
      }
    ]
  }
}

```

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 120.0.2210.61
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.74.1 (a28077b28 2023-12-04)
    ✔ cargo: 1.74.1 (ecb9851af 2023-10-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.20.2
    - pnpm: 8.12.0
    - npm: 8.19.4

[-] Packages
    - tauri [RUST]: 1.5.3
    - tauri-build [RUST]: 1.5.0
    - wry [RUST]: 0.24.6
    - tao [RUST]: 0.16.5
    - tauri-cli [RUST]: 1.5.7
    - @tauri-apps/api [NPM]: 1.5.2
    - @tauri-apps/cli [NPM]: 1.5.7 (outdated, latest: 1.5.8)

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by amrbashir** [comment] 2023-12-15 09:07
duplicate of https://github.com/tauri-apps/tauri/issues/8363

**Closed as not planned by amrbashir** 2023-12-15 09:07 UTC
Labels: type: bug, status: needs triage
