### ISSUE TITLE
[bug] Development Server Do Not Killed After Window Exited

### ISSUE THREAD

**Issue by j4w0** [tauri-apps/tauri#4262] opened 2022-06-03 03:02 UTC
### Describe the bug

When I exited the window, the app window was exited and terminated. But the development server didn't stop and continuously running on background until I manually kill the process.

Confirm that it exists on official cli `create-react-app` template.

### Reproduction

1. Create a testing repo with `create-tauri-app` [select `create-react-app` template]
2. Run `yarn tauri dev`
3. Close the window
4. Repeat step 2 or check ports with `netstat -nlpn`

### Platform and versions

```shell
$ tauri info

Environment
  › OS: Linux Soaring X64
  › Node.js: 16.15.0
  › npm: 8.5.5
  › pnpm: Not installed!
  › yarn: 1.22.18
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0-rc.13
  › @tauri-apps/api [NPM]: 1.0.0-rc.6
  › tauri [RUST]: 1.0.0-rc.14,
  › tauri-build [RUST]: 1.0.0-rc.12,
  › tao [RUST]: 0.9.1,
  › wry [RUST]: 0.17.0,
```

**Comment by FabianLars** [comment] 2022-06-03 07:54
I think we will never get rid of all variations of this issue 😭 

Thanks for the report.

**Comment by PeytonHanel** [comment] 2022-06-17 18:15
I'm having this same problem too, using Yarn with Vite+Svelte on Ubuntu.

**Comment by rgwood** [comment] 2022-06-18 02:36
Same on Fedora with NPM, Vite, React+TypeScript (just the template created using `npx create-tauri-app`). I'm not able to reproduce the issue on Windows.

One unfortunate twist is that the development server stays partially attached to my terminal; I can go back to my terminal prompt and run commands, but then if I save a `.tsx` file my whole terminal is overwritten with `7:33:51 p.m. [vite] hmr update /src/App.tsx` or similar.

```
Environment
  › OS: Fedora 36.0.0 X64
  › Node.js: 16.15.1
  › npm: 8.8.0
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.61.0
  › cargo: 1.61.0
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.0
  › @tauri-apps/api [NPM]: 1.0.1
  › tauri [RUST]: 1.0.0,
  › tauri-build [RUST]: 1.0.0,
  › tao [RUST]: 0.11.2,
  › wry [RUST]: 0.18.3,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ src
  ├─ node_modules
  └─ src-tauri
  ```

**Comment by KaKi87** [comment] 2022-06-18 10:19
Hello,

I'm experiencing the same issue when running a bundler from a Node script : it never receives `SIGTERM` when quitting the app by closing its main window, although it exits successfully when pressing `Ctrl+C` in terminal.

- `beforeDevCommand` : `node ./start.js`
- `./start.js` : from [KaKi87/template-tauri1-vue3-parcel2](https://git.kaki87.net/KaKi87/template-tauri1-vue3-parcel2/src/branch/master/start.js)

I'll eventually create another reproduction repo with a Node script that runs a simple HTTP server with no bundler.

Thanks

**Closed as completed** 2022-06-21 16:16 UTC
Labels: type: bug

**Comment by Seeker14491** [comment] 2022-07-11 07:52
I still have this issue on the current version of the Tauri CLI (v1.0.3). As others have also noted, the issue only happens when you close the app window; using Ctrl-C in the terminal does not cause the issue.

<details><summary>tauri info</summary>
<p>

```
$ tauri info

Environment
  › OS: Linux 16 X64
  › Node.js: 16.15.1
  › npm: 8.13.2
  › pnpm: Not installed!
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.64.0-nightly
  › cargo: 1.64.0-nightly
  › Rust toolchain: nightly-x86_64-unknown-linux-gnu 

Packages
  › @tauri-apps/cli [NPM]: 1.0.3
  › @tauri-apps/api [NPM]: 1.0.2
  › tauri [RUST]: 1.0.3,
  › tauri-build [RUST]: 1.0.3,
  › tao [RUST]: 0.12.1,
  › wry [RUST]: 0.19.0,

App
  › build-type: bundle
  › CSP: default-src 'self' https://asset.localhost; img-src 'self'; img-src https://* asset: https://asset.localhost
  › distDir: ../build
  › devPath: http://localhost:3000/
  › framework: React

App directory structure
  ├─ src-tauri
  ├─ src
  ├─ .idea
  ├─ docs
  ├─ public
  ├─ node_modules
  ├─ .vscode
  └─ .git
```

</p>
</details>
