### ISSUE TITLE
[bug] Unable to install plugins via npm

### ISSUE THREAD

**Issue by erikpa1** [tauri-apps/tauri#11001] opened 2024-09-14 12:31 UTC
### Describe the bug

Hi, I can't install plugins by instructions of documentation from:

https://v2.tauri.app/plugin/store/

or 

https://v2.tauri.app/plugin/dialog/

when I do  ` pnpm tauri add dialog` I got error 

```
> infinitytwin@0.1.0 tauri C:\Work\freetime\InfinityTwinMobile
> tauri "add" "dialog"

    Info Installing Cargo dependency "tauri-plugin-dialog"...
    Updating crates.io index
      Adding tauri-plugin-dialog v2.0.0-rc to dependencies.
    Info Installing NPM dependency "@tauri-apps/plugin-dialog@^2.0.0-rc"...
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @tauri-apps/plugin-dialog@2.0.0-rc

This error happened while installing a direct dependency of C:\Work\freetime\InfinityTwinMobile

The latest release of @tauri-apps/plugin-dialog is "2.0.0-rc.1".
```

But after this command Cargo dependency is added and O cam add plugin by:

`npm i @tauri-apps/plugin-dialog`

### Reproduction

Steps are provided above...

### Full `tauri info` output

```text
In tauri info there is some bulshit, I'm on Windows 11, not 10 and "cargo tauri info" is not working "no such command: `info`".

[✔] Environment
    - OS: Windows 10.0.22631 x86_64 (X64)
    ✔ WebView2: 128.0.2739.79
    ✔ MSVC: Visual Studio Enterprise 2019
    ✔ rustc: 1.76.0 (07dca489a 2024-02-04)
    ✔ cargo: 1.76.0 (c84b36747 2024-01-18)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.14.2
    - pnpm: 8.15.6
    - yarn: 1.22.19
    - npm: 8.5.0

[-] Packages
    - tauri 🦀: 2.0.0-rc.11
    - tauri-build 🦀: 2.0.0-rc.10
    - wry 🦀: 0.43.1
    - tao 🦀: 0.30.0
    - @tauri-apps/api : 2.0.0-rc.4
    - @tauri-apps/cli : 2.0.0-rc.13

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-shell : 2.0.0-rc.1
    - tauri-plugin-store 🦀: 2.0.0-rc.3
    - @tauri-apps/plugin-store : 2.0.0-rc.1
    - tauri-plugin-fs 🦀: 2.0.0-rc.4
    - @tauri-apps/plugin-fs : not installed!
    - tauri-plugin-dialog 🦀: 2.0.0-rc.6
    - @tauri-apps/plugin-dialog : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../build
    - devUrl: http://localhost:1420/
    - framework: React
    - bundler: Vite
```

**Comment by FabianLars** [comment] 2024-09-14 17:08
duplicate of #10906 - thanks for the report

**Closed as not planned by FabianLars** 2024-09-14 17:08 UTC
Labels: type: bug, status: needs triage

**Comment by MrLightful** [comment] 2024-09-16 18:04
Use `pnpm tauri add dialog@2.0.0-rc.1` for now.
