### ISSUE TITLE
[bug] NextJS app directory using router.push from next/navigation doesn't render page correctly.

### ISSUE THREAD

**Issue by Royceb** [tauri-apps/tauri#6762] opened 2023-04-20 17:31 UTC
### Describe the bug

I was uncertain whether to open this in Tauri or NextJS, so I opened issues in both platforms.

While utilizing a NextJS application, version 13, and the experimental app directory, I encountered an issue where using `router.push` to navigate to a new page fails to render correctly. Although the navigation occurs successfully, the page only displays code as text instead of rendering the expected content. I have not found any console logs or errors related to this issue.

This problem only arises after building and running the application. Locally, everything seems to be functioning correctly.
See video: 

https://user-images.githubusercontent.com/3469263/233442201-cdb9872f-cb3a-4bc1-a4bf-acb8ae18aea5.mov

Screenshot:
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/3469263/233442935-7b08944e-5c82-4b78-be02-1f8884ae915e.png">

Simple repro: https://github.com/Royceb/nextjs-app-dir-tauri-router-push-example

### Reproduction

1. Ran `npx create-next-app@latest --experimental-app`
2. Set up Tauri

   2.1: Ran `pnpm add -D @tauri-apps/cli`

   2.2: Added `tauri` to package.json scripts. Ran `pnpm tauri init`.

3. Updated next.config.js to use `output: "export"` for SSG (Static Generation).
4. Made a simple page at `app/examplePage/page.tsx`
5. Imported `next/navigation` in `app/page.tsx` and added a button that calls `router.push('/examplePage')`.
6. Ran `pnpm tauri dev` and clicked the button. The app navigated to the example page as expected and rendered it properly.
7. Ran `pnpm tauri build` and opened the app. Clicked the button. The app did naviate to the example page, but it did not render it properly. The page rendered code as text instead of rendering the page.

### Expected behavior

The page should render correctly like it does in dev.

### Platform and versions

```text
› OS: Mac OS 13.0.1 X64
  › Node.js: 18.12.1
  › npm: 8.19.2
  › pnpm: 7.24.2
  › yarn: 1.22.19
  › rustup: 1.25.1
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-aarch64-apple-darwin
```

**Comment by Royceb** [comment] 2023-04-21 07:02
Adding {forceOptimisticNavigation: true} to the router.push call fixed it.

https://github.com/vercel/next.js/issues/48642

**Comment by brillout** [comment] 2023-04-24 11:27
Shameless plug: [vite-plugin-ssr](https://vite-plugin-ssr.com) just added support for Tauri. Example: [vite-plugin-ssr.com/tauri](https://vite-plugin-ssr.com/tauri).

**Comment by jlarmstrongiv** [comment] 2023-04-24 16:04
Hey @Royceb would you re-open this issue?  

Adding `forceOptimisticNavigation` is a temporary fix that degrades the user experience by forcing hard navigation.

See https://github.com/vercel/next.js/issues/48642#issuecomment-1517477699

**Comment by hopedope** [comment] 2023-05-10 22:32
Doesn't look like you can build any reasonable application using NextJS and Tauri. You can't have dynamic routes like `/posts/1`. Not even search params work, eg. `posts?postId=1`.

Dynamic route issue: https://github.com/vercel/next.js/issues/48022

looks like I am moving to Vite 🎉

**Comment by jlarmstrongiv** [comment] 2023-05-11 05:47
@hopedope looks like I’m moving to [Astro](https://astro.build/)

**Comment by reupen** [comment] 2023-06-01 12:00
I've run into the same problem when using the Next.js app router. It seems to affect any kind of route navigation – I created another simple repro here:

https://github.com/reupen/tauri-nextjs-repro

This only happens in (release or debug) builds and not in dev mode (where the Next.js dev server is used).

What happens is that the Next.js .txt metadata file for the route navigated to ends up being opened as a web page. So, in my example, `subpage.txt` is opened in the browser.

I noticed (in a debug build) that the content type of the .txt file is reported as `text/html` in the developer tools, rather than `text/plain`. Not sure if that's the cause of the problem (or just a red herring).

There's no problem when using another server to serve the static files and opening the site in a normal web browser. I'm on Ubuntu 22.04.

**Comment by reupen** [comment] 2023-06-01 15:45
I did some further investigation. The issue is related to content types, though not in the way I expected. Here, when the web page loads, Next.js checks if the `content-type` header in the `fetch()` response for the `.txt` file (`tauri://localhost/subpage.txt` in my example) starts with `text/plain`:

https://github.com/vercel/next.js/blob/38d9d2efee50e785f9fc707a9fcb349e49fa6dd5/packages/next/src/client/components/router-reducer/fetch-server-response.ts#L78-L93

However, the `content-type` header is not set. In fact, there don't appear to be any headers set in the response at all. This causes Next.js to decide to navigate to the `.txt` file instead when the route is actually navigated to.

I confirmed that to be the case by patching that line of code in Next.js to skip the content type check.

Is there any particular reason why no response headers would be set in the response returned by `fetch()` in the browser?

Thanks

**Comment by FabianLars** [comment] 2023-06-01 19:12
@reupen Are you also on macOS? Or on Linux? In case you're on Linux, can you add the `"linux-headers"` feature flag to the tauri dependency in Cargo.toml and try again?

Anyway, even if that brings back the headers, Tauri's "server" will fallback to an html mime type for txt files: https://github.com/tauri-apps/tauri/blob/5fdf8dcb8ed171d06121dceb32078a7e4f86cc64/core/tauri-utils/src/mime_type.rs#L48-L86. Looks more like an oversight to me since text/plain should be the fallback for textual files according to mdn

**Comment by reupen** [comment] 2023-06-01 19:26
@FabianLars I'm on Linux (Ubuntu 22.04). Did you mean the `linux-protocol-headers` feature? Can confirm that `linux-protocol-headers` + patching that bit of Tauri's code fixes the problem :tada: 

(I actually first tried patching that before I started digging into what was happening in Next.js...)

**Comment by FabianLars** [comment] 2023-06-01 19:33
whoops, yeah that flag. i had Wry's flag in mind, sorry 😅

**Comment by nielsdB97** [comment] 2023-06-09 12:06
Thanks everyone for your efforts, I'm now also looking to use Tauri combined with NextJS which should be a killer combo 😄 

@reupen am I correct in understanding that your PR should have fixed this issue with NextJS App Router builds not working? That would be fantastic, as I'm running into this problem now as well.
@FabianLars could we get some sort of estimation on when this fix will get released?

**Comment by reupen** [comment] 2023-06-09 12:24
@nielsdB97 I know it fixes Linux (with `features = ["linux-protocol-headers"]` for `tauri` in your `Cargo.toml`), and also Windows. I don't have access to macOS to test there.

**Comment by FabianLars** [comment] 2023-06-09 14:40
> could we get some sort of estimation on when this fix will get released?

Pretty soon, what i heard is that there aren't that many things left we want to get into 1.4 so after the last few things are in only the audit is left. I'm a bit out of the loop so i don't want to say something like "probably around 2 weeks" 🤷 

Afaik there is no patch for 1.3 planned though.

**Comment by nielsdB97** [comment] 2023-06-14 14:22
@reupen I can confirm it works on MacOS as well! 🎉
@FabianLars a patch release would be great since this is quite a blocker for everyone starting a new project, following the Tauri NextJS guide. However, I understand this is a more intricate process considering audits and all.

Thanks again both!

**Comment by FabianLars** [comment] 2023-06-14 14:23
How about we just release v1.4 right now? 👀 Would that work for you too?

**Comment by FabianLars** [comment] 2023-06-14 14:24
btw, closing this since the pr was merged (normally issues are autoclosed by github anyway)

**Closed as completed by FabianLars** 2023-06-14 14:24 UTC
Labels: type: bug, status: needs triage
