### ISSUE TITLE
[bug] anchor tag with download attribute not working on macOS

### ISSUE THREAD

**Issue by matthme** [tauri-apps/tauri#6171] opened 2023-01-30 15:59 UTC
### Describe the bug

Adding an anchor tag like this:
```
    <a
      style="margin-top: 40px;"
      download="test_download.json"
      href="data:text/json;charset=utf-8,%7B%22hello%22%3A%20%22test%22%7D"
    >Click here to download sample json file.</a>
```
will download nothing on macOS but work just fine on Linux and Windows.

### Reproduction

Add the anchor tag above to your html and verify that it won't download anything on macOS.

### Expected behavior

Anchor tag works as it should and downloads the file specified in the href field.

### Platform and versions

```
  › @tauri-apps/cli [NPM]: 1.2.2 (outdated, latest: 1.2.3)
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,
```

**Comment by FabianLars** [comment] 2023-01-30 16:01
Duplicate of #4633 - thanks for the report!

> will download nothing on macOS but work just fine on Linux and Windows.

Are you sure about that? I thought it only works on windows 🤔

**Comment by matthme** [comment] 2023-01-30 16:02
Yes I'm sure about it. I tested it multiple times on Linux. Sorry about the duplicate I searched for one but didn't find any.

**Closed as not planned by FabianLars** 2023-01-30 16:01 UTC
Labels: type: bug, status: needs triage
