### ISSUE TITLE
Emitting events consecutively cause hang in front end 

### ISSUE THREAD

**Issue by rdwnsjjd** [tauri-apps/tauri#3021] opened 2021-12-05 07:06 UTC
### **Describe the bug**
I write a simple installer that copies several local files to another local location. the front-end calls a Tauri command by clicking on the "install" button and in the backend, we start counting files and then transferring them to the target location.
when each file is transferred, we must emit an event to the client that has a number of files transferred. 

***NOTE: I use reactjs in the client.***
```rs
...
let mut count = 0;
for path in paths.iter_mut() {

      app.emit_all(
          "new_count", 
          CountPayload {count: count.into()}
      ).unwrap();

      fs::copy(
          path.clone(), 
          path_to.to_string() + path.file_name().unwrap().to_str().unwrap()
      ).unwrap();

      count += 1;
}
...
```

on the client: 
```js
import { listen } from '@tauri-apps/api/event';
import { useState } from 'react';

function App() {
    const [count, setCount] = useState(0);

    listen('new_count', event => {
        setCount(event.payload.count);
    })

    return (
       // somethings...
    );
}
```

but it causes a hang on the window. the backend has no problem, but the window will be frozen.

### **To Reproduce**
other events that emit normally (not consecutively) work well. also, I tried the problem above with a constant value that does not change on each loop and it works well.

### **Platform and Versions:**

```
Operating System - Ubuntu, version 20.04 X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.3
  yarn - 1.22.17

Rust environment
  rustc - 1.52.1
  cargo - 1.52.0

App directory structure
/src-tauri
/.vscode
/src
/bin
/node_modules
/.git
/public

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../src
  devPath - http://localhost:3000
  framework - React
```

**Comment by FabianLars** [comment] 2021-12-05 09:20
First, event listeners (not just tauri ones) pretty much always belong in a onMount useEffect hook where you unlisten on onUnmount (or even more restricted thann mount/unmount if you have special conditions when you want to listen to it).

Now to the actual problem. Just a little bit more code would have been helpful to see where we are on the rust side.
But my guess is we are in a tauri command that is declared like this?
```rs
#[tauri::command]
fn copy_files(...) {}
```
If so then this command will run on the **main thread** and therefore block the ui/window.
To tell tauri to run the command on another thread, you can explicitly ask it to do to it by changing your command to:
```rs
#[tauri::command(async)]
fn copy_files(...) {}
```
or just make the command async, those will run on a seperate thread too and allow to copy files with tokio if you want that:
```rs
#[tauri::command]
async fn copy_files(...) {}
```

**Comment by rdwnsjjd** [comment] 2021-12-05 10:20
I don't understand well what you say in the first lines about unlistening. should I unlisten each event after listening to it?

however, my command was async. more code is here:

```rust
fn copy_files(
    config: String, 
    app: tauri::AppHandle
) -> Result<i32, ()> {

    // getting directory path and count number of files
    // ...

    // emiting number of files  (IT IS WORKING)
    app.emit_all(
        "files_count", 
        CountPayload {count: (result as i32).into()}
    ).unwrap();

    let mut count = 0;
    for path in path_arr.iter_mut() {

        // emit number of files counted
        //! HERE we have hang
        app.emit_all(
            "new_count", 
            CurCountPayload {count: count.into()}
        ).unwrap();

        // copy the file to the target
        match fs::copy(
            path.clone(), 
            path_to.to_string() + path.file_name().unwrap().to_str().unwrap()
        ) {
            Ok(_) => {},
            Err(e) => {
                new_err(e.to_string(), app.clone());
            },
        };

        count += 1;
    }

    return Ok(result as i32);
}


#[tauri::command]
async fn install(
    app: tauri::AppHandle
) -> Result<i32, String>  {

    // handling app 
    let _app_dir = app.path_resolver().app_dir();

    println!("Starting installation...");
    let config = fs::read_to_string("config.json").unwrap();

    match copy_files(config.clone(), app.clone()) {

        Ok(count) => {
            println!("\rDone!\n");
            change_step(2, app.clone());
            Ok(count)
        },
        
        Err(_) => {
            println!("Failed to copy files...");
            return Err("Failed to copy files...".into());
        },
    }

    // doing some stuff ...

    return Ok(1);
}

```

but still is frozen.

**Comment by FabianLars** [comment] 2021-12-05 11:18
> I don't understand well what you say in the first lines about unlistening. should I unlisten each event after listening to it?

What i meant is that you generally do it like this:
```js
useEffect(() => {
    const unlisten = listen('new_count', event => {
        setCount(event.payload.count);
    })

    return () => {
        unlisten.then((f) => f());
    };
}, []);
```
Also i think the unlisten part is optional if your component can never unmount, aside from when the app closes. So for example if you use React Router and this element is part of a Route.


If that doesn't change anything: What exactly do you mean by "the window hangs/freezes"? Is it just the content inside the window or the whole window (can you still resize/move it or something)? Are there any errors, especially in the dev tools console if that is somehow still accessible? Can you show a screenshot or a recording?
Because i wasn't able to reproduce it so far...

**Comment by rdwnsjjd** [comment] 2021-12-05 11:43
the window itself is responding and can move and resize it. but the content is stopped and hung.
also, devTools is working.
I also try unlisten but it was not helpful.

Just an error that I don't think is related to the problem

![Screenshot from 2021-12-05 15-10-29](https://user-images.githubusercontent.com/84472404/144744973-16986c15-f7b6-49fe-80a5-dd3c38e2e6cf.png)

here the window content is hanged but the backend is working very well

**Comment by rdwnsjjd** [comment] 2021-12-05 11:51
If you are simulating this, try with a lot of files (many loops)

**Comment by nothingismagick** [comment] 2021-12-05 12:06
![image](https://user-images.githubusercontent.com/35242872/144745793-b3b6d7c2-beff-4612-9214-b3a30af103fa.png)

**Comment by FabianLars** [comment] 2021-12-05 12:08
1\) What nothingismagick said

2\) But the `Copying: .../filename` stuff in the terminal keeps going right? So the loop doesn't block/stops?
If so then this should be a frontend problem, did you put the listener inside an useEffect hook like i showed above yet? Because if i don't do that (and just put the listen call directly inside the function like you did in your snippet above), then my whole react app crashes...

Otherwise i really can't help you without a minimal reproduction repo here.

**Comment by rdwnsjjd** [comment] 2021-12-05 12:08
what is it say?
I try without it and still have the problem.

**Comment by rdwnsjjd** [comment] 2021-12-05 12:13
No, the backend loop does not stop. I knew from the beginning that the problem is in front end. But I do not know what?!

yes, the listeners are in the useEffect, as you say: 
```jsx
useEffect(() => {

        const change_step = listen('change_step', event => {
            setCurrentStep(event.payload.step);
        })
    
        const files_count = listen('files_count', event => {
            alert(event.payload.count)
            setFilesCount(event.payload.count);
        })
    
        const new_count = listen('new_count', event => {
            setCount(event.payload.count);
        })
    
        const new_err = listen('new_err', event => {
            setErr(event.payload.msg);
        })
    
        const new_log = listen('new_log', event => {
            setLog(event.payload.log);
        })

        let tmpData = {
            "step": currentStep,
            "allFilesCount": filesCount,
            "currentFileCount": count,
            "error": err,
            "warn": warn,
            "log": data.log
        }
    
        tmpData.log.push(log);
        setData(tmpData);

        return () => {
            change_step.then(() => "");
            // files_count.then(() => "");
            // new_count.then(() => "");
            new_err.then(() => "");
            new_log.then(() => "");
        };
        
    }, [currentStep, filesCount, count, err, warn, log])
```

**Comment by FabianLars** [comment] 2021-12-05 12:17
Well that's not quite what i asked for tho. I asked to do an `onMount` event listener == an empty dependency array.

Also that whole code flow is completely broken/wrong... I don't even know where to start tbh

**Comment by rdwnsjjd** [comment] 2021-12-05 12:19
can you describe it a bit more? 

> do an onMount event listener == an empty dependency array.

how to do it in react hooks?

**Comment by rdwnsjjd** [comment] 2021-12-05 12:21
It is my App hook: 

```jsx
function App() {

    const [currentStep, setCurrentStep] = useState(0);
    const [filesCount, setFilesCount] = useState(1)
    const [count, setCount] = useState(0);
    const [log, setLog] = useState("");
    const [err, setErr] = useState("");
    const [warn, setWarn] = useState("");
    const [data, setData] = useState({
        "step": currentStep,
        "allFilesCount": filesCount,
        "currentFileCount": count,
        "error": err,
        "warn": warn,
        "log": []
    });


    useEffect(() => {

        const change_step = listen('change_step', event => {
            setCurrentStep(event.payload.step);
        })
    
        // const files_count = listen('files_count', event => {
        //     alert(event.payload.count)
        //     setFilesCount(event.payload.count);
        // })
    
        const new_count = listen('new_count', event => {
            setCount(event.payload.count);
        })
    
        const new_err = listen('new_err', event => {
            setErr(event.payload.msg);
        })
    
        const new_log = listen('new_log', event => {
            setLog(event.payload.log);
        })

        let tmpData = {
            "step": currentStep,
            "allFilesCount": filesCount,
            "currentFileCount": count,
            "error": err,
            "warn": warn,
            "log": data.log
        }
    
        tmpData.log.push(log);
        setData(tmpData);

        return () => {
            change_step.then(() => "");
            // files_count.then(() => "");
            new_count.then(() => "");
            new_err.then(() => "");
            new_log.then(() => "");
        };
        
    }, [currentStep, filesCount, count, err, warn, log])

    return (
        <ScreenView
            data = {data}
        ></ScreenView>
    );
}

export default App;
```

The commented section it what causes prev error

**Comment by FabianLars** [comment] 2021-12-05 12:36
(when i said `onMount` i meant `componenteDidMount` sorry)
> how to do it in react hooks?

Let's take my code snippet from above:
```js
useEffect(() => {
    const unlisten = listen('new_count', event => {
        setCount(event.payload.count);
    })

    return () => {
        unlisten.then((f) => f());
    };
}, [/* THIS IS THE DEPENDENCY ARRAY. Leaving it empty executes this useEffect ONLY when the component mounts */]);
```

There should be only the event listeners in this hook, not the code below that. Also, the code below that is completely broken or at least in the context of the code flow of the whole hook.

BUT this is not tauri specific at all, you would have the same problem with "normal" event listeners. So tbh i think you should learn some more react first, which would also help with the language barrier(s) we both have here. I don't think i'm able to explain react as a whole here...

Also, i'm gonna close this issue since this is a react thing, but feel free to keep asking questions here or even better on discord (preferably after getting a little bit more comfortable with react)

**Closed as completed by FabianLars** 2021-12-05 12:36 UTC
Labels: status: invalid

**Comment by rdwnsjjd** [comment] 2021-12-05 12:53
I know React enough. your code is not what I want. I want to get a new_count every time the backend updates it (actually after each file copy). so dependency array should have a `count` variable to update the hook every time, otherwise, it will be updated once and I don't want this. I want to get a number of current copied files dynamically.

**Comment by FabianLars** [comment] 2021-12-05 13:34
> I know React enough

I'm sorry, but you don't. Please ask google or another search engine of your choice how event listeners work in react. Probably a good idea to do the same for useEffect (+dependency arrays) and lifecycles.

The useEffect hook (that contains the listeners) doesn't need to run every time you want to receive an update from your backend. You want to run it **to register the listener**, this listener will run the **callback** given to it **on every event**. With the `count` variable inside the dependency array you **register** a **new** listener every time `count` changes! The worst thing is that every time one of the event listeners run, the useEffect will get triggered once again.
-> That's why you most likely want to split it up into at least 2 useEffect hooks.

Also this: `new_count.then(() => "");` is wrong too. This basically doesn't do anything. The `listen` function returns a Promise which resolves to a **function** which you can call to **unlisten** to the event, like shown in my snippet above.
(If you don't actually unlisten to the events here you will end up registering hundreds of listeners, mainly because of the combination with the issues mentioned above and below.)

And then there is the code flow problem too. Because the event listener don't run until they receive an event and also don't block the execution flow at all, the content of the useEffect hook won't run from top to bottom sequentially like your code wants it to!
For example on the `let tmpData` line, the listeners will most likely didn't get a chance to run yet and even if so, the hook might not know about that until the next time it runs.
This problem also interferes with or gets interfered by the problems above.

So yeah that useEffect usage is fundamentally broken... And my vocabulary is too limited to give you a 100% walkthrough, sorry. I hope it was enough tho.

###
~~Also, I'm a little embarrassed to say this, but~~ (edit: no I'm not lol)
Also, this conversation actually kinda tilts me, so i'm going to lock this convo if the explanations above aren't enough, **especially since this is not a _tauri_ "issue"** (you'd have the same problems with `document.addEventListener()`).

**Comment by rdwnsjjd** [comment] 2021-12-05 14:43
OK tnx. I will try it and sorry about deviation of the subject
