### ISSUE TITLE
A third-party web page inside Tauri. How can I scale the page content?[bug] 

### ISSUE THREAD

**Issue by mxismean** [tauri-apps/tauri#6225] opened 2023-02-09 09:47 UTC
### Describe the bug

A third-party web page inside Tauri. 
Want the page content to zoom to show more content.
However, no relevant configuration was found.

### Expected behavior

Expect to scale the page content. I hope to achieve the effect of `zoom` in css.

### Platform and versions

Environment
  › OS: Mac OS 12.6.2 X64
  › Node.js: 16.18.1
  › npm: 8.19.2
  › pnpm: 7.17.1
  › yarn: 1.22.19
  › rustup: 1.25.2
  › rustc: 1.67.0
  › cargo: 1.67.0
  › Rust toolchain: stable-aarch64-apple-darwin

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:5173/
  › framework: Vue.js
  › bundler: Vite

App directory structure
  ├─ dist
  ├─ node_modules
  ├─ public
  ├─ .github
  ├─ src-tauri
  ├─ .git
  ├─ .vscode
  └─ src

**Comment by FabianLars** [comment] 2023-02-09 10:17
i think this counts as a duplicate of https://github.com/tauri-apps/tauri/issues/3310. Thanks for the request.

**Closed as not planned by FabianLars** 2023-02-09 10:17 UTC
Labels: type: question
