### ISSUE TITLE
transparent: true, doesnt make any sense after 1.3.0 release [bug] 

### ISSUE THREAD

**Issue by lol224422** [tauri-apps/tauri#6872] opened 2023-05-05 19:12 UTC
### Describe the bug

After updatin tauri in cargo.toml from 1.2.2 to 1.3.0, i see white border in my app, i think that transparent property works incorect in new version for windows.

tauri.cof.json
`"windows": [
      {
        "center": true,
        "decorations": false,
        "fullscreen": false,
        "resizable": true,
        "minWidth": 1350,
        "minHeight": 800,
        "transparent": true
      }
    ]`

![image](https://user-images.githubusercontent.com/50754761/236548680-442578d7-dbc1-477e-879d-696f268361ab.png)

### Platform and versions

```text
Environment
  › OS: Windows 10.0.22621 X64
  › Webview2: 112.0.1722.68
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.26.0
  › rustc: 1.69.0
  › cargo: 1.69.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3 (outdated, latest: 1.3.0)
  › @tauri-apps/api [NPM]: 1.2.0 (outdated, latest: 1.3.0)
  › tauri [RUST]: 1.3.0,
  › tauri-build [RUST]: 1.3.0,
  › tao [RUST]: 0.16.0,
  › wry [RUST]: 0.24.1,
```

**Comment by amrbashir** [comment] 2023-05-05 19:31
duplicate of https://github.com/tauri-apps/tauri/issues/6868
thanks for your patience while we try to release a fix ASAP.

**Closed as completed by amrbashir** 2023-05-05 19:31 UTC
Labels: type: bug, status: needs triage

**Comment by lol224422** [comment] 2023-05-05 19:38
> duplicate of #6868 thanks for your patience while we try to release a fix ASAP.

thx)
