### ISSUE TITLE
Roadmap: Other Bindings?

### ISSUE THREAD

**Issue by duurland** [tauri-apps/tauri#6373] opened 2023-02-28 10:50 UTC
Is there any issue to track the `Other Bindings` roadmap entry? 
If not, maybe this one could be used for those of us that wish to subscribe to any updates.

Various discussions/issues regarding bindings, loading alternative runtimes with sidecars, migrating from electron/node, etc:

- [Question about whether tauri will support webserver](https://github.com/tauri-apps/tauri/discussions/2537)
- [Bun?](https://github.com/tauri-apps/tauri/discussions/5837)
- [Electron to tauri system](https://github.com/tauri-apps/tauri/discussions/1223)
- [how to use a JavaScript module built for node.js](https://github.com/tauri-apps/tauri/discussions/2592)
- [Node to Deno rust .js](https://github.com/tauri-apps/tauri/discussions/2572)
- [QuickJS instead of Deno for app backend!](https://github.com/tauri-apps/tauri/discussions/1131)
- [Node server doesn't starts on it's own](https://github.com/tauri-apps/tauri/discussions/2174)
- [Rebuilding an Electron Desktop app with Tauri](https://github.com/tauri-apps/tauri/discussions/4873)
- [Executing python scripts using Tauri](https://github.com/tauri-apps/tauri/discussions/1645)
- [Question about whether tauri will support webserver](https://github.com/tauri-apps/tauri/discussions/2537)
- [[feat] Electron to Tauri](https://github.com/tauri-apps/tauri/issues/6142)
- [[bug] Sidecar example fails to produce working Appimage](https://github.com/tauri-apps/tauri/issues/5445)
- [How to run nodejs server in build mode ?](https://github.com/tauri-apps/tauri/issues/1773)
- [Headless Tauri](https://github.com/tauri-apps/tauri/issues/1061)
- [[bug] Can't run Tauri on a different thread](https://github.com/tauri-apps/tauri/issues/3172)
- [How to implement another Backend Service (like C#/ .NET) ](https://github.com/tauri-apps/tauri/issues/5174)

**Comment by amrbashir** [comment] 2023-02-28 12:34
duplicate of https://github.com/tauri-apps/tauri/issues/4670

**Closed as not planned by amrbashir** 2023-02-28 12:34 UTC

**Comment by tiziodcaio** [comment] 2023-09-18 12:40
I suggest reopening because this one is more general than the issue you've mentioned... @amrbashir

**Comment by Zireael07** [comment] 2024-03-10 10:46
Agreed, this one is more generic
