### ISSUE TITLE
[bug] Playing sound is not supported on linux

### ISSUE THREAD

**Issue by shi-yan** [tauri-apps/tauri#6834] opened 2023-05-01 17:09 UTC
### Describe the bug

My project needs to play audio. https://github.com/shi-yan/broca

it is implemented by doing "new Audio(url).play();" in javascript.

The url is a local mp3 file.

Things work fine on mac, but doesn't work on linux. No sound is played and no error messages either.

### Reproduction

create a tauri project with a local mp3 file,

in javascript, do `new Audio(url).play()`

### Expected behavior

Audio should be played

### Platform and versions

```text
will provide later (don't have access to my linux at the moment)
```

### Stack trace

```text
No crash.
```

**Comment by tensor-programming** [comment] 2023-05-01 22:43
What distribution have you tried this one?  I was unable to recreate it with debian on WSL though I will try it again on my native PopOS (ubunutu based) laptop.

**Comment by shi-yan** [comment] 2023-05-02 04:43
I'm using ubuntu 20.04

**Comment by tensor-programming** [comment] 2023-05-02 04:51
Thanks.  Ill check it out and get back to you then. I do have a hunch already about what the issue might be related to.

**Comment by FabianLars** [comment] 2024-12-05 14:02
duplicate of https://github.com/tauri-apps/tauri/issues/3725

**Closed as not planned by FabianLars** 2024-12-05 14:02 UTC
Labels: type: bug, status: needs triage
