### ISSUE TITLE
[feat] Resize window but disable maximize.

### ISSUE THREAD

**Issue by guillerp8** [tauri-apps/tauri#4286] opened 2022-06-07 14:43 UTC
### Describe the problem

It will be cool implementing a Window feature that electron has (windows version at least). Making Window resizable but not maximizable.

### Describe the solution you'd like

I would like to be able to resize an screen without allowing the user to maximize it.

**Comment by JonasKruckenberg** [comment] 2022-06-07 14:48
We can easily disable the maximize button (a post-v1 addition though) so yeah

Edit: Dunno why I commented, I guess I thought I had something more interesting to say lol

**Comment by guillerp8** [comment] 2022-06-07 14:51
I meant to: in Windows when you drag to the top-left or top-right of the screen, the window gets maximized. Disabling the button will be the solution to this?

**Comment by JonasKruckenberg** [comment] 2022-06-07 15:01
> I meant to: in Windows when you drag to the top-left or top-right of the screen, the window gets maximized. Disabling the button will be the solution to this?

I'm not a windows expert, but I'm pretty confident that this is out of the developers control (except maybe you could mark your window as a modal or something)

**Comment by guillerp8** [comment] 2022-06-07 15:04
Not sure of that, I think that Electron supports the resize and the drag-to-top maximization disabled together in Windows.

**Comment by amrbashir** [comment] 2022-06-07 16:39
upstream: https://github.com/tauri-apps/tao/issues/116

**Comment by amrbashir** [comment] 2022-09-30 14:39
closing as duplicate of https://github.com/tauri-apps/tauri/issues/2353

**Closed as not planned by amrbashir** 2022-09-30 14:39 UTC
Labels: type: feature request, status: upstream
