### ISSUE TITLE
[v2 bug]  error on set_size and set_position: invalid value: map, expected map with a single key

### ISSUE THREAD

**Issue by eythaann** [tauri-apps/tauri#9455] opened 2024-04-13 00:09 UTC
### Describe the bug

I can no use setSize and setPosition, this doesn't happen on other beta versions but I run cargo update - npm update and an error start appearing.

[2024-04-13][00:01:37][ERROR][webview::unknown]  "Unhandled Rejection - invalid args `value` for command `set_size`: invalid value: map, expected map with a single key"
[2024-04-13][00:01:37][ERROR][webview::unknown]  "Unhandled Rejection - invalid args `value` for command `set_position`: invalid value: map, expected map with a single key"

### Reproduction

  just using the setSize or setPosition methods on JS
  
  const webview = getCurrent();
  const screenWidth = Math.floor(window.screen.width * window.devicePixelRatio);
  const screenHeight = Math.floor(window.screen.height * window.devicePixelRatio);
  webview.setSize(new PhysicalSize(screenWidth, screenHeight));

### Expected behavior

normal work

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 10.0.22631 X64
    ✔ WebView2: 123.0.2420.81
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.77.1 (7cf61ebde 2024-03-27)
    ✔ cargo: 1.77.1 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.0 (bbb9276d2 2024-03-08)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 20.10.0
    - npm: 10.2.3

[-] Packages
    - tauri [RUST]: 2.0.0-beta.14
    - tauri-build [RUST]: 2.0.0-beta.11
    - wry [RUST]: 0.39.0
    - tao [RUST]: 0.27.0
    - @tauri-apps/api [NPM]: 2.0.0-beta.7
    - @tauri-apps/cli [NPM]: 2.0.0-beta.12

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: dist
    - framework: React
```

**Comment by ConsoleC137** [comment] 2024-04-13 06:51
I am facing the same problem on Windows 10 and Tauri 2.0.

**Comment by FabianLars** [comment] 2024-04-13 14:05
Duplicate of https://github.com/tauri-apps/tauri/issues/9370, will be fixed in the next release by https://github.com/tauri-apps/tauri/pull/9376

**Closed as not planned by FabianLars** 2024-04-13 14:05 UTC
Labels: type: bug, status: needs triage
