### ISSUE TITLE
[bug] Tauri 2.0 cannot run on Windows 7 SP1(x86 or x64)

### ISSUE THREAD

**Issue by eed-cn** [tauri-apps/tauri#11381] opened 2024-10-16 08:04 UTC
### Describe the bug

The compiled result of Tauri 2.0 does not run on Windows 7 SP1.

![20241016160153](https://github.com/user-attachments/assets/f63fd8e0-b2e3-41ac-aa34-e5ec6b880414)

### Reproduction

Run `pnpm create tauri-app`

### Expected behavior

It is expected to run normally. I also want to know if Tauri 2.0 supports Windows 7. Globally, Windows 7 still has a 3% market share, and in some regions like China, the share is as high as 20%. This is a significant proportion.

### Full `tauri info` output

```text
[✔] Environment
    - OS: Windows 6.3.9600 i386 (X32)
    ✔ WebView2: 109.0.1518.78
    ✔ MSVC: Visual Studio Professional 2017
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.77.2-i686-pc-windows-msvc (default)
    - node: 22.9.0
    - pnpm: 9.12.1
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.3
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.1
    - tao 🦀: 0.30.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src
```

### Additional context

I compiled on both Windows 8 x86 and x64 environments, and tested on Windows 7, but it still could not run.

**Comment by eed-cn** [comment] 2024-10-16 08:06
The apps have been installed in Win7:
![image](https://github.com/user-attachments/assets/ce2c9d6c-d7de-43e0-9426-017dfd804515)

**Comment by amrbashir** [comment] 2024-10-16 09:04
closing as duplicate of #10834

**Closed as not planned by amrbashir** 2024-10-16 09:04 UTC
Labels: type: bug, platform: Windows, status: needs triage

**Comment by FabianLars** [comment] 2024-10-16 09:32
Can you translate what the dialog says? Or at least copy paste the text so we can translate it ourselves?

**Comment by eed-cn** [comment] 2024-10-16 11:58
@FabianLars 

![image](https://github.com/user-attachments/assets/81372654-8972-4991-8894-fb6a86328064)


Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	demo-1.77.2-x86-bywin8x86-tauri2.03.exe
  Application Version:	0.1.0.0
  Application Timestamp:	670f628a
  Fault Module Name:	demo-1.77.2-x86-bywin8x86-tauri2.03.exe
  Fault Module Version:	0.1.0.0
  Fault Module Timestamp:	670f628a
  Exception Code:	c0000005
  Exception Offset:	000abbb3
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	2052
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

![image](https://github.com/user-attachments/assets/4f701be7-5f28-4552-8b2f-1f7f654ca8b4)


TIP:Vmware PC

**Comment by eed-cn** [comment] 2024-10-16 12:59
pnpm tauri info：

[✔] Environment
    - OS: Windows 6.3.9600 x86_64 (X64)
    ✔ WebView2: 109.0.1518.140
    ✔ MSVC: Visual Studio Professional 2017
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.27.1 (54dd3d00f 2024-04-24)
    ✔ Rust toolchain: 1.77.2-i686-pc-windows-msvc (default)
    - node: 22.9.0
    - pnpm: 9.12.1
    - yarn: 1.22.22
    - npm: 10.8.3

[-] Packages
    - tauri 🦀: 2.0.4
    - tauri-build 🦀: 2.0.1
    - wry 🦀: 0.46.2
    - tao 🦀: 0.30.3
    - @tauri-apps/api : not installed!
    - @tauri-apps/cli : 2.0.3

[-] Plugins
    - tauri-plugin-shell 🦀: 2.0.1
    - @tauri-apps/plugin-shell : not installed!

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../src

**Comment by FabianLars** [comment] 2024-10-16 20:14
Thanks!

**Comment by eed-cn** [comment] 2024-10-17 06:03
@FabianLars 
I made some new attempts.

Build environment:
Windows 7 SP1 x64
(pnpm tauri build run error, the possible issue is with cli.win32-x64-msvc.node in @tauri-apps/cli)

Test 1:
`cargo build --release` (x86_64-pc-windows-msvc)

Runtime environment:
Windows 7 SP1 x64: Runs normally
Windows 8 SP1 x64: Runs normally

Test 2:
`cargo build --release --target i686-pc-windows-msvc`

Runtime environment:
Windows 7 SP1 x64: **_Abnormal_**
Windows 7 SP1 x86: **_Abnormal_**
Windows 8 SP1 x64: Runs normally
Windows 8 SP1 x86: Runs normally

Build environment:
Windows 11 x64

Test 3:
`pnpm  build` (1.77.2  x86_64-pc-windows-msvc)

Runtime environment:
Windows 7 SP1 x64: Runs normally
Windows 8 SP1 x64: Runs normally

Test 4:
`pnpm  build -t  i686-pc-windows-msvc` (1.77.2)
Runtime environment:
Windows 7 SP1 x64:  **_Abnormal_**
Windows 7 SP1 x86: **_Abnormal_**
Windows 8 SP1 x64: Runs normally
Windows 8 SP1 x86: Runs normally

**Comment by FabianLars** [comment] 2024-10-17 08:27
That looks a bit like an issue with the rust compiler or something 🤔

Thanks for the extensive testing! I'm still out sick for a while so I can't look into it right now :/

**Comment by eed-cn** [comment] 2024-10-21 01:21
@FabianLars 
Wishing you a speedy recovery. I feel the possible issue lies with wry or tauri-runtime-wry, specifically regarding compatibility with Windows 7, because I have tested some programs under Tauri 1.7 that run normally on Windows 7.

**Comment by eed-cn** [comment] 2024-10-21 02:11
Project wry: 
cargo build --release --example simple 
Runtime environment: Windows 7 x64 
simple-1.77.2-x86_64-pc-windows-msvc-by-win11-x64.exe runs well. 
simple-1.77.2-i686-pc-windows-msvc-by-win11-x64.exe throws an exception(the same error occurs on Windows 7 x86 ): 
RUST_BACKTRACE=full ./simple-1.77.2-i686-pc-windows-msvc-by-win11-x64-raw.exe thread 'main' panicked at .....\tao-0.29.1\src\platform_impl\windows\event_loop.rs:708:5: 
assertion failed: subclass_result.as_bool() stack backtrace: 0: 0x109bc3b - <unknown>

**Comment by eed-cn** [comment] 2024-10-21 02:18
Now the issue points to `tao-0.29.1\src\platform_impl\windows\event_loop.rs:708:5`

**Comment by eed-cn** [comment] 2024-10-21 02:20
@amrbashir  @FabianLars 
Could you please reopen the current issue as 'Open'? Thank you.

**Comment by eed-cn** [comment] 2024-10-21 02:59
#https://github.com/tauri-apps/tao/issues/990

**Comment by zjfpcb** [comment] 2025-01-28 04:05
你好，请问你1.77.2的版本是怎么编译通过的，我编译的时候提示  `cargo_metadata v0.19.1` 这个包的版本必须要1.78才能编译通过。

**Comment by FabianLars** [comment] 2025-01-28 13:28
```
cargo update -p cargo-metadata --precise 0.19.0
```

**Comment by zjfpcb** [comment] 2025-01-29 04:46
> ```
> cargo update -p cargo-metadata --precise 0.19.0
> ```

谢谢  可以了.

**Comment by zivenyang** [comment] 2025-03-30 14:27
我通过降级rust实现了win7sp1x64的版本编译，教程如下：
https://yangziwen.cn/zh/blog/tauri/win7

**Comment by friping** [comment] 2025-04-07 12:28
> 我通过降级rust实现了win7sp1x64的版本编译，教程如下： https://yangziwen.cn/zh/blog/tauri/win7

@zivenyang 我按照你的步骤，把依赖的版本都弄成跟你一样的了，还是报了这个错

![Image](https://github.com/user-attachments/assets/aef17dad-437b-4c6a-b645-2345e95f0714)

系统：

![Image](https://github.com/user-attachments/assets/005df42d-953f-42a0-9218-e25023b63c15)


```

[✔] Environment
    - OS: Windows 10.0.26100 x86_64 (X64)
    ✔ WebView2: 133.0.3065.59
    ✔ MSVC: Visual Studio 生成工具 2022
    ✔ rustc: 1.77.2 (25ef9e3d8 2024-04-09)
    ✔ cargo: 1.77.2 (e52e36006 2024-03-26)
    ✔ rustup: 1.28.1 (f9edccde0 2025-03-05)
    ✔ Rust toolchain: 1.77.2-x86_64-pc-windows-msvc 
    - node: 20.10.0
    - npm: 10.2.3

[-] Packages
    - tauri 🦀: 2.3.1
    - tauri-build 🦀: 2.1.1
    - wry 🦀: 0.50.5
    - tao 🦀: 0.32.8
    - @tauri-apps/api : 2.0.3 (outdated, latest: 2.4.1)
    - @tauri-apps/cli : 2.0.5 (outdated, latest: 2.4.1)

[-] Plugins
    - tauri-plugin-shell 🦀: 2.2.1
    - @tauri-apps/plugin-shell : 2.0.1 (outdated, latest: 2.2.1)
    - tauri-plugin-fs 🦀: 2.2.1
    - @tauri-apps/plugin-fs : 2.2.0 (outdated, latest: 2.2.1)
    - tauri-plugin-dialog 🦀: 2.2.1
    - @tauri-apps/plugin-dialog : 2.0.1 (outdated, latest: 2.2.1)

[-] App
    - build-type: bundle
    - CSP: unset
    - frontendDist: ../dist
    - devUrl: http://localhost:1420/
    - framework: Vue.js
    - bundler: Vite
```

**Comment by jiangkaifree** [comment] 2025-05-09 01:38
> 我通过降级rust实现了win7sp1x64的版本编译，教程如下： https://yangziwen.cn/zh/blog/tauri/win7

你的程序能在win7 x86上运行吗

**Comment by friping** [comment] 2025-05-09 01:44
> > 我通过降级rust实现了win7sp1x64的版本编译，教程如下： https://yangziwen.cn/zh/blog/tauri/win7
> 
> 你的程序能在win7 x86上运行吗

我之前就再x86上试的， 成功了，之前那个错误是因为有的库不支持win7，把库降级成能支持的版本就行了

**Comment by jiangkaifree** [comment] 2025-05-09 01:54
> > > 我通过降级rust实现了win7sp1x64的版本编译，教程如下： https://yangziwen.cn/zh/blog/tauri/win7
> > 
> > 
> > 你的程序能在win7 x86上运行吗
> 
> 我之前就再x86上试的， 成功了，之前那个错误是因为有的库不支持win7，把库降级成能支持的版本就行了

我看了你的 blog, 我已经完成了降级，使用的是rust 1.75， 同时我对照了需要降级的依赖， 并没有发现我的项目当中存在这两个
```
cargo update cargo-platform@0.1.9 --precise 0.1.8
cargo update cargo_metadata@0.19.2 --precise 0.19.0 
```
我的报错信息和你类似：无法定位程序输入点ProcessPrng于动态链接库bcryptprimitives.dll

**Comment by friping** [comment] 2025-05-09 02:05
> ```
> cargo update cargo-platform@0.1.9 --precise 0.1.8
> cargo update cargo_metadata@0.19.2 --precise 0.19.0 
> ```

显示在写在Cargo.toml 或者 显示执行一边就行，不过找不到输入点的问题我不太确定，只是觉的应该是某个库用了调用了win7不存在的API导致的，可能要具体去查找一下具体哪个库的问题

**Comment by jiangkaifree** [comment] 2025-05-09 02:13
> > ```
> > cargo update cargo-platform@0.1.9 --precise 0.1.8
> > cargo update cargo_metadata@0.19.2 --precise 0.19.0 
> > ```
> 
> 显示在写在Cargo.toml 或者 显示执行一边就行，不过找不到输入点的问题我不太确定，只是觉的应该是某个库用了调用了win7不存在的API导致的，可能要具体去查找一下具体哪个库的问题

是的，我的报错和上面的图片一样，不同的点在于 中间的输入点不一样和dll不一样

**Comment by jiangkaifree** [comment] 2025-05-09 03:06
> > > ```
> > > cargo update cargo-platform@0.1.9 --precise 0.1.8
> > > cargo update cargo_metadata@0.19.2 --precise 0.19.0 
> > > ```
> > 
> > 
> > 显示在写在Cargo.toml 或者 显示执行一边就行，不过找不到输入点的问题我不太确定，只是觉的应该是某个库用了调用了win7不存在的API导致的，可能要具体去查找一下具体哪个库的问题
> 
> 是的，我的报错和上面的图片一样，不同的点在于 中间的输入点不一样和dll不一样

我重新进行了尝试，因为我是rust 小白，我发现我在打包的时候 rust并没有使用兼容wind7的版本，虽然我在项目当中的 cargo.toml 
 文件进行了声明 `rust-version` 版本，但不知道哪里出来问题,现在我使用命令在系统中切换了rust 版本，现在成功运行了

**Comment by xialeistudio** [comment] 2025-12-21 08:21
Hey everyone!

  I put together a Tauri template that works on Windows 7. It's got the WebView2 runtime and Rust 1.77.2 all set up already.

  You can grab it here: https://github.com/xialeistudio/tauri-template/

  It's using React + TypeScript + Vite and works on Windows 7/10/11 plus macOS.

  Hope this helps someone stuck with Windows 7!

**Comment by mixiuemo** [comment] 2026-01-22 13:29
我来尝试一下，谢谢
