### ISSUE TITLE
[bug] Web fonts that load in browser not loading in app

### ISSUE THREAD

**Issue by zenzoa** [tauri-apps/tauri#6815] opened 2023-04-28 01:44 UTC
### Describe the bug

I am using the [Mono Icons](https://icons.mono.company/) icon font in a tool I'm making using Tauri. I've included that package's css file, which imports the .ttf/.woff/.woff2 files, and everything looks good when I test out the html/js/css in Firefox. However when I compile it with Tauri and run it on Linux, the icons are broken - and the inspector says "an error occurred trying to load the resource."

![image](https://user-images.githubusercontent.com/10480278/235033336-3b792134-c3a4-4ef7-b8f9-930420fa90d3.png)

### Reproduction

1. Add the Mono Icons library to ui/library/mono-icons
2. Include the Mono Icons stylesheet in ui/index.html: `<link rel="stylesheet" href="./library/mono-icons/iconfont/icons.css">`
3. Add an icon to index.html: `<i class="mi-zoom-in">`
4. Compile and run the app in Tauri: `cargo tauri dev`
5. Observe that instead of a zoom-in icon, you see a glyph from a built-in font; and in the inspection tools, ui/library/mono-icons/iconfont/icons.ttf, icons.woff, and icons.woff2, were not loaded successfully

### Expected behavior

I would expect font files included in the ui folder and are loaded successfully in a browser context to load and display successfully in the compiled Tauri app.

### Platform and versions

```text
Environment
  › OS: Arch Linux Rolling Release X64
  › Node.js: Not installed!
  › npm: Not installed!
  › pnpm: Not installed!
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.2
  › cargo: 1.68.2
  › Rust toolchain: stable-x86_64-unknown-linux-gnu 

Packages
WARNING: no lock files found, defaulting to npm
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../ui
  › devPath: ../ui
package.json not found

App directory structure
  ├─ src-tauri
  └─ ui
```

### Additional context

This is my first Tauri project, so I might have missed something after scouring the documentation, GitHub issues, and internet searches. I did try to include the files manually as resources in tauri.conf.json, but it didn't seem to make a difference.

**Comment by muziliuri** [comment] 2023-04-28 13:45
I have the same problem.

**Comment by amrbashir** [comment] 2023-05-03 22:13
The reproduction steps are not quite clear.

We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as not planned by amrbashir** 2023-05-03 22:13 UTC
Labels: type: bug, status: needs triage

**Comment by fatih-dogmus** [comment] 2023-07-22 16:38
I need custom font. I got woff2 file how can i use?

**Comment by diohpix** [comment] 2024-09-20 01:47
try this with plugin-fs
`let exist = await exists("D2Coding.woff2", {  baseDir: BaseDirectory.Font });
			if(exist){
				const file = await readFile("D2Coding.woff2", {  baseDir: BaseDirectory.Font });
				const font = new FontFace('D2Coding', file.buffer);
				await font.load();
				document.fonts.add(font);
			}`

**Comment by diohpix** [comment] 2024-09-20 01:50
try this with plugin-fs
'''
let exist = await exists("D2Coding.woff2", {  baseDir: BaseDirectory.Font });
			if(exist){
				const file = await readFile("D2Coding.woff2", {  baseDir: BaseDirectory.Font });
				const font = new FontFace('D2Coding', file.buffer);
				await font.load();
				document.fonts.add(font);
			}
'''

**Comment by av** [comment] 2024-09-27 10:32
To anyone landing on this issue with Tauri 2:

Check your folder structure and import URLs. For example:

```bash
/src
  /assets
    /fonts
      Font1.woff2
```

Means you want an import like:
```css
@font-face {
  src: url("/src/assets/fonts/Font1.woff2")
}
```
