### ISSUE TITLE
[bug] Packaging Chinese Error Messages on Windows

### ISSUE THREAD

**Issue by JCAlways** [tauri-apps/tauri#7089] opened 2023-05-31 02:17 UTC
### ProductName cannot be packaged when in Chinese

tauri.conf.json
```json
  "package": {
    "productName": "智慧浩翔",
    "version": "0.2.0"
  },
```
use yarn tauri build

```shell
PS D:\Code\Test\tauri-template> yarn tauri build
yarn run v1.22.19
warning package.json: No license field
$ D:\Code\Test\tauri-template\node_modules\.bin\tauri build
   Compiling app v0.1.5 (D:\Code\Test\tauri-template\src-tauri)
    Finished release [optimized] target(s) in 33.65s
        Info Target: x64
 Downloading https://go.microsoft.com/fwlink/p/?LinkId=2124703
     Running candle for "main.wxs"
     Running light to produce D:\Code\Test\tauri-template\src-tauri\target\release\bundle\msi\智慧浩翔_0.2.0_x64_zh-CN.msi
        Info Target: x64
 Downloading https://go.microsoft.com/fwlink/p/?LinkId=2124703
     Running makensis.exe to produce D:\Code\Test\tauri-template\src-tauri\target\release\bundle\nsis\智慧浩翔_0.2.0_x64-setup.exe
File: "D:\Code\Test\tauri-template\src-tauri\target\release\鏅烘収娴╃繑.exe" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "D:\Code\Test\tauri-template\src-tauri\target\release\nsis\x64\installer.nsi" on line 425 -- aborting creation process
       Error failed to bundle project: `系统找不到指定的文件。 (os error 2)`
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Platform and versions

```text
[✔] Environment
    - OS: Windows 10.0.25375 X64
    ✔ WebView2: 113.0.1774.57
    ✔ MSVC: Visual Studio Community 2022
    ✔ rustc: 1.69.0 (84c898d65 2023-04-16)
    ✔ Cargo: 1.69.0 (6e9a83356 2023-04-12)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: stable-x86_64-pc-windows-msvc (default)
    - node: 16.16.0
    - yarn: 1.22.19
    - npm: 8.11.0

[-] Packages
    - tauri [RUST]: 1.3.0
    - tauri-build [RUST]: 1.3.0
    - wry [RUST]: 0.24.3
    - tao [RUST]: 0.16.2
    - @tauri-apps/api [NPM]: not installed!
    - @tauri-apps/cli [NPM]: 1.3.1

[-] App
    - build-type: bundle
    - CSP: default-src 'self'; img-src 'self' asset: https://asset.localhost
    - distDir: https://oa.haoxianggroup.cn/
    - devPath: https://oa.haoxianggroup.cn/
```

**Comment by FabianLars** [comment] 2023-05-31 07:04
Duplicate of #7036. This should be fixed in the next release, thanks for the report :)

**Closed as not planned by FabianLars** 2023-05-31 07:04 UTC
Labels: type: bug, status: needs triage
