### ISSUE TITLE
target folder grows uncontrolably

### ISSUE THREAD

**Issue by conradludgate** [tauri-apps/tauri#2497] opened 2021-08-20 07:15 UTC
### **Describe the bug**

When running a new tauri app using `yarn tauri dev` my target folder grows uncontrollably,
reaching well above 30GB at one point (filling the remaining space on my SSD).
After a `cargo clean`, it went right back up to 7.5GB where it stayed for a bit, but then doubled in size after a short while

### **To Reproduce**
Create a and run a new tauri project 

```sh
yarn tauri init
yarn tauri dev
```

### **Expected behavior**
The window runs but the target folder maintains a stable size

### **Screenshots**

![2021-08-20-08:11:13](https://user-images.githubusercontent.com/6625462/130194616-bc49e936-0514-4098-82ba-456b6e48d05a.png)

### **Platform and Versions (required):**

```
Operating System - Arch Linux, version Unknown X64

Node.js environment
  Node.js - 14.16.0
  @tauri-apps/cli - 1.0.0-beta-rc.4
  @tauri-apps/api Not installed

Global packages
  npm - 7.6.3
  yarn - 3.0.1

Rust environment
  rustc - 1.56.0-nightly
  cargo - 1.56.0-nightly

App directory structure
/src-tauri
/src
/.next
/.yarn

App
  tauri.rs - 1.0.0-beta.7
build-type - bundle
CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
distDir - .
devPath - http://localhost:3000
```

**Comment by nothingismagick** [comment] 2021-08-20 07:18
Its probably not the problem, but your CLI version is ancient.

**Comment by conradludgate** [comment] 2021-08-20 07:22
I'll try update to beta.9, I'm not sure why it chose that version :thinking:, I just ran `yarn add -D @tauri-apps/cli` as the tutorial says (and I've never installed tauri before afaik)

**Comment by conradludgate** [comment] 2021-08-20 07:30
Ok, interesting. In my case `1.0.0-beta-rc.4` is the latest CLI that works for me.

`1.0.0-beta.0` through to `1.0.0-beta.6` all output
```sh
❯ yarn tauri info
Downloading Rust CLI...
```

While `1.0.0-beta.7` through `1.0.0-beta.9` output
```sh
❯ yarn tauri info
(node:591232) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/oon/.yarn/berry/cache/@tauri-apps-cli-npm-1.0.0-beta.7-6434020253-8.zip/node_modules/@tauri-apps/cli/bin/tauri.js:6
import chalk from 'chalk'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.external_module_.Module._load (/home/oon/code/rust/clyde/.pnp.cjs:18550:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by conradludgate** [comment] 2021-08-20 07:32
On another note, it seems just having vscode (rust-analyzer) open causes the continuous codegen inflation

**Comment by nothingismagick** [comment] 2021-08-20 07:42
Maybe its best for you to visit our discord. You're facing several issues. Rust analyzer problems are out of scope.

**Closed as completed by nothingismagick** 2021-08-20 07:42 UTC
Labels: type: bug

**Comment by kubijo** [comment] 2021-09-27 17:04
> Ok, interesting. In my case `1.0.0-beta-rc.4` is the latest CLI that works for me.
> 
> `1.0.0-beta.0` through to `1.0.0-beta.6` all output
> 
> ```shell
> ❯ yarn tauri info
> Downloading Rust CLI...
> ```
> 
> While `1.0.0-beta.7` through `1.0.0-beta.9` output
> 
> ```shell
> ❯ yarn tauri info
> (node:591232) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> (Use `node --trace-warnings ...` to show where the warning was created)
> /home/oon/.yarn/berry/cache/@tauri-apps-cli-npm-1.0.0-beta.7-6434020253-8.zip/node_modules/@tauri-apps/cli/bin/tauri.js:6
> import chalk from 'chalk'
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
>     at wrapSafe (internal/modules/cjs/loader.js:979:16)
>     at Module._compile (internal/modules/cjs/loader.js:1027:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.external_module_.Module._load (/home/oon/code/rust/clyde/.pnp.cjs:18550:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47
> ```

Have you fixed the problem with syntax error?

**Comment by FabianLars** [comment] 2021-09-27 17:19
@kubijo Are your dependencies and node version up-to-date?
```
@tauri-apps/api - 1.0.0-beta.8
@tauri-apps/cli - 1.0.0-beta.10
tauri (rust) - 1.0.0-beta.8
node i think >=14.15 should be safe
```
Also yarn 2&3 like to act up, so if the above isn't the issue i'd suggest trying yarn v1 (or another package manager)

**Comment by kubijo** [comment] 2021-09-27 17:21
```
$ node -v
v14.17.0

$ yarn -v
3.1.0-rc.2

$ yarn why @tauri-apps/api
└─ toolbox@workspace:packages/toolbox
   └─ @tauri-apps/api@npm:1.0.0-beta.8 (via npm:1.0.0-beta.8)

$ yarn why @tauri-apps/cli
└─ toolbox@workspace:packages/toolbox
   └─ @tauri-apps/cli@npm:1.0.0-beta.10 (via npm:1.0.0-beta.10)
```

**Comment by kubijo** [comment] 2021-09-27 17:23
> Also yarn 2&3 like to act up, so if the above isn't the issue i'd suggest trying yarn v1 (or another package manager)

Yeah, that is not a solution though, is it now?
The project is a part of monorepo with several other project and unified build-tooling & package management, so mixing in old version of package manager is not a way to go.

**Comment by kubijo** [comment] 2021-09-27 17:27
My hunch is that the problem is in that you are using ES modules, where Yarn cannot hook into because that whole part of node is still very much unfinished and on the edge & no loader API exists... now then, is there a way to use a CommonJS version of the packages?

**Comment by nothingismagick** [comment] 2021-09-27 17:39
Would just like to remind you @kubijo that we have community guidelines. Neither sarcasm nor expectation that we understand the nuances of your project (and every possible project out there) are types of tone that are not really appropriate in any workplace. In fact it's the best way not to get help in a volunteer run open source project.

**Comment by kubijo** [comment] 2021-09-27 17:48
I am sorry for making it sound as such, it really wasn't my intention to imply that.

It's just that the answer of `Also yarn 2&3 like to act up, so if the above isn't the issue i'd suggest trying yarn v1` is very much suggestive of a known issue with the way the library is set up & cooperation with a very widely used package manager.

That being said, you do have a point and should have known better with my response...

-----------------------

Now for the issue at hand.
What would be your stance on transpilation of the libs into CommonJS to ensure wider support, while it shouldn't hinder your internal developer experience.

I have no practical experience with this kind of change (disregarding the theoretical knowledge), but I'd be willing to lend a hand with it should it help because I'd very much like to re-visit Tauri to validate it's potential for use in an upcoming project.
