### ISSUE TITLE
Incorrect app metadata in help message generated by Tauri

### ISSUE THREAD

**Issue by xyzshantaram** [tauri-apps/tauri#2982] opened 2021-11-29 13:04 UTC
### **Describe the bug**
The help value generated for Tauri apps incorrectly contains the name / version / authors of Tauri instead of those of the application being built.

### **To Reproduce**
1. Use the `next` branch of tauri.
2. Set up a cli in `tauri.conf.json`
3. add code like:
    ```rs
    let context = tauri::generate_context!();
    let cli_config = context.config().tauri.cli.clone().unwrap();

    if let Ok(matches) = get_matches(&cli_config) {
        if let Some(val) = matches.args.get("help") {
            if let Some(help_str) = val.value.as_str() {
                println!("{}", help_str);
                exit(0);
            }
        }
    };
    ```
4. Run app.

### **Expected behavior**
App version, app name, and author should be displayed.

### **Screenshots**
![image](https://user-images.githubusercontent.com/22570968/143872333-5fc7d685-e229-4d65-9c75-7bbeec117766.png)

### **Platform and Versions (required):**

```
Operating System - Arch Linux, version Unknown X64

Node.js environment
  Node.js - 14.18.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.1.3
  yarn - 1.22.17

Rust environment
  rustc - 1.57.0-nightly
  cargo - 1.57.0-nightly

App directory structure
/.github
/src-tauri
/.git
/node_modules
/static

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../static
  devPath - http://127.0.0.1:5500/static/
```

**Comment by FabianLars** [comment] 2021-11-29 13:14
Btw, looks the like the problem is that we use clap's macros for that here: https://github.com/tauri-apps/tauri/blob/ed497d74c8fb664564f53520b3d0204bc906bbdf/core/tauri/src/api/cli.rs#L146-L148.
I guess they get set per package, not for the whole project.

**Comment by amrbashir** [comment] 2022-02-02 13:50
This has been fixed in https://github.com/tauri-apps/tauri/commit/639fcad3075f555e9abab872a811911a5fd1822e

**Closed as completed by amrbashir** 2022-02-02 13:50 UTC
Labels: type: bug
