### ISSUE TITLE
[bug] Always get `Uncaught (in promise) invalid utf-8 sequence of 1 bytes from index 2` with sidecar

### ISSUE THREAD

**Issue by Hellager** [tauri-apps/tauri#5912] opened 2022-12-26 02:42 UTC
### Describe the bug

I'm trying to use the sidecar feature, so i write a console app with c# to test.
The app works well when give it correct options and will return error message if options are wrong.
But when i try using the sidecar feature to call it, the result will always be
`Uncaught (in promise) invalid utf-8 sequence of 1 bytes from index 2`, even if specific the output format to UTF8.
Try put them all under the src-tauri folder won't fix it.
I'm not sure whats wrong, any idea?

### Reproduction

1. Here's my test project [tauri-sidecar-test](https://github.com/Hellager/tauri-sidecar-test)
2. The `MyConsoleApp` folder is a visual studio console app project and build it will get the MyConsoleApp.exe which is the test program for Tauri sidecar.
3. Run the test project and click the `Greet` button, you will see the `Uncaught (in promise) invalid utf-8 sequence of 1 bytes from index 2`

### Platform and versions

Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 108.0.1462.54
  › MSVC: 
      - Visual Studio Community 2022
  › Node.js: 16.15.1
  › npm: 8.15.0
  › pnpm: 7.13.4
  › yarn: 1.22.19
  › rustup: 1.24.3
  › rustc: 1.62.0
  › cargo: 1.62.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.2
  › @tauri-apps/api [NPM]: 1.2.0
  › tauri [RUST]: 1.2.2,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../dist
  › devPath: http://localhost:1420/
  › framework: React
  › bundler: Vite

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ MyConsoleApp
  ├─ node_modules
  ├─ public
  ├─ src
  └─ src-tauri

**Comment by amrbashir** [comment] 2022-12-27 14:29
Please provide the sidecar binary so I can test this without having to setup c# dev env.

**Comment by Hellager** [comment] 2022-12-28 03:01
The sidecar binary is in src-tauri/console, run it with option `-l` will have the expected result.
The c# project is to prove that the console app itself is clean and works well, you don't need to setup a c# env.

**Comment by amrbashir** [comment] 2022-12-28 13:05
Works fine here, the app fails to launch (different issue) but no errors.

![image](https://user-images.githubusercontent.com/48618675/209816178-1b3b41bc-2066-4710-962e-a93da77c6274.png)


Seems like this is the same issue as https://github.com/tauri-apps/tauri/issues/5309 which I can't reproduce. Can you try providing a utf-8 encoding like this:
```js
const command = Command.sidecar("console/MyConsoleApp", ["-l"], { encoding: 'utf-8' })
```

**Comment by Hellager** [comment] 2022-12-31 06:15
Thanks for your help.
Now with `{ encoding: 'utf-8' }`, the stderr result turns to be
```
δ���������쳣:  System.TypeInitializationException: ��QuickAccessShell.Program�������ͳ�ʼֵ�趨�������쳣�� ---> System.IO.FileNotFoundException: δ�ܼ����ļ�����򼯡�NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c��������ĳһ�������ϵͳ�Ҳ���ָ�����ļ���
   �� QuickAccessShell.Program..cctor()
   --- �ڲ��쳣��ջ���ٵĽ�β ---
   �� QuickAccessShell.Program.Main(String[] args)
```

I've updated my console app. With any execution, it will have a log message saved in file.
And i find that there's no log file in `src-tauri\target\debug`, which means the console app is not even executed.

According to the error message in stderr, i'm doubting that the console app is not able to find it's corresponding dll.
So i put them all directly under the `src-tauri` folder and update my tauri.conf.json, but get the same result.

The console app itself is good to run directly in the `src-tauri\target\debug`

**Comment by amrbashir** [comment] 2023-01-02 14:11
> According to the error message in stderr, i'm doubting that the console app is not able to find it's corresponding dll.

Same as https://github.com/tauri-apps/tauri/issues/5844 which is being fixed in https://github.com/tauri-apps/tauri/pull/5950

**Closed as completed by amrbashir** 2023-01-02 14:11 UTC
Labels: type: bug, status: needs triage
