### ISSUE TITLE
[bug] Tauri making <template> elements empty

### ISSUE THREAD

**Issue by xjzh123** [tauri-apps/tauri#6494] opened 2023-03-19 03:54 UTC
### Describe the bug

&lt;template&gt; elements being empty in tauri while having content in source code.

My screenshot: ![](https://raw.githubusercontent.com/xjzh123/tauri-bug-reproduction/master/screenshot.png)

### Reproduction

My repo: https://github.com/xjzh123/tauri-bug-reproduction

`pnpm tauri dev`

### Expected behavior

&lt;template&gt; elements written in the cource code can have content and work properly (can get children nodes).

### Platform and versions

```text
D:\xuexi\tech\js\tauri-bug-reproduction>pnpm tauri info

> tauri-bug-reproduction@0.0.0 tauri D:\xuexi\tech\js\tauri-bug-reproduction
> tauri "info"


Environment
  › OS: Windows 10.0.22000 X64
  › Webview2: 110.0.1587.69
  › MSVC: 
      - Visual Studio Community 2022
      - Visual Studio Community 2017
  › Node.js: 18.13.0
  › npm: 8.19.3
  › pnpm: 7.29.3
  › yarn: Not installed!
  › rustup: 1.25.2
  › rustc: 1.68.0
  › cargo: 1.68.0
  › Rust toolchain: stable-x86_64-pc-windows-msvc 

Packages
  › @tauri-apps/cli [NPM]: 1.2.3
  › @tauri-apps/api [NPM]: Not installed!
  › tauri [RUST]: 1.2.4,
  › tauri-build [RUST]: 1.2.1,
  › tao [RUST]: 0.15.8,
  › wry [RUST]: 0.23.4,

App
  › build-type: bundle
  › CSP: unset
  › distDir: ../src
  › devPath: ../src

App directory structure
  ├─ .git
  ├─ .vscode
  ├─ node_modules
  ├─ src
  └─ src-tauri
```

### Additional context

When I use javascript DOM functions (`appendChild`), templates can have child nodes.

I have consulted #4410 and related issues and PRs, but find my problem not fixed.

**Comment by FabianLars** [comment] 2023-03-19 12:54
Duplicate of #6418. It should be fixed in https://github.com/tauri-apps/tauri/pull/6166 which will be part of tauri 1.3 :)

If you want to try it out before release you can see here https://tauri.app/v1/guides/faq#how-can-i-use-unpublished-tauri-changes how to use the cli from git.

**Closed as not planned by FabianLars** 2023-03-19 12:54 UTC
Labels: type: bug, status: needs triage
