### ISSUE TITLE
Clean install of tauri in combination with vue-cli dosen't work

### ISSUE THREAD

**Issue by ehhc** [tauri-apps/tauri#788] opened 2020-07-09 13:58 UTC
If i install everything new and try to start or build a dummy vue application, i only get a plain white app that crashes on resize.

Steps :
- vue create test
- cd test
- vue add tauri
- yarn tauri:serve 
- yarn tauri:serve --> completely white window that crashes on resize
> app:tauri (runner) ⚠️  [FAIL] Cargo CLI has failed +0ms

- yarn tauri:build --> produces an app that has a completely white window and does nothing

I just read about tauri and wanted to test it. I'll quit that try now..

**Comment by lucasfernog** [comment] 2020-07-09 14:05
We are about to publish the fix for that, thanks for the report.

**Comment by lucasfernog** [comment] 2020-07-09 14:51
Fixed on tauri (npm) v0.8.3

**Comment by ehhc** [comment] 2020-07-09 15:06
Thanks for the new release. Unfortunately, it does not solves the main problem. I'll edit the previous bug report to reflect the current state...

**Comment by ehhc** [comment] 2020-07-09 15:07
@lucasfernog do you reopen this issue?

**Comment by nothingismagick** [comment] 2020-07-09 15:18
can you please add the results of `yarn tauri info`

**Comment by lucasfernog** [comment] 2020-07-09 15:19
We're seeing some Windows issues, I need to reinstall my Windows to try it.

**Comment by ehhc** [comment] 2020-07-09 15:24
@nothingismagick 

```
 C:\Users\WDAGUtilityAccount\Desktop\e\node_modules\.bin\tauri info
[tauri]: running info

Operating System - Windows_NT(10.0.18362) - win32/x64

Node.js environment
  Node.js - 14.5.0
  tauri.js - 0.8.3

Rust environment
  rustc - 1.44.1
  cargo - 1.44.1
  tauri-bundler - 0.8.3

Global packages
  NPM - 6.14.5
  yarn - 1.22.4

App directory structure
/.git
/dist_tauri
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.7.2
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  Windows - Edge
  distDir - unset
  devPath - unset
Done in 2.13s.
```

**Comment by nothingismagick** [comment] 2020-07-09 15:28
![image](https://user-images.githubusercontent.com/35242872/87059086-2e917400-c209-11ea-9e4e-aff4f59c8df2.png)

Can you also tell me which version of Edge you have on your system?

Go to the about page at  `edge://settings/help` (in the browser)

**Comment by ehhc** [comment] 2020-07-09 15:36
@nothingismagick it's not mentioned that i need the chrome based edge browser... i'm currently using the "old" edge. Version 44.18362.449.0

**Comment by ehhc** [comment] 2020-07-09 15:39
To see if it changes something, i've now installed this: 
![grafik](https://user-images.githubusercontent.com/10086873/87060750-2d614680-c20b-11ea-85a0-98e92a057099.png)

But still have the same problems..

**Comment by ehhc** [comment] 2020-07-09 15:46
Btw: I installed everything in the windows 10 [sandbox](https://techcommunity.microsoft.com/t5/windows-kernel-internals/windows-sandbox/ba-p/301849)... so it's like a like i have a completely new system.. but it's gone as soon as i shut down my main system...

**Comment by myAlterX** [comment] 2020-07-09 18:09
I can report that everything works with the repro you provided with a Windows 10 Pro machine with almost the same versions. I'm using rust nightly:

```
[tauri]: running info

Operating System - Windows_NT(10.0.19041) - win32/x64

Node.js environment
  Node.js - 14.5.0
  tauri.js - 0.8.3

Rust environment
  rustc - 1.45.0-nightly
  cargo - 1.45.0-nightly
  tauri-bundler - 0.8.3

Global packages
  NPM - 6.14.5
  yarn - 1.22.4

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.7.2
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'   
  Windows - Edge
  distDir - unset
  devPath - unset
Done in 1.07s.
```

![image](https://user-images.githubusercontent.com/5346300/87075065-b3838a00-c217-11ea-84c6-48026851f2d5.png)

**Comment by lucasfernog** [comment] 2020-07-09 19:40
I can reproduce this issue, seems like it's some kind of loopback problem, Edge simply isn't connecting to localhost. Gonna do some tests.

**Comment by lucasfernog** [comment] 2020-07-09 21:44
@ehhc can you run this command on PowerShell (running as admin)?
`CheckNetIsolation LoopbackExempt -a -n="Microsoft.MicrosoftEdge_8wekyb3d8bbwe"`
and then try again with `yarn tauri:serve`

**Comment by lucasfernog** [comment] 2020-07-09 23:33
Actually I found the problem, the loopback command isn't run on `dev`. The fix will be published tomorrow.

**Closed as completed** 2020-07-10 00:41 UTC
Labels: type: bug

**Comment by ehhc** [comment] 2020-09-24 15:22
I just tried it again today. I've reinstalled everything again from scratch on a new/fresh machine. Still doesn't work. I just get a plain white window that gets a black border on resize.

```
[tauri]: running info

Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.18.4
  tauri.js - 0.12.0

Rust environment
  rustc - 1.46.0
  cargo - 1.46.0
  tauri-bundler - 0.9.3

Global packages
  NPM - 6.14.6
  yarn - Not installed

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.9.2
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - unset
  devPath - unset
```

Edit: at least i don't get any error messages anymore. It's just not working at all

**Comment by Almusamim** [comment] 2020-09-28 08:22
@lucasfernog 
I'm getting this issue too but without black borders on resize change like @ehhc  just a white page!
The localhost is working fine in the web browser as it should!

The issue seems to be just with vue but it works fine otherwise as I tried tauri with Svelte and it was working.

```
$ yarn tauri info
yarn run v1.22.5
$ E:\Projects\tauri\vue-tauri\node_modules\.bin\tauri info
[tauri]: running info

Operating System - Windows_NT(10.0.18363) - win32/x64
Microsoft Edge - 44.18362.449.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 12.18.2
  tauri.js - 0.12.0

Rust environment
  rustc - 1.46.0
  cargo - 1.46.0
  tauri-bundler - 0.9.3

Global packages
  NPM - 6.14.8
  yarn - 1.22.5

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.9.2
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - unset
  devPath - unset
✨  Done in 7.27s.
```

```
Hadi@Thinkpad MINGW64 /e/Projects/tauri/vue-tauri (master)
$ yarn tauri:serve
yarn run v1.22.5
$ vue-cli-service tauri:serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 6720ms                                                                                                 10:15:49

  App running at:
  - Local:   http://localhost:8080/    
  - Network: http://192.168.0.163:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

 app:spawn Running "cargo run" +0ms

   Compiling vue-tauri v0.1.0 (E:\Projects\tauri\vue-tauri\src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 3.76s
     Running `target\debug\vue-tauri.exe`
```

**Comment by Almusamim** [comment] 2020-09-28 10:09
![image](https://user-images.githubusercontent.com/16979898/94418094-336b2180-0181-11eb-9bf9-ef29db58e32e.png)

![](https://snipboard.io/GLh5gy.jpg)

**Comment by Almusamim** [comment] 2020-09-28 11:21
Just used a Rollup Vue Boilerplate instead without the Tauri-vue plugin and it is working..

**Comment by nklayman** [comment] 2020-09-28 23:24
Can one of you post a link to your repo? I just tried it myself and it worked fine. Here is my `tauri info`, it appears to be pretty much the same as yours:
```
Operating System - Windows_NT(10.0.19041) - win32/x64
Microsoft Edge - 44.19041.423.0_neutral__8wekyb3d8bbwe

Node.js environment
  Node.js - 14.4.0
  tauri.js - 0.12.0

Rust environment
  rustc - 1.46.0
  cargo - 1.46.0
  tauri-bundler - 0.9.3

Global packages
  NPM - 6.14.5
  yarn - 1.22.4

App directory structure
/.git
/node_modules
/public
/src
/src-tauri

App
  tauri.rs - 0.9.2
  mode - embedded-server
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: http: https: 'unsafe-eval' 'unsafe-inline'
  distDir - unset
  devPath - unset
```
