### ISSUE TITLE
[bug] There is a delay when the element is clicked

### ISSUE THREAD

**Issue by AlanCZ** [tauri-apps/tauri#3977] opened 2022-04-27 02:57 UTC
### Describe the bug

When I start the Tauri program, there will be a delay or no response when I click on the element！

The code is as follows

```
<template>
  <div class="a">
    <div class="b"></div>
    <div class="b"></div>
    <div class="b"></div>
    <div class="b"></div>
    <div class="b"></div>
  </div>
</template>

<script setup lang="ts">
</script>

<style>
#app {
  height: 100vh;
  width: 100vh;
}

.a {
  height: 100vh;
  width: 100vh;
}

.b {
  width: 40px;
  height: 40px;
  background-color: gray;
}

.b:focus {
  background-color: aqua;
}

.b:active {
  background-color: brown;
}
</style>
```

### Platform and versions

```shell
npm run tauri dev
```

### Stack trace

```shell
tauri vite vue-ts
```

**Comment by AlanCZ** [comment] 2022-04-27 02:59
The problem may be caused by one of tauri and webview2, There is no problem in executing the front-end code in the browser

**Comment by amrbashir** [comment] 2022-04-27 04:37
duplicate of #3691

**Closed as completed by amrbashir** 2022-04-27 04:37 UTC
Labels: type: bug, status: invalid
