### ISSUE TITLE
Transparent window shadow artifacts on MacOS 

### ISSUE THREAD

**Issue by jimmieW** [tauri-apps/tauri#5494] opened 2022-10-27 13:12 UTC
### Describe the bug

We have been experiencing shadow artifacts when using transparent windows on MacOS. 

I managed to repeat the problem by modifying the following example to resemble our use case:

https://github.com/tauri-apps/tauri/tree/dev/examples/parent-window (attached below)

What the issue looks like:
![2022-10-27_14h56_21](https://user-images.githubusercontent.com/10254358/198291484-d6fea4c2-52e3-41da-9787-6161663cc468.png)
https://user-images.githubusercontent.com/10254358/198291550-a9d05769-3a53-47b4-b61a-208e3d2e42e0.mov

Modifications to the example: 
[parent-window.zip](https://github.com/tauri-apps/tauri/files/9879590/parent-window.zip)

### Reproduction

1. Download the tauri repo.
2. Download the zip with the modified parent window example. 
3. Replace the existing parent window example with the attached one. 
4. Open a command prompt and navigate to the root of the tauri repo. 
5. Start the example application by running: 
cargo run --example parent-window --features macos-private-api
6. Click two times on the button that produces a child window (look at the attached video). 
7. Resize the parent window. 
8. Scroll. 
9. Shadow artifacts appear. 

### Expected behavior

No shadow artifacts should appear.

### Platform and versions

MacOS version: Monterey 12.2.1
Tauri dev branch: https://github.com/tauri-apps/tauri/pull/5483/commits/4648ccc423af478610b84a9f4a6e753c39aa85f0

**Comment by FabianLars** [comment] 2022-10-27 13:21
Duplicate of #4243. Thanks for the report and the repro example!

**Closed as not planned by FabianLars** 2022-10-27 13:21 UTC
Labels: type: bug, status: needs triage
