### ISSUE TITLE
[feat] export FileResponse

### ISSUE THREAD

**Issue by Sahasrara** [tauri-apps/tauri#8555] opened 2024-01-05 23:03 UTC
### Describe the problem

Would it be possible to export the FileResponse interface?

### Describe the solution you'd like

I'd just like to be able to access type information for the FileResponse interface. I figured exporting it would be pretty simple.

**Comment by FabianLars** [comment] 2024-01-06 16:49
Duplicate of https://github.com/tauri-apps/plugins-workspace/issues/835, fixed in https://github.com/tauri-apps/plugins-workspace/pull/837. If you update the `@tauri-apps/plugin-dialog` package to the latest version you should have access to it.

(Or do we use the same interface somewhere else outside the dialog plugin? Couldn't find it anywhere.)

**Closed as not planned by FabianLars** 2024-01-06 16:49 UTC
Labels: type: feature request
