### ISSUE TITLE
Build to other platform feature available?? Or only build on local system?

### ISSUE THREAD

**Issue by spirityy** [tauri-apps/tauri#3011] opened 2021-12-02 10:36 UTC
**Is your feature request related to a problem? Please describe.**

My platform is MacOS, i wanna build app for windows. But i can not find msi/exe in target/bundle folder. I believe that was a common requirement.

**Comment by FabianLars** [comment] 2021-12-02 10:40
Duplicate of #1334, #1114, #279 and probably more.
Short answer: Not really possible in the foreseeable future, you have to use something like GitHub Action or VMs for this.

**Closed as completed by FabianLars** 2021-12-02 10:40 UTC
Labels: type: feature request, status: invalid

**Comment by amrbashir** [comment] 2021-12-02 10:41
cross-platform compilation is not possible atm but you can use docker, VMs or Github actions, checkout https://github.com/tauri-apps/tauri-action
