### ISSUE TITLE
[feat] Avoid recompiling unchanged dependencies

### ISSUE THREAD

**Issue by litingyes** [tauri-apps/tauri#11900] opened 2024-12-08 04:03 UTC
### Describe the problem

Every time modify a rust file, have to recompile all dependencies, which affects efficiency.

<img width="711" alt="Screenshot 2024-12-08 at 11 59 45" src="https://github.com/user-attachments/assets/1987673e-e42b-438d-bdd3-beac87055945">

### Describe the solution you'd like

Is there a way to reuse unchanged dependencies without going through the entire process again every time you edit a file?

### Alternatives considered

I don't know if Rust can do this currently, but it would be great if it could.

### Additional context

Mac + Vscode

**Comment by FabianLars** [comment] 2024-12-08 19:01
Closing as a duplicate of https://github.com/tauri-apps/tauri/issues/10826 (try the workaround mentioned in the last comment -> https://github.com/tauri-apps/tauri/issues/11577#issuecomment-2461341697

**Closed as not planned by FabianLars** 2024-12-08 19:01 UTC
Labels: type: feature request
