### ISSUE TITLE
[feat] Generate Typescript Declaration from Structs in Rust

### ISSUE THREAD

**Issue by d3rpp** [tauri-apps/tauri#3586] opened 2022-03-02 08:46 UTC
### Describe the problem

Typically, when you create a struct on the rust side, you need to declare the same struct on the typescript side using a `.d.ts` file or having a dedicated interface file. This normally isn't bad if not a little bit time consuming, though it does open up the floodgates for human error which can slow progress down significantly on larger codebases.

### Describe the solution you'd like

There is a rust crate that can do this, however, which is simply a `derive` macro in [typescript-definitions](https://crates.io/crates/typescript-definitions#Usingtype_script_ify).

my knowledge of rust (and this code base) is very limited however it may be a good idea to have `#[tauri::struct]` macro in the same way we have `#[tauri::command]`, which would release typescript definition files should a typescript mode be enabled in the projects `tauri.conf.json`.

The developer could then simply attach this `#[tauri::struct]` to any struct that are supposed to be accessed by the front end (and while its there, it may be a good idea to make it derive `serde::Serialize` if you can, idk).

### Alternatives considered

Realistically this should only be a minor annoyance (that being, creating the `.d.ts` files yourself) until the codebases start scaling massively although it would be a nifty little feature, so if you absolute gods consider something like this it probably wouldn't be the highest priority at the moment all things considered.

### Additional context

Overall this is purely an idea to improve the developer experience and overall, nothing will happen if this doesn't.

**Comment by nothingismagick** [comment] 2022-03-02 08:49
Great idea! This kind of automation is nice for those lucky enough to struggle with TS in their day-to-day work.

**Comment by amrbashir** [comment] 2022-03-02 08:52
possibly duplicate of #1514

And tbh I don't know why should we implement this since there is already crates for it out there.

https://crates.io/crates/typescript-definitions
https://crates.io/crates/ts-rs

**Comment by FabianLars** [comment] 2022-03-02 08:54
Yeah i think for this specific use-case it makes more sense to promote existing solutions (maybe integrate them in the docs or use them in an example).

**Comment by d3rpp** [comment] 2022-03-02 08:57
> possibly duplicate of #1514
> 
> And tbh I don't know why should we implement this since there is already crates for it out there.
> 
> https://crates.io/crates/typescript-definitions https://crates.io/crates/ts-rs

in a sense, yes it is, and my idea is to implement the crates you listed into the build system, so when you run `tauri dev` for example, it would create the type definitions for your structs and functions in an effort to streamline development

**Comment by lucasfernog** [comment] 2022-06-29 03:36
Closing as duplicate of #1514.

**Closed as completed by lucasfernog** 2022-06-29 03:36 UTC
Labels: type: feature request
