### ISSUE TITLE
[docs] Mermaid Syntax Error

### ISSUE THREAD

**Issue by service-fabric-dev** [tauri-apps/tauri#3514] opened 2022-02-19 17:32 UTC
It appears there is a mermaid syntax error on [the Lockdown diagram](https://tauri.studio/docs/architecture/recipes/lockdown/)

![image](https://user-images.githubusercontent.com/51183415/154812092-6fb06114-8042-4dd4-90fa-9383d621b73a.png)

**Comment by JonasKruckenberg** [comment] 2022-02-19 18:12
The Tauri Website is being maintained [over here](https://github.com/tauri-apps/tauri-docs). this issue is a duplicate of https://github.com/tauri-apps/tauri-docs/issues/462

**Closed as completed by JonasKruckenberg** 2022-02-19 18:12 UTC
Labels: type: documentation
